### ISSUE TITLE
Does logstash support automatic force reloading?

### ISSUE THREAD

**Issue by ysn2233** [elastic/logstash#10005]
We are working on a case that the input is kafka topics with their name relating to date. Because using the topics patterns of  logstash-input-kafka plugins has bug which results in a crash when delete old topics, I'm going to add a feature that user can defined kafka topics by Ruby code.  However logstash's auto reloading  only executes when the config file has changed. In our requirements, we will keep the config file same but reload to execute ruby code to get new topic names. Is it possible to force logstash reload config file every intervals? Sorry for poor Enlgish. Below is our desired config file.
```
input {                                                                                                              
      kafka {
          topics_ruby => "
                  require 'date'
                  d = Time.now
                  topic = d.strftime('xxx_test_%Y%m%d')
                  topics = []
                  topics.push(topic)
              "
         group_id => ['xxx_test']
         bootstrap_servers => xxxx
         auto_offset_reset => "earliest"
     }
 }

 output {
     stdout{

     }
 }
```

**Comment by yaauie** [comment]
I'm closing this issue because general configuration and debugging options are better suited for the [Logstash Forum](https://discuss.elastic.co/c/logstash), but I'll also do my best to answer below. If you'd like to continue the conversation, feel free to mention me in a thread in the forum :)

***

No, there is no current way within Logstash to force-reload pipelines on a schedule. The pipeline reloading feature currently looks for a difference in the _content_ of the pipeline configuration, in order to avoid restarting pipelines that haven't changed.

***

I do feel that your proposal works against the grain of the technologies involved for a number of reasons, and do not believe that a quorum of maintainers would accept a patch to add the proposed `topics_ruby` feature.

First, daily rollover of Kafka topics means that there will always be a window near the daily cutover where we may lose events (e.g., we stop listening to yesterday's topic at precicesly 00:00:00, but are not yet done processing events from the last few seconds or minutes of yesterday). 

Second, Kafka has settings (e.g., `log.retention.hours`, `log.retention.bytes`) that allow old logs to be reaped from a topic in a rolling fashion, which greatly reduces the likelihood of data loss and simplifies the orchestration needed. What is the reason for not using these settings?

Again, if you'd like to continue the conversation, please open up a thread in the [Logstash Forum](https://discuss.elastic.co/c/logstash).
