### ISSUE TITLE
Not able to see elastiflow-* data in Kibana

### ISSUE THREAD

**Issue by Ravivenkatachalam** [elastic/logstash#10027]
- Setup 
cisco netflow exporter -nprobe 8.4->logstash 6.4.1+elastiflow 3.3.0->ES 6.4 -> Kibana 6.4. all in Cent OS 7.x version

- Config File :
nprobe.conf - 
-V=9
--tcp=127.0.0.1:6665
--collector-port=2055
-n=none
-i=none
-b=2

logtash pipelines.yml
- pipeline.id: main
  path.config: "/etc/logstash/elastiflow/conf.d/*.conf"

In logstash/elastiflow/conf.d/ 30_output_10_single.logstash.conf file is as below-

Changed  = index => "elastiflow-3.3.0-%{+YYYY.MM.dd}" to  
index => "elastiflow-%{+YYYY.MM.dd}"  since all the latest 6.4.x kibana dashboard jason files have 
elastiflow-* as index

output {
  elasticsearch {
    id => "output_elasticsearch_single"
    hosts => [ "${ELASTIFLOW_ES_HOST:127.0.0.1:9200}" ]
    ssl => "${ELASTIFLOW_ES_SSL_ENABLE:false}"
    ssl_certificate_verification => "${ELASTIFLOW_ES_SSL_VERIFY:false}"
    # If ssl_certificate_verification is true, uncomment cacert and set the path to the certificate.
    #cacert => "/PATH/TO/CERT"
    user => "${ELASTIFLOW_ES_USER:elastic}"
    password => "${ELASTIFLOW_ES_PASSWD:changeme}"
    index => "elastiflow-%{+YYYY.MM.dd}"
    template => "${ELASTIFLOW_TEMPLATE_PATH:/etc/logstash/elastiflow/templates}/elastiflow.template.json"
    template_name => "elastiflow-3.3.0"
    template_overwrite => "true"
  }
}

Changed 10_input_netflow_ipv4.logstash.conf  modified from udp to tcp  port

input {
  # Netflow

tcp {
    id => "input_tcp_netflow_ipv4"
    host => "${ELASTIFLOW_NETFLOW_IPV4_HOST:127.0.0.1}"
    port => "${ELASTIFLOW_NETFLOW_IPV4_PORT:6665}"
    codec => netflow {
      versions => [5,9,10]
    }
    type => "netflow"
  }

}

- Logs in logstash:
Using geoip database {:path=>"/etc/logstash/elastiflow/geoipdbs/GeoLite2-ASN.mmdb"}
[2018-09-27T19:20:12,607][INFO ][logstash.filters.geoip   ] Using geoip database {:path=>"/etc/logstash/elastiflow/geoipdbs/GeoLite2-City.mmdb"}
[2018-09-27T19:20:12,608][INFO ][logstash.filters.geoip   ] Using geoip database {:path=>"/etc/logstash/elastiflow/geoipdbs/GeoLite2-ASN.mmdb"}
[2018-09-27T19:20:22,776][INFO ][logstash.inputs.tcp      ] Starting tcp input listener {:address=>"0.0.0.0:6665", :ssl_enable=>"false"}
[2018-09-27T19:20:23,226][INFO ][logstash.pipeline        ] Pipeline started successfully {:pipeline_id=>"main", :thread=>"#<Thread:0x450ba0b6 run>"}

Log in elasticsearch:
[2018-09-27T19:20:02,812][INFO ][o.e.c.m.MetaDataIndexTemplateService] [DATA] adding template [elastiflow-3.3.0] for index patterns [elastiflow-3.3.0-*]

Problem:
Looks nprobe,logstash,ealsticsearch and kiabana all are up with elastiflow templates as per 3.30 in github. No change made  . I see logstash pipelines flushes 

No netflow data data piped seen in elasticsearch  and kibana discovery as well nothing. 
in kibana able to see elasti-flow index templates and elasti 3.3.0 template

**Comment by Ravivenkatachalam** [comment]
nprobe sends netflow v9 data. and its emitting flows and netstat is as below -
netstat -anp | grep 6665
tcp        0      0 127.0.0.1:58400         127.0.0.1:6665          ESTABLISHED 12337/nprobe
tcp6       0      0 :::6665                 :::*                    LISTEN      13831/java
tcp6       0      0 127.0.0.1:6665          127.0.0.1:58400         ESTABLISHED 13831/java

**Comment by MyCodeRocks** [comment]
YUP Same issue I am having even rebuilt the entire stack (ELK) from scratch and still the same. Thank the lord I am not going insane I thought I was being dumb

**Comment by erg809** [comment]
Same for me, all seems to be fine but it does not work. F$$%k

root@netwatch:/tmp# sudo /usr/share/elasticsearch/bin/elasticsearch -V
Version: 6.5.0, Build: default/deb/816e6f6/2018-11-09T18:58:36.352602Z, JVM: 1.8.0_191
root@netwatch:/tmp# sudo -Hu logstash /usr/share/logstash/bin/logstash --path.settings=/etc/logstash -t
Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties
ERROR: Failed to read pipelines yaml file. Location: /etc/logstash/pipelines.yml
usage:
  bin/logstash -f CONFIG_PATH [-t] [-r] [] [-w COUNT] [-l LOG]
  bin/logstash --modules MODULE_NAME [-M "MODULE_NAME.var.PLUGIN_TYPE.PLUGIN_NAME.VARIABLE_NAME=VALUE"] [-t] [-w COUNT] [-l LOG]
  bin/logstash -e CONFIG_STR [-t] [--log.level fatal|error|warn|info|debug|trace] [-w COUNT] [-l LOG]
  bin/logstash -i SHELL [--log.level fatal|error|warn|info|debug|trace]
  bin/logstash -V [--log.level fatal|error|warn|info|debug|trace]
  bin/logstash --help
[2018-11-19T02:06:18,998][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit


![2018-11-19 02_33_20-root netwatch_ _etc_logstash_elastiflow_conf d](https://user-images.githubusercontent.com/45154985/48681588-abd72380-eba3-11e8-94e9-ce00f05c8e33.png)
![2018-11-19 02_34_02-root netwatch_ _etc_logstash_elastiflow_conf d](https://user-images.githubusercontent.com/45154985/48681590-ada0e700-eba3-11e8-9e38-95feedf9b42e.png)

![2018-11-19 02_25_09-elastiflow_ overview - kibana](https://user-images.githubusercontent.com/45154985/48681555-64e92e00-eba3-11e8-8d5f-aa07b534b656.png)
![2018-11-19 02_25_52-elastiflow_ top talkers - kibana](https://user-images.githubusercontent.com/45154985/48681558-67e41e80-eba3-11e8-8c83-cef4d91f19cc.png)
