### ISSUE TITLE
Publish releases?

### ISSUE THREAD

**Issue by cnelson** [elastic/logstash#10081]
Would it be possible to publish actual releases (visible via the github releases api) rather than just tags? Other elastic products (like beats) do publish releases on github.

The current strategy makes it hard to track releases automatically, as the tags only exist on their release branches, not the master branch.

**Comment by security-feedi** [comment]
Since I din't find a logstash announce mailing list to get notified of new releases I use github's "watch releases" feature on this repo, but since the releases are just tagged and not declared as actual releases I don't get the usual notification (like it does in with the elastic/beats repo).

Could you make make releases out of the tags in the future?
Or is there any other recommended way to get notified about new releases?

**Comment by jasontedor** [comment]
Thanks for the feedback, we will start doing this with our next set of releases. Feel free to subscribe to releases to receive notification of when that is. 😇

**Comment by cnelson** [comment]
Thanks so much! 🎉
