### ISSUE TITLE
Matlab Support

### ISSUE THREAD

**Issue by ltfi** [elastic/logstash#10186]
Do you plan to provide matlab document format support?

**Comment by yaauie** [comment]
As it stands, I know of no plugins that read or write Matlab document format, either in our [logstash-plugins](https://github.com/logstash-plugins) org or elsewhere.

**Comment by yaauie** [comment]
@ltfi since this is a question that has an answer, I am closing this ticket.

If you would like there to be one or more plugins supporting matlab document format, we would be glad to help you get there. It would be helpful to understand what type of data you would like to extract from matlab documents, as well as information on the document format itself. The [community forum](https://discuss.elastic.co/c/logstash) is a great place to ask members of the community for their help getting together the information you need.

Cheers
