### ISSUE TITLE
String format specifiers is incorrect, should be '%s' instead. 

### ISSUE THREAD

**Issue by winse** [elastic/logstash#10353]
initialize  java stdin/stdout, if not found the codec, throw `java.util.IllegalFormatConversionException: a != java.lang.String`. 

sees the string format is incorrect, it should be `Unable to obtain codec '%s'` .

* Code: 

```
        String codecName = configuration.get(CODEC_CONFIG);
        codec = PluginRegistry.getCodec(codecName, configuration, context);
        if (codec == null) {
            throw new IllegalStateException(String.format("Unable to obtain codec '%a'", codecName));
        }
```

* Source locations:

https://github.com/elastic/logstash/blob/e6d59de458b10795e18070176ca215aaecf3d68e/logstash-core/src/main/java/org/logstash/plugins/inputs/Stdin.java#L67

https://github.com/elastic/logstash/blob/e6d59de458b10795e18070176ca215aaecf3d68e/logstash-core/src/main/java/org/logstash/plugins/outputs/Stdout.java#L42

**Comment by danhermann** [comment]
@winse, thank you for taking a look at the Java plugin API and reporting this bug report. This has already been fixed in the upcoming [beta](https://github.com/elastic/logstash/pull/10232) version of the Java plugin API, and I'll look into getting a fix for the current experimental version of it into an upcoming patch release.
