### ISSUE TITLE
when run --help cpu too high

### ISSUE THREAD

**Issue by mynameiscode** [elastic/logstash#10569]
when I run ./bin/logstash --help the CPU is too high and the help info print after so long time. I guess if logstash firsh compile the ruby to jvm bytes which cause this promblem. Is there anyone can help me?

logstash version: logstash-6.6.2
env:  4c8g (Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz)

**Comment by yaauie** [comment]
In order to launch to the point that the `--help` is available, we need to boot the JVM and load the JRuby runtime, which unfortunately takes some CPU and some time.

This cannot be made faster until the command-line frontend and settings infrastructure are rewritten in pure java, which would allow us to defer loading of the JRuby runtime sufficiently to intercept `--help`.

**Comment by mynameiscode** [comment]
First, thank you for your answer. Now logstash run with JVM and even support java plugin. So may i ask is there one plan to wrriten logstash with other language such as golang or java. Sometime when i want to use logstash i like its easy to use, but i am worried about it is wrriten by Ruby.  If there some thing can not support that i can wrriten my own plugin use java.

**Comment by yaauie** [comment]
As Logstash matures, more and more of it is being reimplemented in pure Java, recent key examples being the java plugin API and the java-based execution engine. This is a gradual process that has little to do with Ruby itself (we love Ruby) and more to do with building implementations that are safer to develop by teams of engineers, since the type-safety features reduce the cognitive overhead of keeping track of types ourselves. It also often ends up improving performance because we are able to reduce the memory-churn cost of passing objects between the java and jruby runtimes. We have no plans to move to a non-jvm language like golang, or to drop support for Ruby-based plugins since the vast majority of our plugin ecosystem is Ruby, but we do plan to continue adding features that make Logstash development and use safer and more performant.

I'm closing this issue, as the performance of `--help` isn't something we can do much about at this time.
