### ISSUE TITLE
urecognized VM option 'UseParNewGC'

### ISSUE THREAD

**Issue by MilanDasek** [elastic/logstash#10789]
Hello,

when I try to build this dockerfile

```
FROM logstash:6.7.2

RUN rm -f /usr/share/logstash/pipeline/logstash.conf
ADD ./logstash.conf /usr/share/logstash/pipeline/logstash.conf

RUN rm -f /usr/share/logstash/config/jvm.options
ADD ./jvm.options /usr/share/logstash/config/jvm.options

RUN rm -f /usr/share/logstash/config/logstash.yml
ADD ./logstash.yml /usr/share/logstash/config/logstash.yml

RUN bin/logstash-plugin list

RUN export LS_USER=root
RUN export LS_GROUP=root
USER root

CMD ["/usr/share/logstash/bin/logstash"]
```

I got error on step RUN bin/logstash-plugin list

```
Step 10/17 : RUN bin/logstash-plugin list
 ---> Running in 7506e83514a6
nrecognized VM option UseParNewGC
Did you mean (+/-)UseParNewGC?
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

I tried to build on localhost, also in Bitbucket pipelines (using image: atlassian/default-image:2) but I get error every time.

I tried FROM logstash:6.6.0, FROM logstash:6.6.2, FROM logstash:6.7.2 - still the same.

I would like to add these plugins
```
RUN logstash-plugin install logstash-output-elasticsearch
RUN logstash-plugin install logstash-output-amazon_es
RUN logstash-plugin install logstash-codec-cloudfront
```

I have to say this dockerfile worked 3 months ago in bitbucket pipelines. Now it doesn't.

Can you please advise?

Thank you

M

**Comment by yaauie** [comment]
It looks like you may have a misconfiguration in your `config/jvm.options`, specifying `UseParNewGC` instead of either `+UseParNewGC` (to explicitly activate ParNew) or `-UseParNewGC` (to explicitly avoid using ParNew, in which case the JVM will select a different one). Historically we have recommended opting into the ParNew Garbage Collector, as it has good performance characteristics for the types of workloads Logstash typically handles.

On JVM's greater than 1.6 ("Java 6"), ParNew is the default garbage collector, and no longer needs to be specified explicitly.

**Comment by MilanDasek** [comment]
yeah, fixed
cached version :-(
