### ISSUE TITLE
The shutdown process appears to be stalled

### ISSUE THREAD

**Issue by arse1410** [elastic/logstash#10935]
Hi all,
I have a problem with Logstash (7.2.0 version) and filebeat (7.2.0 version). I read other issues  but I didnt find any solution to this problem.

I'm using a configuration: filebeat --> logstash --> stdout (all in the same machine).
The configuration **works properly** (so send correctly the logs from a file in a directory using filebeat, passing for logstash and printed out to the stdout). 
But stopping logstash (using Ctrl+c) I receive this error:
![image](https://user-images.githubusercontent.com/18401918/60709581-18bfe380-9f11-11e9-9c71-32192bd37e90.png)
"[ERROR][org.logstash.execution.ShutdownWatcherExt] The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information."

So it seems that during the logstash stop process something went wrong.
After the stop (and after this error), when I try to restart logstash with the **same configuration** it not works. Logstash seems "stalled or blocked" because noone data is printed out in stdout.
The only way to unlock logstash that i found is restart the machine :(

I realize the problem also because, for example:
When I try to start filebeat, and logstash is **NOT** blocked, I have this starting logs:
![image](https://user-images.githubusercontent.com/18401918/60710908-fa0f1c00-9f13-11e9-973d-3afdeee5818d.png)
So correctly.

When I try to start filebeat, and logstash **IS** blocked, I have this starting logs:
![image](https://user-images.githubusercontent.com/18401918/60711744-d220b800-9f15-11e9-8348-c0f43ec9d54e.png)
So, filebeat is not able to establish a connection with logstash.

The command used to start logstash:
bin/logstash -e 'input { beats { port => "5044" } } output { stdout { codec => rubydebug } }'
I also tried to start logstash using --pipeline.unsafe_shutdown (like suggested here [https://www.elastic.co/guide/en/logstash/current/shutdown.html](url)) but nothing changed.

The command used to start filebeat:
./filebeat -e -c ActiveMQ_filebeat.yml -d "publish"

The ActiveMQ_filebeat.yml is not a particolar configuration, only send logs from a certain path to logstash. 

Do you have any ideas to solve this situation?
I need two things:
1) a method to stop logstash properly (but suing Ctrl+c is a normal practice: [https://www.elastic.co/guide/en/logstash/current/shutdown.html](url))
2) a quick method to unlock logstash when it is blocked

Thanks a lot.

**Comment by danhermann** [comment]
Plugins that maintain network connections or other resources may take a few seconds to shut down. The shutdown watcher keeps track of those so that's expected. From the output above, Logstash shut down just over 1 second later. I'm not sure why you can't restart Logstash, but I'd check to see if something else is listening on port 5044 using `lsof` or the like. If you need further assistance with this, please post in our [Logstash forums](https://discuss.elastic.co/c/logstash).

**Comment by abraxxa** [comment]
Please don‘t close this issue, we‘re experience the same with Logstash 7.2.0 and even waiting for 10 minutes doesn‘t shutdown.

**Comment by danhermann** [comment]
@abraxxa, that sounds like a different problem since the Logstash instance in the issue above shuts down within a couple seconds.

**Comment by abraxxa** [comment]
Same message which is why I‘ve subscribed to the issue.

**Comment by arse1410** [comment]
I'm continuing to have the same problem. If I stop logstash (ctrl+c) and filebeat, when I simply start again both components (logstash and filebeat), sometime filebeat is not able to establish a connection with logstash. The strange thing is that I don't change any configuration before to start again them.

**Comment by AnkurThakur** [comment]
I'm facing same issue in 7.1.1. I have to forcefully kill the process.

**Comment by jsvd** [comment]
For folks landing here, the pipeline and the beats input have had multiple fixes since July 5th. please update to the most recent version of Logstash and if the issue still shows up create a new issue with logs, otherwise it's hard to tell if this is all related to the same problem or not.

**Comment by gwvandesteeg** [comment]
Still occurring with 7.15, seems to be caused when logstash is unable to forward the log messages to the output stream (in my case elasticsearch instead of stdout, and elasticsearch is returning a 403).
During this stalled period, with xpack management enabled, a change to the configuration used by logstash does not get applied.

ie.

```
"reason"=>"action [indices:data/write/index:op_type/index] is unauthorized for user 
```

**Comment by Koesters** [comment]
Would be cool to know what went wrong where in what plugin. 

[2022-06-18T02:40:52,003][ERROR][org.logstash.execution.ShutdownWatcherExt] The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.
[2022-06-18T14:25:13,370][ERROR][logstash.outputs.elasticsearch][main][f3735405c6e09f36684b8865a1ae20eedcec96f621461ff0166584be9e2ff9d8] Encountered a retryable error (will retry with exponential backoff) {:code=>401, :url=>"http://localhost:9200/_bulk", :content_length=>5546}

**Comment by yaauie** [comment]
@Koesters the log message that is after the one remaining in your edited comment indicates that an Elasticsearch output plugin is in a retry loop trying to push a batch of events into Elasticsearch but is receiving 401 http responses. The pipeline cannot safely shut down while it has one or more batches of events in this state because doing so would cause the events to be lost.
