### ISSUE TITLE
Don't report "empty" cgroup stats to X-Pack Monitoring

### ISSUE THREAD

**Issue by ycombinator** [elastic/logstash#10963]
Currently, when `xpack.monitoring.*` is setup in `logstash.yml`, the Logstash node will report "empty" cgroup information like below in `logstash_stats` docs in `.monitoring-logstash-*` indices:

```
{
  "logstash_stats": {
    "os": {
      "cgroup": {
        "cpu": {
          "control_group": "/",
          "stat": {
          "number_of_elapsed_periods": 0,
          "number_of_times_throttled": 0,
          "time_throttled_nanos": 0
        }
      },
      "cpuacct": {
        "control_group": "/",
        "usage_nanos": 151040748569
      }
    }
  }
}
```

Going forward, we're going to be using Metricbeat to collect Logstash monitoring information from a running Logstash node and indexing it into `.monitoring-logstash-*` indices. For this, Metricbeat will call the `GET _node/stats` Logstash API. [As it stands today](https://github.com/elastic/logstash/pull/6357), this API only returns cgroup stats if the Logstash node is running in a container.

Could we make the monitoring docs shipped by Logstash internal collection (i.e. when `xpack.monitoring.*` is set in `logstash.yml`) match the behavior of the `GET _node/stats` API? Concretely, could we make internal collection **not** ship the `os.cgroup` field to Elasticsearch when Logstash is not running in a container?

**Comment by cachedout** [comment]
I cannot replicate this behavior.

It is worth noting, though, that the way this is designed (even for the API), is not based around whether the machine is running in a container, per-se, but instead whether the kernel has `cgroups` enabled.

To test this, I did the following:

1) On an Arch Linux virtual machine running on my workstation, I observed that the code which collects cgroup metrics is based [around the existence of cgroup-related files](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/instrument/periodic_poller/cgroup.rb#L39) and confirmed that those files existed.

2) Without modifying any Logstash code, I verified that calling the API endpoint of `GET _node/stats` does indeed contain the `cgroups` data structure from the `os` field in the response.

3) I configured Logstash to send monitoring data by setting the `xpack.monitoring.*` settings. I ensured that no LS monitoring index existed and I restarted Logstash.

4) After the restart, I verified that a Logstash monitoring index was created. I observed that documents that were created also contained the `cgroups` data structure under the `os` key -- just as they did via the API test in step 2.

5) I modified [the check](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/instrument/periodic_poller/cgroup.rb#L39) to include an additional file check (`/tmp/DOES_NOT_EXIST`). My intention was to simulate an environment in which all the required files were not in place for cgroups data to be collected.

6) After modifying the check, I restarted Logstash. I again tested the API by calling the same endpoint as in step 2. (`GET _node/stats`). I observed that the `cgroups` data structure was no longer present in the `os` field.

7) Finally, I deleted the `.monitoring-logstash*` indexes from ES and allowed Logstash to recreate them. I observed that in those documents, the `cgroups` field was no longer present under the `os` field.

Because I'm not able to locate an obvious place in the code path where these collection methods diverge, I am next going to start up the parity tests and see if there is a difference between the environments between Metricbeat and "native" collection. Stay tuned. :)

**Comment by ycombinator** [comment]
Indeed, I can confirm that running Logstash with internal collection setup on my Mac (not in a container), I am **not** seeing the `logstash_stats.os.cgroup` in `.monitoring-logstash-*` for documents of `type: logstash_stats`.

So it does seem like something that's specific to the parity tests' environment. I'm looking into that as well now.

**Comment by ycombinator** [comment]
I suspect now that the issue is that Metricbeat isn't collecting the `os.cgroups` field from the `GET _node/stats` API response, over here: https://github.com/elastic/beats/blob/master/metricbeat/module/logstash/node_stats/data_xpack.go#L61.

I will confirm this shortly by testing a couple things in the parity tests VM and report back.

**Comment by ycombinator** [comment]
Yes, I have confirmed that the problem is with Metricbeat, not Logstash. Thanks @cachedout for your excellent analysis above - it really helped me look in the right direction. I will close this issue now as it's invalid.
