### ISSUE TITLE
Logstash 7.2.0 fails to load MS SQL JDBC driver

### ISSUE THREAD

**Issue by jpazsedano** [elastic/logstash#10983]
This same error happened to me in both jdbc input plugin as well as jdbc_streaming filter plugin, so I guess is a core logstash problem. That's why the post is here.

- Version: Logstash 7.2.0
Specifically, the problem happened when I changed from 7.1.0 (uses Java 8) to 7.2.0 (uses Java 11).
MS SQL JDBC driver version 7.2.2

- Operating System:
Linux (I'm using the official docker images)

- Config File (if you have sensitive info, please remove it):
```
input {
    jdbc {
        jdbc_driver_library => "/mnt/mssql-jdbc-7.2.2.jre11.jar"
        jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"
        jdbc_connection_string => "jdbc:sqlserver://SERVER\FOO;databaseName=DB_NAME"
        jdbc_user => "myuser"
        jdbc_password => "secret"

        statement => "select * from my_table"
    }
}
```
Yes, after changing to Java 11, i've updated the reference to point to the correct library.

I get the following error:

```
Failed to load /mnt/mssql-jdbc-7.2.2.jre11.jar {:exception=>#<TypeError: failed to coerce jdk.internal.loader.ClassLoaders$AppClassLoader to java.net.URLClassLoader>}
[2019-07-23T16:18:01,049][ERROR][logstash.javapipeline    ] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:mssql-importer
  Plugin: <LogStash::Inputs::Jdbc jdbc_user=>"mysuser", jdbc_password=><password>, statement=>"select * from my_table", jdbc_driver_library=>"/mnt/mssql-jdbc-7.2.2.jre11.jar", jdbc_connection_string=>"jdbc:sqlserver://server/foo;databaseName=dbname", id=>"b6ca9c59b3b566eb1e32324c55b847b9d36c6dac734938bd718e18f5f05aa574", jdbc_driver_class=>"com.microsoft.sqlserver.jdbc.SQLServerDriver", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_34d4af37-c5bd-4e04-9d16-81064813768d", enable_metric=>true, charset=>"UTF-8">, jdbc_paging_enabled=>false, jdbc_page_size=>100000, jdbc_validate_connection=>false, jdbc_validation_timeout=>3600, jdbc_pool_timeout=>5, sql_log_level=>"info", connection_retry_attempts=>1, connection_retry_attempts_wait_time=>0.5, parameters=>{"sql_last_value"=>1970-01-01 00:00:00 UTC}, last_run_metadata_path=>"/usr/share/logstash/.logstash_jdbc_last_run", use_column_value=>false, tracking_column_type=>"numeric", clean_run=>false, record_last_run=>true, lowercase_column_names=>true>
  Error: com.microsoft.sqlserver.jdbc.SQLServerDriver not loaded. Are you sure you've included the correct jdbc driver in :jdbc_driver_library?
  Exception: LogStash::ConfigurationError
  Stack: /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.13/lib/logstash/plugin_mixins/jdbc/jdbc.rb:163:in `open_jdbc_connection'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.13/lib/logstash/plugin_mixins/jdbc/jdbc.rb:221:in `execute_statement'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.13/lib/logstash/inputs/jdbc.rb:277:in `execute_query'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.13/lib/logstash/inputs/jdbc.rb:263:in `run'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:309:in `inputworker'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:302:in `block in start_input'
```

This same setup worked fine in Logstash 7.1.0 with Java 8 (and the Java 8 .jar file), but looks like with the change of java version, it can't load the db driver anymore. And yes, I've loaded the correct .jar.

**Comment by davidhuang007** [comment]
i also get the same problem

**Comment by yaauie** [comment]
See https://github.com/elastic/logstash/pull/10951 which will be included in 7.2.2 and 7.3.0

**Comment by danhermann** [comment]
I think this issue is more likely to be addressed by https://github.com/logstash-plugins/logstash-input-jdbc/pull/343. The other issue addresses classloading only for Java plugins.

**Comment by iamraviraj** [comment]
I have the same issue with LogStash 7.5
`Error: com.microsoft.sqlserver.jdbc.SQLServerDriver not loaded. Are you sure you've included the correct jdbc driver in :jdbc_driver_library?
  Exception: LogStash::PluginLoadingError
  Stack: /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.16/lib/logstash/plugin_mixins/jdbc/jdbc.rb:190:in 'open_jdbc_connection'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.16/lib/logstash/plugin_mixins/jdbc/jdbc.rb:253:in 'execute_statement'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.16/lib/logstash/inputs/jdbc.rb:309:in 'execute_query'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.16/lib/logstash/inputs/jdbc.rb:281:in 'run'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:321:in 'inputworker'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:313:in 'block in start_input'
`

**Comment by iamraviraj** [comment]
I have the same issue with LogStash 7.5.0

`[2019-12-04T19:53:57,369][ERROR][logstash.javapipeline    ][main] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:main
  Plugin: <LogStash::Inputs::Jdbc jdbc_user=>"user", jdbc_password=><password>, statement=>"SELECT [id],[user_id],[kegiatan],[created_date],[keterangan] FROM[nadine_log].[dbo].[log_user]where created_date > '2019-11-27'", jdbc_driver_library=>"/home/ubuntu/sqljdbc_4.2/enu/jre8/sqljdbc42.jar", jdbc_connection_string=>"jdbc:sqlserver://server:1433;user=user;password=password;", id=>"b1e2501d8bb2498d94c4a9960c32d47b0c974d44d198d2de746e59d249d56173", jdbc_driver_class=>"com.microsoft.sqlserver.jdbc.SQLServerDriver", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_10401f33-69f7-4e9c-b252-0e9e763ed742", enable_metric=>true, charset=>"UTF-8">, jdbc_paging_enabled=>false, jdbc_page_size=>100000, jdbc_validate_connection=>false, jdbc_validation_timeout=>3600, jdbc_pool_timeout=>5, sql_log_level=>"info", connection_retry_attempts=>1, connection_retry_attempts_wait_time=>0.5, plugin_timezone=>"utc", last_run_metadata_path=>"/root/.logstash_jdbc_last_run", use_column_value=>false, tracking_column_type=>"numeric", clean_run=>false, record_last_run=>true, lowercase_column_names=>true, use_prepared_statements=>false>`

`Error: com.microsoft.sqlserver.jdbc.SQLServerDriver not loaded. Are you sure you've included the correct jdbc driver in :jdbc_driver_library?`

`Exception: LogStash::PluginLoadingError`

`Stack: /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.16/lib/logstash/plugin_mixins/jdbc/jdbc.rb:190:in 'open_jdbc_connection'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.16/lib/logstash/plugin_mixins/jdbc/jdbc.rb:253:in 'execute_statement'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.16/lib/logstash/inputs/jdbc.rb:309:in 'execute_query'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.16/lib/logstash/inputs/jdbc.rb:281:in 'run'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:321:in 'inputworker'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:313:in 'block in start_input'`

**Comment by iamraviraj** [comment]
I have the same issue with LogStash 7.5.0

`[2019-12-04T19:53:57,369][ERROR][logstash.javapipeline    ][main] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:main
  Plugin: <LogStash::Inputs::Jdbc jdbc_user=>"user", jdbc_password=><password>, statement=>"SELECT * FROM Table", jdbc_driver_library=>"/home/ubuntu/sqljdbc_4.2/enu/jre8/sqljdbc42.jar", jdbc_connection_string=>"jdbc:sqlserver://server:1433;user=user;password=password;", id=>"b1e2501d8bb2498d94c4a9960c32d47b0c974d44d198d2de746e59d249d56173", jdbc_driver_class=>"com.microsoft.sqlserver.jdbc.SQLServerDriver", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_10401f33-69f7-4e9c-b252-0e9e763ed742", enable_metric=>true, charset=>"UTF-8">, jdbc_paging_enabled=>false, jdbc_page_size=>100000, jdbc_validate_connection=>false, jdbc_validation_timeout=>3600, jdbc_pool_timeout=>5, sql_log_level=>"info", connection_retry_attempts=>1, connection_retry_attempts_wait_time=>0.5, plugin_timezone=>"utc", last_run_metadata_path=>"/root/.logstash_jdbc_last_run", use_column_value=>false, tracking_column_type=>"numeric", clean_run=>false, record_last_run=>true, lowercase_column_names=>true, use_prepared_statements=>false>`

`Error: com.microsoft.sqlserver.jdbc.SQLServerDriver not loaded. Are you sure you've included the correct jdbc driver in :jdbc_driver_library?`

`Exception: LogStash::PluginLoadingError`

`Stack: /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.16/lib/logstash/plugin_mixins/jdbc/jdbc.rb:190:in 'open_jdbc_connection'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.16/lib/logstash/plugin_mixins/jdbc/jdbc.rb:253:in 'execute_statement'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.16/lib/logstash/inputs/jdbc.rb:309:in 'execute_query'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.16/lib/logstash/inputs/jdbc.rb:281:in 'run'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:321:in 'inputworker'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:313:in 'block in start_input'`

**Comment by iamraviraj** [comment]
To resolve the issue, you need to place JDBC `jar` file at `/usr/share/logstash/logstash-core/lib/jars`

**Comment by byellokore** [comment]
> To resolve the issue, you need to place JDBC `jar` file at `/usr/share/logstash/logstash-core/lib/jars`

Not sure if is the best solution. But it just worked!!! Thank you @iamraviraj

**Comment by niastifarid** [comment]
I still have this problem...
![image](https://user-images.githubusercontent.com/68768292/92318560-46c41a80-f023-11ea-8da9-4f2435b9a89a.png)
can anybody help me?!?

**Comment by asBAKARA** [comment]
you are forgetting a semicolon

`input {
    jdbc {
        jdbc_driver_library => "/mnt/mssql-jdbc-7.2.2.jre11.jar"
        jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"
        jdbc_connection_string => "jdbc:sqlserver://SERVER\FOO;databaseName=DB_NAME**;**"
        jdbc_user => "myuser"
        jdbc_password => "secret"

        statement => "select * from my_table"
    }
}`

**Comment by kares** [comment]
seems the original issue has been resolved, closing

**Comment by yuliansen** [comment]
> seems the original issue has been resolved, closing

Hi, I have this similiar problem
my logstash version is 7.13
OS centos 7
openjdk 11.0.11 2021-04-20 LTS
jdbc 6.0 : "/home/jdbc/sqljdbc_6.0/enu/jre7/sqljdbc41.jar"

my logstash  config
`
input {
  generator {
    lines => [
"CBN00000020121",
"CBN00000040121"
    ]
    count => 1
  }
}
filter{
csv{
   columns => ["noinvoice"]
   separator => ","
}
{
jdbc_streaming {
    jdbc_driver_library => "/home/jdbc/sqljdbc_6.0/enu/jre7/sqljdbc41.jar"
    jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    jdbc_connection_string => "jdbc:mssql://10.64.2.250:1433/mydatabase"
    jdbc_user => "user"
    jdbc_password => "password"
    statement => "select EmailTime from TestInvoice.dbo.storing_ssis WHERE invoiceno= :noinvoice"
    parameters => {"noinvoice" => "noinvoice"}
    target => "EmailTime"
  }
}
output{
stdout{codec => rubydebug}
}
`
When I run by `/usr/share/logstash/bin/logstash -f fjdbc.conf`
it returns
`
Using bundled JDK: /usr/share/logstash/jdk
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
WARNING: Could not find logstash.yml which is typically located in $LS_HOME/config or /etc/logstash. You can specify the path using --path.settings. Continuing using the defaults
Could not find log4j2 configuration at path /usr/share/logstash/config/log4j2.properties. Using default config which logs errors to the console
[INFO ] 2021-06-10 15:55:36.686 [main] runner - Starting Logstash {"logstash.version"=>"7.13.1", "jruby.version"=>"jruby 9.2.16.0 (2.5.7) 2021-03-03 f82228dc32 OpenJDK 64-Bit Server VM 11.0.11+9 on 11.0.11+9 +indy +jit [linux-x86_64]"}
[WARN ] 2021-06-10 15:55:37.253 [LogStash::Runner] multilocal - Ignoring the 'pipelines.yml' file because modules or command line options are specified
[INFO ] 2021-06-10 15:55:39.668 [Api Webserver] agent - Successfully started Logstash API endpoint {:port=>9600}
[INFO ] 2021-06-10 15:55:41.520 [Converge PipelineAction::Create<main>] Reflections - Reflections took 69 ms to scan 1 urls, producing 24 keys and 48 values
[ERROR] 2021-06-10 15:55:43.988 [[main]-pipeline-manager] javapipeline - Pipeline error {:pipeline_id=>"main", :exception=>#<Sequel::AdapterNotFound: Could not load jdbc/mssql adapter: adapter class not registered in ADAPTER_MAP>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sequel-5.44.0/lib/sequel/database/connecting.rb:97:in `load_adapter'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sequel-5.44.0/lib/sequel/adapters/jdbc.rb:380:in `adapter_initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sequel-5.44.0/lib/sequel/database/misc.rb:154:in `initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sequel-5.44.0/lib/sequel/database/connecting.rb:57:in `connect'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sequel-5.44.0/lib/sequel/core.rb:124:in `connect'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-integration-jdbc-5.0.7/lib/logstash/plugin_mixins/jdbc_streaming.rb:62:in `prepare_jdbc_connection'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-integration-jdbc-5.0.7/lib/logstash/filters/jdbc_streaming.rb:122:in `register'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:75:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:228:in `block in register_plugins'", "org/jruby/RubyArray.java:1809:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:227:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:586:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:240:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:185:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:137:in `block in start'"], "pipeline.sources"=>["/etc/logstash/fjdbc.conf"], :thread=>"#<Thread:0x67751750 run>"}
[INFO ] 2021-06-10 15:55:43.991 [[main]-pipeline-manager] javapipeline - Pipeline terminated {"pipeline.id"=>"main"}
[ERROR] 2021-06-10 15:55:44.015 [Converge PipelineAction::Create<main>] agent - Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}
[INFO ] 2021-06-10 15:55:44.146 [LogStash::Runner] runner - Logstash shut down.
`
how i can specify the adapter class?
