### ISSUE TITLE
how to decide the order when multiple filter

### ISSUE THREAD

**Issue by boat320** [elastic/logstash#11058]
- Version:6.7
I install the logstash with RPM. I wish to know when I set filter in multiple config file , how it decide its runing order. Or can I see the instructions in anywhere

**Comment by danhermann** [comment]
The [documentation on the `-f` parameter](https://www.elastic.co/guide/en/logstash/current/running-logstash-command-line.html) alludes to this, but all Logstash files are concatenated together in alphanumeric order, so that determines the order in which they'll be run.

If you need further assistance, please post in our forums:

> Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash).
> Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
