### ISSUE TITLE
Support new 'enterprise' license type

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#11404]
Goal: accept 'enterprise' value via License API, and consider 'enterprise' equivalent to 'platinum'

**Comment by jsvd** [comment]
solved by #11407

**Comment by nerophon** [comment]
@jsvd a user has hit a bug where their enterprise license prevents use of the Centralised Pipeline Management feature, due to this line missing the "enterprise" type:
https://github.com/elastic/logstash/blob/fe7607abd491e2e6ba57f29406627de515334b1d/x-pack/lib/config_management/elasticsearch_source.rb#L24

Assuming this wasn't intentional for some reason, please can we add this?

**Comment by jsvd** [comment]
They must upgrade to 7.6.0 https://github.com/elastic/logstash/blob/v7.6.0/x-pack/lib/config_management/elasticsearch_source.rb

**Comment by nerophon** [comment]
@jsvd sorry, my mistake. My shortcut takes me to an old branch. Re-closing this.
