### ISSUE TITLE
Security: confirm no hard-coded CBC ciphers are used

### ISSUE THREAD

**Issue by kares** [elastic/logstash#11499]
showed up in plugins, mostly those using Netty, namely : 
- https://github.com/logstash-plugins/logstash-input-beats/pull/376
- https://github.com/logstash-plugins/logstash-input-http/pull/118

... we need an audit to make sure no CBC left-overs are in place

**Comment by jsvd** [comment]
The drive for this change came from tcnative dropping support for ciphers using CBC and mozilla [removing these](https://github.com/mozilla/server-side-tls/pull/255) from their [recommended set of ciphers](https://wiki.mozilla.org/Security/Server_Side_TLS).

However dropping of these ciphers is premature, since they're still deemed secure in most contexts, as long as TLS 1.1+ is used (see more [here](https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384/)), and other Elastic products like [beats](https://www.elastic.co/guide/en/beats/filebeat/master/configuration-ssl.html#_cipher_suites) and [elasticseach](https://www.elastic.co/guide/en/elasticsearch/reference/master/security-settings.html#ssl-tls-settings) still support them.

For this reason and to avoid yanking gems, I suggest closing this issue for now and revert the pull requests mentioned.

**Comment by kares** [comment]
Makes sense, for the record I got the wrong impression that beats would be dropping CBCs.
As a negotiated CBC somehow wasn't working and given a context of http input also dropping these.
Lesson learned by now as I was also investigating a bit: I think its not a good idea to make decisions based on what BoringSSL does as they follow their own needs ...
