### ISSUE TITLE
Logstash deletes file in last_run_metadata_path when the track id is very large

### ISSUE THREAD

**Issue by jonathanpalomino** [elastic/logstash#11590]
When a pipeline is configured as follows:
`input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/drivers/ojdbc7-12.1.0.2.jar"
    jdbc_driver_class => "Java::oracle.jdbc.driver.OracleDriver"
    jdbc_connection_string => "jdbc:oracle:thin:@server:1525/SID"
    jdbc_user => "ABC"
    jdbc_password => "ABC"
    schedule => "* * * * *"
    statement => "SELECT * from ABC.TRAZABILIDAD where id>:sql_last_value"
    use_column_value =>true
    tracking_column => id
    tracking_column_type => "numeric"
    jdbc_paging_enabled => "true"
    jdbc_page_size => "10000"
    jdbc_fetch_size => "2000"
    clean_run => false
		record_last_run => true
    last_run_metadata_path => "/usr/share/logstash/pipeline_last_run/trazabilidad_mpe_last_run_des.yml"
  }
}
output {
	elasticsearch {
		hosts => "elasticsearch:9200"
		index => "trazabilidad_index_des"
		user => "elastic"
		password => "changeme"
	}
  stdout { codec => rubydebug}
}`

And in the Oracle table you have large values for the id column like "9490430"
Logstash generates a file with the following text
--- !ruby/object:BigDecimal '0:0.949043e7'
When the Logstash instance is restarted (docker container, files extracted from zip) this file is deleted and all restarts at 0

**Comment by robbavey** [comment]
@jonathanpalomino I believe we fixed this issue with the latest release of the `logstash-integration-jdbc` plugin. This plugin is a replacement for the individual JDBC plugins.

You can install this plugin by running

`bin/logstash-plugin install logstash-integration-jdbc`

If this issue is still occurring for you, please open a follow-up issue in the [logstash-integration-jdbc repo](https://github.com/logstash-plugins/logstash-integration-jdbc/issues).
