### ISSUE TITLE
Is there any option or way to turn off stdout related options?

### ISSUE THREAD

**Issue by chosh31** [elastic/logstash#12480]
When using the `logstash elasticsearch output`, it can be seen that `stdout` logging is displayed even without additional `stdout` setting.

Is there any option or way to turn off `stdout` related options?

**Comment by kares** [comment]
There isn't an official way, since you can simply redirect stdout logging.
If that is too much there's a Log4J configuration, removing [this line](https://github.com/elastic/logstash/blob/v7.11.2/config/log4j2.properties#L80) should do the trick. 
Please use our [forums](https://discuss.elastic.co/c/elastic-stack/logstash/14) to ask questions next time.
