### ISSUE TITLE
Logstash 7.8 version Kakfa v2.4 and v1.1 SSL handshake failure

### ISSUE THREAD

**Issue by dannadanaveenreddy** [elastic/logstash#12529]
We are trying to upgrade our Logstash from 6x to 7x. We use SSL mechanism for Kafka authentication. with same conf file able to connect to kafka (with same certs in 6.2) but not able to in 7.8. tried disabling 'ssl_endpoint_identification_algorithm' by making it null and "". but no luck
my output:
kafka {
    codec => json {
            }
	bootstrap_servers => "localhost:9092"
	ssl_truststore_location => "C:/Users/windows/client.truststore.jks"
    ssl_truststore_password => "yyyy@uuu"
    ssl_truststore_type => "JKS"
	ssl_keystore_location => "C:/Users/windows/client.keystore.jks"
	ssl_keystore_password => "yyy@uuuu"
    ssl_keystore_type => "JKS"
    security_protocol => "SSL"
	ssl_endpoint_identification_algorithm => ""
    request_timeout_ms => "5000"
    topic_id => "my_topic"
    client_id => "my_topic_client"
    id => "my_topic_id"
    }

- Version: Logstash 7.8, Kafka v2.4 and v1.1
- Operating System: Window and unix
- Config File 
- Sample Data:
- Steps to Reproduce:

**Comment by kuradakis** [comment]
Hi

I am faced this type of error(logstash 7.10 -> kafka 2.6 with jks) as well and looks like this is fixed in 7.10.1

Logstash dropped error:
 Failed authentication with /10.99.97.99 (SSL handshake failed)

https://www.elastic.co/guide/en/logstash/current/logstash-7-10-1.html
Kafka Integration - 10.5.3
    Fix: set (optional) truststore when endpoint id check disabled. Since 10.1.0 disabling server host-name verification (ssl_endpoint_identification_algorithm => "") did not allow the (output) plugin to set ssl_truststore_location => "..." #60


This problem is existing between 7.8.0-7.10.0

**Comment by dannadanaveenreddy** [comment]
Thanks @kuradakis.
Is there a way to use logstash v7.8 Kafka output with SSL authentication?

**Comment by kuradakis** [comment]
Hi @dannadanaveenreddy 

I would upgrade logstash plugins from later versions.

Just install a logstash 7.10.1 export plugins and install on 7.8 offline.

https://www.elastic.co/guide/en/logstash/current/offline-plugins.html

**Comment by robbavey** [comment]
@dannadanaveenreddy Given that this error appears to have been fixed in more recent versions of `logstash-integration-kafka`, and you can fix your issue by upgrading the plugin as described above by @kuradakis, I am going to go ahead and close this issue. 

If this problem persists after the upgrade, please open up an issue in the [kafka plugin](https://github.com/logstash-plugins/logstash-integration-kafka) project.

@kuradakis Thank you for your help here.
