### ISSUE TITLE
many clearttext pasword and certificate files in running package, but no description in doc. are they useful when running?

### ISSUE THREAD

**Issue by swxEmily** [elastic/logstash#12561]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version: 7.6.2
- Operating System:
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:
- 
![image](https://user-images.githubusercontent.com/43984746/104259765-fd964280-54bc-11eb-8b2b-5b29eee4a776.png)
![image](https://user-images.githubusercontent.com/43984746/104259892-536aea80-54bd-11eb-975f-4c6926dbbbbc.png)

And, many java file, c file in vendor/ path,  can I delete them?

**Comment by yaauie** [comment]
First, if you have a security-related concern about _any_ project, we _highly_ encourage you to reach out using the correct paths. Opening up a public issue about a security concern should only be done after exhausting all other options, as doing so can "tip off" bad actors before maintainers of a project have a chance to address concerns.

> For security vulnerabilities please only send reports to security@elastic.co.
> See https://www.elastic.co/community/security for more information.

That said, this specific report is a non-issue, and I am closing this ticket along with my analysis.

***

The grep of `password = ['"]` yields nothing of concern.

Much of Logstash is implemented in Ruby, which is an _interpreted_ language; as such the source code for libraries (a.k.a. "gems:) we rely on is part of the distribution. These gem artifacts can include commented-out examples, as well as documentation and specs that are not a part of the loadpath (and therefore cannot be executed by applications that use them), but the maintainer has elected to include in their own artifact distribution. Modifying the source code of the libraries we use is risky, since an unskilled edit may change the behaviour in undesired ways.

A brief audit of those you included in the screenshots include:

 - `march_hare` RabbitMQ library internal function to _redact_ sensitive info before it is output to logs ([source](https://github.com/ruby-amqp/march_hare/blob/v4.1.1/lib/march_hare/session.rb#L548))
 - `bundler` (a tool used by `bin/logstash-plugin` to install and update Logstash plugins) vendors code from another library, which has commented-out examples documenting how to set proxy passwords ([source](https://github.com/drbrain/net-http-persistent/blob/v2.9.4/lib/net/http/persistent.rb#L480))
 - `gems` (a library used by `bundler` to define gem artifacts) similarly has a commented-out example ([source](https://github.com/rubygems/gems/blob/v1.2.0/lib/gems/client.rb#L278))
 - the `sequel` gem (used by the JDBC input and filters to facilitate SQL queries against various databases) included its specs in its artifact ([source](https://github.com/jeremyevans/sequel/blob/5.29.0/sequel.gemspec#L22)) but only included the lib on its load-path, so those specs are not reachable by running ruby code ([source](https://github.com/jeremyevans/sequel/blob/5.29.0/sequel.gemspec#L23)); the project has recently changed their behaviour to not include the specs since v5.30.0([source](https://github.com/jeremyevans/sequel/commit/729b65df739d4065f4539b092dc038df9fd4eb98)) and more modern versions of Logstash include the updated sequel ([source](https://github.com/elastic/logstash/blob/v7.10.1/Gemfile.jruby-2.5.lock.release#L613)).

***

The certificate files are also used by the application and its libraries per their own specification. Again auditing the ones you have included in your screenshot:

 - The .pem files inside the `bundler-1.17.3` are used by bundler, which is ruby's dependency manager that is used by `bin/logstash-plugin` when installing and updating plugins ([source](https://github.com/rubygems/bundler/tree/v1.17.3/lib/bundler/ssl_certs)).
 - the `.pem` file inside the `manticore` gem is a public key used as part of its own artifact publishing and validation ([source](https://github.com/cheald/manticore/commits/v0.6.4/gem-public_cert.pem)).
 - the `.pem` files inside the ruby standard library are a part of the standard ruby distribution and mirror those inside the bundler gem
 - the `crt` files inside the AWS SDK gem are used by the AWS SDK, which in turn is used by several plugins that access AWS services (e.g., S3 Input, Cloudwatch Input, S3-SNS-SQS Input, SQS Input)
