### ISSUE TITLE
Sign Logstash RPM w/ SHA256 header for FIPS-enabled Operating Systems

### ISSUE THREAD

**Issue by n0othing** [elastic/logstash#12597]
The Logstash RPM will fail to install on RHEL 8 w/ FIPS mode enabled because it isn't signed with a SHA256 header (see `BZ#1581990` [1]. 

```
[robbie@rob-nix-06 ~]$ sudo rpm -ivh logstash-7.10.2-x86_64.rpm
warning: logstash-7.10.2-x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID d88e42b4: NOKEY
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
        package logstash-1:7.10.2-1.x86_64 does not verify: no digest
```

It's possible to get around this by installing with `--nodigest --nofiledigest` arguments [2], but such a workaround may not be acceptable for certain organizations.

[1] https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/8.0_release_notes/index
[2] https://access.redhat.com/solutions/4460971

**Comment by SeanathanVT** [comment]
@yaauie I see the commit referenced on 2021-07-09, but as of my writing this (and logstash-7.17.5), there is no SHA256 Digest value in the RPM package -- only SHA1 and MD5. We're moving to RHEL 8 and we're experiencing the same "no digest" issue as @n0othing. For comparison, the SHA256 Digest value does appear in the Elasticsearch and Kibana RPM packages (also 7.17.5) alongside the SHA1 and MD5 Digest values.

**Comment by SeanathanVT** [comment]
> Logstash packages already have header and payload sha256 payloads:
> 
> ```
> ❯ rpm --checksig --verbose logstash-8.5.3-x86_64.rpm | grep SHA 
>     Header V4 RSA/SHA512 Signature, key ID d88e42b4: OK
>     Header SHA256 digest: OK
>     Header SHA1 digest: OK
>     Payload SHA256 digest: OK
>     V4 RSA/SHA512 Signature, key ID d88e42b4: OK
> ```
> 
> Compared to elasticsearch, Logstash is only missing this "Payload SHA256 ALT digest":
> 
> ```
> ❯ rpm --checksig --verbose elasticsearch-8.5.3-x86_64.rpm | grep SHA 
>     Header V4 RSA/SHA512 Signature, key ID d88e42b4: OK
>     Header SHA256 digest: OK
>     Header SHA1 digest: OK
>     Payload SHA256 ALT digest: OK
>     Payload SHA256 digest: OK
>     V4 RSA/SHA512 Signature, key ID d88e42b4: OK
> ```
> 
> I'll take a look to see what's missing.

Just to note, you're checking against the Elastic Stack 8 RPMs while the issue we have experienced is on the Elastic Stack 7 baseline. 

The version I referenced above was 7.17.5 and I believe there have been a couple Elastic Stack 7 releases since then. We will obviously be moving to Elastic Stack 8 in the future but for now we're stuck with Elastic Stack 7.

Thank you for investigating!

**Comment by jsvd** [comment]
Recent 7.17.* Logstash RPMs already have the payload digest,

```
❯ rpm --checksig --verbose /Users/joaoduarte/Downloads/logstash-7.17.5-x86_64.rpm
    Header V4 RSA/SHA512 Signature, key ID d88e42b4: OK
    Header SHA1 digest: OK
    V4 RSA/SHA512 Signature, key ID d88e42b4: OK
    MD5 digest: OK
```
vs:

```
❯ rpm --checksig --verbose /Users/joaoduarte/Downloads/logstash-7.17.8-x86_64.rpm
    Header V4 RSA/SHA512 Signature, key ID d88e42b4: OK
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V4 RSA/SHA512 Signature, key ID d88e42b4: OK
    MD5 digest: OK
```

@SeanathanVT any chance you could do a quick check with 7.17.8?

**Comment by Jaraxal** [comment]
Customer reports this is still an issue with 8.6.0.

**Comment by azabbett** [comment]
To add to @Jaraxal 's report, large fed enterprise customer reports two issues that negatively affect their security posture:

- Cannot install LS on RHEL8 FIPS enabled VM without bypassing file digest
- Have to allow untrusted shared libraries

**Customer's first priority is to install on RHEL8 FIPS enabled without bypassing digest**

From support ticket 01310353:

"We are evaluating Elastic 8.x on RHEL8 and its binary compatible derivatives. At OS install from ISO, we use Anaconda / Kickstart to apply the RHEL8 DISA STIG. This includes enabling FIPS mode, enabling fapolicyd (allowlisting), and making /tmp no-exec.

On both Oracle Linux 8 and RHEL8 when FIPs-mode is enabled in the kernel, we are unable to install Logstash without ignoring the file digest. This is an offline install but we pre trust the Elastic GPG Key. Elasticsearch, Kibana, and Beats install fine via yum. This issue is limited to Logstash. The SHA512 hash of the RPM on our image matches the hash [here](https://artifacts.elastic.co/downloads/logstash/logstash-8.6.0-x86_64.rpm.sha512?_gl=1*1e60yc*_ga*MTkwMDAwMzczMy4xNjc0NjU0NDQ4*_ga_Q7TEQDPTH5*MTY3NDY1NDQ0OC4xLjEuMTY3NDY1NTgwMy4wLjAuMA..).

The install failure is likely due to some sort of code signing error. The only way we can install Logstash is by bypassing the file digest: rpm -ivhU --nodigest --nofiledigest. See the yum error below for more details."

```
[root@jnn77840nsya ~]# yum -yv install /etc/deploy/installers/elastic/logstash-8.6.0-x86_64.rpm
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, fapolic
yd, generate_completion_cache, groups-manager, kpatch, needs-restarting, playground, product-id, repoc
losure, repodiff, repograph, repomanage, reposync, subscription-manager, uploadprofile
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register
.

YUM version: 4.7.0
cachedir: /var/cache/dnf
Repository 'ol8_baseos_latest' is missing name in configuration, using id.
Repository 'ol8_appstream' is missing name in configuration, using id.
Repository 'ol8_developer_EPEL' is missing name in configuration, using id.
Repository 'ol8_developer_EPEL_modular' is missing name in configuration, using id.
Repository 'ol8_UEKR7' is missing name in configuration, using id.
User-Agent: constructed: 'libdnf (Red Hat Enterprise Linux 8.7; generic; Linux.x86_64)'
--> Starting dependency resolution
---> Package logstash.x86_64 1:8.6.0-1 will be installed
--> Finished dependency resolution
Dependencies resolved.
======================================================================================================
Package Architecture Version Repository Size
======================================================================================================
Installing:
logstash x86_64 1:8.6.0-1 @commandline 325 M

Transaction Summary
======================================================================================================
Install 1 Package

Total size: 325 M
Installed size: 568 M
Downloading Packages:
Using rpmkeys executable at /usr/bin/rpmkeys to verify signatures
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
Preparing : 1/1
Running scriptlet: logstash-1:8.6.0-1.x86_64 1/1
Installing : logstash-1:8.6.0-1.x86_64 1/1
Error unpacking rpm package logstash-1:8.6.0-1.x86_64
Errors occurred during transaction.
Verifying : logstash-1:8.6.0-1.x86_64 1/1
Completion plugin: Generating completion cache...
Installed products updated.
Failed: logstash-1:8.6.0-1.x86_64

Failed:
logstash-1:8.6.0-1.x86_64

Error: Transaction failed
```
In order to run Logstash we needed to change it's temp directory. This isn't a problem as we achive that by modifying jvm.options. However, we also need to explicitly allow untrusted shared libraries as Logstash attmempts to open a randomized shared library from it's temp directory at startup. This is not ideal as it opens up the OS to any executable referencing any untrusted shared library.

```
[root@jnn77840nsyi ~]# cat /etc/fapolicyd/rules.d/11-essp.rules
# Rules to enable Auto-ESSP to provision and maintain Ansible
allow uid=0 dir=/home/admin/.ansible/tmp
allow uid=1000 dir=/home/admin/.ansible/tmp
allow perm=open all : ftype=application/x-sharedlib trust=0
[root@jnn77840nsyi ~]#
```

There is no way to pre-trust these libraries as Logstash writes them to it's temp directory and the filenames are randomized. Is there a better method for running Logstash than globally allowing executables to load untrusted shared libraries?

**Comment by jsvd** [comment]
wrt digest mismatch, Logstash artifact tasks aren't setting the `_binary_filedigest_algorithm` value to build RPMs, so by default it's MD5, which isn't accepted when FIPS is enabled in RHEL.
Building a custom RPM after patch:
```~/elastic/logstash 8.6* 11m 22s
❯ git diff
diff --git a/rakelib/artifacts.rake b/rakelib/artifacts.rake
index f69fe2d44..2fe1aa16f 100644
--- a/rakelib/artifacts.rake
+++ b/rakelib/artifacts.rake
@@ -640,6 +640,7 @@ namespace "artifact" do
         out.attributes[:rpm_user] = "root"
         out.attributes[:rpm_group] = "root"
         out.attributes[:rpm_os] = "linux"
+        out.attributes[:rpm_digest] = "sha256"
         out.config_files << "/etc/logstash/startup.options"
         out.config_files << "/etc/logstash/jvm.options"
         out.config_files << "/etc/logstash/log4j2.properties"
```

Installs correctly:

```
logstash-8.6.1-x86_64.rpm:
    Header V4 RSA/SHA512 Signature, key ID d88e42b4: OK
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V4 RSA/SHA512 Signature, key ID d88e42b4: OK

[joaoduarte@jsvd-fips ~]$ rpm --checksig -v logstash-8.6.2-SNAPSHOT-x86_64.rpm 
logstash-8.6.2-SNAPSHOT-x86_64.rpm:
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK

[joaoduarte@jsvd-fips ~]$ sudo rpm -Uvh logstash-8.6.1-x86_64.rpm 
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:logstash-1:8.6.1-1               ################################# [100%]
error: unpacking of archive failed on file /etc/default/logstash;63da885d: cpio: Digest mismatch
error: logstash-1:8.6.1-1.x86_64: install failed

[joaoduarte@jsvd-fips ~]$ sudo rpm -Uvh logstash-8.6.2-SNAPSHOT-x86_64.rpm 
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:logstash-1:8.6.2~SNAPSHOT-1      ################################# [100%]
```
