### ISSUE TITLE
Logstash 7.11.0 fails with "Invalid FieldReference: `${(new java.io.BufferedReader" problem 

### ISSUE THREAD

**Issue by SrikrishnaBingi** [elastic/logstash#12703]
Through k8s, I am using Logstash 7.11.0 to extract data from Internal ES index into BigQuery.  The logstash pipeline uses latest version of logstash elasticsearch input plugin (ver 4.5.0 as of today) but it encounters an error "Invalid FieldReference" while fetching data and keeps restarting the pipeline for the same date range.

Error snippet:
_[ERROR] 2021-02-25 17:57:14.044 [[main]<elasticsearch] javapipeline - A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:main
  Plugin: <LogStash::Inputs::Elasticsearch password=><password>, hosts=> <scrubed the host info>
  Error: Invalid FieldReference: `${(new java.io.BufferedReader(new java.io.InputStreamReader(((new java.lang.ProcessBuilder(new java.lang.String[]{"timeout","11"})).start()).getInputStream()))).readLine()}${(new java.io.BufferedReader(new java.io.InputStreamReader(((new java.lang.ProcessBuilder(new java.lang.String[]{"sleep","11"})).start()).getInputStream()))).readLine()}`
  Exception: Java::OrgLogstash::FieldReference::IllegalSyntaxException
  Stack: org.logstash.FieldReference$StrictTokenizer.tokenize(FieldReference.java:312)_

Initially I suspected that it could be an issue with the date column I used to incrementally extract data but the above seems to be plugin or logstash code issue.

Error log is attached with this ticket.  I can provide the logstash config file and k8s pod spec on request. Please suggest the resolution.

[error.log](https://github.com/elastic/logstash/files/6045017/error.log)

**Comment by kares** [comment]
The error message in this case is clear: `${(new java.io.BufferedReader(new java.io.InputStreamReader(((new java.lang.ProcessBuilder(new java.lang.String[]{"timeout","11"})).start()).getInputStream()))).readLine()}${(new java.io.BufferedReader(new java.io.InputStreamReader(((new java.lang.ProcessBuilder(new java.lang.String[]{"sleep","11"})).start()).getInputStream()))).readLine()}` isn't a valid field reference syntax.

Not sure how this is a bug report, could you please clarify or otherwise close the issue?
For now it seems a user problem with the LS configuration file.
