### ISSUE TITLE
logstash memory exceeded what -Xmx setting

### ISSUE THREAD

**Issue by jaxsong** [elastic/logstash#12747]
Hi, I use logstash to collect server log, everything is ok, but, the logstash runtime memory is amost 1GB, Its too much, and I set `-Xms=256m, -Xmx=512m` in jvm.options file, but, the command `htop` showed, logstash run memory exceed what I set, actual it's about 900M , how can I limit the logstash memory use below 512M? 
- Version: 7.10.2
- Operating System: ubuntu:18.04
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by kares** [comment]
Hey, sorry but this is a bit tricky since there's no explicit setting of "max memory" within the JVM.
Heap should be the main part but there's "other" (native) memory bits a Java process will need (for JIT compiling native code, thread stacks are allocated outside heap, manually allocated direct memory etc.). So the total is going to depend on thread count, direct buffer usage etc (which are than specific to which LS plugins you're using).

Some reading: https://jelastic.com/blog/java-ram-usage-in-containers-top-5-tips-not-to-lose-your-memory/

Some of these could be limited but you'll get into a slippery territory trying to squeeze this into 512M.

Going to close this issue as invalid, since `-Xmx` setting does not mean maximum process memory.
