### ISSUE TITLE
Logstash RPM and DEB incorrect permissions

### ISSUE THREAD

**Issue by joshbressers** [elastic/logstash#12771]
If we look at the file ownership of the Logstash RPM and DEB packages many of the files are owned by logstash:logstash.

The modern practice is to have those files owned by root:root to prevent accidental modification by the logstash user in this case.

Here is the Debian guidance on this (the RPM guidance is functionally the same)
https://www.debian.org/doc/debian-policy/ch-files.html#permissions-and-owners

**Comment by farrp** [comment]
Thank you for opening this issue. It is very dangerous for network demons in particular to have the ability to modify their own code or configurations. At this point all of our Logstash servers fail compliance checks. The problem is not so much accidental modification as it is the potential for malicious modification in the case of a compromise.
