### ISSUE TITLE
Logstash fails to install from redhat 8 on FIPS machine

### ISSUE THREAD

**Issue by justchris1** [elastic/logstash#12853]
Ona a RedHat 8.3 machine with a full update, Logstash fails to install (although with a 'Success' status as far as dnf is concerned) on a FIPS machine.

**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`)
Logstash won't install, so I can't get to bin/logstash, but the RPM version is 7.1.1-1. 
2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker)
Redhat RPM via the Elasticsearch OSS yum/dnf server.
3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes)
Not installed yet.

**Plugins installed**: (`bin/logstash-plugin list --verbose`)
Installation fails

**JVM** (e.g. `java -version`):
openjdk 11.0.11 2021-04-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.11+9-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9-LTS, mixed mode, sharing)

If the affected version of Logstash is 7.9 (or earlier), or if it is NOT using the bundled JDK or using the 'no-jdk' version in 7.10 (or higher), please provide the following information:

1. JVM version (`java -version`)
2. JVM installation source (e.g. from the Operating System's package manager, from source, etc).
3. Value of the `JAVA_HOME` environment variable if set.

**OS version** (`uname -a` if on a Unix-like system):
RedHat 8.3

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) pipeline definition(s), settings, locale, etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. On a FIPS enabled, RedHat 8.3 with current patches, issue: sudo dnf install logstash

**Provide logs (if relevant)**:

```
> dnf install logstash
Last metadata expiration check: 1:23:55 ago on Tue 27 Apr 2021 02:31:45 PM EDT.
Dependencies resolved.
===========================================================================================================================================================================================================
 Package                                         Architecture                                  Version                                           Repository                                           Size
===========================================================================================================================================================================================================
Installing:
 logstash                                        noarch                                        1:7.1.1-1                                         elasticstack                                        164 M

Transaction Summary
===========================================================================================================================================================================================================
Install  1 Package

Total download size: 164 M
Installed size: 284 M
Is this ok [y/N]: y
Downloading Packages:
logstash-oss-7.1.1.rpm                                                                                                                                                      17 MB/s | 164 MB     00:09    
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                       17 MB/s | 164 MB     00:09     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                   1/1 
  Running scriptlet: logstash-1:7.1.1-1.noarch                                                                                                                                                         1/1 
  Installing       : logstash-1:7.1.1-1.noarch                                                                                                                                                         1/1 
  Running scriptlet: logstash-1:7.1.1-1.noarch                                                                                                                                                         1/1 
Using provided startup.options file: /etc/logstash/startup.options
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Unhandled Java exception: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError: null
                 forName0 at java/lang/Class.java:-2
                  forName at java/lang/Class.java:315
    setNonRestrictedJava8 at org/jruby/util/SecurityHelper.java:62
  checkCryptoRestrictions at org/jruby/util/SecurityHelper.java:37
                     init at org/jruby/Ruby.java:1294
              newInstance at org/jruby/Ruby.java:370
              internalRun at org/jruby/Main.java:273
                      run at org/jruby/Main.java:234
                     main at org/jruby/Main.java:206

Caused by:
java.security.ProviderException: NSS module not available: fips
                   <init> at sun/security/pkcs11/SunPKCS11.java:277
                      run at sun/security/pkcs11/SunPKCS11.java:112
                      run at sun/security/pkcs11/SunPKCS11.java:109
             doPrivileged at java/security/AccessController.java:-2
                configure at sun/security/pkcs11/SunPKCS11.java:109
                      run at sun/security/jca/ProviderConfig.java:251
                      run at sun/security/jca/ProviderConfig.java:242
             doPrivileged at java/security/AccessController.java:-2
           doLoadProvider at sun/security/jca/ProviderConfig.java:242
              getProvider at sun/security/jca/ProviderConfig.java:222
              getProvider at sun/security/jca/ProviderList.java:266
                      get at sun/security/jca/ProviderList.java:156
                      get at sun/security/jca/ProviderList.java:151
                     next at java/util/AbstractList.java:371
           getDefaultPRNG at java/security/SecureRandom.java:264
                   <init> at java/security/SecureRandom.java:219
                 <clinit> at javax/crypto/JceSecurity.java:80
                 forName0 at java/lang/Class.java:-2
                  forName at java/lang/Class.java:315
    setNonRestrictedJava8 at org/jruby/util/SecurityHelper.java:62
  checkCryptoRestrictions at org/jruby/util/SecurityHelper.java:37
                     init at org/jruby/Ruby.java:1294
              newInstance at org/jruby/Ruby.java:370
              internalRun at org/jruby/Main.java:273
                      run at org/jruby/Main.java:234
                     main at org/jruby/Main.java:206

Unable to install system startup script for Logstash.
chmod: cannot access '/etc/default/logstash': No such file or directory
warning: %post(logstash-1:7.1.1-1.noarch) scriptlet failed, exit status 1

Error in POSTIN scriptlet in rpm package logstash
  Verifying        : logstash-1:7.1.1-1.noarch                                                                                                                                                         1/1 
Installed products updated.

Installed:
  logstash-1:7.1.1-1.noarch                                                                                                                                                                                

Complete!
```

**Comment by roaksoax** [comment]
Hi @justchris1 ,

Thank you for taking the time to report this issue. Please note that Logstash 7.1.x is already EOL (see https://www.elastic.co/support/eol) and is no longer supported.

That said, I believe this issue may have already been fixed and is available in the latest supported version of Logstash (7.12), which I would encourage you to test. Also note I have not been able to reproduce this issue, although I've not tested on a FIPS system (since I dont have access to one). On a amd64, I see the following:

`[root@centos-8-install ~]# cat /etc/redhat-release 
CentOS Linux release 8.3.2011
[root@centos-8-install ~]# dnf install logstash
Last metadata expiration check: 0:00:13 ago on Fri Apr 30 14:33:34 2021.
Dependencies resolved.
=======================================================================================================================================================================================================================
 Package                                            Architecture                                     Version                                              Repository                                              Size
=======================================================================================================================================================================================================================
Installing:
 logstash                                           x86_64                                           1:7.12.1-1                                           logstash-7.x                                           353 M

Transaction Summary
=======================================================================================================================================================================================================================
Install  1 Package

Total download size: 353 M
Installed size: 607 M
Is this ok [y/N]: y
Downloading Packages:
logstash-7.12.1-x86_64.rpm                                                                                                                                                              28 MB/s | 353 MB     00:12    
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                   28 MB/s | 353 MB     00:12     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                               1/1 
  Running scriptlet: logstash-1:7.12.1-1.x86_64                                                                                                                                                                    1/1 
  Installing       : logstash-1:7.12.1-1.x86_64                                                                                                                                                                    1/1 
  Running scriptlet: logstash-1:7.12.1-1.x86_64                                                                                                                                                                    1/1 
Using bundled JDK: /usr/share/logstash/jdk
Using provided startup.options file: /etc/logstash/startup.options
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/pleaserun-0.0.32/lib/pleaserun/platform/base.rb:112: warning: constant ::Fixnum is deprecated
Successfully created system startup script for Logstash

  Verifying        : logstash-1:7.12.1-1.x86_64                                                                                                                                                                    1/1 

Installed:
  logstash-1:7.12.1-1.x86_64                                                                                                                                                                                           

Complete!
`

In the meantime, I'll mark this issue as 'needs-info' and will wait a few days before closing the issue and/or you are unable to reproduce in the latest supported version.

Thank you!

**Comment by justchris1** [comment]
Thanks for the detailed answer.  I really didn't know what the most recent version was and scratched my head as to why such an old version would be installed.  In case anyone stumbles across this, I think the issue was the confusing nomenclature of the logstash packages.  I had installed the yum repo to the oss version of the repo and didn't realize that the package name should change from logstash to logstash-oss.  However, there is apparently still a version of the just plain 'logstash' installation target in the oss repository and it is version 7.1, a very old version as @roaksoax points out.  Those combinations are the cause of the issue, I suspect.  I will resolve by choosing the better installation target.
