### ISSUE TITLE
kv should always overwrite the target field

### ISSUE THREAD

**Issue by avleen** [elastic/logstash#1315]
In the event that kv has nothing to do, it doesn't write the target field.
If your source and target are the same, this can be a problem: You expect the target to always be a hash but when kv took no action, it's still a string.

This in turn breaks inserting things into ES if ES is expecting an object.

**Comment by jordansissel** [comment]
@avleen If I'm reading your report correctly, you're saying that if you have `kv { source => "foo" target => "foo" }` and an event `{ "foo": "bar" }` (no kv to parse!) that the result should be `{ "foo": { } }` ?

**Comment by jordansissel** [comment]
Example -

```
% bin/logstash -e 'filter { kv { source => "message" target => "message" } }'
hello=world
{
  "message"    => {
    "hello" => "world"
  },
  ...
}

fancy pants
{
  "message"    => "fancy pants",
  ...
}
```

In the 2nd case, no kv was matched and left the original source alone (as a string). This would cause Elasticsearch to be upset if it the field were mapped as an object, right?

I'm not sure what the best default behavior would be, here. 

Options when `@source` == `@target`:
* Promote `@target` to be empty hash `{}` as proposed by @avleen (I think?). This would cause data loss because we obliterate the old value.
* Promote `@target` to be a hash of `{ "_original" => <original field value> }` so it's still a hash but we don't lose data.

Thoughts?

**Comment by avleen** [comment]
That's correct. This comes down to object mappings and potential loss of
data.

@target should always become a hash. Either it ends up empty, or it has
some data. But it's always a hash. If it's empty, just drop it at the end
of the run.

I think the user should get a choice in whether @target is overwritten, or
if the original is preserved. Different people may expect different things.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-kv/issues/11. Let's continue the discussion there! :)
