### ISSUE TITLE
fix for CVE-2021-44228 in logstash 6.8.21 incomplete due to log4j 2.9.1 in logstash-input-tcp-5.2.3.jar?

### ISSUE THREAD

**Issue by RolandOtta** [elastic/logstash#13522]
we have recognized that logstash-input-tcp-5.2.3.jar in logstash 6.8.21 still contains log4j-core 2.9.1

does this mean that the fix for CVE-2021-44228 in the released logstash 6.8.21 is incomplete?

**Comment by jsvd** [comment]
While the newly released Logstash 6.8.21 contains a jar that bundles a vulnerable version of log4j-core, no Jndi lookups will happen once the JndiLookup.class is removed from the logstash core's log4j-core jar and Logstash is restarted.

The fact that the logj4-core from core is the only one loaded was confirmed through code analysis and experimentation, but if you'd like to remove the class, the command is:

```
zip -q -d <LOGSTASH_HOME>/vendor/**/*/logstash*tcp*.jar org/apache/logging/log4j/core/lookup/JndiLookup.class
```

We will update the [discuss advisory](https://discuss.elastic.co/t/apache-log4j2-remote-code-execution-rce-vulnerability-cve-2021-44228-esa-2021-31/291476) to clarify this point but otherwise, unless we find some way how this jar can become an attack vector, we don't foresee doing another 6.8 patch release.

**Comment by RolandOtta** [comment]
i think it is not a good practice to wait with replacing the vulnerable jar until you eventually find out how to exploit it

**Comment by vemonet** [comment]
The whole purpose of logstash is to log user input, it is not responsible to ship it with an executable containing a known vulnerability that is triggered through user input logging, and asking your user to manually fix it with a shady zip command to make sure your product is safe.

More generally it is quite worrying that you are not able to not include executable that you don't want in your final build. Is Java packaging that bad?

**Comment by michaelpaesold** [comment]
@jsvd In light of the global impact that an exploitable issue in logstash would have, I sincerely ask you to reevaluate your decision of waiting for proof-of-exploit before implementing safeguards for a potential one.

**Comment by jsvd** [comment]
I have updated my comment above to clarify: on 6.8.21 no command is needed. Logstash core will load the patched log4j 2.15.0. To load the one from the tcp input you'd have to create a separate classloader and load it there, but if you're able to do that you already have permissions to do that and much more.

**Comment by patelprakashp** [comment]
@jsvd - It would be much appreciated if we fix the issue with 2.16 in 6.8 Logstash version.

**Comment by jsvd** [comment]
There is an ongoing discussion about a Log4j recursion DoS issue, so we're still analyzing the impacts of new reports and the potential of a new 2.17.0 log4j version.

**Comment by jsvd** [comment]
Logstash 6.8.22 and 7.16.2 have been released with Log4j 2.17.0 https://www.elastic.co/blog/new-elasticsearch-and-logstash-releases-upgrade-apache-log4j2

**Comment by patelprakashp** [comment]
@jsvd - Docker Hub don't have the 6.8.22 version of Logstash , can someone please update ?

**Comment by kares** [comment]
@patelprakashp docker hub has been pushed lately and now include both 7.16.2 and 6.8.22 [tags](https://hub.docker.com/_/logstash?tab=tags)

**Comment by patelprakashp** [comment]
> @patelprakashp docker hub has been pushed lately and now include both 7.16.2 and 6.8.22 [tags](https://hub.docker.com/_/logstash?tab=tags)

Thank you very much.
