### ISSUE TITLE
undefined local variable

### ISSUE THREAD

**Issue by AhmadManzoor** [elastic/logstash#13919]
#### Tell us about the issue

I am trying to use aggregate function to make list of a specific field I am following an example as mentioned in the below URL. I am having error of undefined local variable.
**Description:**  
here is my logstash conf:

 ```

LS_JAVA_OPTS="-Xmx16g -Xms1g" ./logstash -e 'input {
    jdbc {
        jdbc_driver_library => "mysql-connector-java-8.0.28.jar"
        jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
        jdbc_connection_string =>"****"
        jdbc_user => "****"
        jdbc_password => "****"
        statement => "SELECT TBSNO.TBItem_ID as product_id *******;"
        prepared_statement_bind_values  => ["*","*" ******]
        prepared_statement_name => "products"
        use_prepared_statements => true
        }
}
filter {
     aggregate {
       task_id => "%{product_id}"
       code => "
         map['product_id'] ||= event.get('product_id')
         map['sleeve'] ||= []
         map['sleeve'] << {'sleeve' => event.get('sleeves')}

         map['pattern'] ||= []
         map['pattern'] << {'pattern' => event.get('patterns')}


         event.cancel()
       "
       push_previous_map_as_event => true
       timeout => 3
     }
     
   }
````
*** are put trim the query as this is a large complex query, just wanted o give you an idea here.

I am having the error aggregation exception undefined local variable product_id

**URL:** https://www.elastic.co/guide/en/logstash/current/plugins-filters-aggregate.html#plugins-filters-aggregate-example4

**Comment by yaauie** [comment]
In your pasted output it appears that the plugin was initialized with code that is _different_ than the pipeline configuration you initially pasted, including a number of unquoted strings that the Ruby interpreter interprets as local variable references (`product_id`, `sleeve`, `sleeves`, `pattern`, etc.)

**Comment by yaauie** [comment]
@AhmadManzoor I believe that the issue is that you are supplying the pipeline as a part of the command-line with `-e` (`--config.string`), using single-quotes to encapsulate the entire pipeline config, but the pipeline config _contains_ single-quotes so your shell is concatenating the quoted bits and the unquoted bits together, effectively swallowing the quotes around the string keys. I believe you will have better luck using a pipeline config _file_ and using `-f` (`--path.config`) to reference that file. 

A similar example that doesn't include Logstash:

~~~
╭─{ yaauie@maybe:~ }
╰─○ echo 'hello'world'this'
helloworldthis
[success]
~~~
