### ISSUE TITLE
Converting Time to Logstash::Timestamp has discrepancy in Logstash 8

### ISSUE THREAD

**Issue by kaisecheng** [elastic/logstash#14088]
**Description of the problem including expected versus actual behavior**:

The timestamp `2000-01-01T05:00:00.120Z` is expected to give the same hash value in versions 7.x and 8. 
Running the following example in 7.17.0 and 8.1.1 give different fingerprint result
```
input {
  generator {
    count => 1
  }
}
filter {
  ruby {
    code => "event.set('[logstash_received_at]' , Time.at(946702800.12));"
  }
  fingerprint {
    source => ["logstash_received_at"]
  }
}
output {
  stdout { codec => rubydebug {}
}
```

In 7.17,  
"logstash_received_at" => 2000-01-01T05:00:00.120Z
"fingerprint" => "51f66657c477149d22a6d926003a647f445ff6a1"

In 8.x, 
"logstash_received_at" => 2000-01-01T05:00:00.120000004Z
"hash" => "15ab32dd0ae7ae8c6d28de1ad6f6e2705dee7224"

There is a breaking change regarding [timestamp](https://github.com/elastic/logstash/pull/12797) 
The expected behavior in the above example is to reserve milliseconds and not to add nanoseconds in version 8.x

**Provide logs (if relevant)**:

**Comment by yaauie** [comment]
This is caused by a float precision where the decimal value `946702800.12` cannot be precisely represented in a `Float` (which is documented to _"represent **inexact** real numbers using the native architecture's double-precision floating point representation"_[*](https://ruby-doc.org/core-2.6.3/Float.html)).

We can reproduce it in pure ruby (without Logstash) by providing a `Float` as the argument to Ruby's `Time::at(seconds_with_frac)` 😩 

~~~ ruby
Time.at(946702800.12).nsec #=>  120000004
Time.at(Float('946702800.12')).nsec # => 120000004
~~~

There are several ways around it:
~~~ ruby
# providing a `Rational` or `BigDecimal` to `Time::at(seconds_with_frac)`
Time.at(946702800.12.rationalize).nsec #=> 120000000
Time.at(Rational(94670280012,100)).nsec #=> 120000000
Time.at(BigDecimal('946702800.12')).nsec #=> 120000000

# using a different overload of `Time::at`:
Time.at(946702800, 120, :millisecond).nsec # => 120000000

# or otherwise parsing string input
Time.iso8601("2000-01-01T05:00:00.120Z").nsec # => 120000000
Time.parse("2000-01-01T05:00:00.120Z").nsec # => 120000000
~~~

**Comment by kaisecheng** [comment]
This is related to the breaking change in version 8, as fractional seconds are different in versions 7 and 8, the hash value will be different.
