### ISSUE TITLE
Add GeoIP db to a know path in docker image

### ISSUE THREAD

**Issue by ThorbenJ** [elastic/logstash#15071]
Good day.

There are other plugins and such that need access to the GeoIP db that comes with logstash.
The paths to these files need to be given in the pipeline config. (E.g. for logstash-filter-elastic_integration)
Currently the GeoIP db files are with a gem, so you have to know the versions of things used in a particular docker image to be able to configure a pipeline to run in that image. These path might change when you update the docker image, thus one would need to also update the pipeline config.

consider:
```
logstash@logstash-65dcf4b5d7-9wqw5:~$ find /usr -iname \*geo\*mmdb -type f
/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-filter-geoip-7.2.13-java/vendor/GeoLite2-ASN.mmdb
/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-filter-geoip-7.2.13-java/vendor/GeoLite2-City.mmdb
```

At minimum one could update /usr/local/bin/docker-entrypoint to include something like:
```
mkdir -p /usr/share/logstash/data/geoipdb
find /usr -iname \*geo\*mmdb -type f -exec ln -s \{\} /usr/share/logstash/data/geoipdb/ \;
```

Although a cleaner solution to get a known path to these files is welcome.

Thanks,
Thorben

**Comment by yaauie** [comment]
Note: The GeoIP databases that are vendored inside of our GeoIP filter are increasingly-stale, and I don't see a path to them being updated. Their presence is an internal implementation detail of the GeoIP plugin and they should not be relied upon external to that plugin (including direct reference from your pipelines).

In ~2019 MaxMind halted publication and updates of an openly licensed database and now exclusively publishes databases that are bound by a EULA that effectively prevents them from being vendored. Our Elastic-licensed complete distribution of Logstash includes a GeoIP database manager that periodically retrieves updated databases from an Elasticsearch cluster, and the GeoIP filter for Logstash subscribes to a managed database so that it can run with an aleays-up-to-date EULA-bound database. Our goal is to adapt that database manager for use by other plugins and to provide it as part of the API we expose to plugins, so that other plugins can use it too.

It may be reasonable in the mean-time to define your pipeline to reference `geoip_database_path => "${GEOIP_DATABASE_PATH}`, and to modify your dockerfile to (a) copy your own licensed database into the container and (b) export the environment variable so that it is available to the pipeline once Logstash starts up.

**Comment by ThorbenJ** [comment]
I did not know about the database download manager in the geoip filter, that would download newer files once running.

So in a container, if any of your pipelines has the geoip filter then `/usr/share/logstash/data/plugins/filters/geoip/` will be updated with the latest files. So other plugins can be pointed there ^

Removing the assumption that you have a geoip filter, the following pre-start script works to prep a container:
```
mkdir /tmp/ls_init
echo '{"source":{"ip":"1.2.3.4"}}' | logstash --path.settings=/tmp/ls_init -e 'input{ stdin{ codec=>json } } filter{ geoip{ source => "[source][ip]" } }'
```

This will lead to the DB being downloaded. Also path.settings is overridden to an empty path to force default settings; to ensure this always works. This avoids, for example, when "-e" is disabled by an elasticsearch managed logstash.

I am closing this issue, as I understand there are plans around decoupling the database download manager from the geoip plugin, thus the work around above will no longer be needed.

**Comment by yaauie** [comment]
> So in a container, if any of your pipelines has the geoip filter then /usr/share/logstash/data/plugins/filters/geoip/ will be updated with the latest files. So other plugins can be pointed there

This _observed behavior_ is an internal implementation detail. The presence of those files in that location are not _promised behavior_, nor is the format that those files are stored in on disk.

The promised behavior is that when the GeoIP filter (and _only_ the GeoIP filter) is run without explicitly providing the path to a database file, it will use a recent EULA-governed database from Logstash's GeoIP database manager, and that as the database manager is able to retrieve updates the GeoIP filter will be notified so that it can use the newer versions to avoid aging out of the EULA.

There is presently _no_ promised behavior with regard to the technology preview of the Elastic Integration filter, which currently requires you to provide your own maxmind databases via file on disk to use Ingest Pipelines with GeoIP Processors. We do plan to connect it to the Logstash GeoIP database manager in the future, but doing so will require some reworking of how the Database Manager handles things to decouple it from the GeoIP Filter's implementation. This reworking _may_ change implementation details such as where those updated files on disk exist, how they are named, or how they are stored.

***

> This will lead to the DB being downloaded

Your workaround certainly seems to work for now, and we won't go out of our way to break the behavior you have observed. I would advise caution with upgrades in the minor series, paying special attention to the release notes for any mention of the GeoIP database manager. Those files will be recent as of when they are retrieved, but the Elastic Integration filter will not notice them being replaced and therefore cannot enforce the maxmind EULA when the version that they loaded on startup ages out of EULA compliance.

**Comment by ThorbenJ** [comment]
Thank you for the clarification!
This is all in the prototype realm anyway.
