### ISSUE TITLE
There are about 800000 log files in my environment, and now logstash is stuck after starting. Is there any solution? You can only collect the latest files

### ISSUE THREAD

**Issue by Alexis-cmyk-a11y** [elastic/logstash#16360]
#### Tell us about the issue

**Description:**  

**URL:** 

Example: https://www.elastic.co/guide/en/logstash/current/introduction.html

**Anything else?**

**Comment by jsvd** [comment]
I apologize for the inconvenience, but this is a usage question, and should be asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.

As a starting point, check if [start_position](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html#plugins-inputs-file-start_position) should be set to "beginning" instead of  "end" (default).
