### ISSUE TITLE
Start logstash on Win10 with error: "could not find java; set JAVA_HOME or ensure java is in PATH"

### ISSUE THREAD

**Issue by XddAdd** [elastic/logstash#16596]
**Logstash information**:
1. Logstash version: logstash Version not detected
2. Logstash installation source: expanded from "logstash-8.15.3-linux-x86_64.tar.gz"
3. How is Logstash being run: bin\logstash.bat (Powershell)

**Plugins installed**: 
Nothing

**JVM** (e.g. `java -version`):

1. JVM version: openjdk version "11.0.0.1" 2023-05-09
2. JVM installation source: expanded from zip
3. Value of the `LS_JAVA_HOME` environment variable if set: not set

**OS version** (`uname -a` if on a Unix-like system):
Windows 10

**Description of the problem including expected versus actual behavior**:
**Steps to reproduce**:
 1. expand "logstash-8.15.3-linux-x86_64.tar.gz"
 2. run bin\logstash.bat on powershell

**Provide logs (if relevant)**:
Using bundled JDK: xxxxx
could not find java; set JAVA_HOME or ensure java is in PATH

**Comment by XddAdd** [comment]
I confirm that I have set the JAVA_HOME environment variable and also added JAVA_HOME/bin to the PATH.

**Comment by kaisecheng** [comment]
Please use -windows-x86_64.tar.gz for Windows OS. The tar gz bundles with jdk and should be able to run with bin\logstash.bat

However, when I checkout source code, build and run locally in Windows, I can see the log hinting to JAVA_HOME, which need to be fixed.
```
$ bin\logstash
"Using system java: "C:\Program Files\Common Files\Oracle\Java\javapath\java.exe""
The system cannot find the path specified.
could not find java; set JAVA_HOME or ensure java is in PATH
```

Since [v8.0.0,](https://www.elastic.co/guide/en/logstash/current/logstash-8-0-0.html) users should set the value of `LS_JAVA_HOME` to the path of their preferred JDK if they wish to use a version other than the bundled JDK. The value of `JAVA_HOME` will be ignored.

Thanks again for reporting the issue
