### ISSUE TITLE
dns.rb SocketError: gethostbyname: name or service not known

### ISSUE THREAD

**Issue by cdenneen** [elastic/logstash#1717]
SocketError: gethostbyname: name or service not known
  gethostbyname at org/jruby/ext/socket/RubySocket.java:286
        resolve at /opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/dns/dns.rb:13
        resolve at /opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/dns.rb:38
           each at org/jruby/RubyArray.java:1613
         inject at org/jruby/RubyEnumerable.java:865
        resolve at /opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/dns.rb:37
        connect at /opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/connection.rb:137
        connect at /opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:406
           call at org/jruby/RubyProc.java:271
          fetch at /opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/pool.rb:48
        connect at /opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:403
        execute at /opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:319
           get! at /opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:217
       register at /opt/logstash/lib/logstash/outputs/elasticsearch_http.rb:117
           each at org/jruby/RubyArray.java:1613
   outputworker at /opt/logstash/lib/logstash/pipeline.rb:220
  start_outputs at /opt/logstash/lib/logstash/pipeline.rb:152

**Comment by rafaltrojniak** [comment]
Hello,
Bumped into that bug few times, and it quite confusing.

Would it be possible to make 'dns resolution' phase part of the configuration parsing/verification ?
IMHO it would be the best if :
- IT would throw error on the 'config check' phase ('logstash -t -f /some/config')
- Cause logstash to return non-0 state when trying to execute
The above assumptions would :
- Allow init-scripts to verify configuration before restarting
- Detect that the service failed to start
- When someone checks and runs logstash agains config with broken host field, will get immediate failure instead of 'Started' .. and crash.
What would you say for such change ?

Not really an expert of how to achieve that on the logstash architecture, especially with so big and important plugin like output-elasticsearch. Can you give me few suggestions ?
- Will failing (throwing exception) in 'register' method achieve goals above
- Is there any other way to achieve goals above ?

**Comment by jsvd** [comment]
elasticsearch_http is deprecated in favor of the `elasticsearch` plugin (which can do http!), if you have this error with that plugin, please let us know over at https://github.com/logstash-plugins/logstash-output-elasticsearch/issues
