### ISSUE TITLE
RFC: Remove ability to run multiple subcommands from bin/logstash

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#1747]
Today, users can do:

`bin/logstash agent -f something.conf -- web`

And they'll get a single process with an agent and a web thingy.

I don't think anyone uses this, and it mostly confuses users.

---

For clarity, I am proposing removing the ability to run multiple 'subcommands' simultaneously. "bin/logstash web" is staying because it is really useful for first-time users, demos, and proof-of-concepts work.

---

I'd like to remove this function (multiple subprocesses) and in doing so clean up a whole bunch of nasty code in `lib/logstash/runner.rb`.

If you depend on this feature, please let me know.

---

**Comment by nehaljwani** [comment]
Someone should update this thread: https://logstash.jira.com/browse/LOGSTASH-2267
I was really hoping to use this feature. Seems I am late.

**Comment by untergeek** [comment]
@nehaljwani We are no longer using JIRA as a ticketing system.  If you look at the 3 GitHub issues linked in the last comment you'll see some of what we're planning for the future.

Future versions of Logstash will be API driven, rather than command-line.  This will allow us to have the same kind of functionality you are requesting.  Please see [our roadmap](https://www.elastic.co/guide/en/logstash-roadmap/current/index.html) for more information.
