### ISSUE TITLE
SQS input plugin won't restart

### ISSUE THREAD

**Issue by nkts** [elastic/logstash#1776]
Logstash stops reading from SQS but is still running. Error message says plugin is restarting but nothing actually happen.

... :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::S3 type=>\"elb\", credentials=>.... region_endpoint=>\"eu-west-1\", tags=>[\"s3\"]>\n  Error: Socket closed", :level=>:error}

**Comment by jsvd** [comment]
this is likely due to [input workers calling teardown before retry](https://github.com/elasticsearch/logstash/blob/v1.4.2/lib/logstash/pipeline.rb#L173-L179)
since sqs checks for `running?`, at that point the plugin instance is not usable anymore https://github.com/logstash-plugins/logstash-input-sqs/blob/master/lib/logstash/inputs/sqs.rb#L114

This will be fixed as a result of https://github.com/elasticsearch/logstash/issues/2477

**Comment by jordansissel** [comment]
Is this still an issue?

**Comment by nkts** [comment]
Hah, dunno, I think we took different approach after we found this problem - not sure how it is now.

**Comment by untergeek** [comment]
Closing then, as #2477 is the proposed fix.
