### ISSUE TITLE
Redis Input plugin blocks Logstash pipeline shutdown

### ISSUE THREAD

**Issue by RyanMorrison04** [elastic/logstash#1779]
Tested against Mac OS X 10.9.4 and CentOS 6.5 x86-64, with Logstash 1.4.2.

To reproduce:

1. Download and extract the precompiled Logstash archive (https://download.elasticsearch.org/logstash/logstash/logstash-1.4.2.tar.gz)
2. Run Logstash with the below configuration (barebones with only a Redis input):
    ```
    input {
        redis {
            host => ["127.0.0.1"]
            data_type => "list"
            key => "test"
        }
    }

    filter {
    
    }

    output {
        stdout { }
    }
    ```
3. Attempt to shutdown Logstash using CTRL+D.
4. Observe that Logstash does not halt. Using CTRL+C prints ```Interrupt received. Shutting down the pipeline. {:level=>:warn}```, but also does not shut down. Using CTRL+C a number of times after will continue to print the same pipeline shutdown message but has no effect otherwise.

**Comment by josegonzalez** [comment]
Note: I'm unable to get it to close, even with CTRL+D. I have to manually kill the agent using `kill -term` or `kill -9` from another terminal (boo). I'm running under the openjre in case that helps.

Also, here is the config i'm running with:

```
/opt/logstash/bin/logstash -e 'input { redis { key => "metricsd" data_type => "list" } } output { elasticsearch { host => localhost } }'
```

When I had it running under `stdin` instead of `redis`, I was able to kill the agent, though it did take a while for it to die.

I can also provide a Vagrantfile where this issue is reproducible (at least for me) if that helps.

**Comment by colinsurprenant** [comment]
this issue is being discussed in #2871 

In a nutshell, we recently fixed a bunch of issues related to the shutdown sequence in both #2863 and #2928 and also some fixes in the redis input in logstash-plugins/logstash-input-redis#5 - now sending kill -TERM to logstash (or doing ^C) when using the redis input correctly shutdown logstash.

**Comment by suyograo** [comment]
Please reopen this if it is not fixed by RC3
