### ISSUE TITLE
Logstash using 100% cpu

### ISSUE THREAD

**Issue by bartjanssens92** [elastic/logstash#1809]
While installing logstash on a Ubuntu 14.04.01 I saw, after starting logstash, that java started using 100% of the CPU. This was using java openjdk-1.7.0_67 and logstash 1.4.2-1 . After comparing with Centos and the same config I saw that logstash stopped if there was no config in the /etc/logstash/conf.d directory, the same was not true on Ubuntu. After putting a bogus config file in the directory on the Ubuntu machine, the CPU usage dropped back to normal.

**Comment by frederikbosch** [comment]
Yesterday I had similar issues. A few weeks ago I installed logstash and runned the service (Ubuntu 14.04). Because we were upgrading the machine, I had to reboot. Afterwards, I saw CPU spikes by logstash.

In my case it turned out to be logstash-web. While I never started it after installing, it started after rebooting. It took me a while to figure out. I first thought logstash was not started correctly and tried to stop it. This was impossible, not with ```sudo service logstash stop``` neither with ```kill -9```. The process kept respawning. Until I figured out I had to stop logstash-web with ```sudo service logstash-web stop```. Then I ran ```sudo service logstash start``` and everything was normal again.

Question: how do I prevent logstash-web from starting? I already understand it will be deprecated in 1.5.0, but still. In the meanwhile, I would be happy to know. Thanks for the wonderful work you are doing already!

**Comment by tunfastdev** [comment]
Since Ubuntu uses upstart, trying to kill the java processes won't succeed as they will keep respawning according to /etc/init/logstash*.conf. The high CPU usage comes from the fact that logstash uses a lot of CPU time at startup and should calm down after a couple of seconds, but because it dies being unable to bind to port 80 and keeps respawning, it looks as if it's constantly using resources.

If you have the same problem as I did, look at logstash's PIDs and you will notice they change. You should also see Address already in use - bind - Address already in use at the end of /var/log/logstash/logstash.log.

So, we just need to disable logstash-web. On Ubuntu, this can be done with:

    $ echo manual | sudo tee /etc/init/logstash-web.override

To stop logstash-web without rebooting, we use

    $ sudo stop logstash-web

source :http://stackoverflow.com/questions/25867244/100-cpu-usage-after-logstash-install

**Comment by frederikbosch** [comment]
Thank you for the explanation @tunfastdev . That will do I hope!

**Comment by gourneau** [comment]
Thanks @tunfastdev that solved my problems too.

**Comment by MacRonin** [comment]
Additional data point since I have seen variations of this thread where people said it didn't work for them.

In my case when I disabled logstash-web I also stopped getting new data, but when I followed the disable with a reboot things went back to normal. No 100% CPU and processing new log entries.

**Comment by frederikbosch** [comment]
We keep seeing very weird things with Logstash. After applying the command by @tunfastdev (```echo manual | sudo tee /etc/init/logstash-web.override```). The following happends while booting.

```
* Starting Logstash Agent      [OK}
* Starting Logstash Agent      [OK}
* Starting Logstash Agent      [OK}
* Starting Logstash Agent      [OK}
* Starting Logstash Agent      [OK}
```

And this repeated recursively. Logs show that Redis is not running yet. But the case is: we are botting the machine. Now Logstash is preventing any other process to start running.

**Comment by suyograo** [comment]
Looks like https://github.com/elastic/logstash/issues/1809#issuecomment-85226502 suggestion helped. Also logstash-web is removed from 1.5.0. 

If this is still an issue with 1.5.0 can you please open a new issue with details?

**Comment by frederikbosch** [comment]
@suyograo This issue is gone with 1.5.0. However, now logstash does not start at system boot. I have to start it manually by ```sudo service logstash start``` (Ubuntu 14.04). How to start it at boot?

**Comment by arbourd** [comment]
@frederikbosch I had to `sudo update-rc.d logstash defaults` to get the service to run on boot after updating

**Comment by frederikbosch** [comment]
@arbourd Thank you for the reply, I already found out, but very kind to answer my question!
