### ISSUE TITLE
Unclear documentation upstart script.

### ISSUE THREAD

**Issue by pjanzen** [elastic/logstash#1892]
When one installs the *.deb packages and uses service logstash start (or other command) it is unclear for the user where stdout is redirect to. A single line in the documentation would clear this up.

ie: When you start logstash with service logstash start you stdout file is /var/log/upstart/logstash.conf.log

Took me and others quite sometime to figure this out.

Paul.

**Comment by jordansissel** [comment]
Sorry for the confusion. In order to reduce confusion, and before we start producing packages per-linux-distribution, we have removed the upstart script from our deb package. We now only ship the /etc/init.d/logstash management script

We also don't document where that logs to, either, and we should.

**Comment by jordansissel** [comment]
Filed https://github.com/elastic/logstash/issues/3346 to track the deb/rpm init script log file location
