### ISSUE TITLE
File log events get to large and exceed JVM

### ISSUE THREAD

**Issue by stevemd** [elastic/logstash#2015]
While processing a logfile the developer placed the application in debug mode which in turn started creating mutiline events that when matched had a stream of multiple lines that appeared endless and exceeded the parser's memory capacity. 
I would appreciate any help to limit the size of these events (gracefully) so that no multiline event would ever exceed a specified size limit.
Any ideas? 
I am assuming that the code will not go past the grok portion prior to collecting the entire event (which would exceed memory capacity) before I could drop it further down in the filter?
Understanding the flow of the filter would also be useful.

**Comment by colinsurprenant** [comment]
Are you using the multiline codec? if so, this is probably related to logstash-plugins/logstash-codec-multiline#4

**Comment by stevemd** [comment]
yes

**Comment by ph** [comment]
Fixed in the latest version of the multiline plugin 0.1.7, we have added a conditionals  to break on the number of lines and the number of MB, if we go over theses limits the event will be flush to queue and tagged with `multiline_codec_max_lines_reached` or `multiline_codec_max_bytes_reached` this will prevent logstash from accumulating too much events in memory.
