### ISSUE TITLE
Using Logstash with Elasticsearch Percolators

### ISSUE THREAD

**Issue by untergeek** [elastic/logstash#2187]
It would be awesome if there were a way to feed Logstash events into the Elasticsearch Percolator.  

I envision this as being a filter.  The filter would feed events to the percolator and then could use the responses (which include both the matching query _and_ the document) with conditionals to tag events and/or inject new events into the Logstash pipeline.

**Comment by chadrik** [comment]
I'd like to perform some action when the percolator finds a match: for example, send a notification, or run an executable.  Since logstash comes with a robust set of output plugins, it makes sense for to feed the percolator response documents back into the logstash agent as brand new events, such that an appropriate output can be chosen for the new event type (e.g. exec or email).  @untergeek, is that what you mean by "inject new events into the Logstash pipeline"? 

I'm still a bit of a logstash newb, so I have a question about how this could be implemented:  can an event occur without an input generating it?  In other words, would this feature need to be achieved with a filter and an input working in tandem?  e.g. the percolator filter sends the document to a tcp input.

**Comment by untergeek** [comment]
Take a look at how the [elasticsearch input](https://github.com/logstash-plugins/logstash-input-elasticsearch) and the [elasticsearch filter](https://github.com/logstash-plugins/logstash-filter-elasticsearch) work.  Percolators would do something of the sort, where matching events go on, but non-matching events get dropped.

**Comment by NavneetMathpal** [comment]
Hi,

@untergeek Does Logstash gives the functionality to use Percolator ?
I indexed the document using Logstash, but if I need to do some preprocessing using PERCOLATOR how can I do it, is there any possibilities to use percolator in logstash(I want to check whether the doc matches with the query or not if it matches i want to index it in one node and if it does not matches i want to index it in another node),  can it be the possible  ( TO use percolator before indexing the document in logstash ) ?

**Comment by untergeek** [comment]
Not at this time.  Percolator would be a very anomalous object in the Logstash world as it's part input and part output.  It has to be able to _send_ to Elasticsearch, but also act on the response that comes back (presumably, matching queries).  That almost certainly relegates percolator to a filter, where an input provides the "source" document/event, and the filter (like the Elasticsearch filter) runs a percolator and can act on the response.  We do not have this yet.  That's what this issue is about.  Unfortunately this is not as pressing as some other issues have been, so no progress has been made.  If you'd like to fork the elasticsearch filter code and make something, we'd be happy to do some review of it and merge when deemed satisfactory.

**Comment by falkenbt** [comment]
I just stumbled across this:
http://blog.toplog.io/real-time-alerts-with-elasticsearchs-percolator
Looks interesting.

**Comment by untergeek** [comment]
This functionality is covered by the Watcher plugin for elasticsearch now, in conjunction with the [http input plugin](https://github.com/logstash-plugins/logstash-input-http) plugin.  

If the community wants to add this functionality in a plugin, we'd still be pleased to merge it in.

**Comment by consulthys** [comment]
In ES 5.0 alpha2, the [Percolate API has been deprecated](https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_50_percolator.html#_percolate_and_multi_percolator_apis) in favor of a new [`percolate` query](https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-percolate-query.html) (see https://github.com/elastic/elasticsearch/pull/17560) which will run like any other normal DSL query, and thus, allow the use of the existing [`elasticsearch`](https://www.elastic.co/guide/en/logstash/current/plugins-filters-elasticsearch.html) Logstash filter in order to percolate documents on the fly.

**Comment by consulthys** [comment]
Here it is:
https://github.com/consulthys/logstash-filter-percolate

This filter supports percolation of ad-hoc and/or existing documents, e.g.

    # percolates the event itself
    percolate {
        hosts => ["localhost:9200"]
        index => "my_index"
        type => "my_type"
    }

    # percolates the sub-structure available in event['my_field']
    percolate {
        hosts => ["localhost:9200"]
        index => "my_index"
        type => "my_type"
        target => "my_field"
    }

    # percolates the existing document having the id as specified in the event id field
    percolate {
        hosts => ["localhost:9200"]
        index => "my_index"
        type => "my_type"
        id => "%{id}"
    }
