### ISSUE TITLE
Plans for supported ruby / jruby in 2.x ?

### ISSUE THREAD

**Issue by wiibaa** [elastic/logstash#2326]
I'm sure you are aware of this but out of curiosity could you please share your thoughs about your plans for upgrading supported ruby version in logstash **2.x**:
*jruby 1.7 - 1.9mode => jruby 1.7 - 2.0mode => jruby 9000* 
or **faith jump to jruby 9000** (with test-test-test)

Because the MRI disclaimer seems scary as **1.9.3 as one month of support left** meaning that jruby 1.9mode will also be frozen with alignment with MRI:

*Ruby 1.9.3 is now in the security maintenance phase. This means that we never fix bugs except for security issues. And, at this time, the end of the maintenance of 1.9.3 has been scheduled for February next year. We recommend that users of Ruby 1.9.3 should migrate to a newer version as soon as possible.*

I just bumped into this because I asked this naive question to jruby  (https://github.com/jruby/jruby/issues/2411) regarding the timeout configuration caveat described in [dns filter](https://github.com/logstash-plugins/logstash-filter-dns/blob/master/lib/logstash/filters/dns.rb#L25).

**Comment by jordansissel** [comment]
@wiibaa We actively test Logstash master against JRuby 9000 - http://build-eu-00.elasticsearch.org/view/LS%20Other/job/logstash_master_jruby_9k/.

The most recent build of this jenkins job used `jruby 9.0.0.0-SNAPSHOT (2.2.0p0) 2014-12-29`.

I am not worried about JRuby 9000 because we have been testing against it for many weeks now :)

When JRuby 9000 is released, we will upgrade to it. Users will not care about this change because use of ruby is an implementation detail, not an interface generally exposed to users (with small exception: the `ruby` filter)

**Comment by wiibaa** [comment]
@jordansissel thanks for the quick response as always, so it means that my request to jruby (jruby/jruby#2411) could be ignored and wait for jruby9000 ?

**Comment by jordansissel** [comment]
@wiibaa yeah, I think we can wait for jruby9000. If this must be fixed before then, we can monkeypatch Resolv in Logstash or write/use a different dns library.

**Comment by jordansissel** [comment]
Our plans are to follow JRuby to 9000. As for the other things (dns stuff), we can attend to those soon. I don't think we've tested much with Ruby 2.x's stdlib, but we will sono.
