### ISSUE TITLE
MonetDB output support

### ISSUE THREAD

**Issue by talevy** [elastic/logstash#2532]
migrated from: https://logstash.jira.com/browse/LOGSTASH-459

**Comment by purbon** [comment]
MonetDB is a very nice "cassandra alike" database that would be a very nice to have as an output.

In order to have that we might use the "generic" JDBC output/input we aim to create sooner or later, more info on the JDBC documentation for Monet, https://www.monetdb.org/Documentation/Cookbooks/SQLrecipies/Clients/JDBC

Relates to #2476

**Comment by untergeek** [comment]
This will be an "adopt me" ticket.  There doesn't seem to be much demand for this.

**Comment by talevy** [comment]
Closing due to no traction
