### ISSUE TITLE
Elasticsearch Output - Ability to send failed messages to dead letter queue

### ISSUE THREAD

**Issue by benberg86** [elastic/logstash#2533]
As a user of logstash we experience lost messages when:
1) Logstash elasticsearch output is not configured correctly for Elastisearch Cluster, Index, or type
2) Message to be output to elasticsearch cannot be indexed due to be malformed and Elasticsearch errors on the index request (not related to Elasticsearch cluster availability - see retry method has been added in other ticket - this is only for messages that will never be able to be indexed until further changes are made either to message)

We would like the ability to configure a dead letter type queue that either can send message directly to a message queue (RabbitMQ) or possibly write to a local log file that can be configured as a 'failed log' input to logstash and handled with additional filters and outputs in logstash config to ensure these messages are not lost.

An alternative (from a user perspective - not sure how technically feasible this is based on how logstash operates) would be to not acknowledge the message from message queue on input pulling from RabbitMQ until the message has been successfully indexed into Elasticsearch.

**Comment by untergeek** [comment]
Thanks for the ticket.  We already have this in our plans for the future!  We'll use this ticket since you were so kind to add it.

**Comment by benberg86** [comment]
Your welcome - heard it was on the roadmap at an Elasticsearch event yesterday but could not find a good ticket that seemed to be tracking this specifically.
Let me know if I can be any help further defining use cases and/or testing.

**Comment by untergeek** [comment]
Include https://logstash.jira.com/browse/LOGSTASH-720, which is about dropping messages after n retries.

> Sometimes, we just don't care if a message gets lost. What's more important at those times is to just keep trying to get out the latest information as it comes in.
> Not all of our Logstash use is as a reliable log-delivery client. It's sort of become the easiest way to grab, parse, and move the latest news from point A to point B when we can't predict what architectures we'll be working with in the finished product.
> Can we, output-by-output, define whether or not any given output is to be tried again, or to define a max number of retries to send any given message before it's thrown away? Or, for minor blockages, set a size for an internal buffer of messages that are allowed to be retried before we toss out the oldest of the lot? That way we can use a single logstash client/conf to handle both the stuff that needs guaranteed delivery for long-term storage, and the stuff that needs to be quickly delivered or not delivered at all.

**Comment by jsirex** [comment]
Vote for this: elasticsearch down -> logs are in "/dev/null"

**Comment by jordansissel** [comment]
@benberg86 There is a branch with code that will help support the dead letter queue on our roadmap - https://github.com/elasticsearch/logstash/tree/feature/persistent_queue

**Comment by benberg86** [comment]
Excellent - thanks! Likely not the place and bad form, so my apologies in advance (if there is a better channel to ask please let me know!) - is there an estimated timeframe for 2.0? I only ask because we are weighing dropping logstash for a certain portion of our critical events and enhancing an internal app of ours to handle this at least until it is available.

**Comment by jordansissel** [comment]
I don't have any estimate on 2.0's arrival, sorry.

**Comment by suyograo** [comment]
@benberg86 thanks for the issue. See general purpose DLQ discussion here https://github.com/elasticsearch/logstash/issues/2533

**Comment by ralphm** [comment]
Some failures are directly correlated to things like message size or a bad value that wreaks havoc with an field analyser. Possibly, it might make sense to break down the failed 'bulk' of events into smaller batches to minimize the number of events in a failing batch and find the *offending* event and have that dead-lettered.

**Comment by sainio** [comment]
Has this been dropped from the roadmap like the log messages are?

**Comment by shaunrampersad** [comment]
+1
I'm seeing a lot of errors in my logstash log file due to fields not being parsed correctly with my filters. 
Due to the volume of logs I am sending, it becomes difficult to debug. 
It would be nice to have logstash log the failed messages to a specified log file for inspection so that we can adjust the filters.

Elasticsearch v2.0.0
Logstash 2.1.1

The error in logstash.log:
{:timestamp=>"2016-02-04T07:16:25.291000+0200", :message=>"elastichost:9200 failed to respond", :class=>"Manticore::ClientProtocolException", :backtrace=>["/opt/logstash/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:35:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:70:in `call'", "/opt/logstash/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:245:in `call_once'", "/opt/logstash/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:148:in `code'", "/opt/logstash/latest/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/manticore.rb:71:in `perform_request'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/latest/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/base.rb:201:in `perform_request'", "/opt/logstash/latest/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/manticore.rb:54:in `perform_request'", "/opt/logstash/latest/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/client.rb:125:in `perform_request'", "/opt/logstash/latest/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.15/lib/elasticsearch/api/actions/bulk.rb:87:in `bulk'", "/opt/logstash/latest/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.2.0-java/lib/logstash/outputs/elasticsearch/http_client.rb:66:in `non_threadsafe_bulk'", "/opt/logstash/latest/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.2.0-java/lib/logstash/outputs/elasticsearch/http_client.rb:38:in `bulk'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/opt/logstash/latest/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.2.0-java/lib/logstash/outputs/elasticsearch/http_client.rb:38:in `bulk'", "/opt/logstash/latest/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.2.0-java/lib/logstash/outputs/elasticsearch/common.rb:158:in `safe_bulk'", "/opt/logstash/latest/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.2.0-java/lib/logstash/outputs/elasticsearch/common.rb:100:in `submit'", "/opt/logstash/latest/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.2.0-java/lib/logstash/outputs/elasticsearch/common.rb:86:in `retrying_submit'", "/opt/logstash/latest/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.2.0-java/lib/logstash/outputs/elasticsearch/common.rb:56:in `setup_buffer_and_handler'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/latest/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.2.0-java/lib/logstash/outputs/elasticsearch/buffer.rb:109:in `flush_unsafe'", "/opt/logstash/latest/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.2.0-java/lib/logstash/outputs/elasticsearch/buffer.rb:93:in `interval_flush'", "/opt/logstash/latest/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.2.0-java/lib/logstash/outputs/elasticsearch/buffer.rb:82:in `spawn_interval_flusher'", "/opt/logstash/latest/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.2.0-java/lib/logstash/outputs/elasticsearch/buffer.rb:63:in `synchronize'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/opt/logstash/latest/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.2.0-java/lib/logstash/outputs/elasticsearch/buffer.rb:63:in `synchronize'", "/opt/logstash/latest/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.2.0-java/lib/logstash/outputs/elasticsearch/buffer.rb:82:in `spawn_interval_flusher'", "org/jruby/RubyKernel.java:1479:in `loop'", "/opt/logstash/latest/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.2.0-java/lib/logstash/outputs/elasticsearch/buffer.rb:79:in `spawn_interval_flusher'"], :level=>:warn}

**Comment by suyograo** [comment]
Closing this in favor of a general purpose dead letter queue implementation in https://github.com/elastic/logstash/issues/2607
