### ISSUE TITLE
Command line tool for grok pattern discovery

### ISSUE THREAD

**Issue by talevy** [elastic/logstash#2536]
migrated from: https://logstash.jira.com/browse/LOGSTASH-769

With the script from Jordan at ( https://github.com/jordansissel/ruby-grok/blob/master/examples/pattern-discovery.rb ) it should be easy to convert that in a cmd line version and distribute that with a tool set.
Not sure how we could include it in the JAR file though..

**Comment by jordansissel** [comment]
Anyone have interest in this?

**Comment by untergeek** [comment]
With the future of Logstash being more java oriented, it seems to me this should be a different project.  I'm going to close this, but leave the idea open to others to address or re-open as desired.  I think if we ever get to having a GUI for Logstash configuration, we'd incorporate something like that in the interface, rather than at the command-line.

Closing.
