### ISSUE TITLE
Lostash ruby filter throws undefined method strftime

### ISSUE THREAD

**Issue by 91pavan** [elastic/logstash#2762]
For some reason, ruby is throwing exception for this perfectly valid ruby filter code:

```
 ruby {
        code => "
year = (Time.now.year).to_s.force_encoding('UTF-8')
event['time'] = Time.parse(event['@timestamp'].strftime(year+'-%m-%d %H:%M:%S.%L') + ' UTC')
 "
    }
```

```
Exception in filterworker {"exception"=>#<NoMethodError: undefined method `strftime' for "2015-03-04T13:53:25.604Z":LogStash::Timestamp>, "backtrace"=>["(ruby filter code):3:in `register'", 
"org/jruby/RubyProc.java:271:in `call'", "/home/vagrant/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-ruby-0.1.4/lib/logstash/filters/ruby.rb:37:in `filter'", "(eval):3009:in `initialize'", 
"org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:805:in `flat_map'", "(eval):3005:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", 
"org/jruby/RubyEnumerable.java:805:in `flat_map'", "(eval):2927:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/home/vagrant/logstash/lib/logstash/pipeline.rb:275:in `filter'", "/home/vagrant/logstash/lib/logstash/pipeline.rb:209:in `filterworker'", 
"/home/vagrant/logstash/lib/logstash/pipeline.rb:153:in `start_filters'"], :level=>:error}
```

It works just fine in 1.4.2

**Comment by torrancew** [comment]
@91pavan it would appear that currently, `strftime` is not one of the methods that `Logstash::Timestamp` forwards to the native ruby `Time` object.

**Comment by chiriaev** [comment]
Hi, Guys. This should work "event['time']  = Time.parse(event['@timestamp'].to_s).strftime(year+'-%m-%d %H:%M:%S.%L' + ' UTC')"

Regards, Andrei

**Comment by jordansissel** [comment]
Can you provide more detail, such as the full exception and error? I don't
have enough information to make a diagnosis.

**Comment by chiriaev** [comment]
Hi, Jordan. Thanks for getting back. I had a similar issue to Pavan's. Details below. Regards, Andrei

P.S.: the fix was tested on RC2.  
...
+[1.4.3]:

filter{
ruby {
code => "event['_index'] = (((var_time_then = event['@timestamp'].to_i) > ((var_time_now = Time.new.to_i) + 172800)) or (var_time_then < (var_time_now - 777600))) ? 'logstash-fixme-' + Time.at(var_time_now).strftime('%Y.%m.%d') : 'logstash-' + event['@timestamp'].strftime('%Y.%m.%d')"
}
}

+[1.5.0]:

filter{
ruby {
  code => "event['_index'] = (((var_time_then = event['@timestamp'].to_i) > ((var_time_now = Time.new.to_i) + 172800)) or (var_time_then < (var_time_now - 777600))) ? 'logstash-fixme-' + Time.at(var_time_now).strftime('%Y.%m.%d') : 'logstash-' + Time.parse(event['@timestamp'].to_s).strftime('%Y.%m.%d')"
}
}
...

**Comment by remotesyssupport** [comment]
I too had the same issue, when using the above method, as right pointed by @torrancew strftime is not one of the method passed on and hence the error pops up. 

I had to get this workaround in place [dont know if this is the best way to do it]. As my end goal is to have a field with YY-MM-DD HH-MM-SS, so that kibana can display it in table form rather than @timestamp which is in ISO format. Seem it is not that readable by the support staff that use kibana.

So kindly do let me know if there is a better way or if there is a way not to do this extract work for just displaying time in a particular format, as every event now require extra operations so cuts down the performance 

```ruby
input {
  stdin {}
}

filter {
  ruby {
    code=>"       
           tstamp = event['@timestamp'].to_i
           event['time'] = Time.at(tstamp).strftime('%Y-%m-%d %H:%M:%S')
    "
  }
}  

output {     
  stdout { 
     codec => rubydebug 
   } 
}

**Comment by remotesyssupport** [comment]
@jordansissel Would appreciate your comments on the above. Thanks

**Comment by jordansissel** [comment]
You don't need to use strftime, btw.

```
event.sprintf("%{+YYYY-MM-dd HH:mm:ss}")
```

Using the formatting the event object gives you already (using joda-time syntax) should work.

**Comment by jordansissel** [comment]
> As my end goal is ... so that kibana can display it
> Seem it is not that readable by the support staff that use kibana.

This seems like a good time to ask for time formatting features in Kibana :)

**Comment by remotesyssupport** [comment]
Indeed. Kinda of very restrictive for otherwise a flexible frontend

**Comment by remotesyssupport** [comment]
Just putting it here, so others like me have a link:

Time formatting is supported in Kibana 4, so upgrade?

or 

http://stackoverflow.com/questions/23834918/change-the-date-format-in-kibana [havent tested it myself, but might try .. ]

**Comment by remotesyssupport** [comment]
@jordansissel  Thanks a lot. 

Tried this:

```ruby
input {
  stdin {}
}

filter {
  ruby {
    code=>"       
              event['time'] =  event.sprintf('%{+YYYY-MM-dd HH:mm:ss}')
    "
  }
}  

output {     
  stdout { 
     codec => rubydebug 
   } 
} 
```

Output
```
bin/logstash -f test.conf

Logstash startup completed
test

{
       "message" => "test",
      "@version" => "1",
    "@timestamp" => "2015-05-04T20:20:29.074Z",
          "host" => "WatchDog-BE-02",
          "time" => "2015-05-04 20:20:29"
}
```

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-ruby/issues/9. Let's continue the discussion there! :)
