### ISSUE TITLE
Logstash - create aliases dynamically in elasticsearch

### ISSUE THREAD

**Issue by raghav92** [elastic/logstash#2791]
I am using logstash to push data to elasticsearch. I wish to dynamically create/assign an alias using the data from the logs I have just received.

The logs I recv go by this format

```
INFO -- a b c d: msg 
```

The values a,b,c and d change depending upon request

I want to create new aliases for every new combination of a, b, c and d. 

Unable to do this using index templates

My current logstash config is :
```
input {
  file {
    path => "sample.log"
    start_position => beginning
  }
}
filter {
  grok {
    match => { "message" =>"%{LOGLEVEL:log_level} -- %{INT:a} %{INT:b} %{INT:c} %{INT:d}: %{GREEDYDATA:msg}"
    }
  }
}
output {
  stdout { codec => rubydebug }
  elasticsearch {
    host => 'host'
    port => port
    protocol => http
    index => my_index
    template => 'my_template'
    manage_template => true
    template_overwrite => true
  }
}

```

And my template -- This is my current config, need a way to specify aliases dynamically

```
{
    "template": "my_template",
    "aliases": {
        "{a}-alias": {}      // Not working -- Value of 'a' is not substituted
    },
    "settings": {
        "refresh_interval": "5s"
    },
    "mappings": {
        "_default_": {
            "_all": {
                "enabled": false
            },
            "dynamic_templates": [
                {
                    "string_template": {
                        "match": "*",
                        "mapping": {
                            "type": "string",
                            "index": "not_analyzed"
                        },
                        "match_mapping_type": "string"
                    }
                }
            ],
            "properties": {
                "message": {
                    "type": "string",
                    "index": "analyzed"
                },
                "log_level": {
                    "type": "string",
                    "index": "not_analyzed"
                },
                "a": {
                    "type": "string",
                    "index": "not_analyzed"
                },
                "b": {
                    "type": "string",
                    "index": "not_analyzed"
                },
                "c": {
                    "type": "string",
                    "index": "not_analyzed"
                },
                "d": {
                    "type": "string",
                    "index": "not_analyzed"
                },
                "msg": {
                    "type": "string",
                    "index": "not_analyzed"
                }
            }
        }
    }
}

```

Any information regarding this is highly appreciated

**Comment by felipegs** [comment]
+1

**Comment by untergeek** [comment]
I appreciate that you want this feature, but there is no infrastructure within Logstash, at present, that can do this in a performant way.  

The problem is that this would require a full halt to the flow of documents, or route to another broker or pipeline, in order to make an API call to Elasticsearch to create a dynamic alias.  Doing this on the fly would result in horrible performance interruptions, because it would require Logstash to constantly poll and make changes to a running Elasticsearch.  This is simply not possible with the current Logstash code base, and keep things usable and speedy.  Perhaps it could be part of an alternate pipeline in Logstash 2.x, but that will still require a considerable amount of development and change.

Templates are also not the way to alter this as they are only read once at Logstash startup, and then updated, and then not touched again for the same performance reasons mentioned.

It is also possible that Elasticsearch will update templates to be able to dynamically assign aliases from within a template.  It would probably be a better solution if this were where the change took place.  Perhaps raising this (or checking to see if that issue already exists in the Elasticsearch repository).

**Comment by suyograo** [comment]
There are no plans to add this feature.
