### ISSUE TITLE
[ 1.5.0rc2 ] : Allowing log verbosity configuration in the "elasticsearch" output.

### ISSUE THREAD

**Issue by chiriaev** [elastic/logstash#2847]
Guys, Hi. I am testing the latest "1.5.0 rc2". I have a couple of Rabbit inputs with four threads each. The output uses the latest "elasticsearch" plugin. There is one very annoying difference between the latter and the deprecated "elasticsearch_http" plugin. Any "POST /_bulk" response with one or more records with a "status" of, for example, 400 or 429, etc..., will generate "warn" level log data corresponding to the original bulk request. In my case I can have dozens of megabytes per seconds. A configuration option controlling this behaviour would be mostly welcome. (i.e.: the Rabbit input has it by the way)

Thanks in advance.

Regards, Andrei

**Comment by untergeek** [comment]
Thank you for submitting this issue.  I agree that this is a good idea.  

Since all plugins have been spun out into their own repositories, and this seems specific to the elasticsearch output plugin, can you re-open this issue at https://github.com/logstash-plugins/logstash-output-elasticsearch please?  It will help us keep core Logstash issues separate from plugin-specific ones.

Thanks!

**Comment by chiriaev** [comment]
Thanks and Done @ https://github.com/logstash-plugins/logstash-input-heartbeat/issues/5 
Regards, Andrei

**Comment by untergeek** [comment]
Um, how did you submit this to the heartbeat plugin?  The new issue was supposed to be opened at the https://github.com/logstash-plugins/logstash-output-elasticsearch repository.

**Comment by untergeek** [comment]
@chiriaev, please resubmit to the correct repository.

**Comment by chiriaev** [comment]
Sorry, not sure what happened. Done @ https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/75 

Regards, Andrei

**Comment by untergeek** [comment]
Thanks!  Closing this one now.
