### ISSUE TITLE
logstash checksum filter

### ISSUE THREAD

**Issue by nicolasfranck** [elastic/logstash#2878]
I know that the logstash checksum filter is deprecated. 

Although I see that the variable @to_checksum in method filter is being reused for every
event, and so building up a very large string..

Shouldn't that be an internal variable?

**Comment by ph** [comment]
You are right, the string should be reset on every event, we have another plugin to replace this behaviour called `fingerprint` you should use this one since we will deprecated the checksum filer.

If you must use checksum, you can use this PR which contains a fix for `#to_checksum` growing infinitely, https://github.com/logstash-plugins/logstash-filter-checksum/pull/1

**Comment by nicolasfranck** [comment]
I should indeed, but fingerprint is not as straight forward as the checksum filter, because fingerprint requires a HMAC key.

**Comment by ph** [comment]
You can define any key you want for the fingerprint filter and reuse it if you need to recalculate the checksum?

```
fingerprint {
key => 'superlongkey'
}
```

**Comment by ph** [comment]
I'll be closing this once since we have this PR/issue https://github.com/logstash-plugins/logstash-filter-checksum/pull/1
