### ISSUE TITLE
logstash-snmptrap doesn't show any logs in logstash

### ISSUE THREAD

**Issue by svezzoli** [elastic/logstash#2939]
We are trying to use logstash 1.4.2 with snmptrap, but nothing happens, the logs are not coming in logstash, using netstat we can see that the logstash udp port (8162) is not present and nothing is traced in log of logstash. 

We use a SNMP Simulator to send snmpv2 trap to 8162 destination port.
The logstash configuration file is the following:
 input { 
	snmptrap { 
		type => "snmptrap" 
		port => 8162 
		host => "0.0.0.0" 
		community => "public" 
	} 
}
output {
    elasticsearch { 
        host => "localhost" 
        protocol => "http"
    }
}

Any idea or suggestion?

**Comment by purbon** [comment]
Hi,
 I've a couple of questions. what do you mean by message are not coming? do they even reach the input? do you see any error being reported? 

Can you explain a bit more what you do in order to reproduce this issue?

BTW, do you know this plugin is now at https://github.com/logstash-plugins/logstash-input-snmptrap ? I see this issue more in there, are you ok with moving the issue there?

/cheers

**Comment by purbon** [comment]
There are also some issues and discussions happening in the plugin repo, not sure if they related to your issue.

**Comment by svezzoli** [comment]
This issue can be closed.
Now, our logstash server receives snmp trap events.
The only change I made is in configuration file, but I don't know if my problem has been resolved by this change:
input { 
	snmptrap { 
		type => "snmptrap" 
		community => "public" 
		port => 8162
		yamlmibdir => "/application/nfmoss/vendors/logstash/vendor/bundle/jruby/1.9/gems/snmp-1.1.1/data/ruby/snmp/mibs"
	}

Thanks.

**Comment by purbon** [comment]
Ok, thanks for your feedback @svezzoli !! good to see your issue is now fix.
