### ISSUE TITLE
Regular expression pattern wrong results

### ISSUE THREAD

**Issue by Anand-J-Kadhi** [elastic/logstash#2969]
Hello ,
I am using a regular expression pattern
DATE (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})

for matching date in this input :
2015-02-02 11:00:58,045 DEBUG - Processing at time : 1422874858045

I tested this regular expression on website :
http://www.regexr.com/

And named this pattern as date in patterns file, and applied filters like:
filter {

grok {
  patterns_dir => "./patterns"
  match => ["message", "%{DATE:date}"]  
}

 date {
  match => ["date","YYYY-MM-dd HH:mm:ss"]
}
}

But when i run for this input :
2015-02-02 11:00:58,045 DEBUG - Processing at time : 1422874858045

I get date as  
{"message":"2015-02-02 11:00:58,045 DEBUG - DEBUG - Processing at time : 1422874858045\r","@version":"1","@timestamp":"2015-04-09T07:03:25.094Z","host":"nag1-ldl-41319","path":"C:/Softwares/logstash-1.4.2/Onlinelogs.txt","date":"15-02-02"}

so the date is parsed incorrectly as you see : "date":"15-02-02"

Attached screen shot after matching the regex :
![regex parsign](https://cloud.githubusercontent.com/assets/11851015/7062039/c5cbf458-deb6-11e4-8415-a6107e5115fb.png)

and after getting the ouptut on the console :
![console output for date](https://cloud.githubusercontent.com/assets/11851015/7062062/17e286f8-deb7-11e4-9dc4-dac6b8eead78.png)

**Comment by Anand-J-Kadhi** [comment]
Hi,
Is anyone looking over this issue.

**Comment by jordansissel** [comment]
My guess is that you are not correctly overriding the `DATE` pattern.

Logstash's `DATE` pattern is defined:

```
DATE_US %{MONTHNUM}[/-]%{MONTHDAY}[/-]%{YEAR}
DATE_EU %{MONTHDAY}[./-]%{MONTHNUM}[./-]%{YEAR}
DATE %{DATE_US}|%{DATE_EU}
```

These two (DATE_EU and DATE_US) have two-digit numbers as the first segment and would give the behavior you are seeing (see screenshot below):


![screen shot 2015-05-17 at 10 48 24 pm](https://cloud.githubusercontent.com/assets/131818/7674973/db81d530-fce6-11e4-80ce-c858aec48226.png)

Best recommendation is to check to make sure your `./patterns` is a directory _and_ has the file of patterns you expect. Maybe try a full path instead of relative path to your patterns directory?
