### ISSUE TITLE
Out of Memory in multiline codec

### ISSUE THREAD

**Issue by iemem15** [elastic/logstash#2984]
I have a file of 4.1GB , and have like 142 lines of the pattern matched, after a while(30mins) logstash crashes, in the log error I have
Error: Your application used more memory than the safety cap of 3942M.
Specify -J-Xmx####m to increase it (#### = cap size in MB).
Specify -w for full OutOfMemoryError stack trace
Thanks in advance.
My conf is as folowed
input{
    file {
        path => "/cilos/logs/SVR_RFC_21_out"
        type => "PROD.WL.WL_OUT"
        sincedb_write_interval => 1
        start_position => "beginning"
        codec =>        multiline{
                pattern => "^log4j:"
                negate => true
                what => "previous"
                }
    }
}
if [type]  == "PROD.WL.WL_OUT"{
        rabbitmq {
            host => "xxx.xxx.xxx.xxx"
            port => "xxxx"
            user => "user"
            password => "password"
            vhost => "cilos.sat.gob.mx"
            exchange => "SAT.CILoS.PRO.E.D.PROD"
            exchange_type => "direct"
            persistent => true
            durable => true
            key => "WL.WL_OUT_1"
        }
    }
}

**Comment by colinsurprenant** [comment]
Thanks for the report @iemem15 - this related to logstash-plugins/logstash-codec-multiline#4

**Comment by ph** [comment]
Fixed in the latest version of the multiline plugin 0.1.7, we have added a conditionals to break on the number of lines and the number of MB, if we go over theses limits the event will be flush to queue and tagged with multiline_codec_max_lines_reached or multiline_codec_max_bytes_reached this will prevent logstash from accumulating too much events in memory.
