### ISSUE TITLE
JSON filter or json_lines codec does not appear to be thread safe

### ISSUE THREAD

**Issue by arei** [elastic/logstash#3006]
Given the following configuration: 

    input {
            rabbitmq {
                    threads => 2
                    codec => json_lines {
                    }
                    ...
            }
    }

    filter {
            json {
                    source => "message"
            }
    }

    output {
        ...
    }

And an input stream of newline delimited JSON...

An endless stream of json parsing errors will occur.  However, if you change `threads` down to 1, and run the same stream of data, no errors will occur.

My suspicion is that either the json filter or the json_lines codec is not thread safe.

A work around for this is to use the following configuration:

    input {
            rabbitmq {
                    threads => 1
                    type => "mq1"
                    codec => json_lines {
                    }
                    ...
            }
            rabbitmq {
                    threads => 1
                    type => "mq2"
                    codec => json_lines {
                    }
                    ...
            }
    }

    filter {
            if [type] == "mq1" {
                    json {
                            source => "message"
                    }
            }
            if [type] == "mq2" {
                    json {
                            source => "message"
                    }
            }
    }

    output {
            ...
    }

**Comment by untergeek** [comment]
Thanks for sharing your problem and your workaround.

Two things:

1. This belongs in either the [rabbitmq](https:/github.com/logstash-plugins/logstash-input-rabbitmq) or the [json_lines](https:/github.com/logstash-plugins/logstash-codec-json_lines) repository, not the core Logstash repository.

2. The json_lines codec is designed to capture _lines_, which implies a newline character at the end of each event.  When multithreading, your newlines could show up in unusual places.  This is not because the codec is not thread safe, but because threading at all is putting lines in different places.  Multithreading an input which fits this "multiline" problem is not isolated to just this input, or this codec.

**Comment by untergeek** [comment]
Closing due to lack of new responses.
