### ISSUE TITLE
Grok elements of an array

### ISSUE THREAD

**Issue by jmcomets** [elastic/logstash#3048]
Hi, I'd like to know if there's a way of extracting nested data types using filters. I'm currently trying to parse the following string :

    1,2;3,4

Into the following structure :

    [{ "x" => 1, "y" => 2}, {"x" => 3; "y" => 4}]

I've got this filter setup :

    filter {
      grok { match => ["data", "(?<positions>(%{POSINT}(;%{POSINT})*)?)"] }
      
      mutate { split => ["positions", ";"] }
      
      grok { match => ["positions", "%{POSINT:x},%{POSINT:y}"] } # this only captures the "x" and "y" fields once
    }

**Comment by untergeek** [comment]
Hi!  Thanks for taking the time to put your question here. 

As this is not a bug, but rather a request for assistance, you will be better served by asking this in the [user group email list](https://groups.google.com/d/forum/logstash-users) or asking in the `#logstash` channel in irc.freenode.org

While we _may_ answer questions here from time to time, issues here are to address software errors, rather than usage questions.

**Comment by jmcomets** [comment]
Okay, just posted (eg. copy-pasted) [here](https://groups.google.com/forum/#!topic/logstash-users/UFoAVZgMCFI)
