### ISSUE TITLE
Suricata syslog JSON parsing

### ISSUE THREAD

**Issue by dirtdiver512** [elastic/logstash#3083]
Has anyone setup a remote Suricata box and sent the logs to ELK in json?  I have my suricata box sending syslogs to my ELK setup using the json format.  The logs are showing up in kibana but they are  not fully parsed.  I and getting the _jsonparsefailure in the tag added as well.  Here is my config and log file:

input {
  udp {
    port => 5143
    type => "SuricataIDPS"
    format => "json_event"
  }
}

filter {

 if [type] == "SuricataIDPS" {

mutate {

        add_tag => ["SuricataIDPS"]
      }

json {
   source => "message"
  }
}
}

Apr 22 07:09:24 hp suricata: {"timestamp":"2015-04-22T07:09:23.726014","flow_id":140548582938816,"in_iface":"eth1","event_type":"fileinfo","src_ip":"129.253.55.56","src_port":80,"dest_ip":"24.237.218.244","dest_port":62494,"proto":"TCP","http":{"url":"\/wdws\/wdtvlive\/ws_wdtvlive.asmx\/wdpromo","hostname":"www.wdtvlive.com"},"fileinfo":{"filename":"\/wdws\/wdtvlive\/ws_wdtvlive.asmx\/wdpromo","state":"CLOSED","stored":false,"size":167,"tx_id":0}}

**Comment by ph** [comment]
From the error, I presume logstash cannot successfully parse the whole line.
**If** the line in your issue is an actual output of suricata, I can say it is not a complete valid JSON document.

Actually, the part after **Apr 22 07:09:24 hp suricata: ** is a valid json doc.

**Apr 22 07:09:24 hp suricata:** {"timestamp":"2015-04-22T07:09:23.726014","flow_id":140548582938816,"in_iface":"eth1","event_type":"fileinfo","src_ip":"129.253.55.56","src_port":80,"dest_ip":"24.237.218.244","dest_port":62494,"proto":"TCP","http":{"url":"\/wdws\/wdtvlive\/ws_wdtvlive.asmx\/wdpromo","hostname":"www.wdtvlive.com"},"fileinfo":{"filename":"\/wdws\/wdtvlive\/ws_wdtvlive.asmx\/wdpromo","state":"CLOSED","stored":false,"size":167,"tx_id":0}}

But nothing is lost, you could extract the actual json with a grok filter and the json filter will be able to parse it.

**Comment by remotesyssupport** [comment]
I have been able to successfully integrate the Suricata with logstash 1.5.0RC3+ Kibana 3.

However my setup is a bit different. In such that all suricata logs are sent to a the eve.json file. The logstash forwarder then picks ups and sends it to the logstash server. 

This setup works perfectly for me.

**Comment by dirtdiver512** [comment]
thanks all.  Putting the forwarder on the suiricata box is a much better route and worked.  


cheers
