### ISSUE TITLE
Configtest validates config but failed to start.

### ISSUE THREAD

**Issue by Mister-X-** [elastic/logstash#3199]
Using 1.5.0rc3, with the following config file, configtest says the configuration is OK:

```
input {
        stdin { }
}

filter {
        date {
                match => [ "M d H:m:s y" ]
        }
}

output {
        stdout { }
}
```

The configuration is obviously wrong, there is a missing field in 'match'.

Here is the output when trying to start it:

```
Error: Cannot register filter date plugin. The error reported is:
  The match setting should contains first a field name and at least one date format, current value is ["M d H:m:s y"]
You may be interested in the '--configtest' flag which you can
use to validate logstash's configuration before you choose
to restart a running system.
```

Configtest should say the configuration is bad.

It might be linked to #2437

**Comment by ph** [comment]
We should definitively improve our validation. 

The current problem is that `--configtest` is only checking if the config syntax is *valid* and doesn't check if the option are semantically correct.

**Comment by ph** [comment]
The check also verify the type of the option, but it is still very basic. We could probably add a `validate` method to the plugin so the author could do more advanced validation and trigger that method when we do the `--configtest`?

**Comment by Mister-X-** [comment]
The code used when starting and parsing could be used in such method and the only difference with start is that it stops before (and cleans up if necessary).

**Comment by jordansissel** [comment]
I think we should also document the limitations of `--configtest` - we can't "test" everything and we should document that fact. For practical examples, because some things are outside our control (is a username/password correct? does it provide the right access level to an external service? Is the network temporarily down? Is DNS working? etc)

+1 on adding clearer validation pathways for plugins. Plugins used to (and may still) support `:validate => proc do .... end` for custom validation.

**Comment by purbon** [comment]
Nowadays the config test is nowaday only checking for syntax and not content of it. I'll #3301 in benefit of  where we can discuss the right solution for this kind of error.
