### ISSUE TITLE
[site] Set up redirects for logstash.net to elastic.co for Logstash 1.5.0 release

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#3240]
The new docs infrastructure for Logstash 1.5 and beyond is hosted on elastic.co. We'll want to update logstash.net to ferry users to the correct locations.

The complexity of logstash.net's hosting caused us to delay (possibly forever) migration of the old Logstash documentation to elastic.co. This means Logstash 1.4.2 and older documentation has not been migrated and still exists on logstash.net.

In order to serve new and old users most effectively, I propose the following:
* Redirect logstash.net's root url to the Logstash product page: https://www.elastic.co/products/logstash
* Redirect logstash.net/docs/1.5.0 to http://www.elastic.co/guide/en/logstash/current/index.html
* Update the `docs` link at the page header to link to http://www.elastic.co/guide/en/logstash/current/index.html
* Update the `bugs` link to point to https://github.com/elastic/logstash/issues (was `elasticsearch/logstash`)
* Update the `home` link to point to the Logstash product page

Ideally, I'd like to keep an eye on the impact of this change after we make it to see if we've negatively hurt folks ability to find information.

cc @sylvie777 @sejiek

**Comment by suyograo** [comment]
:+1: /cc @tbragin

**Comment by sejiek** [comment]
@sylvie please advise what additional info you need if any to get this set up if you can please?

**Comment by sylvie777** [comment]
@jordansissel Hi Jordan! Do you need help updating the logstash.net site? If yes, I will need access to the logstash.net site.

**Comment by jordansissel** [comment]
I'll take care of logstash.net for now, it's a bit of a mess how things are generated on it and managed :)

**Comment by jordansissel** [comment]
@russorat Helped clue me into the right redirect codes to use to keep search-engines happy. <3

**Comment by russorat** [comment]
@arianesunder as an FYI. Any other SEO issues you see here?

**Comment by arianesunder** [comment]
@russorat Maybe we should include a mention of the old documentation (e.g. version numbers of Logstash) in the SEO page titles and descriptions of the pages we are directing to on Elastic? That would ensure that when users google say "Logstash 1.4.2 documentation" they'd end up at Elastic's site and not at Logstash.net.
I think Haley handles this...? 
CC: @hstephenson

**Comment by hstephenson** [comment]
@arianesunder @russorat I'm afraid I'm a bit out of my depth on what SEO work has been done in the realm of documentation. My knowledge extends to the list in the SEO Google Sheet: 
https://docs.google.com/spreadsheets/d/1660Nfv8vB7qnA1CO6JI7lHH_ncn46TM_KAzfzd9ozdk/edit#gid=0

That said, I'm happy to help however I can. Just need to know what URLs I'm dealing with. Russ knows I'm a newbie in this department =)

**Comment by russorat** [comment]
@arianesunder my understanding is only >=1.5 will be directing to elastic.co. The old docs will stay on logstash.net. If someone searches for logstash 1.4.2, they will end up on logstash.net. If someone searches for logstash documentation, they should end up on elastic.co/guide/logstash/current/whatever. 

I actually don't know where google is getting the page titles for logstash.net since all of them are the same:
![logstash_clone_-_google_search](https://cloud.githubusercontent.com/assets/4805997/7639628/4635cc4a-fa32-11e4-99f3-6bf132db50b9.png)

![view-source_logstash_net_docs_1_3_3_filters_clone](https://cloud.githubusercontent.com/assets/4805997/7639639/53c34658-fa32-11e4-81be-b895ae47a8fc.png)

**Comment by arianesunder** [comment]
@russorat My bad, I misunderstood.
So, let me back up a step then so I get this straight. :) One example:
- The docs link in the top navigation is this http://logstash.net/docs/1.4.2/ and will be directed to http://www.elastic.co/guide/en/logstash/current/index.html.
The page title of this page on Logstash is <title>logstash - open source log management</title>. The title of the new page on Elastic is "Reference". There are two issues with this:
1) The URL of the logstash page we are redirecting should NOT contain 1.4.2 because when people search for "Logstash 1.4.2" and click on this page, they'd be redirected to Elastic, where they wouldn't find the old documentation, correct?
2) The new page we are directing to, should receive a new title tag and meat description that includes "Logstash 1.5 documentation" somewhere, such that people who search for that end up with the right search results.
I think in order to do this right, we'll have to look at each URL and page title individually that we want to redirect....

Thoughts?
Ariane
![screen shot 2015-05-14 at 12 32 25 pm](https://cloud.githubusercontent.com/assets/12143479/7640118/2382c8ac-fa36-11e4-8984-06e1f078a334.png)
![screen shot 2015-05-14 at 12 32 38 pm](https://cloud.githubusercontent.com/assets/12143479/7640119/238307b8-fa36-11e4-92e8-a72262304006.png)

**Comment by russorat** [comment]
@arianesunder agreed on both points. 1) the url will contain "current" in place of the version number so we are always linking to the most recent version. 2) Yes, "Reference" is a terrible page name. It should be updated as soon as possible.

**Comment by jordansissel** [comment]
New redirects are in place. I still need to add one more thing, which is to have the "You are reading old docs!" warning link to the new elastic.co site on the correct page per plugin

**Comment by russorat** [comment]
I think some of the warnings have broken links. For example, http://logstash.net/docs/1.4.2/filters/advisor breaks.
![logstash_-_open_source_log_management](https://cloud.githubusercontent.com/assets/4805997/7660338/e4fb76b0-fafd-11e4-8113-b631485aa1ab.png)

**Comment by jordansissel** [comment]
The advisor plugin was not moved to the logstash-plugins org, and so there's no documentation for it, and there's also no published plugin for it. I forget exactly why we didn't migrate it, but it may have been accidental, but it also may have been because nobody knows what that plugin is for.

Given the above (this plugin doesn't exist anymore), I think it's expected that the link 404s. That `version notice` is automatically generated and not hand-curated so there may be some mistakes. We can probably work around that with a whitelist that specifically informs users that this plugin doesn't exist in 1.5, maybe?

**Comment by jordansissel** [comment]
Lots of good improvements to logstash.net's redirects (https://github.com/logstash/logstash.net/blob/master/js/patch.js.in#L24-L124). Is there more to do?

**Comment by jordansissel** [comment]
This is done well enough. Thanks for everyone who helped with this migration! :)
