### ISSUE TITLE
Exception in inputworker with udp input and line codec

### ISSUE THREAD

**Issue by duylong** [elastic/logstash#3385]
Hi,

I'm testing Logstash 1.5.0 and I have this issue (No problem with Logstash 1.4.0.) :

* Logstash configuration:

```
input {
        udp {
                port => XXXXX
                type => "syslog"
                codec => line { }
        }
}
```

* Logstash error:

```
{:timestamp=>"2015-06-05T11:23:55.091000+0200", :message=>"Exception in inputworker", "exception"=>#<TypeError: can't convert nil into String>, "backtrace"=>["org/jruby/RubyArray.java:1892:in `join'", "org/jruby/RubyArray.java:1898:in `join'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/util/buftok.rb:87:in `extract'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-0.1.6/lib/logstash/codecs/line.rb:35:in `decode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-0.1.4/lib/logstash/inputs/udp.rb:95:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-0.1.4/lib/logstash/inputs/udp.rb:74:in `udp_listener'"], :level=>:error}
```

Do you have this problem ?

Best regards,

**Comment by purbon** [comment]
Thanks for your report @duylong, in order to explore more this error. Can you share an example log line that might trigger this error?

**Comment by purbon** [comment]
On the other side, I'm proud to think this error qualify as an error for the plugin itself, so I would rather move this issue to the plugin at https://github.com/logstash-plugins/logstash-input-syslog .  What do you think?

**Comment by duylong** [comment]
My problem is random, I can't share an exact example log line. I use Rsyslog client with this format:

```
<%PRI%>%TIMESTAMP:::date-rfc3339% %hostname% %syslogtag%%msg:::sp-if-no-1st-sp%%msg%\n
```

A output example get from in Elasticsearch:

```
message:"<165>2015-06-08T09:23:49.792109+02:00 plop httpd: X.X.X.X - - [08/Jun/2015:09:23:49 +0200] "GET /" 200 1016 "-" "-" T:0 plop X.X.X.X X.X.X.X 834"
```

I use only udp input in this case. I don't know if I have the same problem with tcp or syslog input.

If I find more details, I would come complete this issue ;)

**Comment by colinsurprenant** [comment]
the problem here is that the JRuby `IPSocket#recvfrom` can return `nil` see https://github.com/jruby/jruby/blob/eb6f35dee6b2b39f0fc20fab74949d7b7e26040c/core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java#L165 (note that I looked the MRI implementation and it can also return nil, so its not a JRuby bug) and passing nil to the line codec down to the `BufferedTokenizer` will add then `nil` value and eventually try to call `join` on it and crash with the exception above, see https://github.com/elastic/logstash/blob/0cf1a98b4a77f3278e814e1a1cb308fd184934ba/lib/logstash/util/buftok.rb#L77-L87

in this case I think we should discard `nil` return in the udp input. 

I do not think the `tcp` input is also affected because it uses the `sysread` method which I think guarantees  a `String` return.  To verify.

for now I will open an issue in the udp input for this.

**Comment by colinsurprenant** [comment]
moved issue in logstash-plugins/logstash-input-udp#4 - please follow progress over there! thanks!

**Comment by colinsurprenant** [comment]
for the record, after some investigations, my hypothesis above is not correct and there is something else going on because `BufferedTokenizer` does not accept `nil` payload but it does end up with an object in its `@input` array that provoke this `TypeError: can't convert nil into String` when doing an `Array#join`. I cannot reproduce this. investigating...
