### ISSUE TITLE
document_id with missing field - goes awry

### ISSUE THREAD

**Issue by KlavsKlavsen** [elastic/logstash#3408]
if I set document_id => "%{message_id}" - and the source does not contain a field names %{message_id} - LS chooses to use the text as a string, meaning I only get 1 logline per index - because they all get _id set to "%{message_id}" :(

It would be very nice if LS choose NOT to set document_id - if field given in document_id does not exist.

**Comment by untergeek** [comment]
Thanks for the suggestion.  Since this request is specific to the Elasticsearch output plugin, please open this issue at https://github.com/logstash-plugins/logstash-output-elasticsearch

As an aside, while this request makes sense for your use case, it may not in others.  As such, it may be added as an option, rather than as a default.

**Comment by KlavsKlavsen** [comment]
I found an issue already covering this issue over there.. so this can be closed.
https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/153
