### ISSUE TITLE
Logstash netflow codec error: "Ignoring netflow version..."

### ISSUE THREAD

**Issue by deusofnull** [elastic/logstash#3435]
Hi there,

I am trying to send netflow data to logstash via a manual backfilling technique.  After generating netflow data files using nfdump, I try and send the data over nc to logstash on an input port configured to listen for netflow data.

My input looks like this:
```
input {
	tcp {
    		port => 9995
    		type => "netflow"
		codec => netflow {}
  	}	
  lumberjack {
    port => 5000
    type => "logs"
    ssl_certificate => "/etc/pki/tls/certs/logstash-forwarder.crt"
    ssl_key => "/etc/pki/tls/private/logstash-forwarder.key"
  }
}
```

I am sending the logs in this fashion:
```
nfdump -r nfdumpout | nc localhost 9995
```

My error log @ /var/log/logstash/logstash.log:
```
{:timestamp=>"2015-06-12T03:30:09.097000-0400", :message=>"Ignoring Netflow version v8224", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.097000-0400", :message=>"Ignoring Netflow version v8224", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.097000-0400", :message=>"Ignoring Netflow version v8224", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.097000-0400", :message=>"Ignoring Netflow version v12592", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.098000-0400", :message=>"Ignoring Netflow version v13614", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.103000-0400", :message=>"Ignoring Netflow version v8224", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.104000-0400", :message=>"Ignoring Netflow version v12832", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.104000-0400", :message=>"Ignoring Netflow version v12850", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.104000-0400", :message=>"Ignoring Netflow version v14898", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.105000-0400", :message=>"Ignoring Netflow version v12346", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.105000-0400", :message=>"Ignoring Netflow version v13876", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.105000-0400", :message=>"Ignoring Netflow version v8224", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.110000-0400", :message=>"Ignoring Netflow version v8224", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.111000-0400", :message=>"Ignoring Netflow version v8224", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.111000-0400", :message=>"Ignoring Netflow version v8224", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.111000-0400", :message=>"Ignoring Netflow version v12832", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.112000-0400", :message=>"Ignoring Netflow version v13618", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.112000-0400", :message=>"Ignoring Netflow version v11828", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.112000-0400", :message=>"Ignoring Netflow version v8245", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.118000-0400", :message=>"Ignoring Netflow version v14126", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.118000-0400", :message=>"Ignoring Netflow version v12855", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.118000-0400", :message=>"Ignoring Netflow version v14898", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.118000-0400", :message=>"Ignoring Netflow version v13882", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.119000-0400", :message=>"Ignoring Netflow version v12854", :level=>:warn}
{:timestamp=>"2015-06-12T03:30:09.119000-0400", :message=>"Ignoring Netflow version v8224", :level=>:warn}
```

Can anyone suggest what is going wrong?

**Comment by jordansissel** [comment]
I'm not sure if the netflow codec has ever been tested over tcp. It's possible we may be misreading something somehow.

**Comment by deusofnull** [comment]
Hey @jordansissel.  Thanks for responding.  

I was able to resolve this issue. It was caused by the format of the netflow data I was sending over tcp. I had used nfdump to format the netflow into essentially a .csv;  I didn't know the binary read purpose of the netflow codec.  

Now I do and everything works fine.  The error message even makes sense now, since .csv is not a Netflow version.

Best,
-w

**Comment by jawad-manzoor** [comment]
@deusofnull 
I am having exactly same issue when i run this command:
nfdump -r nfcapd.201510211030 | nc localhost 9995

My error log looks like this:

{:timestamp=>"2015-11-13T21:03:16.910000+0100", :message=>"Ignoring Netflow version v12333", :level=>:warn}

I have used all possible options of nfdump( -o raw, -o csv, -o line) to print out the netflow records but none works.
I think netflow codec expects binary format. How to i send these records in binary format from nfdump?
As you have solved this problem, I would appreciate if you could share the solution.

Best Regards,
- Jawad

**Comment by Azarack** [comment]
I had to make a custom template on my logstash server in yaml.  Once netflow sent its template the two synced up and data flowed correctly.
 


     On Friday, November 13, 2015 4:52 PM, Jawad Manzoor <notifications@github.com> wrote:
   

 @deusofnull 
I am having exactly same issue when i run this command:
nfdump -r nfcapd.201510211030 | nc localhost 9995My error log looks like this:{:timestamp=>"2015-11-13T21:03:16.910000+0100", :message=>"Ignoring Netflow version v12333", :level=>:warn}I have used all possible options of nfdump( -o raw, -o csv, -o line) to print out the netflow records but none works.
I think netflow codec expects binary format. How to i send these records in binary format from nfdump?
As you have solved this problem, I would appreciate if you could share the solution.Best Regards,   
   - Jawad

**Comment by jawad-manzoor** [comment]
@Azarack
Why do we need a separate template on logstash server side? Is it not possible to send netflow records in default format using nfdump?
When i send the same flow records using nfreplay on UDP port, it works perfectly and the records and stored in ElasticSearch:
nfreplay -r nfcapd.201510211030 -p 9995

But the problem with UDP is that a large number of records are dropped. So i changed my logstash configuration to use TCP input.

input {
    tcp {
            port => 9995
            codec => netflow {}
    } 
}

After changing to TCP i don't get receive any records because nfreplay only supports sending netflow records to a UDP port. This led me to use nfdump command instead.

nfdump -r 201510211030 | nc localhost 9995

This commands sends records to TCP port but unfortunately i receive below errors as the netflow plugin of logstash is not able to parse it.

{:timestamp=>"2015-11-13T21:03:16.910000+0100", :message=>"Ignoring Netflow version v12333", :level=>:warn}

Now my question is that:
1) Is it possible to use some configuration of nfdump that sends records according default netflow template? If nfreplay can send the records with correct template why not nfdump?(as they are both part of the same package)
2) Is there some other utility similar to nfreplay that can send flow records from nfcapd file to a TCP port?

Best Regards,
- Jawad

**Comment by Azarack** [comment]
Sorry, that fixed a different error. I was getting a no template found for flow error and needed to create a template file. 
--------------------------------------------
On Fri, 11/13/15, Jawad Manzoor <notifications@github.com> wrote:

 Subject: Re: [logstash] Logstash netflow codec error: "Ignoring netflow version..." (#3435)
 To: "elastic/logstash" <logstash@noreply.github.com>
 Cc: "Azarack" <jethro888222@yahoo.com>
 Date: Friday, November 13, 2015, 7:40 PM
 
 @Azarack
 Why do we need a separate template on logstash server side?
 Is it not possible to send netflow records in default format
 using nfdump?
 When i send the same flow records using nfreplay on UDP
 port, it works perfectly and the records and stored in
 ElasticSearch:
 nfreplay -r nfcapd.201510211030 -p 9995
 
 But the problem with UDP is that a large number of records
 are dropped. So i changed my logstash configuration to use
 TCP input.
 
 input {
     tcp {
             port => 9995
             codec =>
 netflow {}
     } 
 }
 
 After changing to TCP i don't get receive any records
 because nfreplay only supports sending netflow records to a
 UDP port. This led me to use nfdump command instead.
 
 nfdump -r 201510211030 | nc localhost 9995
 
 This commands sends records to TCP port but unfortunately i
 receive below errors as the netflow plugin of logstash is
 not able to parse it.
 
 {:timestamp=>"2015-11-13T21:03:16.910000+0100",
 :message=>"Ignoring Netflow version v12333",
 :level=>:warn}
 
 Now my question is that:
 1) Is it possible to use some configuration of nfdump that
 sends records according default netflow template? If
 nfreplay can send the records with correct template why not
 nfdump?(as they are both part of the same package)
 2) Is there some other utility similar to nfreplay that can
 send flow records from nfcapd file to a TCP port?
 
 Best Regards,
 - Jawad
 
 ---
