### ISSUE TITLE
Release new logstash-event gem

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3479]
Last release to RubyGems.org was https://rubygems.org/gems/logstash-event/versions/1.2.02 on Sep 2013. We need to release a new version for 1.5.0 compatibility.

**Comment by colinsurprenant** [comment]
I'd like to propose we restructure the logstash-event gem so that the current logstash event code is moved in that gem and that ultimately we could provide the pure Java implementation as a drop in gem replacement. The current event implementation has some Java dependencies like the use of Joda-Time and I think one reason the currently released logstash-event was never updated is that it is pure-Ruby and many users are using it in non-JRuby environments.

Is that also your understanding of the situation @jordansissel ?

If it is important to keep providing a pure-Ruby implementation we could easily release 2 versions:
- the current event implementation which would become `logstash-event-java` because it depends on the Java platform.
- the current implementation minus the Java specific code to make it a pure-Ruby implementation

And eventually maybe a new pure-Java implementation, but we'll have to figure a new name for it.
