### ISSUE TITLE
Where is the "noop" filter ?

### ISSUE THREAD

**Issue by duylong** [elastic/logstash#3493]
Hi,

Since my update to 1.5.x, I can't found the "noop" filter. Why this plugin has been deleted ?

Best regards,

**Comment by purbon** [comment]
@duylong you can find a replacement https://github.com/colinsurprenant/logstash-filter-noop, but I have a question for you, why do you need that filter?

**Comment by duylong** [comment]
I found more clean in order to use only (add|remove)_(field|tag).

**Comment by purbon** [comment]
interesting :-) thanks for sharing, so for now you will need to use @colinsurprenant code. hope this works for you. Should we close this for now?

**Comment by jordansissel** [comment]
You can use mutate instead of noop filter

**Comment by duylong** [comment]
@jordansissel Is it really his role?

**Comment by jordansissel** [comment]
Background: The noop filter was written to aid in testing Logstash internally. All of the features the `noop` filter has are _also_ supported by every other plugin. The `mutate` filter is the best replacement for any use of the `noop` filter because mutate will run add_field/etc on all events, not just some - contrast with date and grok filter which only activate add_field/etc for events which are successfully parsed.

Put shortly, any use of `noop` is literally replacable with the word `mutate` for the filter in your config, and it will work exactly the same. Any deviation of that is a bug.

**Comment by duylong** [comment]
I found more sense to have a plugin that does nothing for the understanding of the final code.

Thank you for your clarification.
