### ISSUE TITLE
Consolidate all the http rest input plugins

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3497]
We have a need for an input plugin which calls external services to retrieve data and insert it into LS pipeline. A lot of folks have shown interest in this and have called it `logstash-input-rest`. It is hard to write a generic, one-size-fits-all plugin which works to consume every REST service out there. 

The main goals for this plugin should be:
1. Provide an easy way to ingest RESTful resources
2. Decide how we schedule the pulls -- periodically? one-time and shutdown?
3. Support security OOTB (https) and basic auth
4. Works as a template plugin -- if there is an use case which does not get solved by this plugin, it is easy to clone/copy and modify to suit the needs. In other words, code should be easy to understand and well documented
5. Default codec as json?
6. Test the rest input with a variety of use cases and end points

*Alternatively*, should there be a REST filter in the same vein to enrich events?

The following PRs need to be evaluated and consolidated with the above goals in mind:

https://github.com/elastic/logstash/issues/3489
https://github.com/elastic/logstash/issues/3387
https://github.com/elastic/logstash/issues/3419

We need one rest input to rule them all :)

**Comment by suyograo** [comment]
This input is kind of related to logstash-input-sql, so /cc @talevy. Maybe we need the same scheduling semantics here?

**Comment by andrewvc** [comment]
These plugins seem to fall into one of two categories:

* Injecting event metadata in the filter phase
* Periodically polling (usually for gauge style stats)

I think the REST nomenclature here is confusingly off given that these are basically HTTP plugins with JSON decoding.

Given that I would propose naming these `logstash-input-http-poller` and `logstash-filter-http-injector`.

@suyograo I think the goals you listed are great. I do think pulls should be periodic. Also, we should be careful around Keep-Alive.

Regrading colaborating with @talevy unless I'm missing something, since these plugins don't perform pagination, there probably won't be any shared code there.

**Comment by bradvido** [comment]
Regarding mine, #3387 it's was developed with a webservice **queue** in mind. So it pulls events from the webservice which provides persistant queueing of the events (think like the redis input). 
We have a webservice that queues up events from various clients (external to Logstash) into a database, and Logstash uses the httpclient to retrieve those from the queue.

It uses special (optional) HTTP headers that:

1. Indicate if the plugin should request more data right away instead of waiting the normal polling interval (e.g. if the queue is not empty), 
2. Provide stats that indicate how quickly Logstash is able to process events and add them to Logstash's internal queue. The webservice can use this as an indicator of how many events to send to Logstash at a time.
3. It has handling for "batch ids" that track the events in each request and are sent back to the webservice when a batch is successfully pushed to Logstash. This is essentially an "acknowledgement" to let the webservice everything went fine with the batch of events it sent. 

This allowed us to build nice Kibana dashboards. Since the webservice is custom, it has been set up to ship "meta-data" to ES.  e.g. the queue size and I/O over time:
![image](https://cloud.githubusercontent.com/assets/884611/8317285/f5090bfc-19c1-11e5-868a-a0ddce7fec9d.png)

We can also track the "throughput capability" (how events can be processed) at each stage (into the queue, out of the queue, and into logstash):
![image](https://cloud.githubusercontent.com/assets/884611/8317327/37e433d4-19c2-11e5-82c3-6a796131fc3e.png)
 
... just some background on the goals behind #3387

**Comment by andrewvc** [comment]
@bradvido That is awesome stuff! I love that Kibana dashboard, and I love your use of KeepAlive. BTW, are you also in the great state of Minnesota?

That being said, I think you've got a pretty specific use case. Most users tend to use a queue like Kafka, RabbitMQ, or Redis for that case. I think for our official plugin it'll make more sense to just handle the polling case, rather than the queue over HTTP case.

**Comment by bradvido** [comment]
@andrewvc I agree, it's a specific use case. I just want to provide insight behind the code as you look to create a http input that "combines" all the proposed ones. I like the idea of the official input being a "template" so I can easily extend it to a my more specific use case.

And, yes -- Duluth, MN

**Comment by andrewvc** [comment]
@bradvido awesome to hear that you're in Duluth, it's beautiful up there. I'm in MPLS.

Thanks for the insight, we'll keep it in mind as we build our polling gem. After discussing it with the team today we won't be combining them so much as just creating an official polling gem based on  @maximede 's REST gem since that covers the broadest use case.

**Comment by andrewvc** [comment]
I've created the new plugin at https://github.com/logstash-plugins/logstash-input-http-poller , it's based off the rest input. Closing this issue down...
