### ISSUE TITLE
How to set field type to "ip"?

### ISSUE THREAD

**Issue by naisanza** [elastic/logstash#3524]
I've used the date filter to set a target field as a date type. I don't see a filter to set a target field type to "ip".

I'm looking to do this so I can use the IPv4 Range Aggregation, but haven't been able to find the documentation on how I can map a field to type: ip, without needing a custom template.

And also, I've been trying to find out how you will deal with a log that contains multiple ip fields.

Logstash isn't able to deal with multiple geoip fields without a custom template. I'm hoping this isn't the same case with ip fields.

An example event would be:
`63.88.73.59,104.197.28.247,104.197.28.0,-,,-,Google Inc.,Mountain View,CA,US,Google Inc.,Mountain View,CA,US`

**Comment by untergeek** [comment]
This should be in https://discuss.elastic.co/c/logstash as it is a usage question rather than a software bug.  That said, there is no way to do this in Logstash that wouldn't drastically reduce performance.  

The ip type is mapped exclusively in Elasticsearch, which requires a template or manual mapping.  Logstash cannot be coerced to apply a mapping manually without drastically slowing down the pipeline, as it would be required to check a mapping and apply one if missing as part of the stream.  A template is your best option.

**Comment by naisanza** [comment]
@untergeek I didn't know it was mapped exclusively in Elasticsearch. Thanks!

I figured if I were able to use the `date` filter and `geoip` filter to give a source field a `target` that I could do the same for ip fields.

**Comment by untergeek** [comment]
The same is actually true of geoip also.  Logstash just auto-maps the `geoip.location` field to type geopoint for you.  If you have more than one geoip field, you'd need to update the template to accommodate that, just as with ip type.

Date is also mapped in Elasticsearch, but Elasticsearch automatically recognizes date patterns for you, so you don't have to manually map dates (though you can, if they're esoteric).

**Comment by naisanza** [comment]
@untergeek ah, I do remember reading about dynamic mapping and some fields are dynamically mapped. Eventually, every bit of information that I've read about ELK, and trial and errored, will come around and piece itself together :)
