### ISSUE TITLE
Ability to govern log file generated by logstash 

### ISSUE THREAD

**Issue by abordia** [elastic/logstash#3658]
Currently, logstash writes to a single log file, if logging is enabled.  This can result in complete usage of disk space causing system to freeze have issues.

Pragmas should be introduced such that log files can be rotated, overwritten and size per each users spec.

**Comment by jordansissel** [comment]
At present, Logstash can be told to reopen its logfile (for example, after rotation) by sending SIGHUP.

Long term, I want to add size/time-based rotation configuration to logstash's own logging system.

**Comment by abordia** [comment]
I have a cloud setup so manual intervention on each pod is almost impossible.  An automated ability to govern the log size would help.  Appreciate if this gets fixed soon.  Thanks!

**Comment by abordia** [comment]
Has this enhancement been deferred to v3?  
From a user side, i currently have to disable logstash logging (cannot afford logs to be filled up with grok parse failures and bring system down).  With missing logs, i am very limited in diagnosing any issues related to logstash.  I have encountered several issues (OOM, LS not sending data to ES etc) but finding root cause is non trivial in absence of these logs.  

Can this ER be expedited?  Ask is to govern the log generated by LS.  Various means are:
1.  Purge policy
2.  Rotate and purge
3.  Generate limited errors especially for grok parse failures (say first 1000 entries of same exception and then stop; recover at LS restart).

I appreciate your help.  Thanks!

**Comment by jordansissel** [comment]
@abordia Can you help me understand what about SIGHUP [my previous comment](https://github.com/elastic/logstash/issues/3658#issuecomment-125383014) doesn't work for you at least for a workaround until we have more elaborate configurations for logging?

Specifically, logrotate can do your purge policy, rotate and purge, etc, and also signal Logstash to reopen its logfile after logrotate does its rotation.

**Comment by derjohn** [comment]
@jordansissel 

At least in 1.5.2 a SIGHUP will cause logstash to hit the canvas in many times:

```
{:timestamp=>"2015-11-02T18:44:32.264000+0100", :message=>"Failed to flush outgoing items", :outgoing_count=>1509, :exception=>#<IOError: closed stream>, :backtrace=>["org/jruby/RubyIO.java:1985:in `tty?'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/cabin-0.7.1/lib/cabin/outputs/io.rb:60:in `tty?'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/cabin-0.7.1/lib/cabin/outputs/io.rb:51:in `<<'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/cabin-0.7.1/lib/cabin/outputs/io.rb:50:in `<<'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/cabin-0.7.1/lib/cabin/channel.rb:176:in `publish'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/cabin-0.7.1/lib/cabin/channel.rb:174:in `publish'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/cabin-0.7.1/lib/cabin/channel.rb:173:in `publish'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/cabin-0.7.1/lib/cabin/mixins/logger.rb:102:in `_log'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/cabin-0.7.1/lib/cabin/mixins/logger.rb:79:in `log_with_level'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/cabin-0.7.1/lib/cabin/mixins/logger.rb:64:in `warn'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.1-java/lib/logstash/outputs/elasticsearch.rb:517:in `submit'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.1-java/lib/logstash/outputs/elasticsearch.rb:512:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.1-java/lib/logstash/outputs/elasticsearch.rb:529:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.1-java/lib/logstash/outputs/elasticsearch.rb:528:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1511:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}
```

**Comment by alastrange** [comment]
Would like to see this as well.  Either more flexibility for rotating logs, or some configuration file like log4j (log4r?)

**Comment by untergeek** [comment]
Closing this in favor of #4548.

**Comment by vsp412** [comment]
@abordia  @jordansissel  Hey @abordia  wanted to ask this to you nice people:
Basically I have connected my mysql table to logstash using the input plugin, and set the schedule parameter to this :  * * * * *( i.e, logging will happen every minute). Now, once i have started my logstash, and all of this table data is logged into logstash once (i.e. after the end of the current minute), only the new records inserted in the mysql table should be logged into logstash in the next minute, and NOT the old ones. Basically, I want my logstash to function like a real time database, into which data is streamed real time. I dont want new logs (with different timestamps) of the same old records being created again and again after each minute. Only the logs of those records which are inserted newly within the current minute should be created. Because this data I'm gets stored in elasticsearch using the jdbc output plugin. And because Im using the elasticsearch php client for providing a search box on my website, whenever a customer searches some text, the response that he gets is multiple instances of the same result, since all those logs of that one particular record in logstash get stored in elasticsearch. So if someone searches for, let's say, "The Shawshank Redemption", instead of a single record returning, the same record , "The Shawshank Redemption", is returned at least 10-15 times. Imagine if you search something on google and you find that the first 10 entries are the exact same. That is the problem that I am facing. Please please help me...
I hope

**Comment by jordansissel** [comment]
@vsp412 This is a closed ticket that doesn't seem related to your question. Questions like yours are best asked on https://discuss.elastic.co/ where our user forums are.
