### ISSUE TITLE
LS > 1.5.0 bin/plugin uninstall not removing gem

### ISSUE THREAD

**Issue by kbrebanov** [elastic/logstash#3678]
```bash
bin/plugin install logstash-output-circonus
bin/plugin uninstall logstash-output-circonus
```

After running these commands, the **logstash-output-circonus** gem is removed from the Gemfile but it is still installed under **vendor/bundle/jruby/1.9/gems**

```
bin/plugin update
```
Plugin not found, aborting
ERROR: Updated Aborted, message: Could not find gem 'logstash-output-circonus'.

When installing uninstalling 2 plugins, it removes the first gem, but not the second one.
```
bin/plugin install logstash-output-circonus
bin/plugin install logstash-output-riemann
bin/plugin uninstall logstash-output-circonus
bin/plugin uninstall logstash-output-riemann
```

After running these commands, both gems are removed from the Gemfile and the **logstash-output-circonus** gem is uninstalled, but the **logstash-output-riemann** gem is still installed under **vendor/bundle/jruby/1.9/gems**.

```
bin/plugin update
```
Plugin not found, aborting
ERROR: Updated Aborted, message: Could not find gem 'logstash-output-riemann'.

**Comment by purbon** [comment]
@kbrebanov Thanks for your report!! I was wondering with LS version and under which system are you testing this?

**Comment by kbrebanov** [comment]
@purbon I tested this with LS 1.5.0 to 1.5.3 on Ubuntu 14.04 with both OpenJDK 1.7 and OpenJDK 1.8

**Comment by purbon** [comment]
I tested this same issue with master, 1.6 and 1.5 and it see it too. I guess the path here, is to make sure the clean call in the uninstall is properly done by bundler. 

Thanks @kbrebanov for sharing.

**Comment by colinsurprenant** [comment]
There are 2 separate issues here and I'd love for @ph to also join the conversation.

1- the first issue is that `uninstall`, as noted by @kbrebanov, does not correctly cleanse the uninstalled gem from`vendor/bundle/jruby/1.9` directory. From a **bundler** perspective this should not really be a problem because it has been removed from the `Gemfile` and `Gemfile.jruby-1.9.lock` but from a **rubygems** perspective this gem is still installed which bring issue (2)

2- the update command uses [`PluginManager#find_plugin_gemspecs`](https://github.com/elastic/logstash/blob/0d70995306c41f2b2019c616a3e226d1d2e6b95f/lib/pluginmanager/util.rb#L61-L64) to build the list of gems to update but `find_plugin_gemspecs` uses **rubygems** to retreive the list of installed gems and will pickup the uninstalled but not cleansed plugins per (1) in that list and invoke the **bundler** update which will result with `ERROR: Updated Aborted, message: Could not find gem ...`.

I think both problems should be looked at.

- for the uninstall problem (1), I am not sure why we shouldn't be able to use the same strategy as with the update command and [do a double bundler invoke](https://github.com/elastic/logstash/blob/0d70995306c41f2b2019c616a3e226d1d2e6b95f/lib/pluginmanager/update.rb#L56-L57), one for install and another for clean. we should try that.

- we should investigate how we could grab the list of live gems from a **bundler** perspective, I **think** it should be as simple as using the [`PluginManager#all_installed_plugins_gem_specs`](https://github.com/elastic/logstash/blob/0d70995306c41f2b2019c616a3e226d1d2e6b95f/lib/pluginmanager/util.rb#L71-L75) method instead of the `find_plugins_gem_specs` [in update](https://github.com/elastic/logstash/blob/0d70995306c41f2b2019c616a3e226d1d2e6b95f/lib/pluginmanager/update.rb#L117)

thoughts?

**Comment by purbon** [comment]
Hi @colinsurprenant, at less in my scenario and test a double bundler invoke is not working, but might be I'm not testing the right thing, so feel free to educate me.

The second scenario I've not investigated yet, I will provide more details as soon as I know.

**Comment by colinsurprenant** [comment]
@purbon if it doesn't work it would be nice to figure out why but OTOH fixing (2) will solve that issue. 

By default, Bundler does not cleanse "old" gems so we should be resilient to that situation. **Ideally** we should be able remove unused gems but it should not be a problem to have them laying around either. The only down side should be the space waste, which frankly, in most situation it should not be a real problem.

**Comment by purbon** [comment]
I would say is a bundler problem as you can see from https://gist.github.com/purbon/6415a7321e8a9a0cdc61, anything not using a clean env, is basically not taking into account while doing a proper cleanup. 

too different calls to ```bin/bundle``` will actually clean the stale gems.

**Comment by colinsurprenant** [comment]
@purbon yeah, I noticed that and I tried to understand what it is in the environment/bundler state that prevents this and I did not find it. it would require more investigations. Bundler has just not been designed for this. I think at this point it would be perfectly acceptable to just solve (2).

**Comment by purbon** [comment]
Hi, in the way #3731 is it solve the two issues, actually having a clean cache, I expect uninstall to work like this, I don't a reason not to keep the implementation like this, so we get (1) and (2) :smile_cat:

**Comment by colinsurprenant** [comment]
@purbon its because there are cases where you do not want to purge "uninstalled" plugins, for example when that gem is a dependency. Are we sure all the cases are covered? I feel this might be dangerous to systematically purge uninstalled plugin gems.

**Comment by purbon** [comment]
@colinsurprenant you mean for example trying to uninstall a codec-plain, that is used as dependency on another plugin? I don't think bundler is going to let this pass right? It will be complaining and then the gemfile gets reverted before you get to that call. At less this is how I understand.

**Comment by colinsurprenant** [comment]
moving this discussion in #3731, otherwise we'll have duplicate conversations.

**Comment by purbon** [comment]
This got fixed by https://github.com/elastic/logstash/pull/3731
