### ISSUE TITLE
AST/Pipeline Refactor (Merged filter+output stage)

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#3774]
In service of the [new pipeline execution model](https://github.com/elastic/logstash/issues/3693#issuecomment-127672028) we need the AST to be turned into new executor primitives. Currently we compile `input {}`, `filter {}`, and `output {}` to execution functions. 

The new pipeline has different characteristics that require the filter and output units to be merged. What we need the AST to yield going forward is:

* The input side should remain the same
* This function MUST be threadsafe.
* Current outputs MUST be internally wrapped in a unique mutex to ensure correct behavior
* We SHOULD create a new `LogStash::Output::Threadable` class for threadsafe outputs
* Outputs utilizing workers SHOULD be rewritten to be `Threadable`
* Outputs not inheriting from Threadable MUST be wrapped in a Mutex

**Comment by suyograo** [comment]
Just to be clear, the configuration from user's perspective will remain the same. This has implications only on the internal code generation and design

**Comment by andrewvc** [comment]
@suyograo that is correct!

**Comment by andrewvc** [comment]
One consideration here is that this design is slower for use cases where strict input -> output ordering is required. Currently the intermediate output queue fixes this issue. by letting us execute the output phases separately. This is important for people who depend on filters that require ordering.

Thinking through it more the actual interface exposed to pipeline plugins should still be `filter_func()` and `output_func()`. The only thing that needs to be changed is the threadsafety of outputs.

**Comment by ph** [comment]
I am really interested in that thing, I will try to gather my notes and add some meat to it.

**Comment by ph** [comment]
So following #3693 we will remove the output queue and only has one queue (or journal) to keep the bookeeping. This is what I have in mind. This will simplify a lot of things, especially for rehydration.

**Simplifying things ahead**

So we will only have an array of inputs that journal the events and a AST for the conditionals/filter that will consume the events in batch and work on them? (not sure about buffered plugins like the elasticsearch, I have to reread the #3693)

Having a real AST with our own primitive will probably allow us to do nice optimization.
Maybe some events from a specific inputs never go in specific branch. (we could have the same behavior with multiple pipelines support). JIT would probably work better since the method will be smallers.

The AST could allow us to follow the flow of events in the pipeline, event origined from A pass through B -> C -> E -> and finish in X and X. This kind of tracing could allow people to assign more resource on specific part of a pipeline. 

We don't have to change the TreeTop grammar for most of the things, just extend it for multiple pipeline support. We just need to change the structure between what treetop is evaluating and the pipeline execution.

**Comment by ph** [comment]
Concerning the lock/mutex for the output, I think we should wrap every plugin into some kind of executor that will handle this kind of scenario. This could also provide a way to be backward compatible with older plugin if we really want to.

**Comment by ph** [comment]
This also open the door to use a new json api, since different language can generate the same AST.

**Comment by andrewvc** [comment]
@ph I'm 100% with you with the JSON API. Thinking through it a bit more I think we should make the AST pretty flexible and decouple the parsing the execution fully, letting the Pipeline (which is pluggable) determine how it wants to execute it. Maybe we should just generate some JSON-like intermediate representation for execution and decouple the representation of the AST in memory from the execution.

So the structure for a naive pipeline might look something like:

```ruby
# This is not a great set of interfaces, but is just here to show
# how I imagine the coupling working
require 'ast_utils'
class MyPipeline
  def run(ast)
      AstUtils.run_inputs(ast).each do |event|
      AstUtils.run_outputs(AstUtils.run_filters(event))
    end
  end
end
```

The advantage here is that if a future plugin wants to take an entirely new approach to executing the AST that's decoupled. We'd still provide a 'standard' package (AstUtils in my example), but it'd be purely optional for the pipeline.

What do you think?

**Comment by ph** [comment]
I am pretty sure the AST could leverage the `stream_identity` concept.

**Comment by andrewvc** [comment]
@ph WRT buffered outputs I'm not sure if its in the thread but in our last discussion we decided to bring buffering into logstash as a first class citizen. Outputs would optionally define a `receive_batch` method, that if implemented would take batch sizes.

A requirement of the new pipeline strategy is that these batch sizes be uniform across all outputs. That greatly simplifies journaling and acknowledgements. If users wish to tune this they can, but it will have to across all outputs.

**Comment by andrewvc** [comment]
I'll just add that an additional benefit of decoupling the AST is that it enables all kind of fun possibilities for the future, like a step-wise debugging executor!

**Comment by ph** [comment]
Decoupling the parsing and the execution is what I had in mind, but I think we can do first draft without that, unless the pipeline execution is already written in java ;)

This is what I had in mind:

```
config - > TreeTop AST -> simplified ruby ast -> Java AST
json -> own interpreter (probably?) -> simplified ruby ast -> Java AST
```
I think the simplified AST is enough, plugins author can visit it and generate a new one if needed.

**Comment by ph** [comment]
Yeah, the step-wise debugger is what the support people want and we discussed it when talking about the metrics api. 

@suyograo I think refactoring the AST would help us extracts the metrics for the api in a non hacky way and might be the first step, I still have to think about it.

**Comment by ph** [comment]
@andrewvc one of the most common question is on what logstash is hanged, having this kind of AST allow easy introspection about which event is in the pipeline and were it is.

**Comment by andrewvc** [comment]
@ph fully agreed. I should add that there's nothing about the current AST that would hold back the new pipeline work in #3693 , so we could target new AST stuff for 2.1 or something.

**Comment by ph** [comment]
@andrewvc Yes, this is what I have to think about, concerning the metrics.
There is multiple way to do it.

- Add new generated code in the pipeline to do the metric bookkeeping
- Add some kind of supervisor between the pipeline and the plugin that log the metrics
- Add the metrics at the AST level, performance of the flow of events
- Add the metrics collection at the queue level, since the queue will know the performance of different plugins (considering the create/fetch/ack)
- Add proxy at the plugin level.

We might have to implements multiple of theses scenario to give people a better understanding of what is actually going on inside logstash. I am reading all the new issues concerning the pipeline because I want to implement it where it will be the best, we have a lot of moving parts, we don't want to step in each other too much ;)

**Comment by ph** [comment]
I've talked a bit on the AST with @jordansissel on our last one on one, and I told him I'll experiment a bit with it. I will probably poke you to make sure our vision in in sync.

**Comment by andrewvc** [comment]
@ph fully understood. The great thing about the pipeline/AST interaction is that it's so minimal, so we can always refactor later if need be without too much of an issue.

**Comment by colinsurprenant** [comment]
I suggest we generate the AST in an easily serializable format, so that we can pass that serialized AST to any pipeline implementation, being it in JRuby or Java. This AST representation should be pretty simple since we basically only have call sequence and branching for conditionals. I guess JSON could do but branches/conditionals in json are funky.

**Comment by andrewvc** [comment]
@colinsurprenant ++. 

FWIW I'm a huge fan of using JSON. It's hardly the most elegant AST format, but I think its still the easiest to work with due to familiarity + good tooling.

**Comment by ph** [comment]
Yeah the easy serialization make sense to do on the fly configuration changes with the api and persist it somewhere, like file based or even in a elasticsearch cluster.

**Comment by colinsurprenant** [comment]
I would also suggest we think about alternatives like Thrift, in terms of concept, which might be useful especially in a cluster context where pipeline definitions, ie the serialized AST, will have to be transported across nodes somehow.

**Comment by ph** [comment]
Agree, This how I see the path to the final implementation:

- Clean the config_ast
- Make a Ruby AST, which can be used directly with the current pipeline.
- Investigate serialization for clustering and for the JVM. (could be JSON, thrift, ETC)
- Serialization implementation.

**Comment by colinsurprenant** [comment]
@andrewvc @ph @suyograo I believe this issue is not really relevant anymore? maybe we should reboot into separate issue(s) if we want to followup on specific points?

**Comment by andrewvc** [comment]
This is already in 2.2 mostly, will follow up in a new issue if need be.
