### ISSUE TITLE
Remove Watchdog in the code base

### ISSUE THREAD

**Issue by ph** [elastic/logstash#3828]
The current implementation of the watchdog is buggy and unused, We should remove this dead code.
We will provide a better way of doing monitoring of the pipeline in #2611 

ref #1512

**Comment by jordansissel** [comment]
+1 removing the existing watchdog that is unused :)

For some background:

The watchdog was added early in Logstash's life because of execution problems with filters - there were certain filters (like grok with an exponential-runtime pattern) that could get stuck uninterruptably, and there was no way to recover without manual intervention. A watchdog was added to ensure no filter took more than 2 seconds of runtime, and if so, logstash would self-terminate (to avoid the required manual intervention). 

The watchdog was broken in Logstash 1.2.0, and I recognized that fact soon after, but the report rate of "stuck filters" had, anecdotally, dropped to nearly zero, so I kind of just allowed the watchdog to continue not to function properly (it is not used since 1.2.0).

Given it's been a few years, _and_ we are moving towards better visibility within the pipeline, I agree with this change.

**Comment by jordansissel** [comment]
For a tangent, as part of the "grok regexp exponential oh my!" problem, I sent JRuby a patch to make Joni interruptable (via Thread.interrupt() in Java), so if we want to interrupt grok in the future, we have a way to do it without terminating logstash.
