### ISSUE TITLE
Move messy [@version] into [@metadata][@version]

### ISSUE THREAD

**Issue by JakeFromTheDark** [elastic/logstash#3866]
Always appended field `@version` has internal purpose only. No one behind the Logstash (f.e. an Elasticsearch) takes care about Logstash internal variables. Therefore it should not mess the output events, so it should be hidden in `@metadata`.

It affects mainly:
* `LogStash::Event`
* `LogStash::Codecs::Graphite`
* `LogStash::Outputs::Graphite`
* `LogStash::Codecs::OldLogStashJSON`
* `LogStash::Outputs::Gelf`
* `logstash-output-elasticsearch-*/lib/logstash/outputs/elasticsearch/elasticsearch-template.json`

**Comment by jordansissel** [comment]
@JakeFromTheDark changing this will affect any future schema changes and further there will be no way to identify schema version from an event. Without a version, there's no way to know how to convert between two schemas in Logstash. The previous Logstash schema (pre logstash 1.2.0) is converted to the new one using the oldlogstashjson schema. I added a version field specifically because if we ever change the schema incompatibly again, we can bump the version and know the difference.

I don't know if removing `@version` is a good idea.

If we ever change the schema again, it will be necessary to know how to identify older schema events so that they can be converted to newer schema.

Your claim "no one behind the logstash takes care ..." but having the version will be a necessary part of converting old logs to a newer schema (otherwise how can we know what version schema is used on a given event?)

I'm not convinced at this time. Can you explain the negative impact of having the version field? How does it negatively affect graphite and gelf?

**Comment by JakeFromTheDark** [comment]
@jordansissel - Understood a purpose of the `@version`. I didn't suggest to *remove* it completely, but just to *move* it into some hidden (not exported) place - to a great `@metadata`.

The `graphite` and `gelf` are fine with that, but why to explicitly disable `@version` on (ideally) every output plugin (and in Elasticsearch templates f.e.) instead of just hiding it at an event birth.

Unnecessary ~10 bytes in EVERY event.

Source data typically uses own `version` field of something data related. Then (f.e. Kibana) user can be pretty confused with many version fields (at least `version` and `@version`).

It's not a bug or an issue, of course, it should be meant as an enhancement hint only :)

**Comment by jordansissel** [comment]
@JakeFromTheDark the purpose of `@version` is to read it after storing it later, so if it's only internal inside Logstash, then there's nothing to communicate it to, and there's no need for it, and we've lost the ability to version the schema. So what would `@version` be used for if not outside of Logstash, or why would Logstash have it if it never communicated it?

**Comment by jordansissel** [comment]
Also, can you work around this by using the mutate filter to remove the `@version` field if you don't want it?

**Comment by JakeFromTheDark** [comment]
@jordansissel - So, I'm not convinced at this time also.

The `mutate` filter to remove the `@version` field is exactly what I use right now already :P

**Comment by anhlqn** [comment]
This looks like an old issue, but is it safe to use mutate filter to remove @version field? The value is always 1 so I don't see any point of having it sent to ES.

**Comment by JakeFromTheDark** [comment]
Yes, I'm removing this field by `mutate` filter with no issue.
So, closing the ticket.

**Comment by anishp55** [comment]
i know this is an old issue, but i have been removing the @version field with a mutate filter, but it still appears in my final output, is there anyway to disable this?

**Comment by johan-boule** [comment]
Elasticsearch is supposed to have its own version field autoincremented when a document is updated, but it seems to be hidden. After reading this issue, I still have absolutely no idea what logstash's @version field is for, so i'll remove it using a mutate filter. It's really confusing.
