### ISSUE TITLE
Logstash Elasticsearch configuration example documentaion issue.

### ISSUE THREAD

**Issue by tarunsapra** [elastic/logstash#3976]
Hi Logstash Team,

The following link contains configuration examples for logstash and elasticsearch 
https://www.elastic.co/guide/en/logstash/current/config-examples.html

One of the things it doesn't mention is that in order for newer version of logstash and elasticsearch to work there needs to be " protocol => "transport" mentioned in the output plugin of logstash configuration section.

For example -

output {
 elasticsearch {
 host => localhost
 cluster => "myES"
 protocol => "transport"
  }
  stdout { codec => rubydebug }
}

**Comment by untergeek** [comment]
You should probably use `protocol => http` instead.  This will be the default in Logstash 2.0.  As a result, the documentation absence you observe here will become a non-issue.  Logstash 2.0 is slated to be released at the same time as Elasticsearch 2.0, which is in just over 3 weeks, at present schedule.

That said, the transport protocol depends on Elasticsearch jar files and is therefore version dependent, just like the node protocol.  All Elasticsearch 1.x jars should work with any Elasticsearch 1.x cluster, so Logstash should not need an update to `protocol =>` in order to work.  Changes have been made for security's sake, but you should only need to change if you were coming from a very old version of Logstash.

**Comment by suyograo** [comment]
See https://www.elastic.co/blog/logstash-2-0-0-beta1-released

**Comment by rajiv180984** [comment]
Thanks untergeek  
My problem resolve by putting protocol=>http in elasticSeach part
