### ISSUE TITLE
Add simple integration test infra to Logstash core

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#4063]
We have good system wide integration tests in Jenkins using [logstash-kitchen](https://github.com/elastic/logstash-kitchen) repo. These are end-end tests infrastructure which validate things like installing/uninstalling plugins, smoke tests for ES, file input, Kafka etc. 

We also need a simple integration test bed in Logstash core which tests multiple combinations of input, filters, codec and output using various test data sets. We should aim to keep the inputs and outputs simple, maybe just use the generator input (or file input) and file output. This will help us catch issues like #4048 which could be reproduced using file input, grok filter and json codec.

Suggest using `spec/integration` dir for adding these tests. Should also add `rake tests:integration-plugins` which will install dependencies, run these simple integration tests. 

Ultimately, it should be easy enough to drop in a config file plus a results (expected output) fixture and the rest should be taken care of by the infra.

**Comment by guyboertje** [comment]
At one time I considered storing the config and expectations in ES, but in attempting to be self-contained we could store a list of config and expectations in a (Yaml JSON?) file and have a runner that worked through them with a bit of help from RSpec.

**Comment by purbon** [comment]
+1 on this idea @suyograo, for this business I see, as you said, a collection of rspec tests inside ```spec/integrations```, this test should test the filter integrations, test kitchen should become the external systems integration tests.

On a more detailed stuff we can leverage some of the actual helpers, that with a bit of more love, will let pass a configuration to the pipeline (basically a collection of filters), and get the output. 

This should not be a complicated task to archive.

Speaking about

> Ultimately, it should be easy enough to drop in a config file plus a results (expected output) fixture and the rest should be taken care of by the infra.

is hard for me to see it right now, especially because drop in test are hard then to fetch context, we should clearly define the interfaces and the report outcome for it so the test results are nice to debug and work with.

**Comment by ph** [comment]
+1 on spec/integration and kitchen for isolated command testing.

**Comment by colinsurprenant** [comment]
+1

I guess a lots of tests involving codecs and filters can be done easily using stdin/stdout, we could maybe look at reusing the perf framework and add the ability to compare output for validation?

It would be nice to be able to easily and "quickly" run a good set of integration tests through rake so that we can integrate this in our "tdd" loop. I would suggest we first focus on this and make it as efficient as possible. Then we can add move involved integration tests using test kitchen for example. 

Thoughts?

**Comment by purbon** [comment]
@colinsurprenant I don't think we've to reuse the perf framework, I think is more easy done by reusing some of the existing specs helpers and make them a bit more generic.

I'm +1 on the idea of good/fast integration test, we need first to define which ones are the integrations we want to run/test (combinations of filters).

**Comment by guyboertje** [comment]
RSpec 3 has a Output matcher http://www.relishapp.com/rspec/rspec-expectations/v/3-3/docs/built-in-matchers/output-matcher for stdin and stderr etc.

**Comment by purbon** [comment]
yes, my vote goes for crafting good rspec helpers/runner that lets us drop the stuff and pass it through the pipeline.

**Comment by colinsurprenant** [comment]
@purbon you're only allowed 1 vote per issue. :cop:

**Comment by ph** [comment]
Initial part done in #4166

**Comment by suyograo** [comment]
Fixed in #5963
