### ISSUE TITLE
Installing Logstash community plugins from Github

### ISSUE THREAD

**Issue by davmrtl** [elastic/logstash#4066]
Hi,

Is it possible to add support for installing community plugins from Github like you did in Elasticsearch? 
As an example:
```
./bin/plugin install <user>/<repo>[/<tag_or_branch>]
```
Thanks,

David

**Comment by untergeek** [comment]
@davmrtl It's an interesting idea.  Even if installing from Github were allowed, the dependencies on other RubyGems would still require access to RubyGems.  Because all of the dependencies (not just Logstash ones) already depend on RubyGems, we thought it simplest to expect community plugins to also be published to RubyGems.org.  

[The instructions to do so are online](https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_input_plugin.html).  More specifically, the end of the document contains a section on [how to publish your plugin to RubyGems.org](https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_input_plugin.html#_publishing_to_ulink_url_http_rubygems_org_rubygems_org_ulink).

**Comment by davmrtl** [comment]
@untergeek Thank you for the quick response. I'll take a look at the links you provided.
