### ISSUE TITLE
What reads the "type" property of log events such as "apache_access"? Where is the behavior of these filters documented?

### ISSUE THREAD

**Issue by jhftrifork** [elastic/logstash#4102]
In the `input` section of a Logstash `.conf` file defining a pipeline, I can put a `file` input such as:

```
file {
  path => "/var/log/apache/access.log"
  type => "apache_access"
}
```

I'm told that that the `type` field is a tag which is available on the log events emitted by this input section, and the value (such as `"apache_access"`) can be used by filters to define how to parse those log strings.

Where is the filter which works on events tagged with type `"apache_access"`? What other type strings can I use (e.g.`"apache_log"`, `"syslog"`, ...), and where is the source/documentation for their corresponding filters?

**Comment by untergeek** [comment]
Please move this question to https://discuss.elastic.co/c/logstash

GitHub issues is not the proper place for usage questions.

**Comment by jhftrifork** [comment]
@untergeek @suyograo I figured this was an appropriate place since the docs are in the repository. It's a documentation bug.

**Comment by untergeek** [comment]
@jhftrifork, I'm sorry you feel that this is a documentation bug.  It sounded much more like a usage question because all documentation since 1.4.x has reflected that the use of "type" in this way was deprecated. This usage has been officially obsoleted/removed in Logstash 2.0.  

> I'm told that that the type field is a tag which is available on the log events emitted by this input section, and the value (such as "apache_access") can be used by filters to define how to parse those log strings.

If you've been informed by anyone, or have been reading blogs or other media that suggests you can use the "type" field in this way, such information is out of date.  If you've found a specific, incorrect entry in our documentation, we definitely want to fix it.  You could even click the edit link to the right of any paragraph in our [online documentation](https://www.elastic.co/guide/en/logstash/current/) to submit a pull request for a correction.

The proper way to use the "type" field (or any other field for that matter) for deterministic behavior is via [conditionals](https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html#conditionals).
