### ISSUE TITLE
logstash fails to start if the parent directory contains a space

### ISSUE THREAD

**Issue by jpountz** [elastic/logstash#4283]
Reproduction on my MacBook:
 - &lt;Download logstash 2.1.0&gt;
 - mkdir "DIR WITH SPACE"
 - cd DIR\ WITH\ SPACE
 - tar -xvzf ~/Downloads/logstash-2.1.0.tar.gz
 - cd logstash-2.1.0
 - ./bin/logstash

And I get: `Error: Could not find or load main class EL.lostash-2.1.0-heapdump.hprof`.

**Comment by dadoonet** [comment]
++ cc @TheMalloum

**Comment by jsvd** [comment]
This issue has been introduced with the HeapDumpPath start up option.
When a -XX:HeapDumpPath=<path> the JAVA_OPTS argument is corrupted during the step where all java options are prepended with "-J", code [here](https://github.com/elastic/logstash/blob/master/bin/logstash.lib.sh#L112-L117)

This results in 


bin/jruby --1.9 -J-XX:+UseParNewGC -J-XX:+UseConcMarkSweepGC -J-Djava.awt.headless=true -J-XX:CMSInitiatingOccupancyFraction=75 -J-XX:+UseCMSInitiatingOccupancyOnly -J-XX:+HeapDumpOnOutOfMemoryError **-J-XX:HeapDumpPath="/tmp/a -Jb/logstash-2.1.0/heapdump.hprof"** -J-Xmx1g /tmp/a b/logstash-2.1.0/lib/bootstrap/environment.rb logstash/runner.rb agent -v


instead of 

bin/jruby --1.9 -J-XX:+UseParNewGC -J-XX:+UseConcMarkSweepGC -J-Djava.awt.headless=true -J-XX:CMSInitiatingOccupancyFraction=75 -J-XX:+UseCMSInitiatingOccupancyOnly -J-XX:+HeapDumpOnOutOfMemoryError **-J-XX:HeapDumpPath="/tmp/a b/logstash-2.1.0/heapdump.hprof"** -J-Xmx1g /tmp/a b/logstash-2.1.0/lib/bootstrap/environment.rb logstash/runner.rb agent -v

**Comment by suyograo** [comment]
Fixed via https://github.com/elastic/logstash/pull/4303
