### ISSUE TITLE
logstash constantly restarting

### ISSUE THREAD

**Issue by zabbal** [elastic/logstash#4380]
Under ubuntu 14.04 logstash is completely broken: it's constantly respawning with:
init: logstash main process ended, respawning
while /var/log/logstash/logstash.err is completely empty.

**Comment by zabbal** [comment]
Could be related to #4352 - feels like .deb packages don't have any sort of QA.

**Comment by jsvd** [comment]
@zabbal it is true, most of the validation on the package is done just for the "happy path", there isn't any automated testing yet..
That aside, I just installed the 2.1.1 package on ubuntu 14.04, added a config to /etc/logstash/conf.d/, did `sudo service logstash start` and it started correctly.
I introduced an error (tcp output to a port that isn't open) and I saw errors on the logstash.stdout instead of .err. this needs to be fixed
Then I edited the config to use a non existing plugin, tried restarting and correctly got:

```
$ sudo service logstash restart
Configuration error. Not restarting. Re-run with configtest parameter for details
```

I should note that the writes to the log file are buffered so if the log rate is very low the error might not be flushed to file immediately after happening

This needs to be fixed, but in the meantime can you provide the config you're using so we can't figure out what's wrong?

**Comment by zabbal** [comment]
The weird thing is "service logstash configtest" gives me:
Configuration OK

Have you done clean install or updated from 1.*? I guess that the installation scripts do not account for proper migration from previous versions and everything breaks.

**Comment by zabbal** [comment]
I'll give a try to fresh install in isolated container. Btw, #3606 seems to be related - having to debug ugly shell script just to get the service running is troubleshooting nightmare.

**Comment by zabbal** [comment]
Holy crap, it's completely broken! The logstash package does not have dependency on java! It only depends on logrotate, dependency on openjdk-8-jre-headless is omitted. It can't possibly work.

**Comment by rgevaert** [comment]
Iirc neither deb packages provided by elastic have depended on Java for long.

**Comment by markwalkom** [comment]
No, they have not.

**Comment by talevy** [comment]
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues
