### ISSUE TITLE
runtime documentation the metrics api

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#4464]
As an api user it would be great to have documentation for the metrics, and each other we've, APIs. This is intended to be bundled with logstash and startup during running time locally. It could be archived by reusing projects like:

* [Swagger](https://github.com/OAI/OpenAPI-Specification) ([example](http://petstore.swagger.io/))
* [API blueprint](https://apiblueprint.org/)

I've used with success Swagger in previous projects, I kinda like it for their good interface. 

related to #4463

**Comment by suyograo** [comment]
@purbon this is better done through sense to be consistent with other products. Sense's autocomplete and context aware features will help end users.

**Comment by purbon** [comment]
@suyograo I don't think so, this are two different things, one thing is discoverability and another is to have an SDK with autocomplete. 

* With a tool like this you let users discover resources, navigate through them, see what do they do, etc. 
* With autocomplete you help people not having to remember each API by default.

See you get javadocs and autocomplete for java, or other kind of documentation that exist in programming languages.

I think the discussion should be if we aim to have our API documentation only in the website, or also embed in our product. For offline situations, having the api in the product is going to be great. 

If you don't feel comfortable with having this ON by default, we can always have it with a flag. What do you think?

**Comment by debadair** [comment]
My gut reaction to this is that if we don't want to maintain slightly different API docs in multiple locations. I can see the value in having the "short descriptions" embedded, but am concerned about how we can make that happen and ensure that everything stays in sync.

**Comment by purbon** [comment]
Hi,
  thinking about it, a middle term approach would be to have the api docs
generated with the same tool as the ones we publish online, but saved
locally so they could be served locally. This will help as only one source
of docs is used, but also provide some API definition without forcing
people to visit the doc website online. What do you think?

- purbon

**Comment by debadair** [comment]
Unfortunately, I don't think we can just drop the generated docs in a "docs" directory and have something that's usable offline. Currently, when you run a web server locally to view the docs, it loads the style sheet from the website. If you just open the index file or don't have a net connection, the docs aren't rendered correctly. Any cross-doc links will also attempt to load pages from the website. 

We already have the situation I was concerned about. I didn't realize we have JSON rest-api-specs that include descriptions. For example: [shield.delete_role.json](https://raw.githubusercontent.com/dakrone/x-plugins/8acb9a462f377adc339e1fbc2529fb7a530de1d4/elasticsearch/x-pack/shield/src/test/resources/rest-api-spec/api/shield.delete_role.json?token=AAWIUiIBXOX5g8Zt6RmWWG2PjR1Nei-Pks5Wpp0QwA%3D%3D) In Elasticsearch, these embed doc links that are potentially fragile: https://github.com/elastic/elasticsearch/commit/949461f5fcefd79ad512fb23483ad613caf900e7

Since we're already doing this, I guess the issue becomes making sure we're consistent for all products and sorting out a way to get the most out of it with the least amount of effort required to keep it consistent with the asciidoc docs.

**Comment by suyograo** [comment]
> I think the discussion should be if we aim to have our API documentation only in the website, or also embed in our product. For offline situations, having the api in the product is going to be great.

I haven't heard any users ask about offline docs. Lets punt this until we have enough users asking for it. Also, as @debadair mentioned, maintaining this in-product and documentation will be an effort.

**Comment by debadair** [comment]
I wasn't aware of it, but there *is* a way to generate a standalone version of the docs, if we decide that dropping them in is worthwhile.

**Comment by suyograo** [comment]
There's really no need for this now. Closing
