### ISSUE TITLE
./plugin list doesn't show deps installed

### ISSUE THREAD

**Issue by robgil** [elastic/logstash#4524]
logstash 2.1.1-1
centos6

When doing an offline plugin install, deps will be missing if there are any. As such, doing a pack will get the dependencies at least on to the offline box. Is there a way to install dependencies through the "plugin" utility?

If so, how can I validate all the deps are there? (offline)

Example of installing a plugin dep offline with the pack unpacked

```
# ./plugin install --no-verify --local webhdfs
Installing webhdfs
Error Bundler::HTTPError, retrying 1/10
Could not fetch specs from https://rubygems.org/
.....
```

It does install, but errors out after 10 tries. 

Heres what happens when a plugin is missing a dep

```
# ./plugin install --no-verify --local /mnt/opt/logstash-infinite/plugins/logstash-output-webhdfs-2.0.2.gem 
Installing logstash-output-webhdfs
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "webhdfs":
  In Gemfile:
    logstash-output-webhdfs (= 2.0.2) java depends on
      webhdfs (>= 0) java
Could not find gem 'webhdfs (>= 0) java', which is required by gem 'logstash-output-webhdfs (= 2.0.2) java', in any of the sources.
```

Verbose only shows plugin versions, no deps

```
# ./plugin list --verbose
logstash-codec-collectd (2.0.2)
logstash-codec-dots (2.0.2)
logstash-codec-edn (2.0.2)
logstash-codec-edn_lines (2.0.2)
logstash-codec-es_bulk (2.0.2)
logstash-codec-fluent (2.0.2)
logstash-codec-graphite (2.0.2)
....
```

**Comment by purbon** [comment]
Hi, I understand your pain, ... thanks a lot for your feedback. To answer your questions.

>  Is there a way to install dependencies through the "plugin" utility?

No there is no way this days, if all required dependencies are in the pack they will be installed when you do the offline installation, otherwise the plugin will not be installed at all. otherwise this is a bug, i guess related to the situation you experience with your first comment. 

> If so, how can I validate all the deps are there? (offline)

if you want to validate this, you can for example cat the Gemfile.lock, all deps should be there.

> Verbose only shows plugin versions, no deps

the command used list only plugins and their versions, would not be hard to extend this functionality with a flag to include deps. Do you think this would be useful for other users?

**Comment by ph** [comment]
I don't think we should display all the dependencies for the installed plugins for now, I think this will generate more confusion and its a sign that our current flow are confusing and broken to say the least.

I think the core of this problem is the way we make the pack install works which was missing some dependencies in the first place. The new offline flow https://github.com/elastic/logstash/pull/6404, take care of take and will only bundle the dependencies that we actually needed.
