### ISSUE TITLE
Hide the implementations details of the MetricStore when retrieving metrics

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#4529]
Hi,
  as a user of the metric store I don't expect to interact with implementation details, today when asking the metric store for data it returns an instance of a ```Concurrent::Map```, this makes the consumer of this api aware of an implementation detail that might change in the feature.

We should return a plain ruby hash, or similar.

The way the Metric store is implemented also make the values of this ```Concurrent::Map``` be a MetricType instance. This is problematic as to retrieve a value out of it a user must call it's value method. The returned value object for the metric store should be a plain ruby object or similar.

**Comment by ph** [comment]
Lets take the followings keys and namespaces.

```
stats.pipelines.pipeline_X.plugins.inputs.file_XXXXXX.events.out
stats.pipelines.pipeline_X.plugins.filters.grok_XXXXXX.events.out
stats.pipelines.pipeline_X.plugins.filters.json_XXXXXX.events.in
```

And we want to retrieve the following branch:
```ruby
metric_store.get(:stats, :pipelines, :pipeline_X)
```

I think what you are proprosing is this following format, Correct?

```ruby
{
  :plugins => {
    :filters => {
      :file_XXXXXX => { :events => { :out => 1 } },
      :grok_XXXXXX => { :events => { :out => 1 } },
      :json_XXXXXX => { :events => { :out => 1 } },     
    }
  }
}
```
I am a bit on the fence to not return the Metric type at the end and return the concrete value.
Since we are losing important information that could be used when serializing the logstash event for the internal pipeline.

This is what I am proposing.

```ruby

counter = MetricType::Counter.new

{
  :plugins => {
    :filters => {
      :file_XXXXXX => { :events => { :out => counter } },
      :grok_XXXXXX => { :events => { :out => counter } },
      :json_XXXXXX => { :events => { :out => counter } },     
    }
  }
}
```

To make thing simplier I can add a `to_s` or `to_json` that return to a default value (which is mostly a call to #value)
So `Logstash::Json.dump` should return what you want, what do you think?
I think this gives us a bit more flexibility, wdyt?
```

**Comment by purbon** [comment]
> I think what you are proprosing is this following format, Correct?

for the case of the webapi this would be much appreciate it as it really simplify the fetching process. Speaking about the format, don't have to be 100% like this, but something alike would be very nice.

> Since we are losing important information that could be used when serializing the logstash event for the internal pipeline.

not sure I follow you with that, can you put me an example. For now I only see:

* namespace and key, already covered and clear by the nested keys.
* value, obviously the value is the counter in this example.
* type, this is the only one you are losing, but do we really need it? for the api point of view I don't think so.

> To make thing simplier I can add a to_s or to_json

both methods are not good options, this would be a behaviour I would expect from ```to_hash```.

**Comment by jordansissel** [comment]
> We should return a plain ruby hash, or similar.

I have a possible alternative: Provide a more use-case specific API -- that is, provide exactly what folks will need, instead of returning a collection:

* For searching/iterating metrics: Instead of being able to ask for all metrics (and returning a Map, or Hash, or similar), maybe we provide an `#each` method that returns an Enumerable such that clients (developers or HTTP or whatever) can use `#select` or similar Enumerable methods to narrow down exactly which metric keys to fetch -- and the yield from an `#each` would be a metric instance.

* For serializing to JSON, having each Metric support `#to_json`, If the above were done, serializing metrics could be done with `metrics.collect(&:to_json)` where `metrics` is a `MetricStore`

**Comment by ph** [comment]
> For serializing to JSON, having each Metric support #to_json, If the above were done, serializing metrics could be done with metrics.collect(&:to_json) where metrics is a MetricStore

I have done this in my current branch.


> For searching/iterating metrics: Instead of being able to ask for all metrics (and returning a Map, or Hash, or similar), maybe we provide an #each method that returns an Enumerable such that clients (developers or HTTP or whatever) can use #select or similar Enumerable methods to narrow down exactly which metric keys to fetch -- and the yield from an #each would be a metric instance.

I think we could add that too, but right now its returing a hash of the correct structure, I think its kinda neat since we will return the same format when serializing.

**Comment by ph** [comment]
#4602 Hide the implementation of the metric store.

`MetricStore#get` return a structured hash with the MetricType at the end of the leaf, MetricType now implements in the base class two different method.`to_hash` which return all the information of the metric into a friendly hash format that can be used to create a `LogStash::Event` internally and a `to_json_data` which will return the serialized format. In most of the cast it will be the direct value.

`MetricStore.get_with_path` takes a namespace path and will return all the nested metric, this method also support retrieving multiples nodes per branch.

`/stats/pipelines/pipelines01, pipelines02/` will return the information for both of the pipeline.

`MetricStore#each` Also accept the same path lookup, but will only return an array with all the nested metric types without containing a structure.
