### ISSUE TITLE
Configuration system similar to Apache httpd

### ISSUE THREAD

**Issue by ThomasdOtreppe** [elastic/logstash#4530]
Apache has conveniently 2 directories, called ```sites-enabled``` and ```sites-available```. Configuration (sites) should be created in the ```sites-available``` directory. Once that is done, you (ideally) create a symlink of the configuration that need to be enabled in the sites-enabled directory (or use a2ensite/a2dissite to do the job).

I usually split my configuration in several files for clarity but there is nowhere the disabled configuration can be put (unusued 'inputs' and 'filters'). It usually require to create a separate directory and move them there.

It would be nice if Logstash had such system. What do you think?

**Comment by jordansissel** [comment]
In my own experience, I've always ignored the sites-enabled/sites-available and simply deployed configuration directly to the sites-enabled directory. It's been nearly 10 years since the last time I managed systems by hand (without puppet, for example), so the enabled-vs-available concept was never used by me since I so rarely manage individual machines (moving files around, etc).

It's also a bit confusing to have an out-of-band signal (a symlink) indicate whether or not a config file is in use. For my own experience, I don't find much value in an enabled-vs-available directory structure.

The coming future for Logstash pipeline configuration is going to be API-driven, so it is very likely that the concept of a pipeline configuration file (like we have today) will no longer exist in this future. For this reason also, I am not in favor of adding this enabled-vs-available configuration structure.

Of course, there's nothing stopping you from doing this today, where Logstash could be told to load all files from a given directory (or loading files matching a wildcard such as `*.conf` or `*.conf.enabled`) and you manage this yourself.

**Comment by ThomasdOtreppe** [comment]
Since it will change, there isn't much point in doing this.

Regarding loading based on a match is a good idea except the modification will most likely be done in the init.d file and when you are using the deb or yum repository, the init.d file will be overwritten and changes will be lost when updated (which is what happens with extra plugins installed; they have to be reinstalled).

**Comment by jordansissel** [comment]
@ThomasdOtreppe True, though the init script does permit changing the configuration path: https://github.com/elastic/logstash/blob/master/pkg/logstash.sysv#L35-L45 via LS_CONF_DIR variable (say, in /etc/sysconfig/logstash or etc/default/logstash). As an alternative, you could have /etc/logstash/conf.d be your `enabled` and /etc/logstash/available.d be your `available` with no change to the init script or its configuration.
