### ISSUE TITLE
[file input] re-using inodes leads to missing/corrupted data - please implement periodic cleanup of sincedb entries

### ISSUE THREAD

**Issue by shoggeh** [elastic/logstash#4566]
Hi,

Sincedb for file input infinitely keeps reference to all files (inodes) that were ever tracked.
Under some (frequent) conditions this will lead to missing or corrupted data.

For example if there is any kind of log rotation mechanism that actually deletes any (even single) source file and new files are created afterwards, then you will certainly see this issue occurring at some point as file will be eventually created using an inode that was already tracked in past. Issue is even more visible if "start_position": is set to "beginning" as likely first parsed message will be incomplete.

The more input files you create the more chances to observe this issue. In my repro case I've created and rotated (deleted) around 1k files per day and I've seen this issue re-occurring few times a day. Currently my sincedb files are having over 100k lines.

If possible please implement dropping references from sincedb to files that do not exist anymore.

**Comment by shoggeh** [comment]
While not solving the real underneath issue It looks like that pull request https://github.com/logstash-plugins/logstash-input-file/pull/50 with follow_only_path would mitigate my issue fully.

Yet, I guess the most ideal solution would be to have everyting -- inode + path tracking (at the same time) altogether with periodic sincedb cleanup. ;)

**Comment by guyboertje** [comment]
@shoggeh - with the latest [refactor of filewatch](https://github.com/jordansissel/ruby-filewatch/pull/74) I have introduced an object that holds the state of a 'watched_file'.
This leads nicely to the rework of the sincedb.  I intend that the collection of watched_file object entries are loaded and saved in place of the sincedb.  This means that much more knowledge about the file is loaded and saved in the sincedb in a backward compatible way.  It will hold the path, inode, creation time, last_position, last_state.  This means that when we start watching a path that we have seen before (by looking up all entries with the same path and/or inode) we can decide more accurately whether it is the same file or a new one.  Further, because this collection == the sincedb, when `stat` on an entry fails it is deleted from the collection and therefore from the sincedb file.

/cc @jordansissel

**Comment by shoggeh** [comment]
Hi @guyboertje,

Sorry for being impatient, but do you have any insight on when this might get implemented and/or shipped? Current implementation heavily corrupts logstash instances with a lot of input files created/rotated/deleted on daily basis.

**Comment by guyboertje** [comment]
@shoggeh I have implemented the watched_file_store that can be loaded from an existing sincedb file and persisted to a new sincedb file with more info per line.  The next step is to integrate it into filewatch.

I have a real problem with constantly trying to change filewatch with backward compatibility.
I think maybe its time to build filewatch2.  This will allow me to move quicker with these changes.

**Comment by gmoskovicz** [comment]
@guyboertje @suyograo any ETA for this? Or any expected release where this will be included?

Thanks!

**Comment by shoggeh** [comment]
(I personally workarounded this with putting Filebeat in front of Logstash and that solution works much better in my scenerio, as by decoupling Logstash from physical files I've effectively created a cluster of Logstash indexers (as I use multiple receiver nodes))

**Comment by purbon** [comment]
moving this to https://github.com/logstash-plugins/logstash-input-file/issues/111 as is clearly a file input issue
