### ISSUE TITLE
Unable to find a non world-writable directory for Dir::tmpdir. Consider setting ENV['TMPDIR'], ENV['TMP'] or ENV['TEMP '] to a non world-writable directory.

### ISSUE THREAD

**Issue by zdharmawan** [elastic/logstash#4600]
Hi all,

I am using Logstash 2.1.1 (ES 2.1.1) on Windows 7. Every time, I start logstash agent, it's outputting this:
```
Unable to find a non world-writable directory for Dir::tmpdir. Consider setting ENV['TMPDIR'], ENV['TMP'] or ENV['TEMP '] to a non world-writable directory.
```
I tried downgrading to 2.1.0. It works fine.

Regards,

Zul

**Comment by ph** [comment]
@zdharmawan Can you share your configuration?

**Comment by zdharmawan** [comment]
Input coming from rabbitmq, do some json filtering, remove the dot, output to elasticsearch and stdout
 
```
input {
  rabbitmq {
    host => "localhost"
    port => "5672"
    queue => "my-queue"
    durable => true
    user => "guest"
    password => "guest"
  }
}
filter {
  json {
    source => "message"
    remove_field => [ "message" ]
  }
  de_dot {
  }
}
output {
  elasticsearch {
    hosts => ["localhost:9200"]
  }
  stdout {
    codec => rubydebug
  }
}
```

**Comment by ph** [comment]
Quick check I dont see what could use tmpdir in the plugins you have defined here:

Can you do the following? Set the env variable `DEBUG` to the value `stacktrace` and start logstash with `--debug` option and gist the log and link it from this issue.

**Comment by zdharmawan** [comment]
@ph Actually I have another conf file, which I call both the same time.
Even I combined both files, it's still giving the error.
The other conf file contains output to AWS S3 only:
```
output {
s3 {
    access_key_id => "<my-access-key-id>"
    secret_access_key => "<my-secret-key>"
    region => "eu-west-1"
    bucket => "<my-bucket>"
    prefix => "<my-folder>/"
    size_file => 2048
    time_file => 5
    canned_acl => "private"
 }
}
```

When I do what you suggested, I do see the message aforementioned. Here's [the debug output](https://gist.github.com/zdharmawan/48891276808a058771c6)

**Comment by ph** [comment]
Yup the problem come from the S3 output we can see it in the stacktrace. 

```
C:/development/logstash-2.1.1/vendor/jruby/lib/ruby/shared/tmpdir.rb:41:in `tmpdir'
C:/development/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-output-s3-2.0.3/lib/logstash/outputs/s3.rb:105:in `S3'
C:/development/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-output-s3-2.0.3/lib/logstash/outputs/s3.rb:65:in `(root)'
org/jruby/RubyKernel.java:1040:in `require'
```

I looked at the changes in the s3 output since 2.1.0 and 2.1.0 and I don't see anything that could cause this issue.
 
Since it work in 2.1.0 and don't in 2.1.1. I think this is a JRUBY bug on windows 7 concerning `File.stat`, I am not sure yet but it might be this one https://github.com/jruby/jruby/issues/3430. One thing we can try in this case, can you download jruby 1.7.24 and replace the `jruby` directory in `vendor` with this release? (Just uncompress the file in vendor and rename it to jruby)

Link to the jruby 1.7.24 release: https://s3.amazonaws.com/jruby.org/downloads/1.7.24/jruby-bin-1.7.24.zip

I know that this release fixes a few problems under window 7 for file handing.

**Comment by zdharmawan** [comment]
@ph It works! I even tried this on logstash-2.2.0, still works.
Thanks.
