### ISSUE TITLE
Bundler could not find compatible versions for gem "jdbc-sqlite3" : Offline installation of third party plugin

### ISSUE THREAD

**Issue by ShekharSahu** [elastic/logstash#4627]
I am new to ELK. I am running it on windows machine. The logstash version is 2.2.0. 
I have to load data from mongoDB to ES. Since there is no official plugin. I am trying to install a third party plugin : logstash-input-mongodb (https://github.com/phutchins/logstash-input-mongodb).

When I try to install it from the offline location using the following command
`
\logstash\bin>plugin install --local --no-verify "D:\.....\logstash-input-mongodb-master\logstash-input-mongodb-0.3.3.gem"`

I get the following error message
`
Installing logstash-input-mongodb
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions
 for gem "jdbc-sqlite3":
  In snapshot (Gemfile.lock):
    jdbc-sqlite3 (= 3.8.11.2)
`
`
  In Gemfile:
    jdbc-sqlite3 (>= 0) java
`
`
    logstash-input-mongodb (= 0.3.3) java depends on   jdbc-sqlite3 (= 3.8.10.1) java
`
`
Running bundle update will rebuild your snapshot from scratch, using only the gems in your Gemfile, which may resolve the conflict. 
`

The reason I am installing with --no-verify and --local is because without it I get the following error
`Validating D:\........\logstash-input-mongodb-0.3.3.gem
 Installing logstash-input-mongodb 
Error Bundler::HTTPError, retrying 1/10
Could not fetch specs from https://rubygems.org/
Error Bundler::HTTPError, retrying 2/10
Could not fetch specs from https://rubygems.org/
Error Bundler::HTTPError, retrying 3/10
Could not fetch specs from https://rubygems.org/
Error Bundler::HTTPError, retrying 4/10
Could not fetch specs from https://rubygems.org/
Error Bundler::HTTPError, retrying 5/10
Could not fetch specs from https://rubygems.org/
Error Bundler::HTTPError, retrying 6/10
Could not fetch specs from https://rubygems.org/
Error Bundler::HTTPError, retrying 7/10
Could not fetch specs from https://rubygems.org/
Error Bundler::HTTPError, retrying 8/10
Could not fetch specs from https://rubygems.org/
Error Bundler::HTTPError, retrying 9/10
Could not fetch specs from https://rubygems.org/
Error Bundler::HTTPError, retrying 10/10
Could not fetch specs from https://rubygems.org/
Too many retries, aborting, caused by Bundler::HTTPError
ERROR: Installation Aborted, message: Could not fetch specs from https://rubygems.org/`

How do I solve this issue?

**Comment by purbon** [comment]
@ShekharSahu Hi, you got a couple of issues in your commands, first

> bin>plugin install --local --no-verify "D:\.....\logstash-input-mongodb-master\logstash-input-mongodb-0.3.3.gem"

is not an intended command, when using the `--local` flag, all your dependencies should be inside the `vendor/cache` directory, otherwise everything will fail. You also need to pass the plugin name, not an URL. If passing a URL you are actually expected to have this plugin locally available, aka in the file system.

I would recommend reading https://www.elastic.co/guide/en/logstash/current/offline-plugins.html to start with, this describe the necessary steps to enable offline installations.

I would say this is not really an issue, is more of a usage questions, so I would close this issue for now. feel free to reopen if we spot actually a concrete issue. You could also leverage the https://discuss.elastic.co forum for such a questions.

Happy to reopen if we spot an issue with the current building.

Let me know if your answer your questions.
