### ISSUE TITLE
Hard stop exception occurs when setting a value on a path and some intermediate value is set already

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#4743]
Confirmed on de_dot and mutate rename. These tests fail.
mutate rename

```
  describe "rename with path destination field ([][][]), when part of the path is defined" do
    config <<-CONFIG
      filter {
        mutate {
          rename => [ "field_one", "[some][other][key]" ]
        }
      }
    CONFIG

    sample("field_one" => "value", "x" => "one", "some" => {"other" => "a value"} ) do
      expect(subject["[some][other][key]"]).to eq("value")
    end
  end
```

Raises IndexError: string not matched.
de_dot

```
  describe "Customer issue" do
    let(:config) do
      {
        "nested" => true,
        "fields" => ["[logSource][class.name]", "[logSource][file.name]"]
      }
    end
    let(:attrs) do
      {
        "customInfo" => { "application.id.remote" => "coyote" },
        "logSource" =>  { "class.name" => "coyote" }
      }
    end
    it "should not break" do
      event["[logSource][class]"] = "foobar"

      expect { subject.filter(event) }.not_to raise_error
      expect(event['[logSource][class_name]']).to eq('coyote')
    end
  end
```

I have not tested add_field but I suspect that these will fail:

```
add_field {
  "[some][other]" => "value1"
  "[some][other][field]" => "value2"
}
```

```
when event is: {  "[some][other]" => "value1"  }
add_field {
  "[some][other][field]" => "value2"
}
```

**Comment by jordansissel** [comment]
I don't know what the expected behavior should be, here. 

My feeling is that if you already have a field that has a string value, trying to treat it as a hash should be an error. Prior art to support my feeling is that if you have a filesystem path "/foo/bar" which is a _file_ and you try to create a file "/foo/bar/baz" it will fail because "/foo/bar" is a file, not a directory.

**Comment by jordansissel** [comment]
Given my feeling above, I think the bug is that you get a cryptic error from Ruby ("string not matched") when we should really fail with something more detailed "Field [some][other] is a string, cannot create nested field [some][other][field]"

**Comment by guyboertje** [comment]
@jordansissel - I think your suggestions are fine.  We should fail predictably, but should the whole pipeline stop? Do we store the failed `set` in a "_event_path_set_failure" keyed object and allow the pipeline to continue?

**Comment by jordansissel** [comment]
I like your suggestion to keep the pipeline moving. This question, for me, is easier to answer once we have dead letter queues, because we can throw the garbage/failures into the DLQ and move on.

I'm not sure how to solve it today (without DLQ). Putting the failure into a separate part of the Event object feels like it might work (as you suggest to store the it in an _event_path_set_failure map), but when I model that in my head it feels like there's some edge cases that would still cause problems for, but maybe not. Could you sketch up a sample input and output JSON for a view before and after the de_dot filter is applied? Might be easier to discuss with a visual or something more tangible.

(I think we're both agreeing on the same solution, but want to make sure, hehe)

**Comment by guyboertje** [comment]
In the support case (#131) the error is most likely a config issue but data can cause this. When this occurs it is more likely to be an undersight on the users part.

For me the main question is: **do we respect the data or the users directives**?

incoming json:
```json
{"customInfo": {"application": {"id": "acme", "machine": "appsvr-uk-2.4-3"}}}
```

add_field directive: { "[customInfo][application][machine][location]" => "UK-DC3"}

If we respect the data...
result event json:
```json
{"customInfo": {"application": {"id": "acme", "machine": "appsvr-uk-2.4-3"}},
  "_eventpathsetfailure": {"[customInfo][application][machine][location]": "UK-DC3"}}
```

If we respect the user directive...
result event json:
```json
{"customInfo": {"application": {"id": "acme", "machine": {"_machine": "appsvr-uk-2.4-3",
"location": "UK-DC3"}}, "tags": ["_eventpathsetconflict"]}
```
here the string `"appsvr-uk-2.4-3"` is moved into the new hash with the key of `"_machine"` so the user can see the tag and find the conflict.

There are pros and cons with either. What does the team think?
