### ISSUE TITLE
logstash did not start on windows - JVM problem

### ISSUE THREAD

**Issue by thmoeller** [elastic/logstash#5116]
Hi,

trying to start logstash 2.3.1 on my Win7 Laptop with Java 7 (also tried most current Java 8) receiving following error:

c:/logstash/logstash-2.3.1/bin/logstash.bat agent --debug -f c:/logstash.conf

io/console not supported; tty will not be manipulated
←[31mtranslation missing: en.logstash.runner.configuration.scheme-not-supported {:level=>:error, :file=>"/logstash/logstash-2.3.1/vend
or/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/agent.rb", :line=>"383", :method=>"create_pipeline"}←[0m
←[32mstarting agent {:level=>:info, :file=>"/logstash/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstas
h/agent.rb", :line=>"207", :method=>"execute"}←[0m
The signal HUP is in use by the JVM and will not work correctly on this platform

Checked for running processes and rebooted. Both does not help.

Any ideas??

Cheers 

Thorsten

**Comment by ph** [comment]
@thmoeller Hello

> ←[31mtranslation missing: en.logstash.runner.configuration.scheme-not-supported {:level=>:error, :file=>"/logstash/logstash-2.3.1/vend


This mean we have a bug in the translation files we will fix it, but it shouldn't stop you to use logstash under windows. When giving a file for logstash on windows you have to correctly escape the path.

I have tested the following command on windows 2012 and it work for me.
```powershell
bin/logstash -f c:\\logstash.conf
```

**Comment by thmoeller** [comment]
Yes, escaping the path fixes the issue for me too.

Thanks for immediate reply

**Comment by ph** [comment]
Glad it worked for you, next 2.3.X release will fix the translation missing! see #5119

**Comment by puneetjindal** [comment]
@ph : I am getting this error on elastic search 2.4.0 version on windows server 2012 R2
```
C:\Users\puneet.jindal>logstash -f D:\logstash-2.4.0\logstash-simple.conf
Settings: Default pipeline workers: 32
←[31mPipeline aborted due to error {:exception=>"LogStash::ConfigurationError",
:backtrace=>["D:/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0
-java/lib/logstash/config/mixin.rb:88:in `config_init'", "org/jruby/RubyHash.jav
a:1342:in `each'", "D:/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core
-2.4.0-java/lib/logstash/config/mixin.rb:72:in `config_init'", "D:/logstash-2.4.
0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/outputs/bas
e.rb:79:in `initialize'", "D:/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logsta
sh-core-2.4.0-java/lib/logstash/output_delegator.rb:74:in `register'", "D:/logst
ash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pip
eline.rb:181:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "D:
/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logsta
sh/pipeline.rb:181:in `start_workers'", "D:/logstash-2.4.0/vendor/bundle/jruby/1
.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:136:in `run'", "D:/log
stash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/a
gent.rb:491:in `start_pipeline'"], :level=>:error}←[0m
stopping pipeline {:id=>"main"}
The signal HUP is in use by the JVM and will not work correctly on this platform
```

**Comment by pvssrikanth** [comment]
Dear All,
Even me too facing the same issue of signal HUP 

/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:
180)", "RUBY.run(G:/Tutorials/2016_Oct/ES/logstash-2.4.0/logstash-2.4.0/vendor/b
undle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:136)", "R
UBY.start_pipeline(G:/Tutorials/2016_Oct/ES/logstash-2.4.0/logstash-2.4.0/vendor
/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:491)", "ja
va.lang.Thread.run(java/lang/Thread.java:745)"], :level=>:error}←[0m
stopping pipeline {:id=>"main"}
The signal HUP is in use by the JVM and will not work correctly on this platform


G:\Tutorials\2016_Oct\ES\logstash-2.4.0\logstash-2.4.0\bin>


Could any body help me please how do i fix this error of signal HUP is in use by JVM in logsthash by emailing to srikanthpvs@gmail.com

**Comment by nklt** [comment]
I am also getting this issue in LogStash 2.4.0 in Windows 2012 R2.

**Comment by jbmahadevan** [comment]
Hi 
  Logstash - issue stuck for a 3 days

[31mPipeline aborted due to error {:exception=>"LogStash::ConfigurationError",
backtrace=>["C:/Users/abc/Innovation/ElasticSearch/logstash-2.4.0/vendor/bundle
jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/config/mixin.rb:88:in `con
ig_init'", "org/jruby/RubyHash.java:1342:in `each'", "C:/Users/abc/Innovation/E
asticSearch/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-jav
/lib/logstash/config/mixin.rb:72:in `config_init'", "C:/Users/abc/Innovation/El
sticSearch/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java
lib/logstash/outputs/base.rb:79:in `initialize'", "C:/Users/abc/Innovation/Elas
icSearch/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/l
b/logstash/output_delegator.rb:74:in `register'", "C:/Users/abc/Innovation/Elas
icSearch/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/l
b/logstash/pipeline.rb:181:in `start_workers'", "org/jruby/RubyArray.java:1613:
n `each'", "C:/Users/abc/Innovation/ElasticSearch/logstash-2.4.0/vendor/bundle/
ruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:181:in `start_w
rkers'", "C:/Users/abc/Innovation/ElasticSearch/logstash-2.4.0/vendor/bundle/jr
by/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:136:in `run'", "C
/Users/abc/Innovation/ElasticSearch/logstash-2.4.0/vendor/bundle/jruby/1.9/gems
logstash-core-2.4.0-java/lib/logstash/agent.rb:491:in `start_pipeline'"], :leve
=>:error}←[0m

I am struggling to resolve Error The signal HUP is in use by the JVM and will not work correctly on this platform for past 3 days. Tried multiple options, never worked.

I saw #5239 and other tags. 
Is there any concrete solution.

**Comment by ph** [comment]
@jbmahadevan seems to me the fix https://github.com/elastic/logstash/pull/6005 was merged 6 days ago and will make it to the next releases.

**Comment by dragrubis** [comment]
I have the same issue BUT i don't have a path since the conf file is in the bin directory...

**Comment by Mutear** [comment]
I added a logstash.conf in the bin directory, and run "logstash.bat -f logstash.conf". Then I got this issue.
But when i copy logstash.conf to logstash.txt, and run "logstash.bat -f logstash.txt".It works.
I don't know what happened, but it really work fine.

**Comment by getgaurav2** [comment]
I am getting the same issue in Windows7 laptop . But "logstash.bat -f simple-out.txt" does not help either
