### ISSUE TITLE
Logstash event constructor mutates the input hash

### ISSUE THREAD

**Issue by magnusbaeck** [elastic/logstash#5130]
The constructor of the Event class—at least the Ruby implementation but AFAICT also the Java one—mutates the hash/map passed as an argument by removing any `@metadata` field and adding a `@version` field if necessary. This is very unexpected for callers who'd have to clone their data structure before instantiating an event to avoid this mutation. Is this intentional or an oversight? Cloning the input argument inside the constructor would solve the problem but I can imagine that you'd object because of the performance cost.

I ran into this while preparing a json_lines addition to include the `@metadata` field in the output (like the rubydebug codec's `metadata` option). See the spec changes in [my commit on the metadata-with-clone branch of magnusbaeck/logstash-codec-json_lines](https://github.com/magnusbaeck/logstash-codec-json_lines/commit/4a57167adb26febe11a132e605bc1c7b4f2aeaca) for an example of the consequences.

I'd appreciate some input on what the desired solution is here (fix this in the event class or work around it in tests) so that I can move forward with the json_lines change and send a PR.

**Comment by suyograo** [comment]
@magnusbaeck not related to your question here, but this tool is fantastic: https://github.com/magnusbaeck/logstash-filter-verifier. See our efforts here: #5013 

<3 it

**Comment by colinsurprenant** [comment]
@magnusbaeck yes you are right, the Ruby Event class mutates the passed data. AFAICT it has never been a problem so far.

The problem with using `.clone` or `.dup` is that it is a shallow clone, so the problem could still happen further down and we certainly don't want to systematically deeply clone every time as this would be very costly. 

I am not even sure if we should do a simple `.clone`. If your immediate problem is with specs, I suggest you refactor the specs to avoid this (as you did) for now. 

Moving forward, I am not sure if we should do something since in most (I believe all?) cases, we are in control of the original data fed to the Event constructor and this data is never reused once the Event is created. 

Thoughts?

**Comment by magnusbaeck** [comment]
Constructors that mutate their arguments make me cringe, but I can see how the performance hit would be prohibitive. Fixing specs where needed is no big deal, but realizing what the problem is can be puzzling the first time you get the test failure.

It'd be great if the specs could detect that the value has been tampered with but I don't think that's doable in a reasonable way. Well, unless we can change the behavior of `let` to evaluate its block every time it's accessed. A new `let_volatile` construct (there's probably a better name for it) would allow one to not have to remember to add `.clone` everywhere the test data is accessed.

Anyway, feel free to close. I'll send the referenced commit in a PR.

**Comment by colinsurprenant** [comment]
@magnusbaeck I am totally with you on this for the constructor, it is not hygienic. But as I said in my previous comment, practically speaking it is a somewhat reasonable compromise. It should be better documenter in terms of Event API. If we had proper+fast immutable collections like Closure has we could leverage that but AFAIK Java nor JRuby offer anything that wouldn't be very costly performance-wise.
