### ISSUE TITLE
QA: Acceptance framework improvements

### ISSUE THREAD

**Issue by ph** [elastic/logstash#5181]
I have been playing with the QA acceptance framework and I like it so far. ❤️ 

I am in the process or porting the plugin manager and cli test to it, I am removing the need for serverspec in favor of simple custom matchers. 

I have a few questions and suggestion.

- Why we have specific platform spec? I see almost identical suite of spec for centos and ubuntu? maybe we could abstract this with our helpers and matchers. The matchers already does a great job depending on the machine with the package management. It is possible to write once and run everywhere, maybe even windows?  related files https://github.com/elastic/logstash/blob/feature/acceptance_test/qa/acceptance/spec/centos/lib/install_spec.rb and https://github.com/elastic/logstash/blob/feature/acceptance_test/qa/acceptance/spec/debian/lib/install_spec.rb

- I am a bit confused by the usage of shared context, They seem to be used to create multiples spec run for the machine. I am wondering if the runner should be responsible to do isolated run of rspec for each machine, this could make it possible to have parallel run (not sure if we will get speed benefit). This is also related to @tal [proposition](https://github.com/elastic/logstash/pull/5173) to have one vm at a time.  In my head I see the following flow. 

```
For each vm in the current run.
bootstrap the vm or start it
runner setup the rspec environment
run test with platform independent test
halt vm
```

- I have noted in the original PR, that it could be nice to make the test target or current host implicit, this might requiring some rspec wrestling.

**Comment by ph** [comment]
@purbon @talevy what your opinion on this?

**Comment by purbon** [comment]
After giving it a few thoughts I've a few questions for you I will try to resume here:

> I am in the process or porting the plugin manager and cli test to it, I am removing the need for serverspec in favor of simple custom matchers.

there is actually not need of _serverspec_ in any part of the code, can you elaborate your idea on this points? my initial idea on the plugin manager test it that we were able to run them for: 

1. As standalone test, part of our current project test, mostly as we have them now.
2. As part of our acceptance test, this means running them vs an installed package, or the `tar.gz` bundle.

I think only 2.- might be necessary or required, but i see the potential benefits, specially during development time for 1.

> Why we have specific platform spec? 

because we need to know the platform when running the commands that for example do the package installation, you use _yum_ for _redhats_ and _dpkg_ for _debians_ for example. So somehow we need to know vs with machine are we running the tests. 

This, in my opinion, could be archived (by having less optional design, like I did in initial version), or by having information in a configuration file about each platform type and then select the commands based on them for each machine. Both's options looks resonable to me.

> , maybe even windows? 

this is the idea, that we also run this on windows 😸 😸 😸 😸 😸 😸 😸 


> I am a bit confused by the usage of shared context,

is only used as you notice to run all platform test at once, I think this functionality is important as we want to do this process:

1. run unit test.
2. run integration test.
3. build packages (_rpm_,_deb_,_tar.gz_,_zip_)

and then:

4.- Run acceptance test jobs, 1 job per platform.

* Destroy all previous VM's.
* Bootstrap all necessary VM's
* Run the tests.
* Halt all the machines

but I do agree for local use case, running with only one box (platform+distribution version) is good and should be done in a single command. Having 4. after having an initial version of the single box should not be hard to get.

>  make the test target or current host implicit

I do agree with you, we should make this possible in a nice and wonderfull way 👍 

hope I made my thoughts clear, but feel free to ask for clarification when need 😃

**Comment by ph** [comment]
> there is actually not need of serverspec in any part of the code, can you elaborate your idea on this points? my initial idea on the plugin manager test it that we were able to run them for

The current test have been written with serverspec, I wrote that I am rewriting them to drop that dependency. Not sure how much much I can elaborate?

**Comment by ph** [comment]
Concerning the configuration I though something like this could be possible and would remove the need of shared context.

```
HOST=127.0.0.1 PORT=2234 MACHINE_TYPE=debian bundle exec rspec spec/plugin_manager_spec.rb:45
```

**Comment by purbon** [comment]
@ph, you mean the plugin manager ones?

**Comment by ph** [comment]
@purbon I used the plugin manager file, but in reality it could have been any spec inside the qa folder.

**Comment by purbon** [comment]
I would rather recommend

HOST=ubuntu-1204 bundle exec ....

addressing stuff by hostname would be better, then let vagrant decide other
bits.

but not against of having both if this makes the overall life easier :-P

- purbon

**Comment by purbon** [comment]
re: https://github.com/elastic/logstash/issues/5181#issuecomment-214320481 there is no requirement of serverspec in the test inside the `qa` folder.

**Comment by ph** [comment]
@purbon Yeah, I would be fine with `HOST=ubuntu-1204 bundle exec`

It changes a bit how the tests are executed and environment bootstrapped but this would allow us to not use shared context.

I see the following.

``
1. A common config with machine definition.
2. Bundle test:acceptance read the file.
3. start a suite with the right environment HOST=ubuntu-1204
4. The suite us shared code to make sure HOST=ubuntu-1204 is bootstrapped for a test run
5. Test are executed, helpers. are correctly configured for host and the OS

**Comment by purbon** [comment]
@ph and me in the same page!! god safe communication!

**Comment by ph** [comment]
@talevy @purbon lets sync for how we implement this asap.
