### ISSUE TITLE
Suppress signal HUP warnings on startup

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#5239]
From 
https://discuss.elastic.co/t/error-the-signal-hup-is-in-use-by-the-jvm-and-will-not-work-correctly-on-this-platform/47128/1

On Windows 10 and LS 2.3.1

```
logstash -e 'input { stdin { } } output { elasticsearch { host => localhost } }'
```

Getting error like -

```
io/console not supported; tty will not be manipulated
The signal HUP is in use by the JVM and will not work correctly on this platform.
```

**Comment by PhaedrusTheGreek** [comment]
I am also hitting this on: 
- Windows Server 2012 R2 Standard on VM
- jdk1.8.0_91 (64 bit installation)
- logstash-2.3.1

Doesn't happen on
- Windows 7
- jdk1.8.0_71
- logstash 2.1.1

**Comment by PhaedrusTheGreek** [comment]
**Note:** This error is benign, and Logstash operation should continue as normal.

**Comment by CarolTozzi** [comment]
I just installed elasticsearch and logstash on my windows 7 machine and I got this error:
"io console not supported; tty will no be manipulated
The signal HUP is in use by the JVM and will not work correctly on this platform."

I tried using the full path to the conf file and it still doesn't start. I am using logstash version 2.3.4 and Java 1.7.0_79.
Is there a way to fix that?

**Comment by PhaedrusTheGreek** [comment]
@CarolTozzi This error message will not stop Logstash from starting.  It seems you must have some other issue.  Please navigate to the [Logstash Discuss Board](https://discuss.elastic.co/c/logstash) and post your question there.  You can also link to this issue, for reference.

**Comment by csivaprasadc** [comment]
I am getting the same issue with logstash 2.4.0 on Windows 7 with jdk 1.8.0.45

**Comment by puneetjindal** [comment]
@PhaedrusTheGreek : I am getting this error on elastic search 2.4.0 version on windows server 2012 R2

C:\Users\puneet.jindal>logstash -f D:\logstash-2.4.0\logstash-simple.conf
Settings: Default pipeline workers: 32
←[31mPipeline aborted due to error {:exception=>"LogStash::ConfigurationError",
:backtrace=>["D:/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0
-java/lib/logstash/config/mixin.rb:88:in `config_init'", "org/jruby/RubyHash.jav
a:1342:in `each'", "D:/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core
-2.4.0-java/lib/logstash/config/mixin.rb:72:in `config_init'", "D:/logstash-2.4.
0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/outputs/bas
e.rb:79:in `initialize'", "D:/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logsta
sh-core-2.4.0-java/lib/logstash/output_delegator.rb:74:in `register'", "D:/logst
ash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pip
eline.rb:181:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "D:
/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logsta
sh/pipeline.rb:181:in `start_workers'", "D:/logstash-2.4.0/vendor/bundle/jruby/1
.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:136:in `run'", "D:/log
stash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/a
gent.rb:491:in `start_pipeline'"], :level=>:error}←[0m
stopping pipeline {:id=>"main"}
The signal HUP is in use by the JVM and will not work correctly on this platform

**Comment by nanew2u** [comment]
This error will not stop Logstash from processing data. You could add a input { stdin{} } and output { stdout {} } to verify.

**Comment by jonizen** [comment]
For me this crashed the service and makes it restart with gives me crazy CPU-usage, are u sure that logstash works? I tried running it in a cmd-promt and it crashed. :)

**Comment by untergeek** [comment]
As has been pointed out by multiple people in this thread, the error message does not actually affect Logstash performance or usability, except in the ability to use the HUP signal to restart Logstash.  If you are having problems with Logstash, that error message is not related to it.

It is not a Logstash error message anyway.  It is bundled in JRuby itself: https://github.com/jruby/jruby/blob/915993886ae6663586d893b7d237f750068aceb5/core/src/main/ruby/jruby/kernel/signal.rb#L35

**Comment by suyograo** [comment]
I believe this is related to config reloading feature, and while this message is benign, this will confuse users as seen in this issue.

Regardless of where this bug is, IMHO, we should remove the `HUP` mechanism to reload configs as it is not cross-platform compatible. I am not sure users find it useful as well. We have a setting file `--reload-config` which is a really friendly, standard, and uncomplicated way of reloading config. Why add more complexity? Config reloads are typically done in dev, QA environment so it would be fair to assume `--reload-config` is used when LS is started. @jsvd what are your thoughts?

**Comment by jsvd** [comment]
We have captured HUP for a long time (even in [1.4](https://github.com/elastic/logstash/blob/v1.4.4/lib/logstash/agent.rb#L123-L126) and before) and it hasn't been a problem before.

I'm a bit on the fence with removing the feature without prior warning, so I'd rather add some error handling on the signal trapping + a deprecation notice that we're going to remove hup-based reloading.

**Comment by jsvd** [comment]
One interesting detail: I haven't been able to replicate this warning message on windows during startup, only at shutdown time (this is with windows 2012 + logstash 2.4.0):

```
C:\logstash-2.4.0>bin\logstash.bat -e "input { stdin { } }"
Settings: Default pipeline workers: 1
Pipeline main started
←[33mSIGINT received. Shutting down the agent. {:level=>:warn}←[0m
^CTerminate batch job (Y/N)? stopping pipeline {:id=>"main"}
Pipeline main has been shutdown
The signal HUP is in use by the JVM and will not work correctly on this platform
```

Same thing on logstash 5.0.0-beta1. If I uncomment the [line that untraps the HUP at shutdown](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/runner.rb#L287) I no longer see this error...this is strange..

**Comment by untergeek** [comment]
@jsvd Does it appear because of the configuration reload (when you're not trying to stop) or is it showing up because it's a bad config, and it's trying to stop?  Both?

**Comment by jsvd** [comment]
For me it shows during shutdown of a good config even without doing reload.

**Comment by jsvd** [comment]
closed by https://github.com/elastic/logstash/pull/6005
