### ISSUE TITLE
Add better user feedback when the HTTP API port is already in use

### ISSUE THREAD

**Issue by ph** [elastic/logstash#5290]
If you start Logstash and the api http port is already in use it will throw this exception:

```
<Errno::EADDRINUSE: Address already in use - bind - Address already in use>
```

We should provide better feedback to the user, maybe a message similar to this one would help

> Logstash tried to bind to port XXXX, but the port is already in use. You can specify a new port by launching logtash with the --http-port XXXX option.

**Comment by ceeeekay** [comment]
I think the error should also mention the API tried to bind to that port. If the user isn't aware the API exists, they will probably try to debug network inputs in their config.

**Comment by purbon** [comment]
With the current refactoring introduced by @andrewvc the problem detected by myself is a bit more complicated as due to the way puma server implementation works, see https://github.com/puma/puma/blob/4ca81231c42828980dad26cfe21e47ba527d8be9/lib/puma/binder.rb#L244, it uses `Socket::SO_REUSEADDR` what means it will bind silently when the address is in use. 

Introducing a new check for this before the server reaches this point to be sure we bind the the right port or raise an error if the port is in use.
