### ISSUE TITLE
Plugins using java code directly as it's ruby

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#5443]
I noticed an increasing usage of java code directly in ruby layer, this has happen either in core or plugins. In my opinion, without the proper abstractions, this might introduce some maintenance problems in the feature.

This could be due to:

* Changes inside the JVM or differences between VM's.
* Request to support other ruby vm's.

As we should leverage java capabilities in ruby, I propose we build proper abstractions, either through extensions or encapsulation in ruby.

Some examples of this are:

* https://github.com/logstash-plugins/logstash-filter-translate/blob/master/lib/logstash/filters/translate.rb#L7
* https://github.com/elastic/logstash/pull/5381/files

Related to: #5352

**Comment by jsvd** [comment]
I'm +1 on converging to a common agreement of using ruby+jruby+java, it's something I think will happen gradually as we use more and more,  which certainly means we'll need to refactor current code.

About the example reasons for risks of lower maintainability I don't see changes in JVMs a big issue (we probably suffer more from issues in jruby itself than breakage within major versions of oracle/openjdk) nor the "request to support other ruby vm's": with so many java code replacing core components in logstash it seems likely that jruby is the only ruby vm we'll ever support.

About the abstractions, to better understand what you mean, could you give an example, maybe using the 2 code repos you presented?

**Comment by andrewvc** [comment]
If I understand you you're worried that we're mixing Java and ruby at the language level by directly using java classes like `java.util.concurrent.ReentrantReadWriteLock`. 

We're already 100% committed to the java platform. The Event class is pure Java, persistence will be pure java, many plugins (e.g. RabbitMQ and Elasticsearch) have strong dependencies on Java libraries already.

Whether we use java classes directly will have little effect on the amount of effort it would take to switch Ruby VMs. Furthermore we're moving toward rewriting Logstash in pure Java anyway, at which point we'll have Ruby inside of Java instead of Java inside of Ruby.

Given all this I see no reason why we should spend extra time creating wrappers for Java stdlib functions. This will take extra time, introduce the possibility of extra bugs, and create extra surface area that can fail for reasons that are not clear to me.

**Comment by andrewvc** [comment]
I should also add that the point about JVM changes is entirely without precedent in the history of Java. If you can demonstrate a meaningful example of your first point being an issue I'd like to hear it. If another JVM doesn't support the standard lib then it isn't a proper Java.

There have been changes in the internal implementation of stdlib functions in Java, but to my knowledge never changes to their actual functionality. And if there are there haven't been enough of them to be worth mentioning.

**Comment by purbon** [comment]
thanks a lot for your comments @jsvd and @andrewvc , closing this issue now as this opinions together with feedback from PH makes this 3 people not happy with it, happy to share concerns and see what do you guys think.
