### ISSUE TITLE
Add default plugins to master Gemfile

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#5533]
Previously, master branch in LS (since 5.0) had a different `Gemfile` than release branches. With the merge of #5460, both release and master branches use the same strategy of using local, unpublished `logstash-*` plugins for packages. With this, there is really no need to deviate `Gemfile` for release branches. Lets make them same. This will settle a lot of merge conflicts as well. Also, we should really be able to release 5.0.0 from master itself. See #5530

**Comment by suyograo** [comment]
@jsvd @ph @jordansissel thoughts?

**Comment by jsvd** [comment]
I'm -1 on adding the default plugins to the gemfile. you often might be working only in core so you don't need the default plugins slowing down your workflow.
Release branches are, however, dedicated to creating releases so it makes sense there to encode the default plugins list.
We can create a rake task that does this updating/injection for us, though.

**Comment by ph** [comment]
I've gave some thought on this since our original discussion from the unified releases.

@jsvd I agree that this could slow down our workflow, switching branch would often mean in some way to  kickstart an install the plugin, some part of this process will be faster since some gems will be present locally in the gem cache.

@suyograo From your proposition the **Gemfile** will be the same in master and in the branches? The only thing that will differ is the **lockfile** wont be present in the master branch but will be available in the releases branch? Correct?

**Comment by suyograo** [comment]
> The only thing that will differ is the lockfile wont be present in the master branch but will be available in the releases branch? Correct?

Correct. 

I do like the simplicity in this approach -- having consistent `Gemfile` across branches going forward. I understand it may slow down development, but I think thats a technical problem we can solve. This is a problem we have to solve regardless. I feel the merges will get easier too.

Others? @colinsurprenant @jordansissel ?

**Comment by jordansissel** [comment]
I think the right place to add this, and would solve @jsvd's concerns, is in a `group` in the Gemfile. @colin has noted previously (on zoom, I think?) that the Gemfile parser that the plugin manager uses doesn't understand groups, but we could fix that and use a group, maybe call it `group :default_plugins` and go from there.

I am +1 on using the Gemfile to include the default plugins, and in favor of using a group to fence it so that installing plugins during development is optional.

**Comment by suyograo** [comment]
I like the `group` idea!

**Comment by ph** [comment]
Adding a `group` make sense and with that I +1 that issue.

**Comment by ph** [comment]
Just to be clear, to make it right lets make sure we support the 2 group definition syntax:

```ruby
group :default_plugins do
end

gem "hola", :group => :default_plugins
```

**Comment by jsvd** [comment]
I'm +1 on the group idea.  Some potential headaches in the implementation side:
* the --without <group> setting messes with the .bundle/config file (which we already have tasks to delete, iirc)
* the set of core gems used for testing core contains plugins from the default plugin set. managing that intersection may be annoying.

**Comment by ph** [comment]
> the set of core gems used for testing core contains plugins from the default plugin set. managing that intersection may be annoying.

I think bundler already deal with that out of the box.

**Comment by suyograo** [comment]
I think we should still merge default plugins to master. Yes we can move to `:group` but until we figure it out, IMO, we can still live with default plugins in master. Thoughts? Also we can merge #5535

**Comment by jordansissel** [comment]
@suyograo +1 on incremental approach; we can use a `group` later. It may hurt a little for some parts of core dev, but hopefully not too baddly.

**Comment by jsvd** [comment]
added in https://github.com/elastic/logstash/commit/019e3d32efe7b3f4848922f1d87fdf06df4fb7d9: https://github.com/elastic/logstash/blob/master/Gemfile#L24-L113
