### ISSUE TITLE
Init.d file and config folder  are missing in Logstash 5 Alpha3 Setup

### ISSUE THREAD

**Issue by gauravjavheri** [elastic/logstash#5572]
Hi,

Last day I installed Logstash 5 Alpha3 version using installation guide https://www.elastic.co/guide/en/logstash/5.0/installing-logstash.html1 on RHEL 6.x. After installation found that "/etc/init.d/logstash" script  and config folder are missing.

Thanks
Gaurav Javheri

**Comment by untergeek** [comment]
That's because starting with alpha3, Logstash generates its own startup files based on what the system uses. RHEL 6 uses upstart, so you can start Logstash with `initctl start logstash` or even just `start logstash`

**Comment by RobinAllen** [comment]
Well, I'm confused.
Here am I, on RHEL6, with logstash 5.0.0-alpha4, and I can't run it either???
You say RHEL6 uses upstart, but on my RHEL6 I'm used to using the init.d scripts. I've used RHEL for years, but I've never used "initctl" in my life. 

Logstash 2 RPM works fine on my RHEL6, but logstash 5 RPM says no.


$rpm -q logstash
logstash-5.0.0~alpha4-1.noarch

$/usr/bin/sudo service logstash start
logstash: unrecognized service

$/usr/bin/sudo initctl start logstash
initctl: Unknown job: logstash

$/usr/bin/sudo start logstash
start: Unknown job: logstash

**Comment by untergeek** [comment]
@RobinAllen 
There should have been some output at the end of the RPM installation.  If an error occurred creating the RPM, some indication should have been made.  Please work with us as we try to troubleshoot this with you.  

For reference, building and installing the RPM works in clean installs (Vagrant VMs) of CentOS 6.

**Comment by untergeek** [comment]
Please show the contents of /etc/logstash as well, please.

**Comment by RobinAllen** [comment]
Why does an rpm post script need to depend on JAVA?

Running Transaction
  Installing : 1:logstash-5.0.0~alpha4-1.noarch                                                                                                                     1/1
Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME.
warning: %post(logstash-1:5.0.0~alpha4-1.noarch) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package 1:logstash-5.0.0~alpha4-1.noarch
  Verifying  : 1:logstash-5.0.0~alpha4-1.noarch                                                 


I have multiple JAVAs installed for different dependencies of different things.  So I deliberately do not put any default JAVA on a JAVA_HOME.  Otherwise things will pick the wrong one.

**Comment by RobinAllen** [comment]
And that Java will always be in "/usr/bin/java" is one heck of an assumption to make, too!....

Using provided startup.options file: /etc/logstash/startup.options
/usr/share/logstash/vendor/jruby/bin/jruby: line 388: /usr/bin/java: No such file or directory
/usr/share/logstash/vendor/jruby/bin/jruby: line 388: exec: /usr/bin/java: cannot execute: No such file or directory

It's pretty rare to find an RPM that depends on a specific Java to be installed in a specific location for the %post script.

**Comment by untergeek** [comment]
While I understand the RPM convention, Logstash is 100% dependent on Java, so that it is required shouldn't be too big a surprise.  

In the event that you need to specify a different Java, go ahead and change the settings in `/etc/logstash/startup.options` and run /usr/share/logstash/bin/system-install as root.  It will regenerate the startup scripts.

**Comment by untergeek** [comment]
startup.options is described here: https://www.elastic.co/guide/en/logstash/5.0/config-setting-files.html#_settings_files

**Comment by RobinAllen** [comment]
I agree that Java is obviously a dependency.  But compare ElasticSearch experience with the Logstash experience:

To run ElasticSearch 5 alpha4 with a non-standard java in a different location, was simple.  A nice clean rpm install with no errors, followed by a simple one-line change in /etc/sysconfig, and run it the usual way with sysv "service elasticsearch start".  Automated with ansible in mere minutes.

But then for Logstash, we have an RPM that spits out errors from the %post script.
It demands I set JAVA_HOME.  So I set JAVA_HOME, and run the %post again (which any normal user won't have a clue how to find out what's going on inside the %post script)... and it ignores the JAVA_HOME that I've given it and decides to look somewhere else.
So then I configure the SECOND location that it needs the java home setting, and run it a third time, and it tells me it's successfully created the init scripts.  Yay!
Except it hasn't.  It's generated the Upstart init scripts.  So I need to run Logstash using Upstart, even though ElasticSearch insists that I run ElasticSearch with SysV.

Two products.  Same company.  Completely different methodology and completely different experience.  Why would one of them insist on using Upstart, when the other one insists on using SysV?  Why would one of them install quick and easy with no issues, but the other one makes rash assumptions about which jdk will be installed, and can only be configured to work correctly AFTER the rpm has already failed to correctly install?  (and, as far as I can tell, only failing because it's trying to go OTT with usage of Java and Ruby to install Upstart scripts that weren't needed to begin with)

**Comment by RobinAllen** [comment]
So back to that comparison of 'experience'.... 
ElasticSearch, installed and running in <5 minutes.
Logstash, an hour later I'm still debugging through bash scripts to figure out why the Upstart script isn't starting the process with the JAVACMD parameter that I gave it in the startup.options.

Even if I do as instructed, and edit the JAVACMD in startup.options, that only gets it past the init-script installer. So, it successfully installs an init script, which when run, FAILS to start up logstash.  It bombs out somewhere in setup_java in logstash.lib.sh, because the script gets JAVACMD from the environment, not from the startup.options file.  In fact, the only reference I can find that touches startup.options is just the init-script writer.

**Comment by untergeek** [comment]
That is correct.  The [referenced documentation](https://www.elastic.co/guide/en/logstash/5.0/config-setting-files.html#_settings_files) makes clear that `startup.options` is only used to create the startup files.

If things are not working the way they were designed (particularly with regard to using different environment variables, java versions, etc.), please help us to figure that out with a new issue.  Please attach the `startup.options` file, as well as the `jvm.options` file, and the resulting upstart file in `/etc/init/logstash.conf`

**Comment by RobinAllen** [comment]
I can get around this by adding 
JAVA_HOME= ....
into the top of /usr/share/logstash/bin/logstash

But.... It would be really handy if the first thing that /usr/share/logstash/bin/logstash did, was something like 
if [ -f /etc/sysconfig/logstash ]; then
   . /etc/sysconfig/logstash;
fi
(like elasticsearch does)

Then is would just be a case of dropping the java home var into a separate file, rather than editing the init script or editing the logstash runner script itself.

**Comment by untergeek** [comment]
I agree that we can improve in this way.  

Please submit your findings in a new issue, as addressing alternate JAVA_HOME environments are different from the subject of this issue.

**Comment by RobinAllen** [comment]
My other observation would be... do you REALLY need to use Java to write an init script?  You can figure out sysV or upstart and generate an init script from a template in a few lines of bash.  You don't really need that dependency on a whole Java JVM to write out the init scripts.  It would be better if the RPM didn't make any assumptions about packages without listing them as "requires: java" in the rpm spec.
