### ISSUE TITLE
logstash input-> file-> path..How matching logs of today's date?!

### ISSUE THREAD

**Issue by Canon88** [elastic/logstash#5582]
I have a question, `logstash input-> file-> path`. How matching logs of today's date.
My directory`/ service / nginx / logs /`contains many nginx log files, these logs are cut by date.
I just want to let logstash to match today's log, I wrote the following configuration, but it is not working.
```
input {
    file {
        path => "/service/nginx/logs/*.%{yyyy}-%{MM}-%{dd}-access.log"
        start_position => "beginning"
        type => "nginx_access"
    }
}

output {
    stdout {
        codec => rubydebug {}
    }
}
```
How should I set? Get it to work properly! Anybody can tell me? Thank you.

logstash version: 2.X

log files (test):
```
test.2016-07-03-access.log 
Today is 07-03
Today is 07-03
Today is 07-03
```

```
test.2016-07-03-access.log 
Today is 07-04
Today is 07-04
Today is 07-04
```

**Comment by jsvd** [comment]
@Canon88 currently there's no way to explicitly tell logstash to read logs based on current timestamp.
However, you can tell Logstash to ignore files that are older than X using the setting `ignore_older` (https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html#plugins-inputs-file-ignore_older)

This plugin already, by default, ignores files that haven't been modified for more than 24 hours, so it approximates your necessity.

Also, once you start running logstash continuously, it will read todays logs, and tomorrow it will only pick up the new files, since Logstash remembers that it has read the old files and will not read them again.

**Comment by Canon88** [comment]
Thanks for your help, but I'm trying to use `ignore older` as an argument when the error occurred.
My configuration code is as follows:
```
input {
    file {
        path => "/service/nginx/logs/*-access.log"
        type => "nginx_access"
        ignore_olderedit => 8000
    }  
}

output {
    stdout {
        codec => rubydebug {}
    }
}

[root@log-server-01 bin]# ./logstash -f ../etc/test.conf  -t
Unknown setting 'ignore_olderedit' for file {:level=>:error}
Error: Something is wrong with your configuration.
```

**Comment by jsvd** [comment]
it's just ignore_older, not ignore_olderedit

**Comment by Canon88** [comment]
I do not understand, can you show me a look. Thank you very much.

**Comment by jsvd** [comment]
```
input {
    file {
        path => "/service/nginx/logs/*-access.log"
        type => "nginx_access"
        ignore_older => 8000
    }  
}

output {
    stdout {
        codec => rubydebug {}
    }
}
```

and not
```
input {
    file {
        path => "/service/nginx/logs/*-access.log"
        type => "nginx_access"
        ignore_olderedit => 8000
    }  
}

output {
    stdout {
        codec => rubydebug {}
    }
}
```

**Comment by Canon88** [comment]
Thank you solved the problem. Cheers!
