### ISSUE TITLE
Update installation guide (on download page, etc) to note Java dependency

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#5595]
Our docs in [at least one case](https://www.elastic.co/downloads/logstash), we don't tell users that Java is required.

**Comment by sylvie777** [comment]
Hi @jordansissel! I staged the content here: 

https://stag-www.elastic.co/downloads/logstash

Please let me know if I should edit or reword. :)

**Comment by dedemorton** [comment]
@sylvie777 A couple of things: 1) Because the statement appears immediately after the statement about installing from repositories, it's a bit grammatically ambiguous as to whether the restriction applies to Logstash in general or specifically to installing from the repositories. Maybe this is just a grammatical thing that would only bother an editor, tho. I'll let Jordan decide about that one. 2) I think that 2.3 supports Java 7 or later. Saying that Java 7 is required makes it sound like you can't use Java 8. AFAIK, you can use either. @jordansissel should confirm.

**Comment by sylvie777** [comment]
@dedemorton @jordansissel  Please advise on what to stage. I can change it to anything.

**Comment by jordansissel** [comment]
My bad on not responding. I flaked on this.

Java 7 or higher is required for Logstash 2.x, Java 8 or higher is required for Logstash 5.x

**Comment by sylvie777** [comment]
No worries, @jordansissel, thanks for the edits! I staged them here:

https://stag-www.elastic.co/downloads/logstash

cc @dedemorton

**Comment by dedemorton** [comment]
LGTM

**Comment by sylvie777** [comment]
Thanks @dedemorton! Page is now live with the latest edits: https://www.elastic.co/downloads/logstash (Please be sure to clear your browser's cache to see the latest.)
