### ISSUE TITLE
Error while loading CSV to ES through Logstash

### ISSUE THREAD

**Issue by punitsachdev220** [elastic/logstash#5602]
When trying to load CSV file this error is coming in Logstash

E:\ES\logstash-2.3.3\bin>logstash -f E:\\logtashtutorial.conf io/console not supported; tty will not be manipulated Settings: Default pipeline workers: 4 ←[31mPipeline aborted due to error {:exception=>#<LogStash::ConfigurationError: The setting `host` in plugin `elasticsearch` is obsolete and is no longer availa ble. Please use the 'hosts' setting instead. You can specify multiple entries se parated by comma in 'host:port' format. If you have any questions about this, yo u are invited to visit https://discuss.elastic.co/c/logstash and ask.>, :backtra ce=>["E:/ES/logstash-2.3.3/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java /lib/logstash/config/mixin.rb:87:in `config_init'", "org/jruby/RubyHash.java:134 2:in `each'", "E:/ES/logstash-2.3.3/vendor/bundle/jruby/1.9/gems/logstash-core-2 .3.3-java/lib/logstash/config/mixin.rb:71:in `config_init'", "E:/ES/logstash-2.3 .3/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/outputs/ba se.rb:63:in `initialize'", "E:/ES/logstash-2.3.3/vendor/bundle/jruby/1.9/gems/lo gstash-core-2.3.3-java/lib/logstash/output_delegator.rb:74:in `register'", "E:/E S/logstash-2.3.3/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logst ash/pipeline.rb:181:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each '", "E:/ES/logstash-2.3.3/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/ lib/logstash/pipeline.rb:181:in `start_workers'", "E:/ES/logstash-2.3.3/vendor/b undle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:136:in `r un'", "E:/ES/logstash-2.3.3/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-jav a/lib/logstash/agent.rb:473:in `start_pipeline'"], :level=>:error}←[0m ←[33mfailed to open /E:/ES/DATA/Test.txt: Illegal char <:> at index 2: /E:/ES/DA TA/Test.txt {:level=>:warn}←[0m stopping pipeline {:id=>"main"} The signal HUP is in use by the JVM and will not work correctly on this platform

**Comment by suyograo** [comment]
Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!

**Comment by javeeddanyal** [comment]
When trying to load Configuration file this error is coming in Logstash CMD on windows

C:\logstash-2.3.4>bin\logstash agent -f logstash.conf
io/console not supported; tty will not be manipulated
Settings: Default pipeline workers: 4
Pipeline aborted due to error {:exception=>#<LogStash::ConfigurationError: The setting `host` in plugin `elasticsearch` is obsolete and is no longer available. Please use the 'hosts' setting instead. You can specify multiple entries separated by comma in 'host:port' format. If you have any questions about this, you are invited to visit https://discuss.elastic.co/c/logstash and ask.>, :backtrace=>["C:/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/config/mixin.rb:87:in `config_init'", "org/jruby/RubyHash.java:1342:in `each'", "C:/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/config/mixin.rb:71:in `config_init'", "C:/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/outputs/base.rb:63:in `initialize'", "C:/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/output_delegator.rb:74:in `register'", "C:/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:181:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "C:/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:181:in `start_workers'", "C:/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:136:in `run'", "C:/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/agent.rb:473:in `start_pipeline'"], :level=>:error}
stopping pipeline {:id=>"main"}
The signal HUP is in use by the JVM and will not work correctly on this platform

Can any one help to resolve this issue?
