### ISSUE TITLE
logstash webhdfs plugin Failed to flush outgoing items {:outgoing_count=>1, :exception=>"NoMethodError"

### ISSUE THREAD

**Issue by lizhenmxcz** [elastic/logstash#5664]
Hi:
 I want to use logstash to read from redis and write to elasticsearch and webhdfs. But when i write to elasticsearch ,it works well , while write to webhdfs, it show me the  NoMethodError.

Failed to flush outgoing items {:outgoing_count=>1, :exception=>"NoMethodError", :backtrace=>["/opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-event-2.3.4-java/lib/logstash/event.rb:105:in `to_s'", "/opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.1.2/lib/logstash/codecs/line.rb:56:in `encode'", "/opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-output-webhdfs-2.0.4/lib/logstash/outputs/webhdfs.rb:179:in `flush'", "org/jruby/RubyArray.java:2409:in `collect'", "/opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-output-webhdfs-2.0.4/lib/logstash/outputs/webhdfs.rb:173:in `flush'", "/opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:159:in `buffer_receive'", "/opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-output-webhdfs-2.0.4/lib/logstash/outputs/webhdfs.rb:166:in `receive'", "/opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/outputs/base.rb:83:in `multi_receive'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/outputs/base.rb:83:in `multi_receive'", "/opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/output_delegator.rb:130:in `worker_multi_receive'", "/opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/output_delegator.rb:114:in `multi_receive'", "/opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:301:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:301:in `output_batch'", "/opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:232:in `worker_loop'", "/opt/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:201:in `start_workers'"], :level=>:warn}

- Version: 2.3.4
- Operating System:centos6.4
- Config File :
`input {
     redis {
               host => "127.0.0.1" 
               port => "6379" 
               key => "metadata" 
               data_type => "list" codec => "plain" 
} } 
filter { 
       ruby { 
               mutate { 
               remove_field => [ "message","@timestamp","@version" ] 
} } 
output { 
            webhdfs { 
                           host => "192.168.XX.XXX" 
                           path => "/abcd.log"
                           user => "root" 
                           port => "14000" 
                           use_httpfs => true } 
}`

I have read the #4020  and  #4044 , when I remove the code in the filter, it works,  but I don't why the filter code works for elasticsearch output but not works for webhdfs output.

**Comment by purbon** [comment]
@lizhenmxcz This happens because of a coupe of things.

* in the filter section you ask to remove the `@timestamp` field.
* the webhdfs output uses by default the line codec, see https://github.com/logstash-plugins/logstash-output-webhdfs/blob/master/lib/logstash/outputs/webhdfs.rb#L115
* the line codec end up calling the `.to_s` method, see https://github.com/logstash-plugins/logstash-codec-line/blob/master/lib/logstash/codecs/line.rb#L56
* the `.to_s` method uses the timestamp that is removed.

this is specific of the webhdfs output and the reason why it happen. i do recommend not removing variables that start with `@` as are part of internal LS routines.

Closing this issue for now, if you think we should make something to enable users to remove the timestamp, please add your comments at https://github.com/elastic/logstash/issues/4044 

Thanks a lot for your reporting.
