### ISSUE TITLE
PeriodicPoller: exception and i/o timeout

### ISSUE THREAD

**Issue by KovRon** [elastic/logstash#5675]
Hi There,

I've set up ELK stack based on 5.0.0-alpha4 version. I have filebeat, metricbeat and packetbeat on 2 remote clients and ELK stack server. 
- Version: ELK stack (elasticsearch, logstash, kibana, filebeat, metricbeat, packetbeat) 5.0.0-alpha4
- Operating System: Amazon Linux AMI 2016.03

Samples of configuration files there https://drive.google.com/folderview?id=0B-kGy5kL5yqzU19GZnF1TXpQRkk&usp=sharing (IP addresses and ports were changed)

Through some time after start of ELK stack and beats on clients I was getting two errors.

First is in logstash.log file:

> {:timestamp=>"2016-07-21T14:23:52.399000+0000", :message=>"PeriodicPoller: exception", :poller=>#<LogStash::Instrument::PeriodicPoller::JVM:0x28e20e0b @task=#<Concurrent::TimerTask:0x5a7f2ecf @observers=#<Concurrent::Collection::CopyOnNotifyObserverSet:0xc79f629 @observers={#<LogStash::Instrument::PeriodicPoller::JVM:0x28e20e0b ...>=>:update}>, @timeout_interval=60.0, @running=#Concurrent::AtomicBoolean:0xe9cd6a2, @StoppedEvent=#<Concurrent::Event:0x2d3698e8 @set=false, @iteration=0>, @execution_interval=1.0, @do_nothing_on_deref=true, @run_now=nil, @freeze_on_deref=nil, @executor=#<Concurrent::SafeTaskExecutor:0x6e3debd9 @task=#<Proc:0x73a7bc7b@/usr/share/logstash/logstash-core/lib/logstash/instrument/periodic_poller/base.rb:52>, @exception_class=StandardError>, @StopEvent=#<Concurrent::Event:0x1be65d6b @set=false, @iteration=0>, @value=true, @copy_on_deref=nil, @dup_on_deref=nil>, @peak_threads=27, @peak_open_fds=88, @metric=#<LogStash::Instrument::Metric:0x28e7727 @collector=#<LogStash::Instrument::Collector:0x2121c739 @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x3ec278c @store=#<Concurrent::Map:0x4de617ee @default_proc=nil>, @structured_lookup_mutex=#Mutex:0x64c2063c, @fast_lookup=#<Concurrent::Map:0x150462cc @default_proc=nil>>, @observer_state=false, @snapshot_task=#<Concurrent::TimerTask:0x7736f7a7 @observers=#<Concurrent::Collection::CopyOnNotifyObserverSet:0xa92d7c8 @observers={#<LogStash::Instrument::Collector:0x2121c739 ...>=>:update}>, @timeout_interval=600.0, @running=#Concurrent::AtomicBoolean:0x48b1cc5c, @StoppedEvent=#<Concurrent::Event:0x87a9122 @set=false, @iteration=0>, @execution_interval=1.0, @do_nothing_on_deref=true, @run_now=nil, @freeze_on_deref=nil, @executor=#<Concurrent::SafeTaskExecutor:0x14ca3b72 @task=#<Proc:0x44157568@/usr/share/logstash/logstash-core/lib/logstash/instrument/collector.rb:87>, @exception_class=StandardError>, @StopEvent=#<Concurrent::Event:0x280829a @set=false, @iteration=0>, @value=false, @copy_on_deref=nil, @dup_on_deref=nil>>>, @options={:polling_interval=>1, :polling_timeout=>60}>, :result=>nil, :exception=>#<Concurrent::TimeoutError: Concurrent::TimeoutError>, :executed_at=>2016-07-21 14:23:52 +0000, :level=>:error}

Second is in filebeat.log file on the client side:

> 2016-07-21T15:38:02+01:00 ERR Failed to publish events caused by: read tcp 10.0.0.1:55888-10.0.0.2:5044: i/o timeout

After that I've increased the type of AWS instance and problem has gone. However, I'm not sure that it won't repeat.

Can you give me some advice to improve performance or link to resources when I can get necessary information?

Thank you in advance.

**Comment by ph** [comment]
What kind of AWS instance were you using?

Concerning the first error (from logstash) I know where the errors is throw, its originating from the code that collect metrics from the jvm/os. I will improve the error reporting in that part, because right now its not really to me clear what actually happened. I am wondering if not one of our java call is falling from time to time and this error get bubbled up.

Is this error just randomly happened or you have tried to shutdown Logstash and got this error?

The second one:
```
2016-07-21T15:38:02+01:00 ERR Failed to publish events caused by: read tcp 10.0.0.1:55888-10.0.0.2:5044: i/o timeout
```

Theses kinds of networks error can happen,  usually beats will recover, if this is not the case can you add the response of  `curl HOST:9600/_node/hot_threads` to this thread.

**Comment by KovRon** [comment]
Hi,

I use t2.medium instance. I just testing 

This error happened after logstash started and could arise randomly. I think it relates to system load because at that time load was high.

Both errors arise almost at the same time. The first is in logstash log file and the second is on the remote client in filebeat log file after several seconds.

You are right beat recovers connection but it can get the error again and again. 

You can get logstash log from this link https://drive.google.com/open?id=0B-kGy5kL5yqzZUJJWGJZcnN1UFE

**Comment by ph** [comment]
Hello,

Thanks for the quick reply! First I would like to know if Logstash was the cause of the load?
If its the case that would mean that we have bug somewhere.

By looking at your logs we see a lot of similar errors `"PeriodicPoller: exception"`, "UNEXPECTED POOL ERROR", "Beats input: the pipeline is blocked". So something is actually happening on the box.

Concerning the `PeriodicPoller` exception we can see that most of them original from a timeout,  this timeout is by default 60 seconds which is pretty long in cpu time. 

So I think the two cause of this problem could be one of the following:

- The Poller in question might be blocked waiting on something, system call?
- It never got scheduled in time to run, that could be due to the load on the machine.

For the *Beats timeout*, if logstash is currently crushing under resources it could cause a timeout, since Logstash wont read from the socket and beats would think thats something is wrong.

Maybe we got some resources starvation? Is everything run on the same machine ES/Logstash?

**Comment by ph** [comment]
Also if we look more closely at the, for some period of time the periodic poller was able to run.

```
{:timestamp=>"2016-07-21T16:56:41.226000+0000", 
{:timestamp=>"2016-07-21T16:57:30.357000+0000", 
{:timestamp=>"2016-07-21T16:58:21.444000+0000", 
{:timestamp=>"2016-07-21T17:03:56.688000+0000", 
{:timestamp=>"2016-07-21T17:08:57.546000+0000", 
{:timestamp=>"2016-07-21T17:10:22.877000+0000", 
{:timestamp=>"2016-07-21T17:10:25.956000+0000", 
{:timestamp=>"2016-07-21T17:12:35.949000+0000", 
{:timestamp=>"2016-07-21T17:12:37.997000+0000", 
{:timestamp=>"2016-07-21T17:14:35.002000+0000", 
{:timestamp=>"2016-07-21T17:20:45.931000+0000", 
{:timestamp=>"2016-07-21T17:28:30.483000+0000", 
{:timestamp=>"2016-07-21T17:31:21.407000+0000", 
{:timestamp=>"2016-07-21T17:31:31.073000+0000", 
{:timestamp=>"2016-07-21T17:31:40.993000+0000", 
{:timestamp=>"2016-07-21T17:31:47.966000+0000", 
{:timestamp=>"2016-07-21T17:38:11.167000+0000", 
{:timestamp=>"2016-07-21T17:40:55.771000+0000", 
{:timestamp=>"2016-07-21T17:42:49.319000+0000", 
{:timestamp=>"2016-07-21T17:46:57.214000+0000", 
{:timestamp=>"2016-07-21T17:53:35.767000+0000", 
{:timestamp=>"2016-07-21T17:55:48.443000+0000", 
{:timestamp=>"2016-07-21T17:56:46.302000+0000", 
{:timestamp=>"2016-07-21T18:00:02.856000+0000", 
{:timestamp=>"2016-07-21T18:01:22.353000+0000", 
{:timestamp=>"2016-07-21T18:01:39.114000+0000", 
{:timestamp=>"2016-07-21T18:02:52.745000+0000", 
{:timestamp=>"2016-07-21T18:04:47.115000+0000", 
{:timestamp=>"2016-07-21T18:14:15.387000+0000", 
{:timestamp=>"2016-07-21T18:17:27.222000+0000", 
{:timestamp=>"2016-07-21T18:17:48.323000+0000", 
{:timestamp=>"2016-07-21T18:28:50.895000+0000", 
{:timestamp=>"2016-07-21T18:32:46.876000+0000", 
{:timestamp=>"2016-07-21T18:34:22.977000+0000", 
```

**Comment by KovRon** [comment]
Hello,

All components of ELK stack located on this instance.

I think you are right and it's a result of resources lack.

Can you give me some recommendation for ELK stack instance to avoid this kind of problem? In plans get information from 10 Linux instances with Nginx and MySQL. In some cases web servers process more than 1000 client requests. 

Do you have some metrics to count the load on the server according to amount of instances and services located on them?

**Comment by ph** [comment]
We usually  recommend separating the Logstash instance from the ES, but in your case having a beafier machine should just work, your load is pretty low.

The T2.medium instance has only 2 core and the machine has to share everything between ES, Logstash, normal operation.

Did you look at what was using all the resources of the machine? I am really interested to know since you are using an alpha :)

> Do you have some metrics to count the load on the server according to amount of instances and services located on them?

We don't have that kind of metric to provide.

**Comment by KovRon** [comment]
Hello,

Sorry for the big delay.

Unfortunately I don't have this kind of data.

Many thanks for advice.

**Comment by ph** [comment]
to help with the issue we have done the following:

- use a bigger timer for the poller
- log to debug instead of error.

done in #6169
