### ISSUE TITLE
Latest snapshot/master breaks plugin tests

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#5702]
The latest logstash snapshot/master breaks all plugin tests using Logstash devutils because https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/environment.rb#L12 depends on `bootstrap/environment.rb` which is not required during plugin tests.

The real fix is not to fix this require statement but to fix devutils to properly define the data path to `/tmp/#{something}` for test runs.

**Comment by ph** [comment]
I think the problem is right there: https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/environment.rb#L40

This value get replaced by https://github.com/elastic/logstash/blob/master/lib/bootstrap/environment.rb when we are running from a distribution.

So I think the solution would be yes to change DEVUTILS and make it change the value of the `LOGSTASH_HOME` into something that make more sense. Temporary directory would be perfect.

**Comment by ph** [comment]
Which is a bit better than the default ruby method. Stud::Temporary.pathname

**Comment by andrewvc** [comment]
Fixed in #5706
