### ISSUE TITLE
[persistence] eviction mechanism first iteration

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#5948]
Per #5283 we need to be able to evict (DLQ) events when closing a batch.

The first iteration will simply leverage our new logging infrastructure as described by @suyograo in https://github.com/elastic/logstash/issues/5283#issuecomment-247690120

One problem is that event dropping is actually done in the plugins, see for example the json filter https://github.com/logstash-plugins/logstash-filter-json/blob/80f1795cf3c2cdd91cd82c1baea3bb6ac6b2e132/lib/logstash/filters/json.rb#L75-L83
- The code higher up in the pipeline https://github.com/elastic/logstash/blob/f01fec411781b84e0ccf068ad80e9796bcacdd7f/logstash-core/lib/logstash/pipeline.rb#L266-L281  has no visibility on dropped/evicted events. If we keep this, writing these errors to a separate log file would require updating all plugins
- One idea would be to introduce a mechanism for a plugin to mark an event as rejected or for a plugin to raise a rejection exception, but this would only work for single-event filtering and would also require updating all plugins.
- An alternative is to keep current behaviour in place temporarily, re: dropping events on failures & logging in the plugins, but improving the `filter` method uncatched exceptions code to avoid poison messages to never be acked and always replayed and possibly systematically crashing LS see https://github.com/elastic/logstash/blob/f01fec411781b84e0ccf068ad80e9796bcacdd7f/logstash-core/lib/logstash/pipeline.rb#L298-L308

**Comment by guyboertje** [comment]
Firstly, I find the word eviction troublesome. For the acronym ETL, the point of the Load step is to place the Event in the designated Destination(s) and if this cannot be done then it needs to be put in a designated Alternate Destination.

Eviction is troublesome for me because the Event is not really evicted, it is acked and drops from the PQ either way - a failed Event is simply put in (one of) the Alternate Destination(s).

I even find the idea of coding for **one and only one** DLQ troublesome.

1. **The user** may regard some transforms as critical to deciding whether an Event should be further transformed and loaded
2. **The user** may regard some transforms as non-critical and may wish for the Event to be routed to an Alternative destination for manual enhancement but maybe not.
3. **The user** may regard some destinations as critical for a successful Load
4. **The user** may regard some destinations as non-critical for a successful Load

When deemed unsuccessful the Event should be tagged and considered failed.

We now have the Batch object. It should be used to segregate the "failed" events from the active ones (it already segregates the cancelled ones).

We have previously discussed a universal error handling inside the pipeline, filters or their base class or filter_delegate so that batches are always acknowledged. We should definitely include a config option that allows a user to specify the criticality of a stage and this option should guide how we tag the event and whether it should be sent to an alternative destination or not.

**Comment by colinsurprenant** [comment]
@guyboertje this is an issue to discuss the **first iteration** implementation for merging in master.   as you note, we don't have a proper/complete/coherent/holistic story for DLQ yet. Also note that **today** events are **dropped** without any recovery or logging guarantees by the plugins - in practice most of them just log the fact that an event was just dropped.

**Comment by colinsurprenant** [comment]
maybe the "first iteration" part was not clear, it is in the issue title and was specifically created to followup on @suyograo 'first implementation, or a poor man's DLQ" proposal in #5283. So, to clarify, this is a stop gap proposal to make us move forward.

**Comment by guyboertje** [comment]
We now have the Batch object. It should be used to segregate the "failed" events from the active ones (it already segregates the cancelled ones).

We have previously discussed a universal error handling inside the pipeline, filters or their base class or filter_delegate so that batches are always acknowledged. This mechanism should indicate to the batch object that an event is "failed"

**Comment by guyboertje** [comment]
@colinsurprenant - point taken, I moved my comment to 5283.

**Comment by colinsurprenant** [comment]
@guyboertje yes, we agree on this. But the problem for the first iteration is that this would requires updating all the plugins that drop events to either tag or mark or in some way surface that information back to the pipeline and the batch object... unless we come up with a way to avoid this I believe this is out of scope for now and still fall in the "better DLQ story" ... ?

**Comment by colinsurprenant** [comment]
Closing this issue, all events are acked after all outputs regardless of their processing status - the current dropping is maintained as it was.
