### ISSUE TITLE
Logstash 5 beta1 elasticsearch outplug plugin does not support "workers" setting

### ISSUE THREAD

**Issue by vbohata** [elastic/logstash#5972]
After upgrading from logstash 5 alpha5 to beta1, workers setting for elasticsearch output plugin stopped working. See error:
`
You are using a plugin that doesn't support workers but have set the workers value explicitly! This plugin uses the shared and doesn't need this option`

Is this a bug or workers setting will not longer be available for elasticsearch output plugin?

**Comment by ceeeekay** [comment]
I'm seeing something similar: setting workers >1 on any output plugin causes logstash to quit on startup.

In my case Logstash is logging nothing so it's very hard to tell what the issue is.

**Comment by jordansissel** [comment]
@vbohata  I believe this is intentional. We are moving away from the `workers` concept for outputs due to some internal design changes that make obsolete the idea of an output having workers.

Some background:
* groundwork where we remove the concept of `workers` and move to a new `concurrency` definition: https://github.com/elastic/logstash/pull/5752
* `workers` as a removed concept: https://github.com/elastic/logstash/issues/5823


I do notice that this change isn't documented in the CHANGELOG nor is it in the breaking changes docs, we can fix that.

**Comment by ceeeekay** [comment]
FYI breaking changes at https://www.elastic.co/guide/en/logstash/5.0/beta1.html points to #5662, but gives the impression this is happening in v6.0.

**Comment by jordansissel** [comment]
specific outputs are moving to the new 'shared' concurrency and these don't support `workers` setting.

Does this answer your question?

**Comment by vbohata** [comment]
Yes, thanks.

**Comment by andrewvc** [comment]
@ceeeekay @vbohata can you confirm which plugins are giving you that error? Only select outputs should be doing that. 

https://github.com/elastic/logstash/issues/5662 removes workers in favor of allowing plugins to be in complete control of their concurrency (implementing whatever makes the most sense for them).

By default plugins use the `legacy` type of `concurrency` which does support `workers`. This will (hopefully) be removed in 6.0 as more plugins move to the new, more powerful, model.

**Comment by ceeeekay** [comment]
@andrewvc I was seeing it with the Elasticsearch output. I also tested with stdout but the error stated the plugin uses 'single', which makes sense. I haven't tested worker settings on any other outputs at this stage.
