### ISSUE TITLE
Configuration errors should be logged, not printed to stderr.

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#5975]
When possible, configuration errors should be logged.

Here's an example in 5.0.0-beta1 where we use `$stderr.puts` instead of a logger:

```
# I put an invalid setting in my logstash.yaml
% bin/logstash -f foo.conf
INFO: Logstash has a new settings file which defines start up time settings. This file is typically located in $LS_HOME/config or /etc/logstash. If you installed Logstash through a package and are starting it manually please specify the location to this settings file by passing in "--path.settings=/path/.." in the command line options
ERROR: Failed to load settings file from "path.settings". Aborting... path.setting=/home/jls/build/logstash-5.0.0-beta1/config, exception=ArgumentError, message=>Setting "path.log" hasn't been registered
```

These are emitted with `$stderr.puts`. Invalid settings should be logged with a logger.

Reference:https://github.com/elastic/logstash/issues/5974

**Comment by suyograo** [comment]
This `Logstash has a new settings file which defines start up time settings.` cannot be logged using log4j logger, because it is a chicken and an egg problem. When this is happening (no valid settings file detected), log4j2 is not setup, so we can't use this. Unfortunately, this has to still go to `stderr` for now

**Comment by suyograo** [comment]
Partially fixed in this https://github.com/elastic/logstash/pull/5999
