### ISSUE TITLE
Logstash 5.0 refuse to start

### ISSUE THREAD

**Issue by JorisAndrade** [elastic/logstash#6142]
Hi,

My logstash v5 crashed yesterday and it refused to start again

Here's the log file 

https://gist.github.com/JorisAndrade/b5174ff18feee5b3a7e36772d7ac8a10

**Comment by suyograo** [comment]
@JorisAndrade can you provide the config and sample event used? Also what is your OS and Java version?

**Comment by colinsurprenant** [comment]
quick followup: we just discussed the issue with @guyboertje and we understand where and how this is happening, I will skip the details just now but if @JorisAndrade could provide his config we could possibly come up with a quick fix to a plugin creating this problem which would hopefully solve this problem without having to wait for a Logstash bugfix release.

**Comment by guyboertje** [comment]
@JorisAndrade - we need your config.

I have a theory that your original data source has a field/key called "tags" - it might be JDBC, Redis/Kafka (JSON) or one of the inputs that get structured data e.g. Beats or CEF.

If this is happening, it would explain the fault.

**Comment by guyboertje** [comment]
I can't recreate this with a JSON file, file input and add_tag on 5.0

**Comment by colinsurprenant** [comment]
It could also be a plugin directly settings the `tags` field with a string value...? Having the config would really help diagnose. @JorisAndrade ?

**Comment by JorisAndrade** [comment]
Yeah sorry for the delay...

My config is pretty big but here's the input and output base config

https://gist.github.com/JorisAndrade/310fe44d0c4467573d45c642ce52dfd8

**Comment by colinsurprenant** [comment]
Hm. I looked at the configs and don't see where this could originate exactly. You mentioned that removing the geoip filter seems to fix the problem, I don't see your geoip filter config in the config files you provided, could you provide a complete config which actually fails?  Also could you provide a sample log line/message which triggers the exception?

Not related but I also noticed that your Ruby filter seems highly inefficient: if the tags file you load and parse is static, you shouldn't read and parse it on every event but do it only once in the init code.

**Comment by colinsurprenant** [comment]
Ok I got it. I am able to reproduce the problem when the original message/log contains a `tags` field with a string value. The problem is any plugin downstream that explicitly call the `Event#tag` method, for example [in geoip](https://github.com/logstash-plugins/logstash-filter-geoip/blob/5efefd8c94fbe686ce7be4358a94a3d7b05d50fa/lib/logstash/filters/geoip.rb#L235) when there is a lookup error. `Event#tag` [assumes the tags content to be an array](https://github.com/elastic/logstash/blob/d063c44293b67ddace68a62b8df0f5ab12f38478/logstash-core-event-java/src/main/java/org/logstash/Event.java#L348-L356) so having a single String value result in this exception. 

Reproduction:
```sh
echo "{\"tags\":\"foo\"}" | bin/logstash -e 'input{stdin{codec => json_lines{}}} filter{geoip{source => "foo"}} output{stdout{codec => rubydebug{}}}'

Sending Logstash logs to /Users/colin/dev/src/elasticsearch/logstash/logs which is now configured via log4j2.properties.
[2016-11-02T15:43:10,494][INFO ][logstash.filters.geoip   ] Using geoip database
[2016-11-02T15:43:10,540][INFO ][logstash.pipeline        ] Starting pipeline
[2016-11-02T15:43:10,567][INFO ][logstash.pipeline        ] Pipeline main started
[2016-11-02T15:43:10,661][INFO ][logstash.agent           ] Successfully started Logstash API endpoint
[2016-11-02T15:43:10,664][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.
Exception in thread "[main]>worker3" java.lang.ClassCastException: org.logstash.bivalues.StringBiValue cannot be cast to java.util.List
	at org.logstash.Event.tag(Event.java:348)
[...]
```

Now I noticed there is another "similar" problem that will happen in the filter config `add_tag`, where the tag addition will result in the string contactenation as we can see below:


```sh
 echo "{\"tags\":\"foo\"}" | bin/logstash -e 'input{stdin{codec => json_lines{}}} filter{mutate{add_tag => "bar"}} output{stdout{codec => rubydebug{}}}'

Sending Logstash logs to /Users/colin/dev/src/elasticsearch/logstash/logs which is now configured via log4j2.properties.
[2016-11-02T15:42:19,628][INFO ][logstash.pipeline        ] Starting pipeline
[2016-11-02T15:42:19,638][INFO ][logstash.pipeline        ] Pipeline main started
[2016-11-02T15:42:19,713][INFO ][logstash.agent           ] Successfully started Logstash API endpoint
{
    "@timestamp" => 2016-11-02T19:42:19.733Z,
      "@version" => "1",
          "host" => "colin-mbp13r.local",
          "tags" => "foobar"
}
```

Both are easily preventable by first verifying if the tags field contains a String value and in which case convert it back into an Array before adding the new tag. I believe this is the least-surprise behaviour for situations where structured input data already contains a tags field with a String value.

**Comment by colinsurprenant** [comment]
created #6177 for fix

**Comment by JorisAndrade** [comment]
Thank you for your help ! 

PS : Duly noted for the ruby part, thanks !

**Comment by colinsurprenant** [comment]
@JorisAndrade :thumbsup: ping me if you have problems making the Ruby filter work that way.
