### ISSUE TITLE
Add a max event size for pipeline

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#6146]
Recently we've had a spate of OOM support issues which had nothing to do with memory leaks in the product. All of these issues were related to heavy events in-flight which caused the JVM to crash with out of memory. One has to analyze the heap dump to even determine the cause to be heavy event objects, and I'd like this process to be more self-service and to not involve downloading MBs of heap dump.

To this end, we should introduce `queue.event.max.bytes` setting which will control the maximum size of a message that the queue (and indirectly, Logstash) can handle without crashing the process. The default can be 10MB to start with. There is really no need for heavy event data to be in-flight. The user should know about this immediately rather via support/JVM crashes. One corrective action could be an increase in heap size, but that is left to the user.

The queue producer stage -- after the event is pulled off the wire -- is a natural place to check for event size.

If the event size increases the threshold, the producer should log and drop it. The user can then take corrective action. FWIW, there is an additional per-event-size check in ES output (https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/497).

**Comment by colinsurprenant** [comment]
I wouldn't tie this setting to the queue. I suggest just `event.max.bytes` - it is only related to the event size and not really to the queue.

**Comment by suyograo** [comment]
That works as well. `event.max.bytes`

**Comment by colinsurprenant** [comment]
It is tricky to compute the Event size. There is really no easy way to evaluate the memory footprint or a Ruby or Java object.

So we could see if the original `Event` creator, either the codec or the input plugin if not using codec, can figure out its input data size which could be used to approximate the resulting in-memory `Event` object representation.  This will be easy for String/streaming IO based input, say TCP, stdin, file, etc. Depending on the data format (json vs raw message, etc), the approximation will be  more or less correct.  It will get trickier for inputs that receives objects for the underlying library, think of JDBC, where the size of each field assignment will have to be tracked to compute the overall fields data size to get to the object size approximation. 

Now, the Event can also get transformed by the filters and its sized can significantly change. 

We could look into the BiValues converters to see if we could keep tab of all values assignments and increment a global size counter.

All this do not look trivial.

**Comment by guyboertje** [comment]
I think that BiValues can track payload size.

**Comment by guyboertje** [comment]
How often will the size be queried?

**Comment by guyboertje** [comment]
what is the worst case estimate of event size increase via event mutations?

**Comment by talevy** [comment]
> worst case estimate of event size increase via event mutations?

the moon? filters like jdbc and ES can potentially add a lot of structured data

**Comment by guyboertje** [comment]
Well in that case we can recalculate the batch size when each filter method is completed in the filter delegator.

**Comment by colinsurprenant** [comment]
I really don't like the idea of a solution that will require **ultimately** patching all plugins all over the code to add raw data size estimate. I understand we say we want to start "small" and do it first for the usual suspects and where it will be easy for inputs/codec that already deal with raw bytes but ultimately this bring a new plugin "feature" that plugin authors will have to think about: keeping tab of Event data size and that will creep all over the place.

- I would strongly prefer if we could come up with a solution which does not require patching all plugins/codecs. I think we should definitely look into the BiValue idea.

- maybe an alternative, if all we want is an rough estimate, would be to simply use the size of the PQ serialization resulting byte array? this implies PQ is enabled though.

**Comment by suyograo** [comment]
**To state our goal again: Find and report on large events which enter Logstash that leads to OOM crashes. That means specifically at the input level.** 

We should skip the filters section completely for phase 1. Filters like ES and JDBC are such a small fractions of our usage, we are focusing on the wrong things here. 

Even in inputs like JDBC, Redis and Kafka, I understand it is hard to estimate the size of an event. If we can't find a heuristic, we skip it.

**Comment by colinsurprenant** [comment]
@suyograo I totally understand the goal but the proposed solution is IMO a knee-jerk reaction to the problem. This  approach means introducing this new "thing" which is adding Event size estimate in the plugins, which has to be done in a very different way for all plugins potentially adding a lot of weird code all over the place similar to `@size += fieldvalue.size` or whatever.

The problem here is that we are saying: let's start small with the "usual suspects" but this will totally lead with plugins implementation inconsistencies, new unclear concerns for plugin authors and code creep. We will end up with this weird, inconsistently implemented "thing" in the plugins  that will be yet another code weirdness in the code base that will be another maintenance burden. 

Let's continue to think about this to see if there is not a better approach to this problem.

**Comment by colinsurprenant** [comment]
So the more I think about this, I am totally -1 on the proposed solution to add sizing at the plugins level. 
I am +1 on looking into potential alternatives like using BiValues or maybe the serialization mechanism (or other alternatives?)

**Comment by andrewvc** [comment]
Have we considered adding this at the codec level instead of the plugin level? I don't think there are any plugins that realistically lead to OOMs that don't use some sort of codec.

It is very unlikely for a JDBC input or some other such structured input to have large fields. 

Things like RabbitMQ use codecs, and those codecs are the point where we already have limits. MultiLine, for instance, has a max size, and is the natural place for this. Ideally the Line, Multiline, JSON, and other codecs would first look at the input size and say "Is this decodable?" and if the answer is "no, its too big" we hit the error path.

**Comment by andrewvc** [comment]
The other nice thing here is that the codecs all get a byte array, so *that* is the size we need to estimate.

**Comment by guyboertje** [comment]
> If the event size increases the threshold, the producer should log and drop it. The user can then take corrective action
^ From the opening comment

This log and drop is yet another form of error/failure handling - we have very poor failure handling semantics in any code before the Queue.

**Comment by colinsurprenant** [comment]
@andrewvc that does not solve the inconsistent nature of this sizing approach, only a subset of setups will benefit this.

**Comment by andrewvc** [comment]
@colinsurprenant I agree that it's not perfectly consistent, but I think it gives the greatest juice for the squeeze. 

I don't think there is a perfect solution for this that isn't unwieldy or undesirable in a number of ways. Specifically, approaches that depend on analyzing complex objects will have some bad leaky issues WRT performance and accuracy.

I think for this problem its important to have a pragmatic approach and not let perfection be the enemy of good. If we can eliminate or reduce the place where the most user pain comes from without creating an undue burden on ourselves I think we will have been successful.

**Comment by colinsurprenant** [comment]
I completely disagree with a half baked solution for the sake of pragmatism. This will lead to more problems in the long run.

**Comment by jsvd** [comment]
We have two major sources of pain that cause OOM: logstash-codec-line and logstash-codec-json.

Why not set a default size_limit on the buftok in codec-line and a size_limit on the json string that we're going to decode and solve many of the current issues?

**Comment by colinsurprenant** [comment]
@jsvd that seems like an acceptable compromise if we want to move forward with a quick fix.

**Comment by jsvd** [comment]
regardless of what we do here, I still think we should add these kinds of checks to the codecs, they're the first piece of code logstash knows it owns that touches the closest thing to raw data (what a terribly constructed sentence!).
sorry for sidetracking the conversation, I'll open 1 issue on each codec

**Comment by colinsurprenant** [comment]
maybe I am over complexifying this in my head but do the thought experiment of going through all the codecs and figuring how this would be implemented to get a consistent setting and behaviour. Then realize this will only solve the cases of config with codecs, some input plugins don't support codecs. 

If 90% (or any large percentage) of these OOM situations come from the line and json codecs, I am ok with adding a "max size" or similar option with a reasonable default to just both codecs. quick fix, very localized and specific modifications, no real consistency concerns. 

If we want something more general, I strongly suggest we take the time to properly evaluate the BiValue idea which if it potentially work with acceptable performance then THIS would be a universal solution without having to touch a single plugin.

**Comment by andrewvc** [comment]
@colinsurprenant I think we just need a "max_decode_bytes" option or something similar. We can work on the name. All codecs take a bunch of bytes and return an object. The codecs can determine what the maximum size of bytes they want to turn into an event should be.

* In the case of a JSON filter this would be the size of the buffer.
* In the case of the line filter it would be buftok as mentioned above.
* in the case of multiline it'd be the size of the maximum accumulated event size.

**Comment by colinsurprenant** [comment]
@andrewvc 
> In the case of a JSON codec this would be the size of the buffer

since the json codec does not do any buffering itself, I see little value in enforcing that because it relies on the input maximum chunk read size which is typically 16k.

>  In the case of the line codec it would be buftok as mentioned above.

the line codec should have had a max size limit since the beginning. note here that `json_lines` is exactly the same as `line` in using the buffered tokenizer. 

> in the case of multiline it'd be the size of the maximum accumulated event size.

I believe there is already a `max_bytes` config option in `multiline`. 

Now you are saying «all codecs». so this means figuring it out for netflow, avro, protobuf, nmap, cef, fluent, collectd, msgpack, gzip-lines, cloudfront, s3, es_bulk, graphite, plain, end_lines, edn, compress_spooler, cloudtrail, sflow,  csv

Do we want to comb through all these to figure if it makes sense to support a consistent `max_decode_bytes` ? 

Again, I am +1 on adding an ad-hoc, quick fix, to the lines and json_lines, similar to what multiline already has, and if this solves the majority of the problems then we win. 

But if we want a universal and consistent story, I suggest we evaluate the alternatives of doing that elsewhere than the codecs or plugins.  The basic idea of using the BiValues is that we could keep tab of an Event size by simply updating its global sized through all the Event fields mutations through the BiValue mechanism. This would provide a universal and consistent way of sizing and Event and a consistent way of deciding when we'd want to trap that and how to act on it. I believe this is an idea worth exploring that seems a lot better that going on a journey of doing a plugins mass update.

**Comment by suyograo** [comment]
>  This would provide a universal and consistent way of sizing an Event and a consistent way of deciding when we'd want to trap that and how to act on it.

I am definitely +1 on exploring a centralized approach like BiValues. I don't feel super excited making changes across plugins. 

Is it worth doing a small POC on that @guyboertje ?

**Comment by andrewvc** [comment]
@colinsurprenant I hear what you're saying about consistency. I don't have a good answer there and that may be a good reason not to do what I'm saying.

The key thing for me is that by doing it in the codecs we don't have to double allocate the memory into an Event, which in and of itself could cause an OOM. It seems like the right place to do the work.

In some sense its less complete because it won't catch every possible scenario. On the other hand it can do a better job of using less total memory, which makes it more complete.

I really don't see this as a quick fix, but rather as limiting memory usage at the earliest stage possible. Now, I'm prepared to hear about why this isn't necessary. Maybe I'm overthinking the whole thing, but it seems to me that if people expect to get large events we would be better off using N memory instead of N*2.

**Comment by ph** [comment]
I am +1 if can find a way to make quality of life improvement across plugins without having to manually changes plugins

**Comment by andrewvc** [comment]
IIRC it has been discussed earlier that we should:

1. Remove codecs for decoding
2. Introduce deserializers for decoding (basically line + multiline)
3. Move all codecs back to filters

If we were to do this we'd only need to check for size at the deserialization point. There were numerous other benefits (not worth rehashing here).

**Comment by abhinigam** [comment]
+1 We are using logstash aggregators and the last thing I want is the aggregators to OOM on really large messages. I would rather have the input plugin drop the events before it makes its way into the pipeline on the lines of what Suyog Rao has recommended.

**Comment by colinsurprenant** [comment]
@abhinigam we never moved forward with this and there is no plan to do so in the near future. I suggest you open a new issue or Discuss thread with your specific setup concerns and we can see how we can help with what we have today.

**Comment by colinsurprenant** [comment]
I also suggest we close this issue. Please re-open if you have any objection.
