### ISSUE TITLE
does filebeat5.0.0  work well with logstash2.4.1? 

### ISSUE THREAD

**Issue by kanezch** [elastic/logstash#6345]
btw, the version of beats in logstash2.4.1 is 3.1.8
`[root@master bin]# ./logstash-plugin list --verbose 'beats'

logstash-input-beats (3.1.8)`

I have gone throught the products support matrix here:
 https://www.elastic.co/support/matrix#matrix_compatibility
but didn't find any detail about that, anyone can help?

**Comment by ph** [comment]
@kanezch Yes, Filebeat 5.0.0 works well with Logstash 2.4.1, Its not explicit in the matrix because we focus in the product versions, which we hope make thins easier.

but a bit of story, lumberjack, the communication protocol we use didn't change much between FB 1.3.X and FB 5.X,so  we make sure that the beats inputs work with both of theses major releases.

Our versioning is a bit complex, we have product version and plugins version.

But Logstash 5.0.1 and Logstash 2.4.1 both ships with the same version of the beats input, we aim to do that because it's just easier to us to keep track and managing less branches and backports..

But If possible I would uses Logstash 5.X on the server too, this is where the development is going and you will benefit from our recent works.
