### ISSUE TITLE
jvm.options is left out of custom path.settings

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/logstash#6379]
This was observed under RHEL 7.2 running Logstash 5.0.2

The [docs](https://www.elastic.co/guide/en/logstash/current/command-line-flags.html) do say that `path.settings` specifies the location of `logstash.yml` and log4j config.  From the `logstash.yml` file, one can then set `path.config` for LS configuration.   So far so good, but it is not clear how `jvm.options` can be moved from /etc/logstash to a custom location.   The possible locations [appear to be statically defined](https://github.com/elastic/logstash/blob/d5d556989dcf8232c83ef9b6558c0bbe299e3455/bin/logstash.lib.sh#L67-L76)

**Comment by untergeek** [comment]
Part of the problem is that Logstash has to set the JVM parameters when it starts, before it reads any of the other settings and initializes Logstash's JVM.   Here's the startup sequence (as roughly as I can remember it):

1. User calls Logstash binary
2. Because the binary path is relative to the Logstash path, it looks up `logstash.lib.sh` and initializes the early Logstash settings
    * The `logstash.lib.sh` file looks for jvm.options in 2 places: `/etc/logstash` and `$LS_HOME/config`, first match wins.
    * JVM options are set accordingly
3. Logstash continues launching with the provided options... _which were provided on the command line_ ...

So `logstash.lib.sh` has to know where to find where the `jvm.options` file is.  All of the other data is passed on the command-line, like where to find the pipeline config and the `logstash.yml` file (path.settings).

It _may_ be possible to extract `--path.settings ARG` from the array of settings at startup time in `logstash.lib.sh`, but without being able to accurately do so, there is no other way I can think of to have `jvm.options` read at start time if it's not in one of those pre-determined paths.
