### ISSUE TITLE
offline installation of a .gem plugin broken in 5.1.1

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#6386]
Installing a .gem plugin without internet will fail in 5.1.1:

```
joaoduarte@Joaos-MBP-5 /tmp % tar -zxf logstash-5.0.0.tar.gz
joaoduarte@Joaos-MBP-5 /tmp % cd logstash-5.0.0
joaoduarte@Joaos-MBP-5 /tmp/logstash-5.0.0 % bin/logstash-plugin install ../logstash-filter-dissect-1.0.8.gem
Validating ../logstash-filter-dissect-1.0.8.gem
Installing logstash-filter-dissect
Installation successful
bin/logstash-plugin install ../logstash-filter-dissect-1.0.8.gem  35.07s user 1.45s system 202% cpu 18.076 total
joaoduarte@Joaos-MBP-5 /tmp/logstash-5.0.0 % cd ..
joaoduarte@Joaos-MBP-5 /tmp % tar -zxf logstash-5.1.1.tar.gz
joaoduarte@Joaos-MBP-5 /tmp % cd logstash-5.1.1
joaoduarte@Joaos-MBP-5 /tmp/logstash-5.1.1 % bin/logstash-plugin install ../logstash-filter-dissect-1.0.8.gem
Validating ../logstash-filter-dissect-1.0.8.gem
Installing logstash-filter-dissect
Error Bundler::HTTPError, retrying 1/10
Could not fetch specs from https://rubygems.org/
Error Bundler::HTTPError, retrying 2/10
Could not fetch specs from https://rubygems.org/
```

more information when running with debug flags can be seen [in this gist](https://gist.github.com/jsvd/72a4467b294df19e8da70edd26dbcbd2)

**Comment by ph** [comment]
Not sure what cause this regression yet, from what I've tested I know that the xpack flow got skipped in that context, so it uses the previous flow.

**Comment by ph** [comment]
OK, this might be a bit harder to track, I've made a special release without any xpack code and I still have the bug.

**Comment by jsvd** [comment]
interesting fact: the plugin actually gets installed and is usable after the error

**Comment by ph** [comment]
@jsvd yes you are right it got installed, I wonder I may have added verbosity to the bundler installation that it was hidden before.

**Comment by ph** [comment]
The Gemfile and the Lockfile are correctly updated.

**Comment by ph** [comment]
Adding a 5.0.2 successful log here https://gist.github.com/ph/5c2484122e1bef8a76a84aff6b6477bb

**Comment by ph** [comment]
`LogStash::Bundler.setup!({:without => [:build, :development]})` this line in the plugin_manager/main.rb was destroying the local cache making bundler's install cli to do a `resolve_remotely!` and this call require a internet access to rubygems.

The xpack feature was not affected by this since it manually force a local resolution.

**Comment by ph** [comment]
I've double checked @jsvd and this doesn't impact anything.

**Comment by ph** [comment]
Also a bit more context we plan to remove that feature in https://github.com/elastic/logstash/issues/6393

**Comment by ph** [comment]
I have now a pretty good understanding of why pack/unpack or even installing a .gem doesn't work when you are offline, I will still do a bit more check but for now its really a **HOT** place.

One of the major feature that we have introduced in logstash 5.0 is the unified build process, to make it work we have decided to ship Logstash with the core gems bundled in the root of the project. It was convenient since we didn't need to push new gems on rubygems to make workable releases.

But it has a side effect, to make theses gem available in our project we have to use the `:path` option in our gemfile and this change impact what bundler has to do.

When a normal gem is installed, the gemspec is read, the hooks like jar dependencies are executed and the gem and specification are saved in the appropriate directory in vendor/bundle, for bundler this gem is done, no hook will never be needed to be executed again.

When we do `plugin install` and bundle sees a path in the gemfile, It will think that its a new gem and it will trigger the hooks, so everytime the hooks will be triggered.

When you are offline AND your ~/.m2 doesn't exist or the cache has expired it will fail.

**Comment by ph** [comment]
You can disable `jar-dependencies` with JARS_SKIP='true', making the error go away.
```
DEBUG=1 JARS_SKIP='true' bin/logstash-plugin install --local logstash-input-stomp
```

```
Updating files in vendor/cache
Bundle complete! 115 Gemfile dependencies, 205 gems now installed.
Gems in the group development were not installed.
Bundled gems are installed into /tmp/pack-unpack/logstash-6.0.0-alpha1-SNAPSHOT/vendor/bundle.
Installation successful
```

**Comment by ph** [comment]
So we could do the following when `--local` is specified, we turn off `jars_dependencies`, so this would mean that the previous flow should be back to normal behavior.

I still think #6393 is the better long term solution instead of pack/unpack since it give a better flow/experience until it land we could use the above strategy.
