### ISSUE TITLE
Debian package does not depend on Java

### ISSUE THREAD

**Issue by joshuaspence** [elastic/logstash#6394]
We use Puppet to manage our Logstash hosts and are using the [puppet-logstash](https://github.com/elastic/puppet-logstash) module to install and configure Logstash. We have noticed that sometimes Logstash fails to install properly because Java has not yet been installed. Quite possibly the Puppet module could/should add the necessary relationships in order to ensure that the `java` package is installed before the `logstash` package, but I think that probably the Debian package should also specify a dependency on Java. This can be done with the [Depends](https://www.debian.org/doc/debian-policy/ch-relationships.html) field of the `debian/control` file.

**Comment by untergeek** [comment]
There are several tickets filed before with this same request. We feel it imprudent to put in a dependency because too many potential packages meet the "java" requirement. For example, Logstash shouldn't be used with Java 7 anymore, but Java 7 meets a Java requirement. And both OpenJDK 8 and Oracle Java 8 meet that requirement, but which one should you deploy? We leave that to the end user to resolve. 

For many more responses to similar tickets, please search the GitHub closed issues.

**Comment by joshuaspence** [comment]
Thanks for your reply and apologies for filing a duplicate ticket. I had searched for similar issues before creating this one, but I couldn't find anything.
