### ISSUE TITLE
RSpec is no longer bundled

### ISSUE THREAD

**Issue by joshuaspence** [elastic/logstash#6479]
Logstash 2.4 shipped with a shim script for `rspec`, which was installed to `/opt/logstash/bin/rspec`. It seems that this script is no longer distributed with Logstash 5. Is this intentional? We were using this script for running unit tests for our Logstash configuration.

**Comment by disaster37** [comment]
+1 Same problem for me

**Comment by guyboertje** [comment]
See #5666 and #5667 for the reasoning.

**Comment by guyboertje** [comment]
I have had success with copying the script 'as is' from a 2.4 install - this would be a workaround.

We should respond here with the intended mechanism for 5.X soon.

**Comment by ph** [comment]
Another way to test your configuration is to use @magnusbaeck's logstash-verifier at https://github.com/magnusbaeck/logstash-filter-verifier

**Comment by blalor** [comment]
Please bring this back.  Logstash configs get super complex; I have like 80% test coverage on my 1.4.2 configs and it's the only way to survive, given the long startup times of Java and Logstash, and the otherwise difficult nature of testing pipelines.

**Comment by benpolzin** [comment]
Any guidance from Elastic on this? 

The workaround of copying the script from v2.4 isn't working for me in 5.x nor is it working for me in 5.x if I build from source and reverse this commit (seems like a simple dependency error for rake-12.0.0, but that's a separate issue). 

While I certainly appreciate @magnusbaeck's contribution here with his Logstash Filter Verifier it doesn't fully support v5.x yet and is missing some other things for our use case that rspec has.

In #5666 @purbon commented that it would be easier to call bin/logstash and think of LS as a black box. Can you comment further on this? I can consider Logstash a black box, but need to test the input and output of that black box in a systematic way. The bin/logstash config test just says the config is valid, not that the output will be as expected (e.g. no parsing failures). Is there another option here I'm missing? 

In #5667 @ph commented that it would be good to write a doc with guidance on how to write tests for Logstash configs. If rspec is not included in the distribution bundles, but it is possible to include it when building from source or some other method I'd appreciate a doc from Elastic describing this so that those using it can be assured it won't break with every new release.

**Comment by talevy** [comment]
hey @joshuaspence, thanks for bringing this up!

We no longer wish to package development dependencies into the Logstash distributable. I encourage you to check out the logstash development repository and execute rspec from there!

If you need help with this, feel free to ping!

**Comment by suyograo** [comment]
@joshuaspence to add to what @talevy mentioned, development dependencies bundled in a production release are a pain to maintain.

If folks have been using `rspec` previously, they can continue to do that, but they'll have to checkout Logstash (git clone) and follow these instructions to run their tests: https://github.com/elastic/logstash#testing

**Comment by gquintana** [comment]
I suggest that doing some special command, like `logstash install --development' (meaning I want a Logstash for development purpose not production) could install the `rspec` script in the bin folder.

When you install Shield plugin in Elasticsearch, you get an extra `esuser` script to manage users, it's the same idea.

**Comment by joshuaspence** [comment]
+1 on installing optionally via an extra command

**Comment by thehybridtechnician** [comment]
I would agree with this.

**Comment by nilskuhn** [comment]
I wrote [this docker image](https://hub.docker.com/r/iteratec/logstash-rspec) one could use for running rspec tests for own filter configs. 

Feel free to review, use and/or improve ;)
