### ISSUE TITLE
Events "in" metric calculation should happen before inserting into queue

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#6512]
GET `_node/stats` gives event `in`, `out`, `filtered` metrics. With the introduction of PQ, we've added an unbounded buffer capacity between input and filter stage. The metric calculation we do for reporting on incoming events should happen before writing to the queue, instead of doing at the [beginning](https://github.com/elastic/logstash/blob/c03f30fedb3eb440fc8e307aaade57b3f2314fcb/logstash-core/lib/logstash/filter_delegator.rb#L38) of the filter stage.

**Comment by suyograo** [comment]
This is evident if you use PQ and generator config + sleep filter as such: https://gist.github.com/suyograo/659098e66526bf07abe89c3b2997ab12

The events in stats will show lesser than what was actually generated. Generator is basically inserting events as fast as possible, which does not get reflected in the in metric.

**Comment by ph** [comment]
I will take a look.

**Comment by colinsurprenant** [comment]
I think the issue title should read "should happen **before**" ?

**Comment by ph** [comment]
This is not a hard fix, I will wrap the write client into an instrumented client.

**Comment by ph** [comment]
Actually, the referenced code is not where the bug is the `:in` is calculated in the `ReadClient` section and should be done at the `WriteClient` level.

I think the definition we are looking for is the following:

- Input
  - global **in** rate
  - per plugin **out** rate
  - **push_queue_duration_in_millis** This will be new with the PR I am making, looking for a better name?
 
- Filter
  - per plugin: **in**, **out**, **duration_in_millis**

- Output
  - per plugin: **in**, **out**, **duration_in_millis**

- Worker Loop
  - **duration_in_millis**
  - global **out**

**Comment by suyograo** [comment]
Can we rename `push_queue_duration_in_millis` to `queue_push_duration_in_millis`
