### ISSUE TITLE
Metrics internal API: Add method to check if key exists

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#6533]
Some metrics are available only on certain platforms/OS, so it may be empty when queried on these systems. The approach [now](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/api/commands/stats.rb#L72) is to do this in a `rescue` block and catch `MetricNotFound` exception. I think a better way is to expose a `has_metric()` which takes a path.

`has_metric?([:os])`
`has_metric?([:os, cgroups])`

**Comment by ph** [comment]
+1 since exception are expensive in ruby/jruby.

**Comment by jsvd** [comment]
doesn't this mean we'd have to do the lookup twice? like

```
if has_metric?([:os])
  get_shallow([:os])
end
```

The only alternative I see is a value that represents a failed lookup..

**Comment by ph** [comment]
@jsvd the `has_metric` could target the fast lookup table?

**Comment by jsvd** [comment]
fair point. even from that perspective it is tricky to ensure that this change actually makes the overall performance better due to the following observations:

1. overall most get operations succeed consistently
2. some get operations on certain keys and certain environments will never succeed 
3. as it is, a succesful lookup does `get_shallow` and a failed one does `get_shallow + exception handling`
4. with the change, both a sucessful and a failed lookup will do `has_metric + get_shallow`
5. on the most common production platforms (linux based), we'll be adding the extra has_metric call needlessly (because all lookups are succesful).

Another suggestion would be to do like `Hash.fetch` and have an extra parameter for default value.

**Comment by suyograo** [comment]
> on the most common production platforms (linux based), we'll be adding the extra has_metric call needlessly (because all lookups are succesful).

I wouldn't do this for _all_ metric calls. Just ones we know may be empty. It would still be faster than relying on exceptions that we have now.

> and have an extra parameter for default value.

I like this better, actually. But we should short circuit immediately in the code and not do any extra work if the key does not exist.
