### ISSUE TITLE
remove queue.max_bytes option from PQ and rely only on free disk space threshold

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#6612]
I'm seeing some troubles lately in understanding the values of the queue size on disk because of different FS behaviour. This has affected both the feature itself (people not understanding how the limit was reached) and the creation of user facing metrics (e.g. https://github.com/elastic/logstash/pull/6518#issuecomment-276451360).

With this in mind, **I'm proposing to remove the queue.max_bytes feature completely**.
This would mean the only method of controlling queue size disk usage would be to compare the amount of free FS usage with a threshold (e.g. a percentage and/or an absolute value).
The check would happen during page allocation (both during pipeline startup and runtime) which, IMO, is a more reliable and simpler mechanism to understand than the queue.max_bytes, so I don't see a reason to keep it anymore.

So, the action plan would be:

a. remove `queue.max_bytes` option and runtime checks (effectively removing all traces of queue.max_bytes from logstash)
b. add a new setting for minimum free disk space on path.queue (e.g. `path.queue.minimum_free_space`)
c. during page allocation check if `current_free_disk_space + queue.page_size  < path.queue.minimum_free_space` and..deal with it (abort logstash or exert back pressure)

Thoughts on this?

**Comment by jordansissel** [comment]
Having the queue size limit be dependent on the available disk capacity, I feel, assumes that Logstash alone has permission to use the entire disk. I don't believe this to be the case for many users that Logstash will have permission from humans to use most/all disk space as a default behavior.

Consider that the JVM. It also has this kind of default behavior where, on startup, the default max heap size is 25% of total system memory -- a default that users are largely (by my observation) unaware of, and a default that upsets many users causing them to say "Java uses too much memory!" because nobody sets the default heap size. This default behavior has forced us in Logstash to set a small-ish default heap size (1gb) because the JVM default is too large.

Back at Logstash and the PQ size. I feel it would be hard for many users to only have a percentage/threshold based on the disk capacity.

My current thinking is this -- we could have several limits on the size of the queue, at least:

1) The disk is near full (configurable percentage)
2) The queue is of a certain byte size (configurable byte size; currently queue.max_bytes)

We can block writes when either condition is met (disk near full _or_ queue is full)

We need some defense against disk fullness because we do not currently preallocate disk space  to my knowledge, and mmap'd writes are not given direct feedback (not a function call that returns error), so we could think a write succeeds when shortly after we get SIGBUS (or whatever the platform sends when an IO error occurs).

Still, with disk sizes today, even 1% can be a really large value for some users (1% of 1TB is 10GB), so my question is this:

Would a user want to control flow by having a small-number-of-megabytes max queue size, such as 10mb? I think they might want that in a variety of scenarios -- For example, if you've got a slow grok but are reading from redis, draining redis completely (into the PQ) with a really large disk, you can't easily add additional Logstash nodes to help process data from Redis because you've got so much already backlogged into a local-only PQ in Logstash.

**Comment by jordansissel** [comment]
While I'm not convinced we can get rid of the max_bytes setting, I love this exploration to remove it -- fewer settings means less user confusion. Thanks for this proposal :)

**Comment by jsvd** [comment]
> Having the queue size limit be dependent on the available disk capacity, I feel, assumes that Logstash alone has permission to use the entire disk. I don't believe this to be the case for many users that Logstash will have permission from humans to use most/all disk space as a default behavior.

True, I guess more and more I assume that production scenarios, specially those with PQ on, will have logstash instances running on dedicated machines. This is something I believe should be highly recommended, specially in a software that is often cpu bound.

> Still, with disk sizes today, even 1% can be a really large value for some users (1% of 1TB is 10GB)

+1, if `path.queue.minimum_free_space` were to be implemented, I think it should support both a percentage or an amount of bytes (ideally both?):

`path.queue.minimum_free_space: "1%"`
`path.queue.minimum_free_space: "500mb"`

> Would a user want to control flow by having a small-number-of-megabytes max queue size, such as 10mb? I think they might want that in a variety of scenarios -- For example, if you've got a slow grok but are reading from redis, draining redis completely (into the PQ) with a really large disk, you can't easily add additional Logstash nodes to help process data from Redis because you've got so much already backlogged into a local-only PQ in Logstash.

This is a very valid scenario, many users may want to have a similar behaviour as logstash 1.x and 2.x with a very small queue, but have it persisted.
In this scenario, it's still possible to set `queue.max_events`:

```
# If using queue.type: persisted, the maximum number of unread events in the queue.
# Default is 0 (unlimited)
```

So a user can, for example, set `queue.max_events: 512` to have at most 512 events unacked.

**Comment by jsvd** [comment]
> In hindsight I agree we should support options to constrain a queue by either byte size or number of events, to support the "control flow" use-case @jordansissel mentioned. I am convinced this will be agreed on by everyone.

As I mentioned in my response, I disagree here. The low event, control-flow scenario can be materialized through the use of queue.max_events, which maps cleanly to the control-flow Logstash users have always used: number of events (before 20, now it's "batch size")

**Comment by colinsurprenant** [comment]
@jsvd this option is already supported - it is a question of agreeing on how we want to compute queue byte size in relation to the filesystem. If we nail that then I don't see why we couldn't continue to support `queue.max_bytes`?

**Comment by jsvd** [comment]
@colinsurprenant I was just trying to determine how useful it is, and if it's needed. Otherwise I suggest keeping settings to a minimum: less code, less metrics, one less setting you'll be tempted to tweak

**Comment by colinsurprenant** [comment]
@jsvd so, "In hindsight" :P I do believe that specifying a queue max byte size is more comprehensive  than by number of events especially since we are dealing with **disk**-based persistence here. Max number of events make sense when using a very low number like 10 or 100. but what does 100000 or 1000000 means? I really think that it is just more useful to say max 10mb or max 250mb queue.

**Comment by jsvd** [comment]
alright, let's keep it.
btw that reminds me of something that we haven't accounted for: settings queue.max_bytes to 10mb will result in at most 10mb only if page_capacity is <= 10mb. If, for example, the page size isn't changed from the default (250mb), the queue will use 250mb
