### ISSUE TITLE
Documenting content-type header integration compatibility

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#6718]
We should have some documentation around ES compatibility with the [inclusion of content-type http headers option](https://github.com/elastic/elasticsearch/pull/22691).

If users want to use LS versions 2.4 - 5.2 with ES 5.3+ (with content-type headers are turned on), they will need to update their ES related plugins to:
- ES output - [6.2.5](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/CHANGELOG.md#625)+
- ES input - [4.0.2](https://github.com/logstash-plugins/logstash-input-elasticsearch/blob/master/CHANGELOG.md#402)+
- ES filter - [3.1.1](https://github.com/logstash-plugins/logstash-filter-elasticsearch/blob/master/CHANGELOG.md#311)+

We should decide where the best place is to put this. Here's an proposal:
- Include a statement in each of the 3 plugins
- Perhaps reference this as a client compatibility caveat on the ES side

/cc @dedemorton @suyograo @jordansissel

**Comment by dedemorton** [comment]
@acchen97 Ok, I've added info to the source for the plugin docs. I am concerned that this info will be overlooked, though. I hope there's some error messaging that will help users figure out this problem because I worry that they won't see this in the doc.

@debadair Do you have any suggestions for how to document this on the Elasticsearch side? The gist is that setting `http.content_type.required` to `true` is going to break older Logstash Elasticsearch plugins that don't yet support sending Content-Type headers.

**Comment by acchen97** [comment]
@dedemorton can we close this? The cross-referencing docs on the ES side are a nice to have as turning on the requirement for content typer headers is optional.

**Comment by dedemorton** [comment]
Yes, closing...
