### ISSUE TITLE
Make plugin install with "--local" option really local : no specs download on rubygems.org

### ISSUE THREAD

**Issue by fbaligand** [elastic/logstash#6787]
Currently, if I install a plugin referencing a local gem file, with "--local" option, the plugin is correctly installed, but after installation, Logstash tries to reach rubygems.org to download specs. 
This doesn't work when you're on a offline machine, and plugin specs are not useful to install plugin.

=> So it would be great to not try to download specs on rubygems.org after plugin install, when "--local" option is set.

Here's a sample :
```
$> logstash-plugin install --local /path/to/logstash-filter-translate-3.0.1.gem
Validating /path/to/logstash-filter-i18n-3.0.0-java.gem
Installing logstash-filter-i18n
Error Bundler::HTTPError, retrying 1/10
Could not fetch specs from https://rubygems.org/
```

**Comment by suyograo** [comment]
@fbaligand `--local` is deprecated. See https://www.elastic.co/guide/en/logstash/current/offline-plugins.html#offline-plugins

**Comment by fbaligand** [comment]
Elasticsearch and Kibana allow to install offline plugins from the standard plugin package. 

I don't understand no such feature exist in Logstash...

" prepare-offline-pack" feature is nice. But it requires a staging server which has full access to internet. 

Elasticsearch and kibana plugin install do not need it.

**Comment by untergeek** [comment]
Elasticsearch and Kibana don't use rubygems for their plugins.

**Comment by ph** [comment]
@fbaligand I think the problem is often a plugin doesn't come without dependencies, Kibana and ES goes around that by having all the dependencies bundled in the plugin. I would say a plugin for ES only work on a specific version of ES. This is obviously not the case with Logstash.


On our side, the `prepare-offline-pack` command will do that, bundle all the dependencies in a zip that we can distribute.

Maybe in a future we will offer self contains plugins in zip, meaning we will run `prepare-offline-pack`, but this is not in our short term road map.

**Comment by fbaligand** [comment]
Thanks for this answer @ph

I understand that Logstash needs internet to download missing dependencies. 

But it would be great that if all runtime dependencies are already resolved locally on gem home, there is no need for internet. 
This is particularly useful for filters which rarely depend from external dependencies.
