### ISSUE TITLE
Docs generation change

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#6846]
Background:

Logstash plugins have had their documentation embedded as comments within the plugin code for 6+ years. This was a design choice intended to make plugin docs maintenance easier on me.

Over time, this design choice has started to become a burden on us because:

1) We moved from markdown to asciidoc
2) We moved from docs hosting on logstash.net (maintained by me) to elastic.co (maintained by Elastic)
3) We moved plugins from this repository (logstash) to each plugin having its own repository.

All of these above changes have made it harder to publish documentation from the original sources. In discussions, we spend lots of time thinking and working on the logstash plugin docs generator tooling.

----

Proposal: Each plugin will have an asciidoc file living in the same repository as the plugin and will contain the documentation for that plugin.

@ph, @dedemorton, @suyograo, and others contributed to the ideas and decisions here.

Desired impact:

* reduce time spent on troubleshooting documentation pipeline issues
* reduce time-to-publish on new plugin documentation
* reduce time spent previewing new docs in code review (no more logstash-docgen to run!)

Key measurable:

* Folks don't ask us about out-of-date or missing plugin documentation anymore.

Next steps for implementation:

* [x] For each plugin type, write a new asciidoc file in this (logstash) repository which details the settings provided by the base plugin classes. Example: the base filter class provides the `add_fields` setting.
* [x] Tweak the logstash-docgen tool to produce the per-plugin .asciidoc which will live in the same repository as the plugin.
* [x] Update the docs-tools/logstash build job[1] to also collect the new per-plugin asciidoc files from each repository. https://github.com/elastic/docs-tools/issues/3

[1] this build job ships our docs into the elastic.co docs pipeline.

**Comment by ph** [comment]
For the plugin directory structure I propose this, to have a top level directory `docs` with the plugin documentation named `index.asciidoc`. This could allow complex plugins to have more pages when if/needed or images.

```
├── docs
│   └── index.asciidoc
├── lib
├── logstash-input-beats.gemspec
├── settings.gradle
├── spec
└── vendor.json

**Comment by ph** [comment]
I have a script that creates the documentation for every plugin and strips the fields inherited from the base classes ((inputs|codecs|outputs|filters|/base.rb and plugin.rb), these information will be moved to the filter for each plugin type that will be included by the ascidoc.

Remaining steps for me:
[ ] - Add the include for each type
[ ] - Scripts that update each plugin with the new structure
[ ] - Create a PR for each plugin
[ ] - Meta issue with link to each doc.

I understand how cumbersome creating a PR for each plugin can be, but we can review each plugin doc and make in place change in the PR before merging it.

WDYT?

**Comment by ph** [comment]
@jordansissel @dedemorton I've created an example PR at https://github.com/logstash-plugins/logstash-filter-dissect/pull/16, I am currently missing the generics parts for the plugin type and to use the asciidoc include to add them.

The doc is generated from the current logstash-docgen in logstash with the inherited plugin options removed, I've created a script to automate the PR creation on all the plugins repository.

**Comment by ph** [comment]
`docs-tools/logstash` build job will need to be updated to support the following scenario:

*Build master doc*
- Fetch master branch of Logstash
- Fetch all the master branch of the plugins
- build doc.

*For a specific version LS version*
- Fetch a specific tag of Logstash
- build Logstash
- fetch the docs in the `vendor/bundle` directory
- build docs

**Comment by ph** [comment]
@dedemorton we will need to sync to decide how we want to format the base options for the plugin types, this is the only thing missing to move the work forward. I have extracted all the information for each plugin type in this [gist](https://gist.github.com/ph/c204155ad9feed50cd718432368834f2)

**Comment by dedemorton** [comment]
@ph How about having two sections?  I actually had someone come up to me at Elastic{ON} who said that they would prefer to see the common options listed separately from the ones added by each plugin (good for experienced users who just want to see the options that a specific plugin adds). Here's an example. View the "raw" file to see the comments that I've added. There's some stuff I think we should remove or do differently. https://gist.github.com/dedemorton/d4e5a8791ec6a73881723a73af8a3826

**Comment by dedemorton** [comment]
@ph I was thinking a bit more about this over lunch. If we use an `include` statement to pull the common options into  the doc for each plugin, we're going to run into issues with IDs. asciidoc requires each ID to be unique across the book (not just across the file). So if we have a common file with something like:

````
[[plugins-filters-common-add_field]]
===== `add_field`
````

And we try to  include this content in more than one file place, we will get the build error:

`validity error : ID age-add_field already defined`

I don't know if there is a way to set IDs dynamically in asciidoc, but that would be the way to go.

**Comment by dedemorton** [comment]
@ph Sorry, one more notification. :-) I figured out how to set the ID dynamically. Not sure if this is the *best* way, but it seems to work. 

You can add a variable to the top of the page. For example:

`````
:plugin: dissect

[[plugins-filters-dissect]]
=== dissect
`````

And then use the following syntax in the shared file to use the variable to set the ID:

`````
[id="{plugin}-add_tag"]
===== `add_tag`

`````

The following syntax DOES NOT work, maybe because the ID gets set before the value of `{plugin}` is resolved? (`[[plugins-{plugin}-add_tag_test]]`).

We might also be able to use `{plugin}` in the examples by allowing substitutions (`["source","ruby",subs="attributes"]`), but we'd need to figure out how to escape the bits in the example that actually should appear in curly brackets (and not be evaluated as variables).

**Comment by ph** [comment]
<3 all your recommendation @dedemorton 

Concerning the following section, I think you have a valid point, they often don't offer real value and humanly crafted examples with comments are better, even our es output display an empty block.

```
Required configuration options:

[source,json]
--------------------------
dissect {
}
--------------------------
```

For the next steps tomorrow:
- create a PR on the LS repo that create the initial version of the common files
- update the common file with dynamic ids.
- Update the template for the plugin to add the variable.
- Test the includes.


But I will let you do the final edit on the common file, this sound like a good plan?

**Comment by ph** [comment]
@dedemorton I've pushed an example repo at https://github.com/ph/example-doc, it contains the asciidoc for each plugin type, html and the common include.

**Comment by dedemorton** [comment]
@ph I went through the example repo (only looked at the asciidoc because I wanted to generate the html on my end anyhow). Here's some stuff that needs a bit more work:

- Add a colon after the sentences that introduce the config options. For example: The following configuration options are supported by the beats input: (right now there is no punctuation)

- Is the extra space before Configuration Options necessary? (I think we might have added it for situations where there is no description, but I can't remember. We can leave it in for now, and maybe clean out the extra space after we've extracted all the docs.

- I do like having two separate sections for the plugin-specific options vs the common options. I think that occasionally users will miss seeing that the second section exists. I have no good ideas for avoiding this problem given that we want to use a shared file and we want experienced users to see the short list of what the plugin adds.

- Shouldn't the "Installation" and "Getting Help" sections be common files that get pulled in? Note that variables won't resolve if they appear within in backticks, so you'll need to enclose the install command in plus signs (+) instead: `For plugins not bundled by default, it is easy to install by running +bin/logstash-plugin install logstash-{type}-{plugin}+`

- Where does `{section}` get set? I guess in the overview file for each output type? I hard-coded  section in the files to get the IDs to work. 

- BTW, your syntax for the ID at the top of each file is a little off. Shouldn't there be an end quote. So `[id="plugins-{section}-{plugin}]` should say `[id="plugins-{section}-{plugin}"]`

- How are we planning to keep the "version" and "released on" info up-to-date after we've initially extracted the asciidoc from the code files?  Will we continue to run a script that adds this info? My apologies if this is obvious by looking at the script. I haven't delved into the details of the script yet.

- How will the `:plugin:` and `:type:` variables get set by new plugin developers? Will our script (if we have one) also do that?

**Comment by ph** [comment]
> Where does {section} get set? I guess in the overview file for each output type? I hard-coded section in the files to get the IDs to work.

Ahh it should be `{type}` here not `{section}`, I've paid attention to everything below missing the first line. 🐛 

> How are we planning to keep the "version" and "released on" info up-to-date after we've initially extracted the asciidoc from the code files? Will we continue to run a script that adds this info? My apologies if this is obvious by looking at the script. I haven't delved into the details of the script yet.

I think this is something we didn't plan for, but I have  a few ideas:


1. We could get around that by instead of using concrete values and rely on variables and get them replaced by a preprocessor scripts before we render the html?

```
:release_date: XXX-XX-XX
:version: X-X-X
```

2. I still new in asciidoc world, could we write our own macro, that could read a content of a file.

3. We make the header of the plugin document be managed outside the plugin documentation?

I feel that if we ask users to keep them in sync, we will lost the battle, so solution 3 doesn't look so bad.

> How will the :plugin: and :type: variables get set by new plugin developers? Will our script (if we have one) also do that?

I would think that we will ship an example document with our example repo and people can start from them?

**Comment by dedemorton** [comment]
@ph Whatever we do needs to happen to the asciidoc files before they're checked into the build (we can't rely on the doc build to have extra logic running that's specific to Logstash). Not sure if that's what you're proposing, but I think it's best for any processing to happen on our end.

The Beats team uses make scripts to generate some of the content that we have in the docs, so I think that's a viable option for us. I'm no developer (not the best person to recommend how we architect this), but what if we had the version info in a separate generated file called something like `json_version.asciidoc` (in the same directory as the source doc). The file would contain something like:
```
////
This file is generated! Do not update.
////

* Version: 3.0.2
* Released on: July 14, 2016
* https://github.com/logstash-plugins/logstash-codec-json/blob/master/CHANGELOG.md#302[Changelog]
```

Then we could use an include to bring in the file. 

I guess we'd need to script to run whenever the version is updated.

**Comment by ph** [comment]
I was thinking about the same, some plugins already have their version
extracted.

**Comment by ph** [comment]
Add a colon after the sentences that introduce the config options. For example: The following configuration options are supported by the beats input: (right now there is no punctuation)

Is the extra line before Configuration Options necessary? (I think we might have added it for situations where there is no description, but I can't remember.) We can leave it in for now, and maybe clean out the extra space after we've extracted all the docs.

> I do like having two separate sections for the plugin-specific options vs the common options. I think that occasionally users will miss seeing that the second section exists. I have no good ideas for avoiding this problem given that we want to use a shared file and we want experienced users to see the short list of what the plugin adds.

I don't have a good solution for that too.

> Shouldn't the "Installation" and "Getting Help" sections be common files that get pulled in? Note that variables won't resolve if they appear within in backticks, so you'll need to enclose the install command in plus signs (+) instead: For plugins not bundled by default, it is easy to install by running +bin/logstash-plugin install logstash-{type}-{plugin}+

I have extracted that into a new file that get included.

> Where does {section} get set? I guess in the overview file for each output type? I hard-coded section in the files to get the IDs to work.

it should have been {type} in the file not {section}

> BTW, your syntax for the ID at the top of each file is a little off. Shouldn't there be an end quote. So [id="plugins-{section}-{plugin}] should say [id="plugins-{section}-{plugin}"]

Fixed it.

> How are we planning to keep the "version" and "released on" info up-to-date after we've initially extracted the asciidoc from the code files? Will we continue to run a script that adds this info? My apologies if this is obvious by looking at the script. I haven't delved into the details of the script yet.

this is a pretty good question, I think our merge tool should take care of that and create a file that get included?

**Comment by ph** [comment]
I've pushed the final version of the extracted doc of a plugin at the following URL https://github.com/elastic/logstash/issues/6846, It uses the scripts to create the PR.

The PR make one assumption about the structure of the plugins versus logstash, I think it's fine because it allow plugin author to be able to generate the doc.

Expected structure for the asciidoc include.
```
~/es/logstash
~/es/logstash-plugins/logstash-filter-dissect.
```

**Comment by ph** [comment]
The expected structure is just to set the number of nested directories to search for the include.

**Comment by ph** [comment]
I've create an official PR for the changes proposed by this issue at https://github.com/elastic/logstash/pull/6941

**Comment by ph** [comment]
- [ ] Fix our tooling to take the new files
- [ ] Bump all the patch version of the plugins
- [ ] Backport the doc commit to some other branch for plugins that have multiple release branches.

**Comment by dedemorton** [comment]
Closing because it appears that all this work is done.
