### ISSUE TITLE
Idea: mini-filters!

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#6847]
It is often that a user needs to do something complex with an event that has a weird data format, but where existing filters cannot manipulate the event in the desired way. 

The standard advice today is to either:

1. Write a custom filter (high effort, but robust)
2. Write a ruby filter (low effort, not robust,  not easily testable).

I'm proposing a third idea, **mini filters**!

These would be:

1. Testable
2. Easy to write
3. Easy to share
4. Intentionally limited in features
5. Hopefully replace most uses of the ruby filter

The idea here is to be able to define a filter in a single short file that *includes* some minimal tests. This could be implemented as a `mini_filter` plugin, or some such.

You would use it in a config like so:

```
filter {
  mini {
    file => "/path/to/keyzipper.rb"
  }
}
```

I've provided an example mini-filter below:

```ruby
define_filter :keymapper do
  init do |params|
    @keys_path = params['key'] || 'keys'
    @values_path = params['values'] || 'values'
  end
  
  process do |event|
    keys = event.get(@keys_path)
    vals = event.get(@values_path)
    next unless keys && vals && !keys.empty? && !vals.empty?
    
    keys.each.with_index do |key,i|
      event.set(key, vals[i])
    end
    
    event
  end
  
  test(
    "keys map to vals",
    :params => {},
    :input => { "keys" => ["a", "b"], "vals" => [1,2] },
    :output => {  "keys" => ["a", "b"], "vals" => [1,2], "a" => 1, "b" => 2 }
  )
  
  test(
    "no keys, not problem",
    :params => {},
    :input => { "a" => "b" },
    :output => { "a" => "b" }
   )
end
```

Note that the tests here are not rspec and have no dependencies and would run whenever the plugin is initialized. They would simply compare events exactly. The goal here is not perfection, but quick and good for the cadence our users operate at. An improved version of the ruby filter.

We could also consider implementing this sort of thing in javascript with nashorn since JS is so well known by people.

**Comment by untergeek** [comment]
I love the idea! I hope I don't sound pessimistic when I ask how these will be handled when we move to online/centralized configuration. 

I would love to figure out a way to bridge the promise of mini-filters with centrally stored configuration.

**Comment by andrewvc** [comment]
@untergeek that's a great question!

I'm thinking that it might make sense to have an inline option for declaring these as well. Just like the ruby filter has a 'source' attribute.

This also would work well if we make a new config language using LIR. If we had a .yml based config you could define one inline with a heredoc.

That being said, the reusable part becomes problematic there.

Do you have any specific ideas here?

**Comment by untergeek** [comment]
> Do you have any specific ideas here?

Unfortunately, no. Not yet anyway. I feel bad poking at such an awesome idea without providing a possibility to address my issue. ☹️

**Comment by acchen97** [comment]
@andrewvc is this only for scripting use cases? Would it technically just be enabling a wrapper to pass in scripting code that include tests?

I'm still not totally convinced how much value this adds, but other scripting languages like Painless, Python, JS could also add benefit to something like this.

**Comment by jordansissel** [comment]
@andrewvc Lovely idea -- I think it captures the spirit of some existing things in Logstash. Specifically the ruby filter and [the `sample` rspec helper](https://github.com/elastic/logstash-devutils/blob/master/lib/logstash/devutils/rspec/logstash_helpers.rb#L34).

I still wish for general plugins to be easier to write. This is a good path for experimenting with such a goal :)

**Comment by ph** [comment]
Pushing that idea a bit further, some of the problems could be solved by adding `require/include` statement for the config syntax.
```
filter {
sleep { time => 1}
include "mini/my_ruby.rb" # The LIR could already know to create a mini filter representation based on the file extension.
}
```

We could also support inline definition (agree that it can open other problems) :

```
filter {
sleep {}
#language/ruby
my ruby ...
}

```

**Comment by andrewvc** [comment]
@ph I love both of those ideas.

My preference is to wait till we have a new, more extensible logstash config file format post-LIR.

For now I think implementing as a filter plugin is better to at least start experimenting with the idea. WDYT?

**Comment by ph** [comment]
@andrewvc Yup, I think think we should have an include mechanism in the current LIR with the additions of multiples pipeline.

**Comment by breml** [comment]
I am not quite sure what to think about this proposal, so here are my thoughts:

1. Testable: I fully agree, it is important to be able to test a LS config, especially if it includes customized ruby code, but this is also true, if one has a rather complex config, which includes for example grok-filters and conditions. So in these cases, the built in tests in the mini-filter do not help. A solution like [logstash-filter-verifier](https://github.com/magnusbaeck/logstash-filter-verifier) for me seems to be a better fit. Also, if one has a complex config and wants to add it to a CI system, I am not quite sure, how this would be possible with the proposed solution.
2. Easy to write: I agree mostly, because
    1. it is a simplified form of a complete filter plugin (even thou a complete filter plugin is also not that hard to write)
    2. it is a valid ruby file and therefore it may be edited with proper syntax highlighting (no longer true, if it is inline in the config).
But: the code is not runnable without LS, which means, for the development (iterating on the code) one is still suffering from the quite slow startup times of LS.
3. Easy to share: I would argue, that it is equally easy to share a ruby filter via Gist, but sure, easier than a full blown plugin (ruby gem).
4. OK
5. In this case, why not extend the already existing filter?

Just to give an example of a rather complex LS configuration, have a look at: [logstash-modsecurity](https://github.com/bitsofinfo/logstash-modsecurity). This config allows to process the audit log of  ModSecurity (Apache module), which is a complicated multi line beast. To process these log entries, quite some Ruby code was necessary. But if one wants to test this kind of configuration, the added tests in this proposal do not solve the whole problem, but one would need some kind of end-2-end test.

CC: @magnusbaeck

**Comment by andrewvc** [comment]
@breml  Thanks so much for the feedback.

1. I don't see this as overlapping with logstash-filter-verifier. The logstash-filter-verifier is more of an integration test. This is a unit test. Even small bits of code need testing!
2. Good point about iteration! Like I said this is trying to occupy a middle ground.
3. Yeah, this is definitely a bit harder to share than a ruby filter, but still way easier than packaging a gem.
5. That's also a good point about extending the ruby filter. Maybe we *should* do that. OTOH, it might be nice to separate it out since I'd love to support languages other than ruby. It could have a `lang` option for javascript for instance (that's easy to support since we're on the JVM).

**Comment by suyograo** [comment]
I like the idea of moving away from _inlining_ the ruby filter to a file on disk. It makes the config more manageable and easier to read as well. +1 on the tests not being rspec syntax. That's a great idea. 

Long term, we should think about moving away from ruby filter (it is _too_ powerful) since it is not sandboxed in any way, but for now since we don't have an alternative scripting language, this approach will really help.

**Comment by guyboertje** [comment]
I like the idea but am also mindful of what we spoke about in Tahoe regarding Java plugins or rather the idea that a plugin will supply a Java compute class instance for embedding in a graph node component. This compute class can be a wrapper around the jruby generated class if its defined in Ruby (wrapper to aid Java <-> Jruby datatype marshalling).

**Comment by andrewvc** [comment]
@suyograo I think the intention here is that users will not do things like I/O with this. Maybe one day we'll enable painless for security reasons, and when that day comes we can make that the default lang, but, TBH, I even question that. Painless, is, well, not quite painless since its another lang you have to learn. I'd rather have a world where users can use painless/JS/Ruby or whatever *they* find most comfortable. Maybe users need to opt in to use insecure langs, but I think its a good feature.

@guyboertje what specific changes would you make to this proposal to be mindful of those concerns.

**Comment by guyboertje** [comment]
I don't think what I said above affects the proposal much. It would be something the `process` DSL keyword would do to provide the Java compute class.

In addition, I guess we would want to abstract away the need for ruby ivar specifics. e.g. in the init block to provide a DSL keyword that internalises an ivar...
```
# ruby
@keys_path = params['key'] || 'keys'
```
becomes
```
#dsl
locals('key_path').put(
  from(params).using('key').default('keys').get()
)
```
Above, I am thinking of a way to abstract the language variant away so that a locals "map" could be passed to the Java compute class instance.

And then to abstract away the event API and null/empty checks...
```
    locals("keys_path").as_array().with_index().apply() do |key, i|
      from(event).using(key).put(
        locals("values_path").as_array().using(i).get()
      )
    end
```
or as functions
```
  define_function('map_key_to_val') do |event, key, i|
    from(event).using(key).put(
      locals("values_path").as_array().using(i).get() # 
    )
  end

  define_function('process') do |event|
    locals("keys_path").as_array().with_index().apply(event, functions('map_key_to_val'))
  end
```
`locals` and `from` would return a Value or NullValue that would insulate the user from exceptions etc.
`put` would insulate from a missing key in the event (collection) or trying to store a NullValue
`as_array` would ensure a memoized local array
`apply` would take a block or an event and a Function

NOTE: I am not advocating the above directly, only to illustrate that we can provide a more DSL and less code approach.

**Comment by andrewvc** [comment]
@guyboertje I like the idea of getting rid of ivars with a special 'locals' map. I don't want to architect beyond that though until there's something concrete to pin that to. We can always change the code there later.

**Comment by guyboertje** [comment]
#justsayin :-)

**Comment by andrewvc** [comment]
I have a PoC here: https://github.com/logstash-plugins/logstash-filter-script
I renamed it to `logstash-filter-script` because I felt that was more descriptive. I kept it generic because I thought it'd be nice if it had a `lang` attribute to support javascript in the future.

Check out an example script here:
https://github.com/logstash-plugins/logstash-filter-script/blob/master/spec/fixtures/field_multiplier.rb

**Comment by ph** [comment]
Good thing @andrewvc, I wonder if we should be more explicit or DSL'y and pass another variable so people can add new event or cancel other?

```
filter do |batch, event|
 new_event = event.clone
 batch << new_event
 batch.cancel(event)
end
```

**Comment by andrewvc** [comment]
I've created an initial commit here: https://github.com/logstash-plugins/logstash-filter-script/pull/1

This uses a new, more ergonomic API where the user doesn't need to worry about cancel and batches.

You just return an array of events and the code figures out what to cancel, what to pass on, etc.

**Comment by colinsurprenant** [comment]
since the DSL `filter` and `flush` are callback style blocks, maybe we could rename them:
- `filter` could become`on_event`
- `flush` could become `on_flush` 
and for batch support we could add
 - `on_batch`

**Comment by colinsurprenant** [comment]
@andrewvc would you prefer I made such suggestions in the PR instead or here is good to discuss suggestions and ideas even though the PR is out?

**Comment by andrewvc** [comment]
@colinsurprenant yes! That'd be great. I'll close this issue and let's move the discussion to: https://github.com/logstash-plugins/logstash-filter-script/pull/1
