### ISSUE TITLE
Protobuf codec docs missing for 5.3

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#6864]
It appears the protobuf codec plugin docs are missing for 5.3; they're available for 5.1 and 5.2. We should fix this when we have the chance.

/cc @ingafeick @dedemorton

**Comment by suyograo** [comment]
Done. https://www.elastic.co/guide/en/logstash/master/plugins-codecs-protobuf.html and https://www.elastic.co/guide/en/logstash/5.3/plugins-codecs-protobuf.html

**Comment by IngaFeick** [comment]
Thanks a lot! -------- Originalnachricht --------Betreff: Re: [elastic/logstash] Protobuf codec docs missing for 5.3 (#6864)Von: Suyog Rao An: elastic/logstash Cc: Inga Feick ,Mention Done. https://www.elastic.co/guide/en/logstash/master/plugins-codecs-protobuf.html and https://www.elastic.co/guide/en/logstash/5.3/plugins-codecs-protobuf.html

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/elastic/logstash","title":"elastic/logstash","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/elastic/logstash"}},"updates":{"snippets":[{"icon":"PERSON","message":"@suyograo in #6864: Done. https://www.elastic.co/guide/en/logstash/master/plugins-codecs-protobuf.html and https://www.elastic.co/guide/en/logstash/5.3/plugins-codecs-protobuf.html"}],"action":{"name":"View Issue","url":"https://github.com/elastic/logstash/issues/6864#issuecomment-290960297"}}}
