### ISSUE TITLE
include PQ threaded spec as a normal test or integration test

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#6917]
this spec https://gist.github.com/colinsurprenant/b3ca535857a0e5d4ab48580fdfd653fe originally authored by @jordansissel and then greatly enhanced by @guyboertje and slightly fixed by myself in #6829 and #6901 should be included as a test or an integration test.

This is a spec which stress tests the PQ concurrency under various parameters. On my MBP is takes about 3 minutes to complete. 

I wouldn't mind adding this spec in the normal test suite but not sure if the added extra 3 minutes of "normal" specs would hurt our patience? 

WDYT?

**Comment by ph** [comment]
We had a discussion on that, I've proposed the following:

1. We merge that spec in master and the time is increased.
2. We create a followup issue to decide to decide what to do with these stress specs.
    1. Either make them a separate suite.
    2. Either tag them with slow
    3. Make separate rake task to run them.
3. tag that suite with a very specific tag like *persistent_queue_stress_test* that are not excluded by default.


I have *proposed* option 3, because when you debug weird agent/pipeline issues in the suite you often need to run the full test multiple time to discover issues, removing 3 minutes of run time, in that case, is a big deal. By having a very specific tag, when you exclude them it's because you really want to, it is an explicit choice.

**Comment by colinsurprenant** [comment]
In principle I agree with the tagging idea but in practice our problem is that currently, tags are not really used and/or maintained. I say "not really used" but [we do use them](https://github.com/elastic/logstash-devutils/blob/a90eaea0de1147a9eea2cc6320d8b82448a8b8cb/lib/logstash/devutils/rspec/spec_helper.rb#L50-L57) but simply as a set of automatically excluded and AFAIK not really maintained list of tests. We know that automatically excluded tests are as good as no tests. 

That being said (and not wanting to transform this issue into a "refactor our specs tags" issue (which we should also do btw)), similar to what @ph mentioned, maybe a temporary solution would be to tag it with a "stress_test" tag but -not- exclude it by default and, and this is the important part, create 2 new rake tests tasks: `rake test:core-fast` and `rake test:core-slow` and have the current `rake test:core` do the `test:core-slow` by default. Then, if you want a faster core specs run by excluding stress tests, you can specifically run `rake test:core-fast`.

**Comment by suyograo** [comment]
+1 on running these stress tests by default.

**Comment by colinsurprenant** [comment]
PR in #6930
