### ISSUE TITLE
Pipeline aborted due to error {:exception=>"NoMethodError", :error=>"undefined method `set_validate_after_inactivity

### ISSUE THREAD

**Issue by kailashv** [elastic/logstash#6948]
Hi, I am Using Logstash:2.4 in a Docker Container. The service is not getting started. Its breaking with following error mentioned below : 

Pipeline aborted due to error {:exception=>"NoMethodError", :error=>"undefined method `set_validate_after_inactivity' for #<Java::OrgApacheHttpImplConn::PoolingHttpClientConnectionManager:0x407957f6>", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/client.rb:403:in `pool'", "org/jruby/RubyKernel.java:1858:in `tap'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/client.rb:402:in `pool'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/client.rb:208:in `initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/http/manticore.rb:58:in `build_client'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/http/manticore.rb:49:in `initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/client.rb:118:in `initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport.rb:26:in `new'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:129:in `build_client'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:20:in `initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:44:in `build'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch.rb:134:in `build_client'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:14:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/output_delegator.rb:75:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:181:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:181:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/agent.rb:491:in `start_pipeline'"], :level=>:error}

* To resolve this issue, I have given full access to the user and also changed the  permissions of the logstash.conf file.
Referred : https://github.com/jruby/jruby/issues/3824 . But still facing the same issue.

**Comment by kailashv** [comment]
Issue resolved. it was my fault. The logstash version was different(2.4 instead of 2.1).
The manticore was not supported for that version (logstash:2.4), custom plugins i had was for previous version (logstash:2.1). Just changed the logstash version to 2.1 and it worked.

**Comment by VinodHY** [comment]
Hi All,

I am using Logstash 6.3.0 and i am observing the same issue. I am not able to figure out the solution. I have fresh setup with very basic changes. I just want to test the basic flow,

Below is the logs which i am getting once i start logstash,

[2018-06-16T06:27:43,664][ERROR][logstash.pipeline ] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<NoMethodError: undefined method set_v alidate_after_inactivity' for #<Java::OrgApacheHttpImplConn::PoolingHttpClientConnectionManager:0x66f5055d>>, :backtrace=>["D:/Softwares/ELK/logstash-6.3.0/vendor/bu ndle/jruby/2.3.0/gems/manticore-0.6.1-java/lib/manticore/client.rb:403:inblock in pool'", "org/jruby/RubyKernel.java:1741:in tap'", "D:/Softwares/ELK/logstash-6.3 .0/vendor/bundle/jruby/2.3.0/gems/manticore-0.6.1-java/lib/manticore/client.rb:402:inpool'", "D:/Softwares/ELK/logstash-6.3.0/vendor/bundle/jruby/2.3.0/gems/mantic
ore-0.6.1-java/lib/manticore/client.rb:208:in initialize'", "D:/Softwares/ELK/logstash-6.3.0/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.1.1-java /lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:26:ininitialize'", "D:/Softwares/ELK/logstash-6.3.0/vendor/bundle/jruby/2.3.0/gems/logstash-ou
tput-elasticsearch-9.1.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:279:in build_adapter'", "D:/Softwares/ELK/logstash-6.3.0/vendor/bundle/jruby/2.3.0/g ems/logstash-output-elasticsearch-9.1.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:283:inbuild_pool'", "D:/Softwares/ELK/logstash-6.3.0/vendor/bundle/j
ruby/2.3.0/gems/logstash-output-elasticsearch-9.1.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:63:in initialize'", "D:/Softwares/ELK/logstash-6.3.0/vend or/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.1.1-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:102:increate_http_client'", "D:/Softw
ares/ELK/logstash-6.3.0/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.1.1-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:98:in buil d'", "D:/Softwares/ELK/logstash-6.3.0/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.1.1-java/lib/logstash/outputs/elasticsearch.rb:231:inbuild_cli
ent'", "D:/Softwares/ELK/logstash-6.3.0/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.1.1-java/lib/logstash/outputs/elasticsearch/common.rb:24:in r egister'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:97:inregister'", "org/logstash/config/ir/compiler/OutputDelegatorExt.java:93:in register'", "D: /Softwares/ELK/logstash-6.3.0/logstash-core/lib/logstash/pipeline.rb:340:inregister_plugin'", "D:/Softwares/ELK/logstash-6.3.0/logstash-core/lib/logstash/pipeline.
rb:351:in block in register_plugins'", "org/jruby/RubyArray.java:1734:ineach'", "D:/Softwares/ELK/logstash-6.3.0/logstash-core/lib/logstash/pipeline.rb:351:in re gister_plugins'", "D:/Softwares/ELK/logstash-6.3.0/logstash-core/lib/logstash/pipeline.rb:728:inmaybe_setup_out_plugins'", "D:/Softwares/ELK/logstash-6.3.0/logstas
h-core/lib/logstash/pipeline.rb:361:in start_workers'", "D:/Softwares/ELK/logstash-6.3.0/logstash-core/lib/logstash/pipeline.rb:288:inrun'", "D:/Softwares/ELK/log
stash-6.3.0/logstash-core/lib/logstash/pipeline.rb:248:in `block in start'"], :thread=>"#<Thread:0x7d40ef71 run>"}
[2018-06-16T06:27:43,695][ERROR][logstash.agent ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Co
uld not execute action: PipelineAction::Create, action_result: false", :backtrace=>nil}
[2018-06-16T06:27:43,948][INFO ][logstash.agent ] Successfully started Logstash API endpoint {:port=>9600}

logstash.config file:
input {
beats {
port => "5043"
}
}
output {
elasticsearch { hosts => ["localhost:9200"] }
stdout { codec => rubydebug }
}

COMMAND I AM RUNNING TO START LOGSTASH:
logstash -f logstash.config

Please help me here
