### ISSUE TITLE
Req: $LS_CONFIG_DIR option, to mirror $LS_SETTINGS_DIR

### ISSUE THREAD

**Issue by jarpy** [elastic/logstash#6971]
The settings directory can be specified by CLI flag, or, at lower precedence, by the [`LS_SETTINGS_DIR` environment variable](https://github.com/elastic/logstash/blob/645fcec234e44c43e595710b438db757ac519f46/logstash-core/lib/logstash/runner.rb#L443). This issue proposes a matching mechanism for specifying the location of the pipeline configuration.

In general, the ability to configure things via the environment is highly valuable to the Docker image. Anything that must be specified as a CLI argument is problematic, due to the nature the `CMD` statement in the Dockerfile.

See https://github.com/elastic/logstash-docker/issues/24 for the backstory on this suggestion.

**Comment by jordansissel** [comment]
@jarpy for environment variables or configuration inputs (in general), anything we may not support can be done with post-processing between docker and the startup of Logstash.

That said, I would prefer that if we must have environment variables (I prefer not, but that's outside the scope), let us try to minimize the interface. Let's have only LS_SETTINGS_DIR because that file contains a `logstash.yml` which contains `path.config` which users should use to specify the path to their configuration.

**Comment by jordansissel** [comment]
@jarpy I am confused by the issue you linked to, and I will follow up there.

**Comment by jarpy** [comment]
Resolved (in a much nicer way) by https://github.com/elastic/logstash-docker/commit/f3369698440fecdfa800f0b9d1a560c82f3c98ed
