### ISSUE TITLE
ignore configuration files not ending in .conf

### ISSUE THREAD

**Issue by inqueue** [elastic/logstash#6979]
* Version: 5.3.1

Today, Logstash loads all files sitting in `/etc/logstash/conf.d`.  This can be problematic if a user makes a copy of a configuration file, for example, using the `.bak` extension, as unexpected result occur. This can be especially problematic for Kafka as it can lead an unsuspecting user to balancing issues that are not immediately apparent. Please require and document the use of `.conf` file extensions in `/etc/logstash/conf.d`.

**Comment by jordansissel** [comment]
Well, we do document the behavior, but that's no excuse -- documented behavior is meaningless if users are tripping over it, so we must fix!

Proposal:

* Change the default to load "/etc/logstash/conf.d/*.conf" [1]
* And to help users more, we should log any files ignored by a wildcard -- like if there is a "foo.conf.bak" we should log an INFO message that says we are skipping it because it doesn't match the wildcard.
* And we should update our docs anywhere we specify the default load path for rpm and deb packages to be the new path above.

[1] https://github.com/elastic/logstash/blob/master/pkg/centos/after-install.sh#L5 (and other after-install scripts do this as well)

**Comment by jordansissel** [comment]
@inqueue for what it's worth, I have seen similar problems but different file naming practices. The `'*.conf` won't solve this problem generally because not everyone has the same personal tactics for "backup the file and make a change"- -- for example

* User wants to try a change, and prefers to call files `old_somename...`
* User does `cp stuff.conf old_stuff.conf`
* User edits `stuff.conf`
* User runs logstash, and unexpectedly, both stuff.conf and old_stuff.conf are used.
