### ISSUE TITLE
Dead Letter Queue feature should have metrics available via the monitoring API

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#7287]
The Dead Letter Queue feature should expose metrics for each queue, including

- [ ] Queue path
- [ ] Number of segments stored
- [ ] Max segment size (?)
- [ ] Number of items in the queue (is total segments sufficient?)
- [ ] Disk space used by the queue
- [ ] Last event written

_work in progress_

**Comment by robbavey** [comment]
Initial thought - similar to how queues are exposed in the pipeline, the same could be done for the dead letter queue: 



eg:
 ```
      "dead_letter_queue": {
        "path": "/Users/robbavey/code/logstash/data/dead_letter_queue/main",
        "current_queue_size_in_bytes": 684,
        "current_segment_count": 27,
        "last_entry_timestamp": "2017-06-05T00:28:57.394Z",
        "max_segment_size_in_bytes": 10485760
      }
 ```

- Do we need to mark if dlq is not enabled for a pipeline?

**Comment by suyograo** [comment]
@robbavey 👍 

`last_entry_timestamp`: not sure we need this. Turns out this was not very useful.

> Do we need to mark if dlq is not enabled for a pipeline?

Yes, that would be useful. we could do:

```
"dead_letter_queue": {
    "enabled": true|false
}
```

And skip stats if it is `false`.

> Getting current number of entries in the queue with the current DLQ implementation might be somewhat 'expensive' for queues with many segments (bulk of this expense most likely on startup/first stats call?)

Agreed. I do think the number of entries in the DLQ will be small, so this should be ok for now. I would do that on the first API call, not at LS startup. 

I think the actionable field here would be `current_queue_size_in_bytes` so users can alert on a DLQ which is filling and hasn't been purged.
