### ISSUE TITLE
Implement LIR Execution Using Janino

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#7358]
We decided to move the compilation of the pipeline from Ruby to Janino (as least where it's possible at this point). This issue is to track that effort as part of #7291.

**Comment by original-brownbear** [comment]
@andrewvc @ph FYI

**Comment by ph** [comment]
@original-brownbear Can you update this description? I believe we should thread Janino as an _unknown_ and we need a spike to understand better what we currently need to do. For me, I see that we need to explore the following the class loading/release of theses classes, potential leaks? Can you define a few goals that we want to test for this iteration?

Also, I am pretty sure we will hit other issues, our current implementation of the Logstash conditionals is mostly a straight 1:1 port to Ruby, I mean by that we are really flexible, and we depend at how the Ruby language handle a lot of things.

With that change, it might also be a good time to make sure we can report a better error to the users related to conditionals against `nil` values.

**Comment by original-brownbear** [comment]
@ph will do very soon :), still thinking about the not so small details here tbh.

**Comment by andrewvc** [comment]
IMHO the best place to do the spike would be compiling `Expression`. It's a relatively small surface area and is where most of the potential issues would lie.

Compiling the graph itself would be quite easy. You could just topographically sort it and then compile each vertex in the sorted list to something like:

```
vertex1Result = vertex1.execute(initialBatch)
vertex2Result = vertex1.execute(vertex1Result)
```

Obviously, there'd be more complexity and different signatures and interfaces, but that basic approach should be really fast since there would be no traversal of data structures to execute a pipeline.

It would also make flushing relatively easy, you could just compile a subgraph using the same methodology for each plugin that has flushing enabled.

**Comment by colinsurprenant** [comment]
It feels premature at this point to already tackle byte code generation? Isn't that an optimization once the overall expression evaluation is correctly working?

**Comment by ph** [comment]
@colinsurprenant this isn't clear in the issue description, but when we discussed that feature we come up with a few possible solutions:

- Use ruby directly
- Go with Nashorn
- Go with Painless
- bytecodes

At first, bytecodes seems a really hard goal to try. But with new tools or library like janino which just create Java class that will get compiled to bytecodes it seems that goal is not too far off. So we decided that its worth it to create a spike to see the complexity of it and also the time to put in place.

**Comment by ph** [comment]
@colinsurprenant also this will help us find any problem we might have with our data structure.

@original-brownbear @andrewvc we agree that we manage this as an experimentation to better understand our problem space, this doesn't necessary mean v1 will have bytecodes generation.

**Comment by andrewvc** [comment]
@colinsurprenant I wouldn't exactly characterize janino as bytecode generation in the sense that I suspect you're thinking of it, which is probably something along the lines of OW2 ASM.

Janino is just an in-memory java compiler, so this is more like transpilation, just with java as a target instead of ruby. Given that, I actually do think it makes sense as an initial approach, and will probably be comparable in terms of LOC/complexity to a naive interpreter.

**Comment by andrewvc** [comment]
And to clarify, I agree with @ph that this is all experimental at this stage.

I do think that Janino is where I'd place my bets at this point , both from the perspective of efficient execution *and* efficient delivery of the project. That being said, we'll know more after the initial spike :)

**Comment by colinsurprenant** [comment]
@andrewvc make sense. I was just concerned that this was more a potential optimization that could be tackled once we went through the first iteration(s) to first make it work correctly, compounded with the fact that I do not think that at this stage specifically optimizing expression evaluation will have an actual significant impact performance wise. But if Janito actually helps to achieve a *correct* implementation then I guess this is for the better.

**Comment by andrewvc** [comment]
@colinsurprenant yeah, I share your concern about making sure the first implementation is correct. The good news is that LIR was built with the idea that we would have Java bytecode as a target, which obviously translates well to java the language as the target, hence why expressions in LIR like `if ([event][foo])` compile to `NotNull(EventGet('[event][foo]'))`, which makes ruby's 'truthy' behavior explicit.

We should make sure that we also do a good job testing generated janino code against the existing implementation looking for discrepancies, but we would need that process with a new ruby target as well. One thing I wonder is if we need to use onigurama as the regex engine or if regular java regexps are fine. It's not a big deal either way, onigurama works fine from java, but its an interesting thing to consider.

WRT perf, in my POCs the expressions, to my surprise, were a performance issue with the java pipeline, I have reason to believe that was due to moving between ruby and java land. I hacked around this by making the generated expression ruby code operate on batches of events to amortize that cost (one method invocation per batch vs one invocation per event). Maybe there aren't significant gains beyond that, but it would be preferable, of course, to not have that extra concern (though I think it makes sense to batch expressions anyway, it should be more CPU cache friendly). 

So, the nice thing about a pure java approach is that it simplifies complexity from a performance standpoint since we have one less layer to worry about.

**Comment by colinsurprenant** [comment]
Totally agree in removing any Ruby moving parts from this.

**Comment by original-brownbear** [comment]
Bad(ish) news on this topic imo, without code-gen Java isn't all that great relative to Ruby here:

I was able to fix the Ruby execution in https://github.com/elastic/logstash/pull/8428 to be faster (meaning 15%+ faster in many cases) than the new Java one except for the case of using a lot of conditionals (those are much faster in the Java exec).

Looks like we'll need some codegen(ish) way here to invoke Ruby plugins more efficiently here to have the Java approach slow things down. Also, we could use codegen in to avoid the megamorphic callsites introduced in the `Dataset` APIs in https://github.com/elastic/logstash/pull/8357

**Comment by original-brownbear** [comment]
closing in favour of https://github.com/elastic/logstash/issues/8441
