### ISSUE TITLE
Logstash Centos rpm missing dependency on Java version

### ISSUE THREAD

**Issue by schwicke** [elastic/logstash#7459]
The logstash rpm for CentOS7 is missing a dependency on Java 1.8. It happily installs when Java 1.7 is present but logstash will fail to run. Adding a dependency on the required Java version would solve this issue. 

- Version: 5.4.1
- Operating System: CentOS7
- Config File (if you have sensitive info, please remove it): not relevant
- Sample Data: not relevant
- Steps to Reproduce: install default CentOS7 java version and the logstash rpm. This will not upgrade Java.

**Comment by untergeek** [comment]
This has been a sticky subject in _many_ discussions.  In short, the problem is that there are multiple Java versions, multiple OSes which can install from the same RPMs, and each handles the dependency differently (to say nothing of version matching), making it pretty much impossible to implement with any guarantees.

That is why we simply instruct the end user to ensure Java 8 is installed first, before installing Logstash, in our [official documentation](https://www.elastic.co/guide/en/logstash/current/installing-logstash.html).  As nice as it would be to make the dependency on Java work cleanly, disparities between OpenJDK and Oracle Java and how they report the existence of Java 8 on the various systems have forced us into this approach.  Feel free to peruse the issue history to find the other, lengthier discussions on the subject here in GitHub.
