### ISSUE TITLE
Fingerprint documentation is confusing

### ISSUE THREAD

**Issue by morgango** [elastic/logstash#7493]
The [documentation for the fingerprint filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-fingerprint.html) is very confusing.

- Is `key` the field that I need to populate?  If so, its importance isn't really noted.  If not, what is the important value that I need to know about?
- The description is essentially blank.  
- Is there an example of using this filter with one or more fields?

**Comment by jakelandis** [comment]
For all [methods](https://www.elastic.co/guide/en/logstash/current/plugins-filters-fingerprint.html#plugins-filters-fingerprint-method) but ```MURMUR3``` or ```UUID``` the key is required. The default is ```SHA1``` which requires a key. 

There is an outstanding bug : https://github.com/logstash-plugins/logstash-filter-fingerprint/issues/18 that should address the need to NOT use keys for simple (keyless) hashing. 

The key is really only important if you are trying to provide a means of [nonrepudiation](http://searchsecurity.techtarget.com/definition/nonrepudiation) which (imo) is only relevant w/r/t security. If you are only using the fingerprint for uniquness, I would still suggest using one of the hashing functions, such as ```SHA1```, since it will be tied to the data and likely more collision resistant then the non-crypto methods. 

Example with multiple fields:
```
input { stdin { } }
filter {
  fingerprint {
    key => "mysupersecretkeyhere"
    source => ["message", "@timestamp"] 
    }
  }
output {  stdout { codec => rubydebug }}
```

@morgango - Would you mind closing this issue and re-raising it as a [plugin issue](https://github.com/logstash-plugins/logstash-filter-fingerprint/issues).  I agree the documentation can be confusing.

**Comment by jordansissel** [comment]
Closing since this was moved to the fingerprint repo
