### ISSUE TITLE
Improved Metric type definitions

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#7509]
The current metric types are problematically loose in their use of types. For the purposes of charting we need different formulas for different conceptual things than we have in our current contract. Luckily our de-factor contract is mostly correct, but we need to tighten up the real interfaces. Where we should get to is:

* Counter - Currently this increments *and* decrements. It is only used in existing code for increment-only operations, things like `bytes_sent`. We should remove the ability to decrement (or increment by a negative), this will make charting counters dependable.
* Gauge - This is currently an object wrapper holding anything. This should change to be a double type that can increment, decrement, or be set to a new value. While there are some issues around incrementing doubles at some level we can document these. Doubles are accurate to 2^53, which is more than enough for everyone :-D. Users are free to use their own long object and record to a double if need be in the worst case.
* Text - String value that can only be set, useful for things like recording a protocol version etc.

**Comment by jakelandis** [comment]
Do you believe we should try to implement this as passively as possible (deprecation + bridge code), or simply implement the new typing as defined ?

**Comment by jakelandis** [comment]
@andrewvc 

```Gauge - This is currently an object wrapper holding anything. This should change to be a double type ``` 

Thinking about this some more, and I think we should continue to allow gauge to be a wrapper to anything _(at the the risk of not serializing properly)_.  While working on this issue I found existing gauges that are boolean, long, double, text, and ruby hashes (string to string mapping).  If we only concern ourselves (like we do today) with the simple get/set use case, we can wrap any type of object, which can be powerful.  

```that can increment, decrement, or be set to a new value.```

I think adding more functionality to the gauge is a slipperly slope and limits the ability to support any type for a guage. I agree that we should support double type counters (and have done so in the [PR](#7595)).  I am not sure we have the decremented use case yet, but it should be simple to add it in as new type (perhaps as a PolarCounter ?)

```Text - String value that can only be set, useful for things like recording a protocol version etc.```

Again if we keep gauge to be a wrapper to anything then we can keep this as a guage, and don't need a new type. 

What is not in the PR is the ability to (optionally) serialize the type as well, so that the consuming thing could have more information to make informed decisions on how/what to graph/display.  This would be pretty easy add in if desired.

For example:
"pipelines" : {
    "main" : {
      "events" : {
        "duration_in_millis" : 59,
...
Could optionally be:
"pipelines" : {
    "main" : {
      "events" : {
        "duration_in_millis" : {
          "type" : "counter/long",
          "value" : 59
        },

I believe all of this is illustrated in the [PR](#7595). 

Also note that this change is non-passive (no decrements, removal of the base class, and possible other subtle areas not yet found).  Ideally, this change would make the 6.0.0 cut, and all other changes should be able to be made passively.

**Comment by jakelandis** [comment]
>we should support double type counters

After further discussions, we don't currently have a use case for this, and a floating point counter is of questionable value.  WIDLIO

**Comment by andrewvc** [comment]
@jakelandis well, this all makes sense to me. I'm fine having gauge continue as a wrapper given the concrete subtypes.

WRT changes to the WEB API, I like that idea but we should scope them to another issue IMHO.

**Comment by jakelandis** [comment]
> WRT changes to the WEB API, I like that idea but we should scope them to another issue IMHO.

Agreed:
https://github.com/elastic/logstash/issues/7645 (expose type)

also related:
https://github.com/elastic/logstash/issues/7646 (expose unit)
