### ISSUE TITLE
review behaviour of Event.getTimestamp upon inexistent @timestamp field

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#7613]
The current `Event.getTimestamp` implementation throws an exception  if the `@timestamp` field does not exist, see:  https://github.com/elastic/logstash/blob/1152378b09c7722cfda162288bad5be66d4dc247/logstash-core/src/main/java/org/logstash/Event.java#L119

I believe the original idea was that not having `@timestamp` was indeed an error condition because when we introduced the `Timestamp`class we decided that an `Event` needed to always have a `@timestamp`. The problem is that this was never actually enforced in the code for field deletion and renaming and while this is generally not a problem, i.e. an `Event` **always** have a `@timestamp` field upon initialization and users *usually* don't remove that field, the `@timestamp` can be removed using a simple mutate filter like this:

```
mutate{rename => {"@timestamp" => "foo"}}
```

We need to think if we want to either double-down on the idea of an always-valid `@timestamp` in the `Event` which mean that throwing an exception would be valid or accepting that an `Event` could not have a `@timestamp` field in which case we should remove the exception throwing and replace that probably with a `null` value return.

**Comment by danhermann** [comment]
If `Event` should have as an invariant that its `@timestamp` field is never null, then each of its methods that can mutate fields should ensure that the `@timestamp` field can be neither deleted nor set to null. Throwing an exception (and especially an `IOException` since it is entirely unrelated to IO) is not a good way of handling that.

As part of extracting the `Event` API for use with Java plugins in https://github.com/elastic/logstash/pull/10232, I eliminated the `IOException` on the `getTimestamp` method and ensured that all its callers would properly handle a `null` return value.
