### ISSUE TITLE
Build verbosity can lead to ci job failures on travis?

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#7739]
Lately there are many DEBUG level messages being printed during CI tests, so much that logs can be many megabytes, causing travis to not show everything, even in raw form https://travis-ci.org/elastic/logstash/jobs/255092890#L9475

Could this be from a recent fix of log4j2 logging?

**Comment by jakelandis** [comment]
Hmm... it may be related.  I have a theory that maybe a test is leaving the logger(s) in a debug state.  The extra logging _shouldn't_ cause failures, but should be addressed.  

I will take a look.

**Comment by jakelandis** [comment]
With the changes over at https://github.com/elastic/logstash/pull/7528 that fixes the logging from Java, we now re-use Java's default logging context.

Prior to that change there were 2 contexts in use.  One for Ruby (initialized by Ruby), and the other used for Java (initialized with the JVM).  Only the Ruby context worked as expected, the fix to get Java logging to work was to allow Ruby to re-use the Java context instead of initializing a new one.   

Now that we only have 1 context, initialized by Java at startup, AND the rspecs are running inside the same JVM, the logging levels will bleed over from test to test since the rspecs are only starting / initializing Logstash at the Ruby level (e.g. not spinning up a whole JVM each time).  

The fix here will be to ensure that after each test that changes the log level we set it back to ```info``` level.

**Comment by original-brownbear** [comment]
@jakelandis @jsvd +1 to this issue https://github.com/elastic/logstash/issues/7679 :)
