### ISSUE TITLE
[discuss] stalled filter or output

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#7763]
We know a filter or output plugin can stall. When this happen we usually realize it upon shutdown when the `ShutdownWatcher` starts logging about it.

With Persistent Queue, one nasty side effect is that when a filter or output stalls and never closes its inflight batch, the page file where that batch events are read from will never be fully acked and will be kept around until the plugin un-stalls or LS is shutdown. 

The second nasty side effect to this is that in the case of an abnormal shutdown which has good chances to happen since a plugin is stalled and LS will need to be forced stop,  all the events **after** that batch in the page file will also be replayed. 

In a normal situation where all the plugins continuously process batches without actually stalling, this is not a big problem since all batches acking is continuously flowing forward and no particular batch should lag too much behind. 

I would like to open the discussion on plugin stalls and see how we could mitigate it. The pipeline is totally capable of identifying a stalled plugin. Now, what can be done about it is not so trivial. 

We know that one does not just kill a thread, if we could, I'd be easy to kill that worker thread and restart a new one with it's in-flight batch. On the other hand, it could be possible to flag a worker thread as being stalled so that if it ever resume, it would stop its processing and kill itself. 

With this idea we could have a worker watcher that looks for stalled workers and flag it as stalled and spin a new one with the stalled worker in-flight batch. If we reach a threshold of stalled worker (rate? total number?) we could shutdown logstash, for example. 

WDYT?

**Comment by colinsurprenant** [comment]
Issue #7538 is an example of a stalled plugin and a lingering PQ page.

**Comment by jordansissel** [comment]
This sounds kind of like a [halting problem](https://en.wikipedia.org/wiki/Halting_problem) scenario. If we detect a worker being stalled[1], we may not be able to detect why it stalled. Therefore, I am unconvinced that we can have code attempt to recover from the stall because we don't know what is causing the stall.

[1] for whatever we define 'stalled' to mean

So some thoughts in no particular order:

* If we detect a stall, we can flag the worker, but I don't know what other corrective action could be taken because we don't know why it stalled.
* I am not sure what value there is in killing a stalled-and-later-recovered worker after it has recovered from the stall.

> one nasty side effect is that when a filter or output stalls and never closes its inflight batch

This seems like a feature (avoid data loss), not a bug, to me.

>  all the events after that batch in the page file will also be replayed.

This seems like a bug. We wanted to support out-of-order acks for batches in the PQ, so this behavior (already-acked batches are replayed) feels like the bug.

Maybe the corrective action could be to DLQ the whole stalled batch? More specifically, this order of actions:

1) A worker is detected as stalled (whatever we define stalled to mean)
2) That worker's current batch is written to the DLQ
3) That worker's batch is then ack'd

Consequences of the above proposal:

At some later time, that worker *might* finish the batch and ack it, in which case we have data in the DLQ that was actually delivered successfully. 

Alternate proposal:

1) Same as above
2) We append the batch to the end of the queue.
3) We ack the current batch.
4) Another worker picks up that batch and tries again.

Consequences with the above proposal:

If a batch contains a poison event, then giving the poison batch to another healthy worker will make it a stalled worker and eventually cause all workers to be stalled and Logstash will completely stall.

----

I'm open to other ideas.

**Comment by colinsurprenant** [comment]
Thanks @jordansissel for your input, I mostly agree with you and also think DLQ is part of the solution. I think I may have not correctly explained some of my thoughts, let me clarify.

- First, a stall for me is just that: a worker does not complete a cycle in a given amount of time. I have no idea what that time is: 100ms? 1 second? 10 seconds? I am not sure, we can discuss that specifically.

> If we detect a stall, we can flag the worker, but I don't know what other corrective action could be taken because we don't know why it stalled, and specifically how to prevent future stalls.

Yes, we can flag a worker to avoid it acknowledging a batch we decided to either DLQ or hand to another worker if we decided the plugin is stalled. Let me illustrate: this is the current simplified worker process : 

```
1- read batch
2- filter batch
3- output batch
4- ack batch
```

A stall can happen in (2) and (3). Let's say the pipeline decides that a worker is stalled, it can set a `stalled` flag for that worker and DLQ that batch. If the plugin never resumes then its a *non-issue* WRT to the batch, but if it does we could minimize double processing with schematically something like that:

```
1- read batch
2- filter batch
  2.1- abort if stalled
3- output batch
  3.1- abort if stalled
4- ack batch
```

> We wanted to support out-of-order acks for batches in the PQ, so this behavior (already-acked batches are replayed) feels like the bug.

Let me clarify: this was a conscious tradeoff we made by leveraging our at-least-once guarantees and to simplify the model: we only need to keep track of the first unacked seqnum pointer into a page. In a *non-stalling* situation, this is practically not a problem. But a stalled unacked batch means that all other events after that batch, in that page, will be replayed but again in **an abnormal shutdown situation**.

So yes, as you suggested, I believe that DLQing and acking the batch upon stall detection is the thing to do to avoid the poison batch problem and I think we can probably add something like a `stalled` flag to avoid double processing.

**Comment by andrewvc** [comment]
I chatted with @jordansissel and @colinsurprenant  about this directly yesterday, putting those comments here where they can be part of the real thread here.

The summary of it is that we should define what a 'stall' is.I think there may be some confusion there, the term stall there usually refers to some sort of backpressure, like, if ES is down the ES output will ‘stall’ on the current batch forever until it comes back up.

This is correct for the in-memory queue so we don’t lose data, but could be interruptible for the PQ. However if we mean stall to mean the plugin can't make progress for an internal reason  that’s not really what’s usually going on Logstash plugins should only stop making progress if an external IO dependency is in a temporarily down state (like a broken connection) that could be fixed (by reconnecting the server on the other end for example, or trying another host). Anything else could be considered bad data and should be sent to the DLQ ASAP.

So, the short version is, when 'stall detection' feature was added the intention to notify the user what was stuck when a shutdown couldn't proceed due to an output or filter not being able to make progress, usually for legitimate reasons as shown above.  Without this feature, you’d wonder why LS wouldn’t shutdown, and wouldn’t know to check your ES instance, for instance, to make sure that it was still up (or to check your logstash logs where you'd see connection errors).

In hindsight maybe we should have used the term ‘blocked’ instead of ‘stalled’.

WRT the more queue related issue of a single batch not being ACKed but subsequent batches being ACKed this is usually quite rare. The only way this can happen is if N-M workers get stuck, where N is the total number of workers and M is the number of blocked ones. This is most likely to happen if there is a config that outputs to both, say, HTTP and ES, and 99.999% of events go to ES, while 0.001% of events go to say, HTTP. If the HTTP endpoint is down, and a single rare event goes through then one worker will be stuck while others will be functional. Of course, if more HTTP events come through eventually all workers will be blocked.

I think the best solution here might be to find a way to let users insert additionally queues into the config graph before components they'd like to decouple. For instance, it might make sense for most people to put queues in front of outputs if they have >1 output. Or to put a queue in front of the elasticsearch filter. This would require significant config-level changes to LS of course. You can kinda approximate this with multiple pipelines but it gets ugly fast.

**Comment by andrewvc** [comment]
I'll add we did have real stalls in the grok filter with REDOS, but ever since we added a timeout to groks that has gone away AFAIK, and I'm not aware of other filters that get stuck on a tight inner loop.

**Comment by colinsurprenant** [comment]
> WRT the more queue related issue of a single batch not being ACKed but subsequent batches being ACKed this is usually quite rare. The only way this can happen is if N-M workers get stuck, where N is the total number of workers and M is the number of blocked ones. This is most likely to happen if there is a config that outputs to both, say, HTTP and ES, and 99.999% of events go to ES, while 0.001% of events go to say, HTTP. If the HTTP endpoint is down, and a single rare event goes through then one worker will be stuck while others will be functional. Of course, if more HTTP events come through eventually all workers will be blocked.

This is not taking into account scenarios of *poison* batches where a worker would be stuck at the filter or output because of the actual batch content. This could happen infrequently but have the effect of keeping that batch unacked (which is fine) for potentially a very long time if this problem is not identified and something done about it. Currently LS will not tell you that a worker is stuck and the only way to fix it if/when you realize it is to restart logstash. I think this situation could be avoided since the pipeline could detect this condition and minimally push out error logs or even *fix* the condition as per the suggestions above. 

I agree we have to reason about the output back pressure situation. Without PQ and DLQ, it made/makes total sense for outputs to block and incidentally propagate back pressure because the only other option would be to drop data on the floor to keep the spice flowing.

> I think the best solution here might be to find a way to let users insert additionally queues into the config graph before components they'd like to decouple

Sure, definitely worth discussing but this is a long(er) term vision. I'd like to see how we can iterate in the short term in a pragmatic way to improve the current design.

**Comment by andrewvc** [comment]
@colinsurprenant can you provide some examples of poison batches / events?

**Comment by colinsurprenant** [comment]
@andrewvc any stall induced by the content of an event itself, same idea as a poison event/batch which triggers a bug.

**Comment by andrewvc** [comment]
@colinsurprenant yeah, I'm curious if we have any concrete examples

**Comment by colinsurprenant** [comment]
@andrewvc well, it's a little bit like asking to see a bug before it's discovered. But the fact is that we know this can happen per the grok example, it happened there, it could happen elsewhere. For me I feel it is easy to see that a filter could hang in some way because of its input. We know a crash can happen and a hang is probably more marginal but a serious condition nonetheless. It could be from a poison event, and it could be happening in a library code we don't control. But it could also be because of a transient IO/network condition? I guess anything which does a socket connection (DNS filter?) with a poorly connection timeout handling? ... an example on top of my head.

**Comment by colinsurprenant** [comment]
So from another angle, I am saying: we have provisions in the pipeline to deal with bugs and exceptions in plugins because we know bugs/exceptions scenarios will happen that won't be dealt with in the plugin. Why no put in place something that will deal with potential stalls in a similar way?  

I understand it is not trivial and we still need to reason about the blocking output & back pressure condition though.

**Comment by jordansissel** [comment]
@andrwevc, @colinsurprenant, and I talked on Zoom about this issue and we came up with some ideas to explore. @colinsurprenant will file an issue soon with details.

**Comment by colinsurprenant** [comment]
Filed followup issue #7796 - closing this one.
