### ISSUE TITLE
"Lazy" Flag in org.logstash.instrument.metrics.counter.LongCounter Deteriorates Performance

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#7935]
This line (and hence that patch) https://github.com/elastic/logstash/pull/7872/files#diff-c08ac103577f611066ab7e0876756088R72

```diff
         longAdder.add(by);
+        dirty = true;
      }	
```

has a very detrimental impact on the metrics overhead since `dirty` is a `volatile`.
Adding a hot write to a `volatile` is kind of a nasty anti-pattern and we should fix this some other way.
On trivial approach that comes to mind is simply making `dirty` `AtomicLong` and simply setting it to the counter value on `setDirty(false)` and setting it to `-1` on `setDirty(true)`.
Then `getDirty` simply becomes `return longAdder.longValue() != dirty.get()` and we get the same behavior without messing with with the performance of `public void increment(long by)` in any way whatsoever? :)

In numbers, this is a `~10%` hit on `baseline` benchmark run.

**Comment by original-brownbear** [comment]
@andrewvc @jakelandis FYI that's what I was talking about in Slack :)

**Comment by jakelandis** [comment]
@original-brownbear - I believe you, but am confused.  I have never heard of a volatile breaking inlining, or assignment of a boolean causing a performance issue.

Can you help me understand what is happening here with JIT compiler? On the surface it sounds like a bug in Java.

**Comment by jakelandis** [comment]
We spoke on Slack and cleared up some of my misunderstandings around `volatile` in hot code.  Basically it gets deep into the ability for the JIT compiler to optimize and how the CPU memory caches work. Reading a `volatile` in the hot code _should_ be OK, but writing can cause performance issues. I believe that the deep JRuby stacks here may play a part in how large this is a performance issue.

In this particular case, we can simply remove the `volatile` since it is not protecting something that needs to be critically correct. This flag controls if a metrics value will be serialized or not. The only consequence of removing the `volatile` is that the serialization output may stale by for a very short period of time, and that is OK.

**Comment by original-brownbear** [comment]
@jakelandis perfect + I just tested this without `volatile` and it seems that makes this change performance neutral => let's just remove the `volatile` :)
