### ISSUE TITLE
Describe heuristics used to flag problem areas in pipeline viewer

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#7977]
Pipeline docs need to describe heuristic used to flag problem areas. See

https://github.com/elastic/logstash/pull/7966#discussion_r132370138

@andrewvc Can you post the heuristics here so I can update the docs? I saw your formula in the demo you gave, but not sure if we want to give that exact formula.

**Comment by andrewvc** [comment]
The Logstash pipeline viewer highlights CPU%, and event latency in cases where the values are anomalous. The purpose of these highlights is to enable users to quickly be able to identify things that are disproportionately slow. This may not necessarily mean that anything is wrong with a given plugin, since some plugins are slower than others due to the nature of the work they do. For instance, you may find that a grok filter using a complicated regexp runs a lot slower than a mutate filter that simply adds a field. The grok filter might be highlighted in this case, though it may not be possible to further optimize its work.

**Comment by dedemorton** [comment]
Closed via #8368.
