### ISSUE TITLE
Bullet content missing in LS intro docs

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#8049]
The bulleted content at the bottom "Choosing Your Stash" section is missing. https://www.elastic.co/guide/en/logstash/5.5/introduction.html

![image](https://user-images.githubusercontent.com/13039544/29581214-79bf0cd6-872d-11e7-9c64-357cfab4b6d4.png)

**Comment by dedemorton** [comment]
This should be resolved in the next build. The tl;dr is that we recently started using asciidoc attributes to resolve paths in this table (to support translations) and the attributes no longer resolved because there's some odd interaction when you use bullet points in a table with asciidoc attributes. I've changed the formatting to fix the problems.

What's baffling is that I'm pretty sure I saw these reference working a couple weeks ago when I fixed a related problem.

**Comment by acchen97** [comment]
@dedemorton thanks for chasing this down so quickly!
