### ISSUE TITLE
Error: No log4j2 file found

### ISSUE THREAD

**Issue by GaofyDev** [elastic/logstash#8054]
I'm a beginner at logstash. Everytime I start the logstash, an error warning comes up, even if the logstash works succeffully:
`ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Sending Logstash's logs to /var/log/logstash which is now configured via log4j2.properties`

What's the problem and how to fix it? 
Environment: Ubuntu server 16.0.2, logstash 5.5.2
Thanks.

**Comment by jakelandis** [comment]
@GaofyDev - Thanks for reporting this. It's already fixed, but the fix is not part of GA release yet. 

The error message is benign and can be ignored.

This will be fixed in 5.6+ _(soon to be released)_ as part of https://github.com/elastic/logstash/issues/7526 

Also feel free to try out [6.0.0-beta](https://www.elastic.co/downloads/logstash#preview-release), it is fixed there too. 

Closing issue.
