### ISSUE TITLE
Plugin documentation does not have DLQ references yet

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#8080]
The statement [here](https://www.elastic.co/guide/en/logstash/5.6/dead-letter-queues.html#dead-letter-queues) appears to be a bit premature:

>The dead letter queue feature is currently supported for the elasticsearch output only. Support for additional outputs will be available in future releases of the Logstash plugins. Before configuring Logstash to use this feature, refer to the output plugin documentation to verify that the plugin supports the dead letter queue feature.

"Before configuring Logstash to use this feature, refer to the output plugin documentation to verify that the plugin supports the dead letter queue feature.".  Even in the ES output plugin documentation, there's no mention of DLQ or its support for it.  Maybe we can remove the 3rd sentence until we have additional plugins (and corresponding documentation) that support it.

**Comment by dedemorton** [comment]
Closing because the docs are added in https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/670. Unfortunately the docs didn't get updated before the 5.6 freeze, so the changes won't be available immediately in the published docs. It's a little funky as-is, but since we mention only support the ES output at this point, I think it's OK.
