### ISSUE TITLE
Timestamp Values are not Correctly Serialized for all Keys 

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#8128]
Currently, this does not work:

```java
        Event e = new Event();
        final Timestamp timestamp = new Timestamp();
        e.setField("tsfoo", timestamp);
        Event er = Event.deserialize(e.serialize());
        assertEquals(timestamp, er.getField("tsfoo"));
```

it throws

```java
java.lang.AssertionError: expected: org.logstash.Timestamp<2017-09-03T07:49:53.853Z> but was: java.lang.String<2017-09-03T07:49:53.853Z>
Expected :org.logstash.Timestamp<2017-09-03T07:49:53.853Z> 
Actual   :java.lang.String<2017-09-03T07:49:53.853Z>
```

The reason for this is that we're using a simple `JsonSerializer` without type information to serialize it.

```java
public class TimestampSerializer extends JsonSerializer<Timestamp> {

    @Override
    public void serialize(Timestamp value, JsonGenerator jgen, SerializerProvider provider)
            throws IOException
    {
        jgen.writeString(value.toString());
    }
}
```

This is not caused by c8b8b6bf6 (I verified that :)) => we can't fix this by the Java serialization route (the Java route we had there wasn't ever used even because of the registered `JsonSerializer`).
This should be fixed by registering a typed serializer for the CBOR (Json cannot be typed because it'll break ES output as far as I understand) serialization path.
Currently, this would break any input that puts a `Timestamp` field and passes PQ.

**Comment by jordansissel** [comment]
It's not clear if we need or want to support timestamp types on any field
other than @timestamp.

**Comment by original-brownbear** [comment]
@jordansissel great timing :D I just found the fix to this. The fix comes with a neat sped-up either way though.

That said if we don't support timestamp for any other field, we should translate that into some code simplifications in `Valuefier` etc. 


* As the code currently works it def pretends to do this, it's just broken
* We should def remove `Timestamp` from `Valuefier` to not create different behaviour between PQ enabled and disabled right?

**Comment by andrewvc** [comment]
I am in favor of supporting timestamp for arbitrary fields. This is a requirement for multi-stage (across multiple queues) processing. The `date` filter would be essentially broken without this.

Additionally, this is a requirement for `logstash->logstash` comms. Timestamps should work in a distributed setting.

**Comment by jordansissel** [comment]
> This is a requirement for multi-stage 

@andrewvc Can you detail what you mean? I'm not following. 

----

Thinking about things, this is how I see it: Types are useful in that they carry functionality. If a user has a field "foo" with a timestamp value, what functionality can they do with it? Nothing today? TIme formatting with `%{+TIME FORMAT}` only acts on `@timestamp`. You coudl do math, but now you're burdened by writing custom code in the the Ruby or script filters.

I'm not sure what you mean with respect to "date filter would be broken" -- the date filter for many years only supported writing in to `@timestamp` and only recently allows specifying a target field, for example.

If we want to embrace timestamp as a field value type, then we should consider, at a minimum, enhancing the time formatting `%{+...}` to allow choosing a field other than `@timestamp`.

I'm open to whatever, but step needs to be more detailed than encouraging any field to contain a Timestamp value -- otherwise users won't' be able to make use of it.

**Comment by andrewvc** [comment]
@jordansissel those are all good points.

The best use case I can think of for dates in multiple fields today, is it is the only way to normalize dates and time when interacting with external systems. For instance, if outputting to an RDBMS, you may have multiple date fields. Usually the DB driver will take a `java.sql.Date` class. Having an explicit `Timestamp` class gives a blessed normalize thing to pass around the processing pipeline before then. The same is true of Elasticsearch. While the date ultimately is text in that case as well, the job of formatting the date should be left up to the output, not some intermediate process IMHO.

OTOH, this stuff largely works today without that ability. If that's the direction we want to continue to go, I would argue that `event.set('foo', ::LogStash::Timestamp.new)` should be forced to write out the timestamp as a string (with a specific formatting option). The `Event` class shouldn't allow fields to be set to non-serializable fields.
