### ISSUE TITLE
ArcSight module doc enhancement

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#8348]
For the [ArcSight module docs](https://www.elastic.co/guide/en/logstash/current/arcsight-module.html), we should replace the first two architecture diagrams with these two below.

https://www.elastic.co/assets/bltccd56f0fc1beeddd/arcsight-diagram-smart-connectors.svg
https://www.elastic.co/assets/blt81f02fcfcd96cf34/arcsight-diagram-adp.svg

/cc @suyograo

**Comment by jordansissel** [comment]
@acchen97 in these images, the data flows from right-to-left. I think most of our diagrams flow left-to-right (data source on left, processing in middle, storage on right).

Can these be mirrored to have a left-to-right flow?

The current images use a bottom-to-top data flow which also feels awkward to me, so maybe my criticism here is invalid because I am preferring left-to-right or top-to-bottom flow (follows english writing direction) and neither the proposed nor the current diagrams use these directions. 

Thoughts?

**Comment by acchen97** [comment]
@asawariS @hstephenson thoughts on @jordansissel comment above? I figured these diagrams we made for the landing page would fit better in the docs as well since we split it up into the two getting started sections ([smart connector](https://www.elastic.co/guide/en/logstash/5.6/arcsight-module.html#arcsight-getting-started-smartconnector) and event broker). The other diagram takes up too much vertical real estate now imo.

**Comment by asawariS** [comment]
In general, I completely agree with the left to right convention. In this specific case, I am ambivalent though because there's only 1 arrow. Mirroring the image to go left to right should be fairly easy without any impact.

On the bottom to top convention, this one is trickier because we are leveraging the stack diagram, with the visualization layer on top. For that reason and because we are not explicitly showing flow here, I would vote for not changing the vertical  order. 

if this works, I can open a ticket to flip left-right order and replace the image on the web for consistency. 

cc @hstephenson @acchen97 @jordansissel

**Comment by acchen97** [comment]
@asawariS ++ if you may, can you please open a ticket for that? Another benefit for using these diagrams here instead is that users will already be familiar with them if they saw the landing page prior to the docs.

**Comment by asawariS** [comment]
@acchen97 @jordansissel updated visuals here: https://elasticsearch.app.box.com/folder/36907774763
(I will open ticket to update the [/arcsight ](http://elastic.co/arcsight )page

I assume you will handle getting things updated on the docs side.

**Comment by dedemorton** [comment]
I'll take care of the docs. I already have a PR open. Thanks!!

**Comment by dedemorton** [comment]
@asawariS I don't seem to have access to box. Do I need to request access?

**Comment by asawariS** [comment]
@dedemorton thanks! try this: https://elasticsearch.box.com/s/8hvah6p8bnr9l7ktydk1x6zuf7ztdjmv

(also realized the only "smart connectors" version needs updating. I think it should in that same folder later today / tomorrow. )

**Comment by dedemorton** [comment]
@asawariS Looks like the smart connectors image hasn't been updated yet? Or maybe it's somewhere else? Here's where I'm looking:

https://elasticsearch.app.box.com/s/8hvah6p8bnr9l7ktydk1x6zuf7ztdjmv/file/222312203438

Thanks!

**Comment by asawariS** [comment]
ha yes, @dedemorton -- I mentioned that to Adrian on the web ticket this morning. Stay tuned

https://github.com/elastic/Design/issues/609#issuecomment-333182577

**Comment by asawariS** [comment]
@dedemorton updated images

[smart connectors](https://elasticsearch.box.com/s/psc07klbgl0ekcko4bim3z5u6rrj0442). 
[Event broker](https://elasticsearch.box.com/s/fr6osnitb9kyt4ru1bwahq9tk363d6q2).

**Comment by dedemorton** [comment]
Closing because these images are now in the dos.
