### ISSUE TITLE
pipeline.queue.events is updated only after logstash restart

### ISSUE THREAD

**Issue by dandrestor** [elastic/logstash#8382]
The monitoring API value `pipeline.queue.events` does not update while logstash is up, only after restarting the daemon. This applies to logstash running with the persistent queue option enabled.

See https://discuss.elastic.co/t/monitoring-api-value-is-updated-only-after-logstash-restart/100971

- Version: 5.5.2
- Operating System: RHEL 7

**Comment by coolprag** [comment]
hi...any updates on this? Another customer is complaining about the persistent event count not getting updated until logstash is restarted. Is there a work around for this?

**Comment by jordansissel** [comment]
I tried to reproduce this, but it works for me:

```
% while true; do ; date; curl -s localhost:9600/_node/stats/pipeline?pretty | jq .pipeline.queue.events; sleep 1; done
Fri Oct  6 13:48:42 PDT 2017
2995072
Fri Oct  6 13:48:43 PDT 2017
2995072
Fri Oct  6 13:48:44 PDT 2017
2995072
Fri Oct  6 13:48:45 PDT 2017
2995072
Fri Oct  6 13:48:46 PDT 2017
2995072
Fri Oct  6 13:48:47 PDT 2017
3225442
Fri Oct  6 13:48:48 PDT 2017
3225442
Fri Oct  6 13:48:49 PDT 2017
3225442
Fri Oct  6 13:48:50 PDT 2017
3225442
Fri Oct  6 13:48:51 PDT 2017
3454222
Fri Oct  6 13:48:52 PDT 2017
3454222
Fri Oct  6 13:48:53 PDT 2017
3454222
Fri Oct  6 13:48:54 PDT 2017
3454222
Fri Oct  6 13:48:56 PDT 2017
3454222
Fri Oct  6 13:48:57 PDT 2017
3681497
Fri Oct  6 13:48:58 PDT 2017
3681497
```

It appears to not "increment" every time I query, but it is incrementing. Every 5-10 seconds the value is updated with a new value.

**Comment by jakelandis** [comment]
hmm... i was able to reproduce this with the pipe and stdin input, but not the TCP input. 

I am taking a deeper look.

**Comment by dandrestor** [comment]
Just a wild guess, but perhaps it happens when more than just one input plugin is used? @jordansissel What configuration did you test with?

**Comment by jakelandis** [comment]
OK.... figured it out. It only happens when you have XPack installed, and even then it is not guaranteed. 

Basically when X-Pack is installed a hidden pipeline `.monitoring-logstash` is running too. So even with only 1 pipeline defined with X-Pack there is actually 2 pipelines running internally. The problem is that our code assumes only 1 pipeline, and is simply picking the first one out of the list. 

If  `.monitoring-logstash` is happens to be the first in the list, we are trying to pull the PQ metrics from that pipeline which is incorrect. 

Incidentally, this also discovered in bug in 6.0.0 monitoring where as a user you can define multiple pipelines with PQ and due to this bug it will only monitor the first one. I believe that this is also impacts the DeadLetterQueue as well. 

I will submit a PR to fix soon.

**Comment by jakelandis** [comment]
This fix will be out in 5.6.4. (not released yet)

------
Disclaimer - Patching production code via copy and paste is not recommended, not supported, and generally a very bad idea.

...but if you were to patch your production code via copy paste...

```
In this file: <path_to_logstash>/logstash-core/lib/logstash/instrument/periodic_poller/pq.rb (or dlq.rb )

Find this line:
  pipeline_id, pipeline = @agent.running_pipelines.first
  
Change it to:  
  pipeline_id, pipeline = @agent.running_pipelines.sort_by { |id, p| id }.reverse!.first
```

Note - the ^^ code change doesn't take into pipeline names that may not sort as expected (like starting with non-alpha characters). The official fix will work fine with any pipeline names.

**Comment by jakelandis** [comment]
Jake Landis merged this into the following branches!

Branch | Commits
-------|--------
5.6 | 61638a59cd1dfce60f6fd62abc05741b49f1f9b0

**Comment by dandrestor** [comment]
Brilliant! Thanks @jakelandis
