### ISSUE TITLE
Remove custom serializers/de-serializers for bigint and bignum

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#8387]
As introduced in https://github.com/elastic/logstash/pull/8205, it appears that this may be superseded by a newer version of Jackson that properly supports those types, as evident by this comment : https://github.com/elastic/logstash/issues/8379#issuecomment-332010164. 

Jackson 2.9.1 is introduced with PR https://github.com/elastic/logstash/pull/8373

I _think_ we can remove these custom serialization. 

cc/ @original-brownbear

**Comment by original-brownbear** [comment]
@jakelandis we can't remove the custom serializers because those serialize the Ruby wrappers, not the Java classes.

What we can do with `2.9.1` though, is use the native ability to serialize the large numeric types to speed things up (at least I'd hope that whatever Jackson added is faster than just serializing as `String` :)). I'll look into that next week, should be trivial.

**Comment by colinsurprenant** [comment]
done in #8405
