### ISSUE TITLE
filter duration problem

### ISSUE THREAD

**Issue by kiwi0217** [elastic/logstash#8403]
I really don't know how to write the filter to get user online's time like 2017-09-27-14:25:15 - 2017-09-27-14:24:41

|2017-09-27-14:24:41|INFO|JupyterHub|User logged in: jupyter|
......
|2017-09-27-14:25:15|INFO|JupyterHub|User logged out: jupyter|
and i will got logged in repeat like
.....
|2017-09-27-14:27:30|INFO|JupyterHub|User logged in: jupyter|
.....
|2017-09-27-14:30:31|INFO|JupyterHub|User logged out: jupyter|

**Comment by jakelandis** [comment]
@kiwi0217 - This doesn't sound an issue with Logstash, I will close this issue. 

Please re-direct questions to our Forum: https://discuss.elastic.co/c/logstash you will get many more eyes on your issue. 

That said, your question may be better suited for Kibana: https://discuss.elastic.co/c/kibana (e.g. maybe do this in ES/Kibana instead of Logstash ?)
