### ISSUE TITLE
Netflow module is not reading flow data  on udp46

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#8640]
- Version: 6.0.0-25bd7392
- Operating System: Mac
- Steps to Reproduce:

I verified that these steps DO work on 5.6.4, but DO NOT work on 6.0.0 (BC2).

1 - Run the netflow module:
```
bin/logstash --modules netflow --setup -M netflow.var.input.udp.port=2055
```
2 - Run [softflowd](https://code.google.com/archive/p/softflowd/) and pass in a PCAP:
```
./softflowd -r /Users/dedemorton/BuildTesting/Data/test_netflow/smallFlows.pcap -n localhost:2055
```

Not sure if this is related, but it looks like LS version 6.0.0 is listening for `udp4` instead of `upd46`.

Taken when 5.6.4 was running:
```                         
$ netstat -an | grep 2055
udp46      0      0  *.2055                 *.*  
``` 

Taken when 6.0.0 was running:
```
$ netstat -an | grep 2055
udp4       0      0  *.2055                 *.*    
 ``` 

Incidentally, here is the output when I run softflowd:

```
$ ./softflowd -r /Users/dedemorton/BuildTesting/Data/test_netflow/smallFlows.pcap -n localhost:2055
softflowd v0.9.9 starting data collection
Exporting flows to [::1]:iop
Shutting down after pcap EOF
Shutting down on user request
Number of active flows: 0
Packets processed: 14243
Fragments: 0
Ignored packets: 18 (18 non-IP, 0 too short)
Flows expired: 636 (0 forced)
Flows exported: 1209 in 41 packets (0 failures)

Expired flow statistics:  minimum       average       maximum
  Flow bytes:                  40         14176        510726
  Flow packets:                 1            22           524
  Duration:                  0.00s        21.07s       258.52s

Expired flow reasons:
       tcp =         0   tcp.rst =         0   tcp.fin =         0
       udp =         0      icmp =         0   general =         0
   maxlife =         0
over 2 GiB =         0
  maxflows =         0
   flushed =       636

Per-protocol statistics:     Octets      Packets   Avg Life    Max Life
           icmp (1):           4602           34      31.44s     112.03s
            tcp (6):        8943270        13708      20.43s     258.52s
           udp (17):          68339          501      22.92s     177.18s
```

**Comment by ycombinator** [comment]
Just wanted to add some more details from what I observed as well:

Notice that `softflowd` is being run with `-n localhost:2055`. The `softflowd` tool (or OS, not sure) is resolving `localhost` to `::1`, the IPv6 address. You can see this in the 2nd line out of output from running the `softflowd` tool:

```
Exporting flows to [::1]:iop
```

Since the 6.0.0 version of Logstash is not listening on `udp46` but only on `udp4`, the packets from `softflowd` aren't reaching Logstash. I was able to verify this by running `softflowd` with `-n 0.0.0.0:2055` instead of `-n localhost:2055` and everything worked as expected after that (the `netflow-*` indices were created and documents were indexed into them).

**Comment by ycombinator** [comment]
I wonder if this comes down to a regression in the UDP input? I ran `./bin/logstash -e 'input { udp { port => 4321 } }'` with 6.0.0 Logstash. Then `netstat -an | grep 4321` reports:

```
udp4       0      0  *.4321                 *.*
```

@dede is running the same with 5.6.4 (since she already has it setup) and will report her findings here.

**Comment by dedemorton** [comment]
When I run the same command on with LS 5.6.4 running, I see:
```
udp46      0      0  *.4321 
```

**Comment by ycombinator** [comment]
If it matters, all these commands were run on OSX.

**Comment by jordansissel** [comment]
Same version of udp input is in v5.6.3 and 6.0:

* 6.0: Gemfile.jruby-2.3.lock.release:    logstash-input-udp (3.1.2)
* 5.6.3: Gemfile.jruby-1.9.lock.release:    logstash-input-udp (3.1.2)

**Comment by jordansissel** [comment]
I'm doing some digging, bear with me ;)

**Comment by jordansissel** [comment]
This is a bug in the udp input that is trigged due to Logstash 6.x's upgrade to JRuby 9.x

https://github.com/logstash-plugins/logstash-input-udp/blob/master/lib/logstash/inputs/udp.rb#L72

```
    @udp = UDPSocket.new(Socket::AF_INET)
```

This instructs the OS to create an IPv4 socket, and somehow on JRuby 1.7.x (Logstash 5.x uses this) makes this bind to ipv6.

I can reproduce this in JRuby shell directly. 

I can write a patch to fix this, but it's too late to fix the code for 6.0.0's release time. As a workaround, we can maybe focus our examples documentation to use ipv4 directly (instead of localhost, use 127.0.0.1).

**Comment by jordansissel** [comment]
Bug fix: https://github.com/logstash-plugins/logstash-input-udp/pull/31

**Comment by dedemorton** [comment]
Closing because this issue is very old. Please feel free to reopen if it's still valid.
