### ISSUE TITLE
Dead letter queue not sending syslog events to output server. 

### ISSUE THREAD

**Issue by vishal0708gautam** [elastic/logstash#8710]
Hello Experts,

We are using logstash as syslog receiver and forwarder both is done using TCP & UDP. Logstash outputs syslog to a server whenever it receives syslog in input. But in some cases server may not be available so the events occured at that point of time should be buffered/stored and resend whenever server is available back again. For this purpose we are using **dead letter queue** but facing difficulty while setup.
We enabled dead letter queue in logstash.yml & path set to default i.e. logstash/data/dead_letter_queue.
It is also creating files 1.log, 2.log .... but all are empty files, and not sending events to output server whenever server coming online

Below is the logstash.conf file
-----------------------------------------------------------
input {
  syslog {
    port => 1470
  }
  udp {
    port => 514
    type => syslog
  }

  dead_letter_queue {
    path => "/usr/share/logstash/data/dead_letter_queue"
    commit_offsets => true
    pipeline_id => "main"
  }
}

output {
  syslog{
   host => "192.168.10.1"       
   port => 514
   protocol => udp
  }
}
---------------------------------------------------------------

In some documents its mentioned that dead letter queue only supports elastic search output, if this is the case then can you kindly suggest some workaround to achieve our solution

Following details for fast resolution:

- Version: logstash 5.6.3
- Operating System: ubuntu 14.04

**Comment by jakelandis** [comment]
> mentioned that dead letter queue only supports elastic search output

That is correct (as of today).

> suggest some workaround

It sounds like you may want the persistent queue: https://www.elastic.co/blog/logstash-persistent-queue . However, you will need an output the blocks when the downstream thing is down so that events get buffered to disk. UDP won't block, but TCP should. 

> It is also creating files 1.log, 2.log 

That is a known issue: https://github.com/elastic/logstash/issues/8022 and while abit odd, may be ignored as harmless. 

I am going to close this issue since we try to keep issues here for code related matters. If the above doesn't solve your use-case, please repost at https://discuss.elastic.co/c/logstash there are many more people with that with alot of real world experience that watch that .
