### ISSUE TITLE
PQ large page performance degradation

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#8801]
This is a followup of #8797 and relates to #8688. 
We noticed that large (typically > 64mb) pages exhibit performance degradation. 
More tests & investigation is required to identify the root cause. Also different queues scenarios show different behaviours: always-empty queue, growing queue, emptying queue.

**Comment by original-brownbear** [comment]
I explained this before :) The reason for this is simply that we do `msync` operations on unbounded (can't `msync` on a range in Java when we call `java.nio.MappedByteBuffer#force`) areas of a file => the larger the file the larger the area that needs to be synced on a single call.
`java.nio.MappedByteBuffer#force` is effectively `O(n)` in runtime relative to the file size. This is barely relevant/visible if the file you call it on is in the page cache. If it isn't in the page cache though this is a huge deal since the whole file needs to be read into the page cache before writing the changed areas of it back to disk.
=> As long as we use `msync` we will see a significant performance degradation if the queue has pages go out of the page cache and it will at least be linear in the size of the individual page files from the theory of things.

**Comment by colinsurprenant** [comment]
@original-brownbear 

> I explained this before

are you referring to #7317 ?

**Comment by original-brownbear** [comment]
@colinsurprenant yea for example

**Comment by colinsurprenant** [comment]
Closing - no followup is planned about this in the foreseeable future. We will reboot if need be.
