### ISSUE TITLE
Performance: unnecessary sychronized method in hot path

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#8826]
`org.logstash.FieldReference#deduplicate` is `synchronized` to protected access to a non-concurrent HashMap.  This should be updated to use either concurrent objects / access patterns , or at least use a ReadWriteLock to avoid all threads bottle necking on this method.

```
 private static synchronized FieldReference deduplicate(final FieldReference parsed) {
        FieldReference ret = DEDUP.get(parsed);
        if (ret == null) {
            DEDUP.put(parsed, parsed);
            ret = parsed;
        }
        return ret;
    }
```

cc: @original-brownbear

**Comment by original-brownbear** [comment]
@jakelandis this method is barely called after the cache is warmed up. You could technically shorten this by using a concurrent hash map (and `computeIfAbsent`) but it'll be the same performance since that method itself will just internally run a `synchronized` blocked afaik.

I don't think there's much to be won here, since that cache warms so quickly (run realistic scenarios we don't have ever new keys coming up and if we did our current caching would leak memory like hell and this would be the least of our problems :D)

**Comment by jakelandis** [comment]
@original-brownbear - i see now, thanks for the explains. closing as not an issue.
