### ISSUE TITLE
Test Failure: 6.X Java test failed - org.logstash.secret.store.backend.JavaKeyStoreTest

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#9031]
[Jenkins Console](https://logstash-ci.elastic.co/job/elastic+logstash+6.x+multijob-unix-compatibility/os=oraclelinux/308/console)

```
22:57:45 org.logstash.secret.store.backend.JavaKeyStoreTest > notLogstashKeystore FAILED
22:57:45     java.lang.AssertionError: 
22:57:45     Expected: an instance of org.logstash.secret.store.SecretStoreException$LoadException
22:57:45          but: <org.logstash.secret.store.SecretStoreException$AccessException: Could not determine keystore password. Please ensure the file at /tmp/junit3815207842415552041/junit8525297366384896794/alt.not.a.logstash.keystore is a valid Logstash keystore> is a org.logstash.secret.store.SecretStoreException$AccessException
22:57:45     Stacktrace was: org.logstash.secret.store.SecretStoreException$AccessException: Could not determine keystore password. Please ensure the file at /tmp/junit3815207842415552041/junit8525297366384896794/alt.not.a.logstash.keystore is a valid Logstash keystore
22:57:45     	at org.logstash.secret.store.backend.JavaKeyStore.getKeyStorePassword(JavaKeyStore.java:198)
```

**Comment by guyboertje** [comment]
I reran the suite and this test passed.

**Comment by jakelandis** [comment]
Running locally and on the build box (manually) always passes.... but I think i found the problem...

This test is writing random bytes as a keystore and ensuring that the proper exception is thrown.  Based on the last byte of the keystore we compute the obfuscated password size. If the last random byte happens to be zero, the code fails to compute the obfuscated password, hence the  Could not determine keystore password. 

The test is really testing that we throw a custom exception instead of letting the Java Keystore decide what to throw.  Since the exceptions thrown from this class follow a parent-child, and in this case we we are testing where child = LoadException ...but child =AccessException is also valid, I will update the test to look just for the parent = SecretStoreException (which is actually what we care about).

**Comment by guyboertje** [comment]
Nice.
