### ISSUE TITLE
Test failure: Master and 6.x failing for since January 24

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#9123]
https://logstash-ci.elastic.co/job/elastic-logstash-6.x/ and https://logstash-ci.elastic.co/job/elastic-logstash-master/

Some of the dependent jobs are succeeding, but at least one has failed every time for the past 15 days.

**Comment by robbavey** [comment]
@jordansissel Windows builds appear to have been a problem since January 24:

Tests started failing here on master:
https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-windows-compatibility/364/

And here on 6.x:
https://logstash-ci.elastic.co/job/elastic+logstash+6.x+multijob-windows-compatibility/309/

Master logs include `org.logstash.LockException: The queue failed to obtain exclusive access, cause: Lock held by this virtual machine on lock path: D:\data\queue\main\.lock` errors included

Note - these builds were the first builds with #8978 included (cc @colinsurprenant)

**Comment by colinsurprenant** [comment]
@jordansissel  @robbavey thanks for the heads up - I will run this on my Win VM to see if I can repro.

**Comment by colinsurprenant** [comment]
I can't reproduce locally. Inspecting the build log above I see that the first error is 
```
   1) LogStash::Api::Modules::Plugins should return a 404 to unknown request
18:10:48          Failure/Error: status = RSpec::Core::Runner.run(ARGV.empty? ? ($JUNIT_ARGV || ["spec"]) : ARGV).to_i
18:10:48 
18:10:48          IOError:
18:10:48            java.io.IOException: Not enough free disk space available to allocate persisted queue.
```

So there seems to be a disk space problem on this build node? All the other errors are a cascade from this one.

**Comment by colinsurprenant** [comment]
for 6.x it seems to hang at the agent specs. 

I suggest we first look into the disk space issue and see if there is a problem with that to start with,

**Comment by robbavey** [comment]
@colinsurprenant Another data point: looking at the build history of that node, it appears to be able to build 6.1 and 6.2 consistently, but fail in master and 6.x - https://logstash-ci.elastic.co/computer/SLAVE-07FA0C31A/builds

**Comment by colinsurprenant** [comment]
Right.  I am following up with infra to see if this might be a slave problem.

**Comment by colinsurprenant** [comment]
@robbavey ah yes I see what you mean. 6.x and master are running all tests using PQ, while 6.1 and 6.2 are using the legacy in-memory acked queue.  It seems related to that and thus tests in 6.x and master will require more disk space. 
The weird thing is that I can't repro locally so it does not look like its a *bad* disk space check implementation...

**Comment by colinsurprenant** [comment]
The slave wa replaced and we still get the same error
```
16:46:39     [ERROR] 2018-02-10 16:46:38.961 [LogStash::Runner] pipeline - Logstash failed to create queue {:pipeline_id=>"test-without-dlq", "exception"=>"Not enough free disk space available to allocate persisted queue.", "backtrace"=>["org.logstash.ackedqueue.Queue.ensureDiskAvailable(Queue.java:854)", "org.logstash.ackedqueue.Queue.open(Queue.java:157)", 
```

The problem here is that I can't repro locally.

I just remembered that one thing that is different is the `subst` trick we do on Windows CI to remap too-long paths to a drive letter. I am wondering if that might be causing problems. Investigating.

**Comment by colinsurprenant** [comment]
Ok, finally was able to reproduce. It is related to running the tests from a `subst` drive. Now onto fixing it.

**Comment by colinsurprenant** [comment]
monitoring build.

**Comment by colinsurprenant** [comment]
build success on master. waiting for 6.x
