### ISSUE TITLE
Logstash 6.2.1, endless GC on 2 instances with filled heap memory

### ISSUE THREAD

**Issue by nklmilojevic** [elastic/logstash#9195]
Hi.

We are having a lot of problems with our two Logstash instances. The instances have 72 cores and 128GB heap memory per host.

I'll upload the monitoring screenshots below so you can have better insight into our configuration and events per seconds. 

300 hosts are sending their log files via filebeat and logstash to elasticsearch.

The problem is that the Logstash goes into the endless GC and it fills all the heap memory. After that, we don't have any activity and logging doesn't help because there's nothing in it, even in debug mode, it just stops working.

Here’s are the config files:

**logstash.yml**
```
node.name: "our.host.com"
path.data: "/var/lib/logstash"
http.host: "our.host.com"
http.port: 9600
log.level: debug
path.logs: /var/log/logstash
xpack.monitoring.enabled: "true"
xpack.monitoring.elasticsearch.url: ["http://our.elkhost.com:9200"]
```

**pipelines.yml**
```
- pipeline.id: main
  path.config: "/etc/logstash/pipelines/main/*.conf"
```

**jvm.options**
```
-Xms128g
-Xmx128g


-XX:+UseG1GC
-XX:MaxGCPauseMillis=500
-Djruby.compile.invokedynamic=true
-Djruby.jit.threshold=0
-XX:+HeapDumpOnOutOfMemoryError


-XX:+PrintGCDetails
-XX:+PrintGCTimeStamps
-XX:+PrintGCDateStamps
-XX:+PrintClassHistogram
-XX:+PrintTenuringDistribution
-XX:+PrintGCApplicationStoppedTime

# log GC status to a file with time stamps
# ensure the directory exists
-Xloggc:/tmp/logstash-gc.log

# Entropy source for randomness
-Djava.security.egd=file:/dev/urandom
```

**example from gc.log**

```2018-02-26T14:50:21.057+0100: 1856.031: Total time for which application threads were stopped: 5.1607071 seconds, Stopping threads took: 0.0005625 seconds
2018-02-26T14:50:21.068+0100: 1856.041: [GC pause (G1 Evacuation Pause) (young)
Desired survivor size 436207616 bytes, new threshold 15 (max 15)
, 0.1091606 secs]
   [Parallel Time: 99.3 ms, GC Workers: 48]
      [GC Worker Start (ms): Min: 1856042.4, Avg: 1856042.9, Max: 1856043.2, Diff: 0.8]
      [Ext Root Scanning (ms): Min: 3.9, Avg: 7.1, Max: 18.1, Diff: 14.2, Sum: 341.2]
      [Update RS (ms): Min: 79.9, Avg: 90.3, Max: 93.6, Diff: 13.6, Sum: 4336.2]
         [Processed Buffers: Min: 64, Avg: 133.6, Max: 214, Diff: 150, Sum: 6413]
      [Scan RS (ms): Min: 0.0, Avg: 0.0, Max: 0.0, Diff: 0.0, Sum: 0.0]
      [Code Root Scanning (ms): Min: 0.0, Avg: 0.0, Max: 0.0, Diff: 0.0, Sum: 0.0]
      [Object Copy (ms): Min: 0.0, Avg: 0.1, Max: 0.3, Diff: 0.3, Sum: 2.6]
      [Termination (ms): Min: 0.0, Avg: 0.4, Max: 0.7, Diff: 0.7, Sum: 20.8]
         [Termination Attempts: Min: 1, Avg: 1.0, Max: 1, Diff: 0, Sum: 48]
      [GC Worker Other (ms): Min: 0.0, Avg: 0.0, Max: 0.0, Diff: 0.0, Sum: 0.8]
      [GC Worker Total (ms): Min: 97.7, Avg: 98.0, Max: 98.5, Diff: 0.8, Sum: 4704.7]
      [GC Worker End (ms): Min: 1856140.9, Avg: 1856140.9, Max: 1856140.9, Diff: 0.0]
   [Code Root Fixup: 0.1 ms]
   [Code Root Purge: 0.0 ms]
   [Clear CT: 1.6 ms]
   [Other: 8.2 ms]
      [Choose CSet: 0.0 ms]
      [Ref Proc: 3.5 ms]
      [Ref Enq: 0.0 ms]
      [Redirty Cards: 2.1 ms]
      [Humongous Register: 0.8 ms]
      [Humongous Reclaim: 0.2 ms]
      [Free CSet: 0.0 ms]
   [Eden: 0.0B(6528.0M)->0.0B(6528.0M) Survivors: 0.0B->0.0B Heap: 125.7G(128.0G)->125.7G(128.0G)]
```

And the screenshots.

**logstash-1**

![19|690x327](https://i.imgur.com/sRmLE9B.png)

**logstash-2**

![28|690x324](https://i.imgur.com/FORWPPW.png)

It seems that there's some kind of memory link.

If you need configuration for our filters, I’ll gladly post it, just let me know, but we've tried with a simple filter and it was the same.

I would be very grateful if someone has any idea that could help us. We tried putting the queue to persistent, changed the values for checkpoints, acks, queue max bytes, etc and nothing helped.
 Thanks in advance,

N

**Comment by jakelandis** [comment]
We have tracked down a few memory pressure issues lately.  You can try to upgrade the following plugins (one at a time preferably)

`bin/logstash upgrade logstash-ipnut-beats`  https://github.com/logstash-plugins/logstash-input-beats/issues/286 (this is likely the issue, though it is not a leak)

`bin/logstash-plugin update logstash-input-jdbc`  https://github.com/logstash-plugins/logstash-input-jdbc/blob/master/CHANGELOG.md  a couple memory/thread leaks, but depends on workflow

` bin/logstash-plugin update logstash-filter-grok`  https://github.com/logstash-plugins/logstash-filter-grok/issues/135 unlikely since the issue was only demonstrable on 5.x , not 6.x

**Comment by praseodym** [comment]
If your Logstash pipeline is not too complex, 72 cores and 128GB is _way_ overkill for 6000 events/sec, in the sense that it can actually hurt performance due to JVM GC stalls and thread contention in Logstash. I’d suggest trying a smaller heap with fewer pipeline workers; maybe try 4-8GB heap with 8-16 workers to see if this improves. If this cannot handle the load (I think it should), I’d suggest sharding Logstash to multiple instances per machine instead of having one huge JVM.

**Comment by frueht** [comment]
Hi
we use the same version 6.2.1 of Logstash on three instances with 4 cores an 2GB. 
And about 50 hosts sends via filebeat the messages. This is more or less the same configuration as described by nklmilojevic.
Now the important point is: 
**We have exactly the same problems with the heap memory!!**

If we runs only one instance of Logstash the situation is much better.
But for us it's important that we could runs more than one instance of logstash. 

It would be very grateful if someone has any idea, solution...
 Thanks,
T

**Comment by spawluk** [comment]
Hi. I had exactly same problem. I resolved it bu setting number of pipeline workers exactly to number of cores assigned to my machine

**Comment by original-brownbear** [comment]
This is a/the well-known problem with the beats input, see https://github.com/logstash-plugins/logstash-input-beats/issues/286.

The situation should have been improved to some degree in recent versions of the plugin, but a full fix is still ongoing.
=> Close here since we're tracking it in the beats input repo.
