### ISSUE TITLE
Grok does not change data type of semantic

### ISSUE THREAD

**Issue by Ekouyoja** [elastic/logstash#9196]
Hi,

I have problem with Grok, I want to change data-type to integer type directly in my grok pattern but it doesn't work. I can see that data-type is string in my Kibana GUI.

Here an exemple of pattern that i use :

APACHE_FORMAT_EXTENDED (?:-|%{IP:[apache][remote][ip]}|%{APACHE_FORWARDED:[apache][forwarded_host_raw]}) (?:-|%{USER:[apache][remotelogname]}) (?:-|%{APACHE_AUTH:[apache][remoteuser]}) \[%{HTTPDATE:[apache][date]}\] "(?:-|%{APACHE_METHOD:[apache][method]} %{NOTSPACE:[apache][request]}(?: %{APACHE_HTTPVERSION:[apache][httpversion]})?)" %{UINT:[apache][response]:int} (?:-|%{UINT:[apache][bytes]:int})(?: "(?:-|%{URI:[apache][referer]})" "(?:-|%{APACHE_QUOTED:[apache][useragent]})"(?: %{UINT:[apache][duration]:int} %{IPORHOST:[apache][server][cname]} %{IP:[apache][server][ip]} "(?:-|%{APACHE_FORWARDED:[apache][forwarded_host_raw]})")?)?

For exemple apache.duration will be an string type when i want an integer type.

- Logstash version : 6.1.2
- ES version : 6.2.2
- Operating System: RHEL 7

**Comment by yaauie** [comment]
@Ekouyoja is this problem persisting? have you re-created the ES index since you added the type-conversion directive?

When an ES index is created without an explicit mapping, the first time a record is inserted with this field, ES uses its [dynamic field mapping feature](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html) to detect the type of the field and declare its type based on what it saw.

Once a field's mapping has been determined (whether explicitly or implicitly), on subsequent inserts ES will [coerce](https://www.elastic.co/guide/en/elasticsearch/reference/current/coerce.html) the field's given value to the determined type.

If your pipeline was run before you added the type-conversion directive, it's likely that the field was dynamically mapped to be a `String`, and that LogStash is now correctly emitting integers, but they're being coerced back to strings in ES.

**Comment by andrewvc** [comment]
@Ekouyoja I'm going to close this because this ticket is in the wrong spot. If you believe it to be a bug, you can open an issue on https://github.com/logstash-plugins/logstash-filter-grok. If you think it's an issue with your use of the filter our discuss forum at https://discuss.elastic.co/c/logstash is the correct place.

This repo is for Logstash core bugs only.
