### ISSUE TITLE
Feature Request: restrict pipelines to specific file types

### ISSUE THREAD

**Issue by andrewbanchich** [elastic/logstash#9218]
Logstash should have a universal input configuration option that allows you to specify file types, similar to the `codec` option which works across all input plugins.

Example: I am using the Amazon S3 Logstash input plugin to process files from S3, but there are multiple types; some are XML, some are images, etc. Currently the only way to do this with the S3 input plugin is to master regexp (the Ruby version) and then use the `exclude_pattern` option to match any file extensions that _do not_ end in what you want. Seems pretty backwards to me.

I think it would be really useful for any kind of input that processes file data to specify the file type so that Logstash doesn't accidentally try to run the pipeline on a totally unexpected type of data.

**Comment by andrewvc** [comment]
Reading this, I feel like the ask is maybe to standardize on an `include_pattern` option for these plugins.

I don't know if it needs to be a part of core, but it makes sense to have as a feature for all file handling plugins.

WDYT @jsvd ?

**Comment by jsvd** [comment]
most input plugins don't deal with files or file types (e.g. udp, redis, kafka, elasticsearch, stdin)  so I don't think this should be a core-level setting.

for file based ingestors, like the file input plugin on logstash (and even filebeat), we have the `path` which can be something like `/var/log/*.log`. This serves both to determine where to look for files, but also has an implicit include criteria. For the s3 input we only have `bucket` and we're missing the include pattern, and there's already [an issue requesting this](https://github.com/logstash-plugins/logstash-input-s3/issues/95).

@andrewbanchich are you feeling this need in any other plugin? otherwise I think we can close this issue and follow up in the s3 input plugin side.

**Comment by andrewbanchich** [comment]
@jsvd Nope, that sounds good to me! I just wasn't sure if this was a common need for other plugins as well.
