### ISSUE TITLE
Incorrect error message: Settings 'path.config' (-f) and 'config.string' (-e) can't be used simultaneously

### ISSUE THREAD

**Issue by cawoodm** [elastic/logstash#9248]
Logstash 6.2.2 Windows

I want to run logstash in the console `-e` and have it reload the config file automatically `-r`.

However, when I run:
```
bin\logstash.bat -f config\logstash.dev.conf --path.data data_dev -e -r
```
Logstash fails with the following error:

> ERROR: Settings 'path.config' (-f) and 'config.string' (-e) can't be used simultaneously.

The error text must at least be be wrong since the following (`-f` and `-e`) works fine:
```
bin\logstash.bat -f config\logstash.dev.conf --path.data data_dev -e
```

**Comment by jsvd** [comment]
this seems to be an error parsing the cli options. because there's no argument to the `-e` flag (typically it'd be something like `-e "input {} output {}"`, the code parsing the cli flags disregards that `-e` is even called. if you do pass a string to `-e`, you'll see an error.

In the first example the cli parser is also likely being fooled and accepting `-r` as the argument to `-e`

**Comment by cawoodm** [comment]
I see my mistake: I have gotten mixed up trying to use `-e` as it's used with filebeat (log to stderr).
Sorry for the trouble!
