### ISSUE TITLE
when logstash read file, use "vi" to add 1 line and use "echo" to add 1 line, they are differerent?

### ISSUE THREAD

**Issue by springCkWyy** [elastic/logstash#9276]
conf:
`input {
        file {
                path => "/root/ck/test.log"
                start_position => "beginning"
        }
}
`

when use "vi" to add 1 line, logstash read from begin.Bbut use "echo"  just read last line.

i am confused.

**Comment by yaauie** [comment]
This type of question is best suited for the [Logstash Forums](https://discuss.elastic.co/c/logstash), where our community is ever-present to help each other out.

> The plugin keeps track of the current position in each file by recording it in a separate file named sincedb. This makes it possible to stop and restart Logstash and have it pick up where it left off without missing the lines that were added to the file while Logstash was stopped.
> 
> -- https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html#_tracking_of_current_position_in_watched_files

The file input plugin uses inodes to keep track of how much of a file has already been processed; this is what allows it to remember where it left off across renames during log rotation.

When you append to a file (e.g., with `echo` and the double-shovel operator `>>`), the existing inode is modified, which means Logstash is able to read only the new bytes.

When you edit a file with `vi` (or many other editors), the entire file is rewritten; under the covers, your operating system creates a brand new inode, and then points the existing filesystem path to point at the new inode. Since Logstash does not have knowledge of this inode, the entire file is read from the beginning.

**Comment by springCkWyy** [comment]
yeah. Right,  Thanks
