### ISSUE TITLE
Logstash 6.2.3 completely ignores configuration

### ISSUE THREAD

**Issue by pkaramol** [elastic/logstash#9277]
$ ./logstash --version
    logstash 6.2.3

    $ cat /etc/logstash/conf.d/logstash.conf
    input {
    	file {
    		path => "/home/pkara/Desktop/mylogfile.log"
    	}
    }

    output {
    	stdout { }
    }

    $ cat /etc/logstash/pipelines.yml 
    - pipeline.id: main
      path.config: "/etc/logstash/conf.d/*.conf"

However,  when performing `sudo journalctl -f -u logstash` nothing appears in the stdout.

Neither in `tail -500f /var/log/logstash/logstash-plain.log`

What is more, when performing:

    $ sudo ./logstash -f /etc/logstash/conf.d/
    WARNING: Could not find logstash.yml which is typically located in $LS_HOME/config or /etc/logstash. You can specify the path using --path.settings. Continuing using the defaults
    Could not find log4j2 configuration at path /usr/share/logstash/config/log4j2.properties. Using default config which logs errors to the console
    [INFO ] 2018-03-22 17:59:12.505 [main] scaffold - Initializing module {:module_name=>"netflow", :directory=>"/usr/share/logstash/modules/netflow/configuration"}
    [INFO ] 2018-03-22 17:59:12.514 [main] scaffold - Initializing module {:module_name=>"fb_apache", :directory=>"/usr/share/logstash/modules/fb_apache/configuration"}
    [WARN ] 2018-03-22 17:59:13.102 [LogStash::Runner] multilocal - Ignoring the 'pipelines.yml' file because modules or command line options are specified
    [INFO ] 2018-03-22 17:59:13.122 [LogStash::Runner] agent - No persistent UUID file found. Generating new UUID {:uuid=>"16d994a1-d125-4c30-9406-a307c1f8a4a6", :path=>"/usr/share/logstash/data/uuid"}
    [INFO ] 2018-03-22 17:59:13.305 [LogStash::Runner] runner - Starting Logstash {"logstash.version"=>"6.2.3"}
    [INFO ] 2018-03-22 17:59:13.457 [Api Webserver] agent - Successfully started Logstash API endpoint {:port=>9600}
    [INFO ] 2018-03-22 17:59:14.062 [Ruby-0-Thread-1: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:22] pipeline - Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
    [INFO ] 2018-03-22 17:59:14.693 [Ruby-0-Thread-1: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:22] pipeline - Pipeline started succesfully {:pipeline_id=>"main", :thread=>"#<Thread:0x72d8395f@/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:246 run>"}
    [INFO ] 2018-03-22 17:59:14.743 [Ruby-0-Thread-1: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:22] agent - Pipelines running {:count=>1, :pipelines=>["main"]}

and the logs stay at this point **forever**!

Here is a [gist](https://gist.github.com/pkaramol/b3c6b0952e2ff46bd36074a2b8b96071) with debug level info.

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

```

```
$ uname -r
4.13.0-37-generic
```

**Comment by pkaramol** [comment]
It gets more interesting....Here is a [gist](https://gist.github.com/pkaramol/cbc12561b3ac27b1e151ffa136c33f09) with debug level info when using a non existent file in the input pipeline...

**Comment by yaauie** [comment]
This issue may be better suited for the [discuss forums](https://discuss.elastic.co/c/logstash); feel free to ping me when you open a thread regarding this over there.

A couple notes to get you started:

****

> ~~~
> sudo ./logstash -f /etc/logstash/conf.d/
> ~~~

You probably shouldn't be running logstash as the super user (i.e., with `sudo`); doing so gives the process _carte-blanche_ on your system, which is especially dangerous because Logstash can be easily configured to run arbitrary, unvalidated plugins.

****

> However, when performing sudo journalctl -f -u logstash nothing appears in the stdout.

I am not immediately familiar with `journalctl`, but the location of the logstash logs depends a bit on how Logstash was installed; documentation can be found [here](https://www.elastic.co/guide/en/logstash/current/dir-layout.html).

****

> ~~~
> [DEBUG] 2018-03-22 18:16:58.929 [[main]<file] file - /home/pkara/Desktop/mylogfile.log: sincedb last value 727460, cur size 727460
> [DEBUG] 2018-03-22 18:16:58.930 [[main]<file] file - /home/pkara/Desktop/mylogfile.log: sincedb: seeking to 727460
> ~~~

These messages in your logs indicate that the file input has seen this file before, and the last event it read was from offset `727460`.

Are the files being appended to, or are they static? By default the `logstash-input-file` plugin you are using will effectively "tail" the file, skipping over the existing lines (and any lines that have already been read) and only emitting new events each time a line is _appended_:

> Stream events from files, normally by tailing them in a manner similar to `tail -0F` but optionally reading them from the beginning.
>
> -- [File Input Plugin -- Description](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html#_description_7)

****

> It gets more interesting....

Your linked gist looks appropriate; the given glob pattern, which explicitly references a file that does not exist, gets periodically expanded against your filesystem and doesn't find any files (hence the empty array).

**Comment by pkaramol** [comment]
@yaauie thanks for the feedback this was really helpful.

However If I may be allowed a comment, imho having `logstash` **NOT** throwing a specific and informative error when the `file` plugin is pointed to a non-existent file, is kind of weird design decision and may mislead the user.

Unless of course plugins are a separate thread of development so I may be pointing this out in the wrong place.
