### ISSUE TITLE
Invalid cast in Accessors#setChild

### ISSUE THREAD

**Issue by lovasoa** [elastic/logstash#9295]
Related to https://github.com/elastic/logstash/issues/8777 and https://github.com/logstash-plugins/logstash-filter-geoip/issues/137 : 

There seems to be a problem in that piece of code:

https://github.com/elastic/logstash/blob/c77b6b5cbe1c6a98bc6d570e5a34a033643e7857/logstash-core/src/main/java/org/logstash/Accessors.java#L102-L109

The method makes an unchecked cast to `ConvertedList`, when the variable can actually have a different type.

In the case of https://github.com/logstash-plugins/logstash-filter-geoip/issues/137, `target` is an `EmptyMap`, and in the case of #8777 it is a String.

I think the method should not accept an `Object`. It should instead be polymorphic, and accept only the types that it can work with.

**Comment by andrewvc** [comment]
Thanks for the report @lovasoa , and thanks for the extra detail in the ticket.

I've opened up a fix in #9299 

While type safety would be great, since the Event class interops with ruby almost exclusively it doesn't buy much.

As we build out our java plugin API #9215 we can re-examine that signature and potentially improve on tihs experience for java devs.

**Comment by lovasoa** [comment]
thanks for the quick fix!
