### ISSUE TITLE
Add config option to disable webserver

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#9408]
Users should be able to disable the webserver via logstash.yml

**Comment by benoitdupont** [comment]
Hello, here's a first proposition of solution for this issue: I added a configuration parameter _webserver.disabled_ in _logstash.yml_ as requested, set to _false_ as default value.

This is my first time with Ruby so any feedback is welcome :-)

Some things to discuss/improve:

1. Can you clarify  or give some examples for this use case ? I guess that we don't want to start a webserver for simple file manipulation for instance, or local transformations.
2. I only tested at first 'manually' the config option with the following test cases: no entry in logstash.yml, the entry set to _true_ and the entry set to _false_. Next step is to add them into the test suite, I didn't do it right away because I should investigate first how to assert that a webserver is launched.
3. Is the configuration entry at the right place in _logstash.yml_ ? It's currently in _Other Settings_ section, I didn't see anything better, or we can create a new section.
4. Are there manual, tutorials, release notes somewhere to update with this new configuration parameter ?

Hope this help ;-)
